### ISSUE TITLE
display friendly warning when bundle size is too big for deploying

### ISSUE THREAD

**Issue by fdidron** [graphcool/prisma#1002]
Hello,

Following up on https://www.graph.cool/forum/t/feedback-framework-preview/949/84?u=florian_didron

Using `gc` version 0.8.0

**Current behavior**
When deploying a graphcool service using `gc deploy` , the cli bundles the whole content of the working directory potentially making the bundle bigger than it should and causing the deployment to fail with the following error:

```
✖ software.amazon.awssdk.services.lambda.model.InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes (Service: null; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: #######-####-####-####-##########)
```

**Reproduction**
1. Init a new project
2. Add some heavy content to the project's dir in order for the build.zip to exceed 262144000 bytes
3. Run `gc deploy`

**Expected behavior?**
The bundler should only import the required files or display a friendly message

**Comment by marktani** [comment]
I think it's more feasible in the short-term to display a friendly error message that asks whether the deploy command was run in the directory of another project with a `package.json` or `node_modules`.

See #837 for the discussion about a long-term solution here.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
