### ISSUE TITLE
Database connectors and adapters

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1006]
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Postgres)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Postgres/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/MS%20SQL)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/MS%20SQL/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/MongoDB)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/MongoDB/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Oracle)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Oracle/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/ArangoDB)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/ArangoDB/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Neo4j)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Neo4j/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Druid)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Druid/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Dgraph)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Dgraph/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Cassandra)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Cassandra/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Elasticsearch)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/Elasticsearch/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/AppSync)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/AppSync/vote)
[![](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/TimescaleDB)](https://api.gh-polls.com/poll/01BYE4TA8D8FA6NF22X3HFNB0P/TimescaleDB/vote)

**Comment by geralt3** [comment]
Postgres
MSSQL
...

**Comment by kbrandwijk** [comment]
From a corporate perspective:
1. MS SQL
2. Oracle

**Comment by dallen66** [comment]
Postgres

**Comment by luminarious** [comment]
Postgres

**Comment by crubier** [comment]
... arangodb ?

**Comment by sebastianmacias** [comment]
Postgres

**Comment by makstr** [comment]
arangodb once more

**Comment by ansarizafar** [comment]
Postgres

**Comment by marktani** [comment]
Please use Github reactions over restating a previous comment 🙂

**Comment by kimf** [comment]
I guess it would be easier for you guys to just write an API that all the different "database-adaptors" needs to adhere to. Like rails did with ActiveRecord. Then people can write adaptors for whatever database they have the need for.

**Comment by crubier** [comment]
@kimf That is an amazing Idea ! I'd be willing to write the arangodb adapter in that case

**Comment by kbrandwijk** [comment]
We should also look at what's already there, like [Squeryl](http://squeryl.org/index.html) that already supports a [whole set of databases](http://squeryl.org/supported-databases.html), and also makes it easy to support more. Personally, I don't feel like starting all over again for every database out there...

**Comment by idkjs** [comment]
Dgraph? www.dgraph.io

**Comment by kbrandwijk** [comment]
@idkjs Wow, thank you for pointing me to that database. I wasn't aware of its existence, but it seems a lot faster than Neo4j! https://blog.dgraph.io/post/benchmark-neo4j/

**Comment by sorenbs** [comment]
@idkjs @crubier @kimf You have suggested databases that have very different characteristics than traditional relational databases. It would be very helpful if you could describe some different use cases so we can better understand how these query engines would fit in with the existing Graphcool capabilities. I have some ideas that I think are quite exciting, but i'd like to get some more diverse input from the community as well.

**Comment by crubier** [comment]
@sorenbs Arango db would fit really nicely thanks to its graph database feature: just use document collections for entities and edge collections for relations. Use AQL instead of SQL and you are done. No need for an Orm layer or anything. From my point of view this is the database that maps the best to graphql. 

I used arango as a backend for my graphql server and it was really easy. The graphql layer was just a thin translation layer.

**Comment by kbrandwijk** [comment]
@crubier I agree that Arango is a great fit to GraphQL. But the consideration is also if it's a good fit to the way the current data layer is structured. I don't really see it as a drop-in replacement.

**Comment by crubier** [comment]
@kbrandwijk Aha hell no, for sure ! 

It is definitely not a drop in replacement for a SQL database, that was not my message.

Clearly it seems to me that creating a new implementation of the data layer, dedicated to noSQL document databases such as mongo and arango would be waaaay easier than trying to make those fit into a SQL ORM layer (and back)...

**Comment by makstr** [comment]
I have been working on an apollo express server which closely mimics graph.cool behaviours, it uses ArangoDB as a backend. 

Most importantly it is modular due to schema stitching, so that architecture makes it easy to bend and expand to your own needs. So far there are some basic CRUD operations, filtering, sorting,  JWT auth with email / password, social login with Facebook, a faker fixture script. Currently working on s3 uploads with presigned urls. It is not fully polished but is fully tested with graphql-tester. 

Thinking maybe I should clean it up and release if there was more interest...?

**Comment by crubier** [comment]
@makstr I would definitely be interested ! That would basically totally fit my need. 

I developed a arango graphql backend with apollo, but I got fed up with having to **manually** code each new entity, with all its resolvers and stuff. So I went into graphcool, but I loose the scalability and general niceness of my arango backend, for a SQL server that I do not have much direct control on.

If you developed a tool that does this work of **automatically** creating resolvers, collections and everything based on a schema, I would be really interested in it, even willing to help you out !

**Comment by mingzhou** [comment]
Postgres
 MSSQL

**Comment by SamAriafar** [comment]
That would be nice if we can connect GraphCool to our own DB server, in my case Postgres, however i have no idea about implementing logic layer on top of it.

**Comment by idkjs** [comment]
I was just making suggestions. I basically still confused about the DB in graphcool. In mongo, i can go into the data and mess with it if I want to. Graphcool, i have no idea how to do that or if its even possible. Importing data would so much easier, even if I had to learn the sql to figure it out. dgraph was just an example where i was able to move a dataset into it and see how it works.

**Comment by marktani** [comment]
Hey @SamAriafar, your input in #1230 would be appreciated 🙂

**Comment by SeanStewart37** [comment]
I would love to use Graphcool if MSSQL was supported.

**Comment by sorenbs** [comment]
@SeanStewart37 could you describe your use case in more detail? Especially why MSSQL is a requirement. Feel free to ping me (@sorenbs) in the Graphcool slack if you'd rather talk in private :-)

**Comment by sorenbs** [comment]
Elasticsearch

**Comment by mark-james** [comment]
I think cassandra offers interesting features in terms of horizontal scale that would interest graph.cool. It's architecture is also quite complementary to graphql.
(I haven't looked at the innards of the graph.cool framework yet, so not sure how easy an integration it actually is).

**Comment by crubier** [comment]
Amazon Appsync ?

**Comment by lowsky** [comment]
Cassandra ?

**Comment by joshhopkins** [comment]
TimescaleDB – [Home](http://timescaledb.com) | [Repo](https://github.com/timescale/timescaledb)

**Comment by Shadow117** [comment]
MariaDB, please 🙇

**Comment by marktani** [comment]
Thanks everyone for the participation, that gives a great first impression for what is most asked and is super helpful 🙌 

I'll split up this issue into the individual feature reqeusts, for example for [MongoDB](https://github.com/graphcool/prisma/issues/1643) or [PostgreSQL](https://github.com/graphcool/prisma/issues/1641).

**Comment by lastmjs** [comment]
I'm curious about what happened to the idea of general database connectors and adapters?

**Comment by sorenbs** [comment]
@lastmjs The idea took off, so now we have split this issue into individual dbs all linked from the main readme https://github.com/graphcool/prisma#supported-databases

**Comment by rohanray** [comment]
@lastmjs https://github.com/biggora/caminte and https://github.com/1602/jugglingdb were based on similar principles. an abstraction layer for crud ops which was implemented by db specific operations behind the scene.... Sorry for polluting a closed thread, but i thought similar design can be thought of for this specific issue cross-cutting all DBs.

**Comment by brunocascio** [comment]
DynamoDB
