### ISSUE TITLE
graphcool delete fails locally

### ISSUE THREAD

**Issue by timwis** [graphcool/prisma#1008]
I hope this is helpful but I apologise if it lacks details or is difficult to reproduce. I ran into this while troubleshooting and wanting to start over without leaving 4 docker machines running in the background.

**Current behavior**
```bash
graphcool delete
? Are you sure that you want to delete cj943qp0l000601098v37d5do? y/N y
Deleting project cj943qp0l000601098v37d5do... !

ERROR: Cannot query field 'deleteProject' on type 'Mutation'. Did you mean 'addProject'? (line 3, column 7):
      cj943qp0l000601098v37d5do: deleteProject(input:{
      ^

{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'deleteProject' on type 'Mutation'. Did you mean 'addProject'? (line 3, column 7):\n      cj943qp0l000601098v37d5do: deleteProject(input:{\n      ^",
      "locations": [
        {
          "line": 3,
          "column": 7
        }
      ]
    }
  ],
  "status": 400
}
```

**Comment by timwis** [comment]
Same as #964

**Comment by marktani** [comment]
For now, you can remove the docker containers, **which will delete all local Graphcool services irreversibly**.

With `docker ps` you get the ids of the following containers:

* `graphcool/graphcool-dev`
* `mysql`
* `graphcool/localfaas`
* `rabbitmq`

Then kill & delete them:

```sh
docker kill <container id>
docker rm <container id>
```

**Comment by timwis** [comment]
Thanks -- is there, by any chance, a mounted volume that's persisting the data/configuration of those images? Because I did that, but when I try to reinitialise, I'm told that a project with that name already exists in my account (on my local cluster).

```bash
? Please choose the cluster you want to deploy to

local

? Please choose the target name dev
Creating service textblast locally in cluster local... !

ERROR: A project with the name 'textblast' already exists in your account

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 2003,
      "message": "A project with the name 'textblast' already exists in your account",
      "requestId": "eu-west-1:system:cj94sd7eh000a0172vspxze7d"
    }
  ],
  "status": 200
}

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

**Comment by Toosick** [comment]
@timwis Yes the data is persisted even after removing the containers. I know there is a better way to delete the persisted data but I just resorted to resetting Docker in the Docker settings.

**Comment by timwis** [comment]
Thanks, but I think the better way is to find out where the volume is persisted locally by looking at the `docker-compose.yml` file, then deleting the local directory/file. Do you know where we can find the `docker-compose.yml` file?

**Comment by Toosick** [comment]
`gc local eject`
The persisted folder is located relatively on the VM. I just didn't have the time to research.

**Comment by timwis** [comment]
That didn't quite reveal the persisted volume location. Here's how I nuked it. Note that it will nuke any other docker containers.

```bash
# stop all running containers
docker stop $(docker ps -a -q)

# remove all running containers
docker rm $(docker ps -a -q)

# remove all dangling volumes
docker volume rm `docker volume ls -q -f dangling=true`
```

**Comment by kbrandwijk** [comment]
using `docker ps -f name=local -a -q` (or the name of your cluster instead of 'local') would limit this to the docker containers of the cluster you want to eradicate only.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
