### ISSUE TITLE
New console Playground has scrollbars everywhere

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1014]
**Current behavior**
![image](https://user-images.githubusercontent.com/852069/31947442-a01a7fae-b8d4-11e7-81bf-471c533cf302.png)

![image](https://user-images.githubusercontent.com/852069/31948311-db0e6858-b8d6-11e7-8c8d-e5cdda7f055f.png)

**Expected behavior?**
Without.

**Comment by panzupa** [comment]
Have same problem

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
