### ISSUE TITLE
No schema for Permissions shown in new console playground

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1015]
**Current behavior**
While on a permission tab, I would expect the schema to show the permission endpoint schema.

**Comment by dukuo** [comment]
Same thing happening here, any updates @kbrandwijk  ?

**Comment by kbrandwijk** [comment]
Don't ask me, I just reported the issue 😄

**Comment by dukuo** [comment]
Lol i was wondering maybe if you had some progress since you reported it.

**Comment by kbrandwijk** [comment]
It's still missing...

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
