### ISSUE TITLE
Share button doesn't work in console playground

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1017]
**Current behavior**
It doesn't do anything.
Also, be aware that if you decide to fix this, it has become even easier to share a master rootToken, because it is added by default when selecting 'Admin'!

**Expected behavior?**
It just works.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
