### ISSUE TITLE
After prettify, generate code dialog shows incorrect query type

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1018]
**Current behavior**
When you have this query:
```
query {
  allUsers{ id }
}
```
The generate code dialog says: "Generate Code for your Query"

After prettify:
```
{
  allUsers{ id }
}
```
It says: "Generate Code for your Mutation"

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
