### ISSUE TITLE
Improve health checks for status.graph.cool

### ISSUE THREAD

**Issue by joarwilk** [graphcool/prisma#1029]
Something has to be done regarding the status page, as it is way too slow to respond. I think it needs a realtime view of the amount of 5xx's going through the system, or just something that makes it yield realtime, relevant information.

Right now we're getting a lot of CloudFront 504's but the status page is all green which is clearly incorrect.

**Comment by marktani** [comment]
Thanks a lot for bringing this up, this is already on our plate 🙂

**Comment by the-simian** [comment]
I was coming to add this feature. I am currently getting some 504s as well. Is this on cloudfront's end, or could it be something I am doing wrong?
