### ISSUE TITLE
Usability of graphcool console

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/prisma#103]
The following features, which are supported by most other database tools, would be nice to have: 

* By shift-clicking two nodes A and B: selecting all successive nodes (or table rows in the UI) between A and B. 
* Support undo with ctrl-z. 
* Do not commit changes when the field in the data browser looses focus, commit all current changes when a save button is pressed. Sometimes, I would like to make changes consistently across multiple fields. This is already done for schema, but not for data views. 
* Support copy/paste. I can imagine that JSON would be a great representation for the clipboard. 

Currently, the GC console is the only UI-based way to edit live data. Without the features mentioned above, it's very easy to bring the data into inconsistent state or accidentally edit or delete data.

**Comment by marktani** [comment]
Thanks for these valuable suggestions! We're constantly iterating the console and this helps us to stay on track.

**Comment by timsuchanek** [comment]
Good points @ejoebstl !

**Comment by ejoebstl** [comment]
I'd like to add, possibly with a lower priority: 
* Make it possible to change the width of columns.

**Comment by marktani** [comment]
Related to #15.

**Comment by marktani** [comment]
Another suggestion

* Add "duplicate" feature for node/s

**Comment by ejoebstl** [comment]
Some more: 
* When I paste a correct id in a relation field, I still need to explicitly click on some item in the suggestion list. Otherwise the id will just be discarded and null used instead. 
* When I create a new node and, before saving the new item, delete some other node, all data I entered for the new item will be discarded. 

Why do I have such odd and specific use-cases? 
Testing webhooks!

The missing #102 requires that I re-create nodes when I want to trigger the webhook, which is somewhat painful due to the issues above.

**Comment by ejoebstl** [comment]
Some more: 

* Allow editing and copying of non-localized ISO 8601 date-time string, including timezone, when working in the console.

**Comment by marktani** [comment]
See also https://github.com/graphcool/console/issues/539

**Comment by ejoebstl** [comment]
Some more: 
* When a field loses focus (e.g. because I wanted to copy or edit the value), the view scrolls all the way to the left. 

This is *super* annoying if you have a model with more fields than fitting on the screen.

**Comment by ejoebstl** [comment]
Some more: 
* The UI for permissions is not scrollable horizontally. That means if I have a lot of fields, I can't see my permissions.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
