### ISSUE TITLE
Allow specifying cacheControl attributes on Types and Fields

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1032]
**What feature are you missing?**
I am trying to configure caching on my Apollo API Gateway. For this, I need to add `@cacheControl` directives to my Types and fields. When I try to do that, the server doesn't throw any error, but the directives are silently removed. Unfortunately, `mergeSchemas` does not allow redefining fields, so it would be helpful if I could add them on the Graphcool side.

Also, the top-level queries that are generated are not accessible from the schema. It would be nice to be able to define cacheControl attributes for the generated query fields as well somehow.

Apollo Cache Control is an open standard, that will not only be implemented by Apollo Server, but also Sangria, etc. (according to their docs), so this is not a 'vendor-specific' thing.

**How could this feature look like in detail? Tradeoffs?**
- Do not remove additional directives.
- Proposal for generated query fields is to take the cacheControl attribute off the Type, so if I define:
```
type Post @model @cacheControl(maxAge: 30) {
 ...
}
```
Then the generated queries would also get that setting:
```
type Query {
   allPosts(...) @cacheControl(maxAge: 30)
   Post (...) @cacheControl(maxAge: 30)
}
```

**Depends on:**
- [ ] Expose user-defined directives in API schema #1228

**Comment by marktani** [comment]
Can you provide links to more resources about `@cacheControl`? :)

**Comment by kbrandwijk** [comment]
I have a working example here: https://github.com/kbrandwijk/graphcool-gateway-apollo-engine-demo#caching-example. The reason behind this issue is that adding directives to an existing field in a Gateway is difficult (see: https://github.com/apollographql/graphql-tools/issues/451).
This is not necessarily just about cacheControl, but potentially about any directive not recognized by Graphcool, but useful 'downstream', like the new `stream` directive, or any other for that matter.

**Comment by marktani** [comment]
Since this discussion ended ~half a year ago, a lot has changed in the GraphQL ecosystem.
You should be able to define directives in your application schema, and also define their logic there.

Feel free to revisit this discussion in a new issue if you feel that this approach could be extended 🙂

**Comment by kbrandwijk** [comment]
@marktani I think it would be very helpful if directives would be 'preserved' across Prisma. When importing Prisma types into your schema, it's still hard to add directives to them.

**Comment by marktani** [comment]
Yup, let's continue the discussion here: #1228 🙂
