### ISSUE TITLE
Cannot create permissions when relation has the same name as Type

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1038]
**Current behavior**
I cannot create any permission for a Type with the same name as a Relation.

**Reproduction**
types.graphql
```
type Address @model {
  id: ID! @isUnique
  city: String!
  user: User @relation(name: "Address")
}

type User @model {
  id: ID! @isUnique
  name: String!
  dateOfBirth: DateTime
  address: Address @relation(name: "Address")
}
```
Error: `Wrong operation defined for RelationPermission. You supplied: 'Address.read'`

**Expected behavior?**
Either relation names should be validated, or permissions should work.

**Comment by marktani** [comment]
I think a good way to solve this would be by providing an optional field `type` on a permission in the yml file which accepts strings` model` or `relation`.

**Comment by kbrandwijk** [comment]
Could it also be handled without an extra field?

`.read`, `.create`, `.update`, `.delete` -> find type with the specified name
`.connect`, `.disconnect`, `.*` -> find relation with the specified name

**Comment by do4gr** [comment]
We are thinking about enabling .* for model permissions as well. This would then not be enough to identify whether a model or a relation is meant.

**Comment by kbrandwijk** [comment]
Then I think that requiring a relation name to be unique is the best option. I really don't like the permission setup to become more verbose that it already is by having to add another field to every single permission.

**Comment by do4gr** [comment]
I also think that that is a nicer solution. But we'll have to discuss it internally since this might be a breaking change for some users.
