### ISSUE TITLE
More details for "Insufficient permissions for this mutation"

### ISSUE THREAD

**Issue by lolcoolkat** [graphcool/prisma#1039]
I'm getting a "Insufficient permissions for this mutation" when i'm trying to run a mutation. I've looked everyone but I can't seem to figure out what is causing the insufficient permissions on the mutation.

Would love if it gave the reason for the insufficient permission... for example "Unable to read id field on Type Post" etc. Something like that :) On local development ofc not production!

![4s3-i6quqk2v0g_oygyunq](https://user-images.githubusercontent.com/20114263/32029482-e3cd8234-b9c2-11e7-9963-fc0604b98c82.png)

![z-qnfhicqtapqag2fddfiq](https://user-images.githubusercontent.com/20114263/32029438-8ccaaf5c-b9c2-11e7-8169-8f585d426790.png)

![3qzjuzcpslga7fytcn7pmg](https://user-images.githubusercontent.com/20114263/32029437-892620d4-b9c2-11e7-84bf-4817387329b2.png)

![r1y0tgpvrkocqd4sp0ns5q](https://user-images.githubusercontent.com/20114263/32029389-205c249a-b9c2-11e7-89ea-d7e34361da59.png)

![czffbn8itq2am14gzjp7wg](https://user-images.githubusercontent.com/20114263/32029449-a37d2d56-b9c2-11e7-9225-52f375050f71.png)

I have everything I should need... and I still don't know what I don't have sufficient permissions. The user i'm using with is a valid Admin aswell. :(

**Comment by kbrandwijk** [comment]
Although this would be helpful during development, it would be a huge leak of sensitive information in production. But there are more FR for a 'development mode', so this fits right in.

**Comment by lolcoolkat** [comment]
I forgot to mention @kbrandwijk that i'm doing this on my local build.. not on production :)

**Comment by kbrandwijk** [comment]
The `create` permission is limited to the id field. That means you can't create any other fields on the Type.

**Comment by lolcoolkat** [comment]
Solved! But the part about more details locally when receiving permission errors would still be amazing :)

**Comment by Alex-Mann** [comment]
@lolcoolkat How did you solve this? Also getting a similar error.

**Comment by kbrandwijk** [comment]
@Alex-Mann Please create a new question on the forum. This issue is about supplying more information to the developer when you have insufficient permissions.
