### ISSUE TITLE
Fix License

### ISSUE THREAD

**Issue by sbrichardson** [graphcool/prisma#1050]
Just a heads up on the License file in the main repo:

Copyright {yyyy} {name of copyright owner}

Need to fix the license.

**Comment by joestrouth1** [comment]
I believe that's part of the Apache License text itself, which should not be modified. Provided as an example for what to include within other files.

```
APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "{}"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

Copyright {yyyy} {name of copyright owner}
```

Most other projects under this license leave it unmodified, including Kubernetes, TypeScript, Swift, etc.

See [this issue](https://github.com/kubernetes/kubernetes/pull/65) for the rundown on what some lawyers had to say about a similar request
