### ISSUE TITLE
createdBy and updatedBy

### ISSUE THREAD

**Issue by kimf** [graphcool/prisma#107]
In almost all of the applications I worked on I needed to be able to see who created and/or updated a record.

I figure this could work exactly as createdAt/updatedAt, and just get auto-populated.

One use-case I'm working on right now is to show a "notification" when a new item comes in on a subscribtion, but not for the user who performed the mutation.

**Comment by sedubois** [comment]
Related https://github.com/graphcool/feature-requests/issues/93

**Comment by marktani** [comment]
Great suggestion, thanks! It should be noted that this is already possible, of course with more effort needed.

I think the ID type for those fields would work well. In the case of `EVERYONE` creating or updating a node, the field would be `null`.

We should keep this in mind when researching #83 as well. 

> One use-case I'm working on right now is to show a "notification" when a new item comes in on a subscribtion, but not for the user who performed the mutation.

This will be better handled with GraphQL subscriptions as decribed [here](https://www.graph.cool/docs/reference/simple-api/subscribing-to-created-nodes-oe8oqu8eis)

**Comment by danmkent** [comment]
Any plans to implement this?

I think it would be best implemented as automatic relationships with the User type for every other type.

That way, the relationship could be used in permission queries, filters etc just like any other relationship.

It would also  be possible to use the other end of the relationship (maybe createdNodes and updatedNodes on the User type) to get Ids for everything the user has touched

**Comment by pcooney10** [comment]
+1 for something like this. I have implemented `createdBy` myself on some Types (pretty straightforward), but `updatedBy` or something like `updates` would be a little trickier.  I am trying to implement something with Server-Side Subscriptions and a `lastUpdatedBy` field, but #146 is a bit of a roadblock at the moment.

Right now if I had a `lastUpdatedBy` field that gets overwritten with each mutation, I can deduce all of the information I need to create a log (`timestamp`, `userId`, `newValues`,  and `previousValues`), but this is something you guys may want to provide more explicitly in the subscription params ( in addition to, or instead of `updatedFields` and `previousValues`).

**Comment by OlafJacobson** [comment]
Trying to make a functions to create notifications as well. All is there as described by @pcooney10, with the `updatedBy` field just as string it would implement the workaround that triggers the function. However, the only blocker now is the `previousValues` on the relations.

**Comment by rezonjov** [comment]
hi @pcooney10 do you mind sharing how you implemented the createdBy? I needed to create an audit trail of who did what. All I can think of right now is to create a relation createdBy for each Type and pass the user authenticated id whenever it makes a mutation. I'm not sure that's the best solution though.

**Comment by krinoid** [comment]
@rezonjov: this is how I've done this:

Say I have a model `Post` and a (required) field `createdBy` that points to the `User` model. I call the mutation `createPost` with all the arguments (so the `createdBy` field is populated on client). Now, I need some verification on the server-side/graphcool-side (cause one could easily change the mutation data and pass different `userId` to the server. So, the crucial part is using the Permission system offered by graph.cool. In the permissions view, I change the Create permission to only allow authenticated users and create Permission Query such as this one:
```
query ($input_createdById: ID!, $user_id: ID!) {
  SomeUserExists(filter: {
    AND: [{ id: $user_id }, { id: $input_createdById }],
  })
}
```

This way, if somebody would try to change `createdBy` field, this Permission Query would fail.

Hope that helps :).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
