### ISSUE TITLE
Return related nodes in delete mutation

### ISSUE THREAD

**Issue by Noitidart** [graphcool/prisma#108]
### Delete doesnt return related data
```
mutation {
  deleteVerify
  ( id:"cizdpqfq0iwqg0144xtrbosoy" )
  { id user { email } }
}
```

On success however it gives me null for user:

```
{
  "data": {
    "deleteVerify": {
      "id": "cizdpqfq0iwqg0144xtrbosoy",
      "user": null
    }
  }
}
```

### Query works fine
The query for this works perfectly fine:
```
query {
  allVerifies
  (filter:{ id:"cizdpvvab1cr6013655of1man" })
  { id user { email } }
}
```

```
{
  "data": {
    "allVerifies": [
      {
        "id": "cizdpvvab1cr6013655of1man",
        "user": {
          "email": "blah@blah.com"
        }
      }
    ]
  }
}
```

So I'm confused why the `mutation` delete is not giving me the email.

**Comment by Noitidart** [comment]
A side note, on delete, i need to get the user email like this:

```
mutation {
  deleteVerify
  ( id:"cizdpqfq0iwqg0144xtrbosoy" )
  { id user { email } }
}
```

On success however it gives me null for user:

```
{
  "data": {
    "deleteVerify": {
      "id": "cizdpqfq0iwqg0144xtrbosoy",
      "user": null
    }
  }
}
```

**Comment by marktani** [comment]
Thanks for your report, we'll look into this :slightly_smiling_face:

**Comment by marktani** [comment]
I migrated your issue report here: https://github.com/graphcool/console/issues/707.

**Comment by Noitidart** [comment]
Thanks @marktani , is it possible to query and mutate in single statement?

**Comment by marktani** [comment]
No, that's not possible.

**Comment by tehwayne** [comment]
Is this something the graphcool is planning to support? I'm currently using functions to help push notifications and for deletes relational data is necessary for me to refresh clientside data. Thanks!

**Comment by maxdarque** [comment]
When you update the local store on `apollo-client` you might need the parent ID of a deleted object to read and edit a query. The easiest way to get the parent ID is to have it passed back by the API. So it would be great if you could pass back more data on a delete than just the ID of the deleted object. Thanks

**Comment by marktani** [comment]
Moving this here: https://github.com/graphcool/graphcool-framework/issues/519

**Comment by c10b10** [comment]
@maxdarque I'm running into trouble because of the exact usecase @maxdarque is describing.

**Comment by maxdarque** [comment]
@c10b10 I found another way around this. You can pass in parent ID via `updates` on `options` on the mutation call. See the example below:

```
const options = {
        variables: this.formatCreateDataRequest(),
        update: (proxy, { data: { createDataRequest }}) => handleNewDataRequest(proxy, createDataRequest, parentId),
      }
this.props.createDataRequest(options)
.then( response => console.log('Data request successfully sent', response) )
.catch( e => console.log('error', e) );

const handleNewDataRequest = (proxy, createDataRequest, parentId) => {
  try {
    let data = proxy.readQuery({query: DataRequestQL.allDataRequestsOnParent, variables: { parentId }});
    if (data.allDataRequestsOnParent) {
      data.allDataRequestsOnParent.unshift(createDataRequest);
      proxy.writeQuery({query: DataRequestQL.allDataRequestsOnParent, data, variables: { parentId }});
    }
  } catch (e) {
    console.log(e);
  }
}```
