### ISSUE TITLE
Docker Compose fails if it requires sudo

### ISSUE THREAD

**Issue by diit** [graphcool/prisma#1081]
**Current behavior**
- execute `graphcool local up` || `sudo graphcool local up`
- exits with code 1 showing docker-compose help screen

**Reproduction**
- On (at least my setup of) Ubuntu 16.04 docker-compose requires sudo to access the docker-daemon
- execute above with that env to recreate

**Expected behavior?**
- spin up local instance

**Solution?**
- execute docker-compose with same user-level as the graphcool lib, so if run as sudo run `sudo docker-compose ...`

**Comment by tomasowa** [comment]
did you try adding $USER to docker GROUP (so you can run docker without needing sudo privileges) and did you check the docker-compose version? The older versions of docker-compose do not work with graphcool commands.

I had the same problem on the latest version of Debian, the docker-compose (version 1.17, the debian repo had 1.8.0) and docker versions from the docker repository do work with graphcool.

**Comment by diit** [comment]
Above issue is resolved when running docker as non-root user, See [Details](https://docs.docker.com/engine/installation/linux/linux-postinstall/).
