### ISSUE TITLE
internal server error when using local deployment on port 60001

### ISSUE THREAD

**Issue by UADACID** [graphcool/prisma#1082]
I get internal server error on graphcool playground after graphool deploy, 
this is my step : 
graphcool local up
graphcool init
graphcool deploy

and i get this : 
<img width="620" alt="screen shot 2017-10-30 at 6 56 46 pm" src="https://user-images.githubusercontent.com/15373307/32169684-21902cc2-bda4-11e7-9bce-eff6aedc2f49.png">

after i type graphcool playground i get this : 
<img width="1277" alt="screen shot 2017-10-30 at 6 53 27 pm" src="https://user-images.githubusercontent.com/15373307/32169717-3f790ab0-bda4-11e7-9e80-ab66be844aeb.png">
this my global .graphsrc 
<img width="378" alt="screen shot 2017-10-30 at 6 58 20 pm" src="https://user-images.githubusercontent.com/15373307/32169749-5c04660c-bda4-11e7-8cb9-7d25335c0e34.png">

what i missing step? or setup?

**Comment by UADACID** [comment]
here is my repo [https://github.com/UADACID/example-graphcool-local.git](url) , can you check please??

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/32189760-02b76038-bdac-11e7-9284-e0cee4a0bca8.png)
![image](https://user-images.githubusercontent.com/852069/32189769-069a9e54-bdac-11e7-9601-e23c7dced438.png)

I can't reproduce this locally, I think you might be running into https://github.com/graphcool/framework/issues/825. What version of graphcool are you running?

**Comment by UADACID** [comment]
<img width="386" alt="screen shot 2017-10-31 at 1 28 39 pm" src="https://user-images.githubusercontent.com/15373307/32210323-94b2a478-be3f-11e7-93f9-2174209541d6.png">
that is my gc and docker version

**Comment by UADACID** [comment]
it work's after change local port to 60000
<img width="1280" alt="screen shot 2017-10-31 at 2 17 55 pm" src="https://user-images.githubusercontent.com/15373307/32211717-6904b4fe-be46-11e7-97e2-ae04d15341be.png">

**Comment by kbrandwijk** [comment]
@nilan Do you want to reopen #825, or do you think this is a different issue?

**Comment by marktani** [comment]
@timsuchanek, what do you think?

**Comment by kbrandwijk** [comment]
@timsuchanek Any update on this?

**Comment by scko823** [comment]
I was able to replicate this problem, did a bit debugging and fixed it on my local machine
OS: macOS 10.3.3
```
docker -v                                                                                                                                                                                  
Docker version 18.03.0-ce, build 0520e24
graphcool -v                                                                                                                                                                               
graphcool-framework/0.11.6 (darwin-x64) node-v8.9.3
```
it looks like when I did `npm install -g graphcool-framework` to update my local graphcool, during the update process, it sees I have a global `.graphcoolrc` file, it make a back up of it and changes the port from 60000 to 60001 in the rc file.

upon closer inspection using `docker inspect {graphcool dev container}`, it was running it with some env variable referencing 60000, like the `CLIENT_API_ADDRESS`, among other things

![screen shot 2018-04-19 at 9 31 32 pm](https://user-images.githubusercontent.com/12867107/39030899-d01f9fce-4419-11e8-8c34-d292f6e377f6.png)

I changed my `.graphcoolrc` back to the original port for both host and FaasHost and things are back to normal.
