### ISSUE TITLE
"User Authentication with Email for React and Apollo" template tutorial out of date. 

### ISSUE THREAD

**Issue by RoryKelly** [graphcool/prisma#1090]
**Current behavior**
"User Authentication with Email for React and Apollo" is out of date the tutorial does not match the code and the instructions do not line up. 

**Reproduction**
Follow the instructions [here](https://github.com/graphcool/framework/blob/master/docs/03-Tutorials/02-Auth/02-Authentication-with-Email-and-Password-for-React-&-Apollo.md). Notice that the some java script files are written in type script.

**Expected behavior?**
Instructions match filenames and steps result in compiling code.

**Comment by rnkdev** [comment]
Encountered the same issue as I was browsing the docs in the main web this weekend. 

I think this has been updated just recently with df3f393. Also confirmed that the web has been updated as well.

**Comment by nikolasburk** [comment]
Hi @RoryKelly, thanks a lot for reporting this issue and apologies for the delayed response! With the switch to [Prisma](https://prismagraphql.com), we're now focussing on new tutorials for Prisma and will remove old content that is broken/outdated. I've just deleted the broken authentication tutorial from the Graphcool Framework docs!  🙌
