### ISSUE TITLE
`graphcool help` chalk coloring is not visible in cmder on Windows

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1110]
![image](https://user-images.githubusercontent.com/852069/32303125-ea98cc78-bf66-11e7-9699-af78de478d21.png)

**Comment by panzupa** [comment]
I have the same issue.

**Comment by fabien0102** [comment]
I know that it not resolve this issue, but you can use https://hyper.is/ on windows :wink: It works perfectly ^^

**Comment by kbrandwijk** [comment]
Seems to be a Windows 10 specific issue:
https://github.com/Microsoft/WSL/issues/2174
https://github.com/chalk/chalk/issues/145

Bottom line is: don't use `chalk.dim`

**Comment by kbrandwijk** [comment]
There is an update on https://github.com/chalk/chalk/issues/145. It seems the fix is part of the fall Creators' Update.
