### ISSUE TITLE
Rename fields, mutation callbacks, etc properly when modifying a relation 

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#112]
When renaming a relation, we're currently only warned that it will break everything, or it can even refuse altogether when there are existing nodes.

Instead, it should transitively modify things as appropriate. Otherwise this renaming feature is kind of useless. This appears critical to be able to modify/refactor an existing backend.

**Comment by marktani** [comment]
I can rename a relation or a relation field, even with existing data. Changing the multiplicities of a relation is not possible with existing data though.

The "breaking change" hint refers to queries in your client application that might break by this change.

**Comment by sedubois** [comment]
In general if something is not allowed for some reason, as a user I'd just like to know why, and whether that's a temporary limitation or an upcoming feature. Currently it's a bit illogical that the user is given the opportunity to change something, but then just gets sometimes a warning, and sometimes even an error message.

OK I hadn't understood that about "breaking change". It would help to clarify the "breaking change" message, that it doesn't compromise the backend's integrity.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
