### ISSUE TITLE
Mobile console

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#113]
The graphcool console is basically useless on mobile. It would be good to offer at least something minimal, starting with just being able to view data, for example.

![img_0257](https://cloud.githubusercontent.com/assets/4217871/23211848/a67172c8-f90c-11e6-9b03-36cd1d4d7d40.PNG)

**Comment by sedubois** [comment]
A temporary workaround is also to add a link "switch to desktop version" as GitHub does.

**Comment by marktani** [comment]
On Android, I can choose the "Request Desktop Site" setting in Chrome, after which I can use the Console just fine. Is there a similar feature for iOS/Safari?

**Comment by sedubois** [comment]
@marktani unfortunately I don't know of any such feature in iOS/Safari.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
