### ISSUE TITLE
Interactive deploy selection should have option "Deploy to existing service"

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1133]
When deploying for the first time or explicitly running `gc deploy -i` there should be an. list item (additional to "Local Cluster" and "Shared Cluster") which says "Select existing service". Once selected this should display a selection list of all existing services deployed outside of the scope of this service. Once a service was selected the service should be added to the `.graphcoolrc` file.

**Comment by kbrandwijk** [comment]
Related to https://github.com/graphcool/framework/issues/1000

**Comment by kbrandwijk** [comment]
> all existing services deployed outside of the scope of this service
Well, also the existing targets within the project.
