### ISSUE TITLE
System types and fields are not described accurately

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1142]
https://www.graph.cool/docs/reference/database/data-modelling-eiroozae8u#system-artifacts-(only-for-legacy-console-projects)

It says that `File` and `User` are only special for legacy projects. This is not accurate. Currently, `User` and `File` behave _exactly_ the same for legacy projects, after they have been added to `types.yml`.

For `User`, there might be upcoming changes, but `File` is unlikely to change soon.

System fields `id`, `createdAt`, `updatedAt` are also behaving similarly at the moment.

**Comment by TheSneakyOne** [comment]
The article isn't accessible anymore.
