### ISSUE TITLE
Can't create record with required relation in data browser

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1145]
_From @nikolasburk on June 7, 2017 13:22_

I want to create a new entry in the data browser, the type has a field that's a required relation. I can set the regular values directly, but I can't set the relation when creating a new record - the label in the corresponding field says _Should be added later_. 

When I try to add the entry without setting the relation, there is an error (correctly) saying:

```
The field 'postedBy' on type 'Link' is required. 
Performing this mutation would violate the constraint
```

_Copied from original issue: graphcool/console#1062_

**Comment by marktani** [comment]
To create a node that's part of a required relation right now, you can use the Playground:

```graphql
mutation {
  createLink(
    url: "example.com"
    postedBy: "user-id"
  ) {
    id
  }
}
```

**Comment by GeroSalas** [comment]
**DOUBT HERE**
But following the [docs](https://www.graph.cool/docs/reference/graphql-api/mutation-api-ol0yuoz6go/#modifying-edges-for-one-to-many-relations) ...so we need to set the parent as 'optional' to create the child alone and then execute another mutation to associate them by the Ids.
So...following the **docs example**:
 - How can we create only one **mutation** to insert a '**Post**' associated to a '**User**' without making 2 mutations or nesting parent data always in once ?
 - There is some approach more simple to do this ?
