### ISSUE TITLE
Explain wildcard permissions in reference

### ISSUE THREAD

**Issue by danielglasgow** [graphcool/prisma#1148]
**Current behavior**
Permissions Ignored for CLI projects

**Reproduction**
`graphcool init`
`graphcool deploy`

open postman and query the returned graphcool service endpoint with the following body:
`{"query":"query {\n  allUsers {\n    id\n \nname  }\n}","variables":null}`

I receive the response:
`{"data":{"allUsers":[]}}`

After creating a user via the sandbox named 'test user' I receive the following response:
`{"data":{"allUsers":[{"id":"cj9k2e5fvf1og0109j4mp9l6q","name":"test user"}]}}`

**Expected behavior?**
Because all fields are automatically hidden, I should receive a invalid permission error

**Comment by marktani** [comment]
Thanks a lot for reporting this. 

New projects come with this permission setup by default:

```yml
permissions:
  - operation: "*"
```

This is called the _wildcard permission_, and it allows access to _everyone_ for all read and write operations to your API. This permission is included for new projects to allow for an easy getting started experience and should be removed for production purposes.

We should add an explicit section about the wildcard permission in the docs, thanks for bringing this up 🙂

**Comment by danielglasgow** [comment]
@marktani Thanks for the response! Now I understand that by removing the wild card permission, everything will default to being access restricted!

**Comment by kbrandwijk** [comment]
@marktani Well, it is already documented inside the `graphcool.yml` file:
```
# Model/Relation permissions are used to limit the API access
# To take the burden of thinking about those while development, we
# preconfigured the wildcard ("*") permission that allows everything
# Read more here:
# https://docs-next.graph.cool/reference/auth/authorization/overview-iegoo0heez
```

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this @danielglasgow! 🙌 With the switch to [Prisma](https://www.prismagraphql.com/docs) we're putting all our efforts into the new documentation! Please let us know if you have any questions around the new docs and or need some clarification there 🙂
