### ISSUE TITLE
Intermittent "io.netty.channel.ChannelException" when deploying

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1152]
Looks like under heavy load, an error message

> io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel

is returned when deploying.

Probably related to #595.

**Comment by maxdarque** [comment]
Also getting
```
software.amazon.awssdk.SdkClientException: Unable to execute HTTP request: lambda.eu-west-1.amazonaws.com
```
The issue is intermittent and I can keep hitting graphcool deploy until it works maybe on the 2nd or 3rd time. At the time I'm generally deploying fairly frequently maybe every 2mins as I'm debugging a function

**Comment by marktani** [comment]
This has been resolved earlier.

**Comment by rubelux** [comment]
I am getting this error again:
``` io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel```
thanks

**Comment by rubelux** [comment]
worth noting: I have got it once after months working with Graph.cool but worth bringing it here
