### ISSUE TITLE
Update email-password template in permissions example

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1158]
**Current behavior**
The permissions example here: https://github.com/graphcool/framework/tree/master/examples/permissions uses a version of the email-password template that is not the same as the one here: https://github.com/graphcool/templates/tree/master/auth/email-password. Combined with the fact that it contains a single Typescript version of signup.js adds to the confusion.

**Expected behavior?**
Use the same template.

**Comment by riongull** [comment]
Would be nice to have versions for both typescript and javascript.  We are trying to support simple javascript devs are we not?

**Comment by kbrandwijk** [comment]
Maybe there could be different branches for different languages? That way, the structure stays exactly the same, and we could add as many as we want.
