### ISSUE TITLE
Deploying root tokens with a too long name results in internal server error

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1191]
## Reproduction

See https://github.com/marktani/graphcool-too-long-root-token-name for a reproduction.

## Expected behaviour

A meaningful error should be returned. Also, the name length limit should be documented.

**Comment by kbrandwijk** [comment]
I think this should also be part of #979.

**Comment by kbrandwijk** [comment]
And this also goes for type names, function names etc. and everything else that is supposed to fit into a `varchar(255)` field.
