### ISSUE TITLE
Easily change name of project after it's created

### ISSUE THREAD

**Issue by lunchboxer** [graphcool/prisma#1206]
**What feature are you missing?**
I gave my project a name when when I created it with `graphcool init [project name]`. Now I would like to change it. A command on the CLI or keeping the name of the project in one of the config files like .graphcoolrc would be swell.

**How could this feature look like in detail? Tradeoffs?**
It could be a command like `graphcool rename [new project name]`. Whether or not a command is added to the CLI I'd really like a configuration option in a text file somewhere. At present I can't figure out how to change the name if the project isn't listed in the web console.

**Comment by lunchboxer** [comment]
It looks like this issue is being address here: #1328 
Notice the first line of the new graphcool.yml defines a service by name. Am I correct in reading this as allowing changing of the service name?

**Comment by sorenbs** [comment]
@lunchboxer #1328 changes the unique identifier from an opaque id to a globally unique service name. Simply changing the name in the `graphcool.yml` file would not change the name of the deployed service, but cause the cli to deploy a new service with the same name. We still need a dedicated cli command to rename a deployed service, so let's keep this issue open :-)

It's worth noting that #1329 proposes changing the endpoint url to include the service name, so changing the service name would change the url and break any running application that depends on the old endpoint url.
