### ISSUE TITLE
Suggest singular model names

### ISSUE THREAD

**Issue by heymartinadams** [graphcool/prisma#121]
Small thing, but a reminder when creating a new `Model` to keep the `Model` singular could be helpful.

**Comment by marktani** [comment]
Thanks! I'll work this into an FAQ article soon enough :slightly_smiling_face:

**Comment by BallisticPain** [comment]
@marktani It may also make sense which is more likely what @heymartinadams is suggesting to recognize when someone is pluralizing a model name, and *suggest* at that point to make them singular. If @heymartinadams isn't suggesting that, then I am now. ;)

**Comment by marktani** [comment]
Thanks @BallisticPain, makes sense :+1:

**Comment by sorenbs** [comment]
I like this idea very much

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
