### ISSUE TITLE
GRAPHCOOL_TARGET environment variable is not used as target in some CLI commands

### ISSUE THREAD

**Issue by vtsatskin** [graphcool/prisma#1211]
**Current behavior**

Deploying to a graphcool target works without a `.graphcoolrc` file by setting the environment variable:

```
export GRAPHCOOL_TARGET=local/cj9evgxgm00040174yoi292dw
graphcool deploy
```

However, this is not the case for the following commands which also support a target parameter:

* `graphcool playground`
* `graphcool info`
* `graphcool root-token`
* `graphcool logs`
* `graphcool delete`
* `graphcool invoke-local`

**Reproduction**

1) Delete the `.graphcoolrc` file.
2) Set GRAPHCOOL_TARGET environment variable to a valid target
3) Use one of the aforementioned commands
4) See error:
> Please provide a valid target that points to a valid cluster and service id

**Expected behavior?**

The aforementioned commands respect the `GRAPHCOOL_TARGET` environment variable.

**Discussion**

If the expected behaviour is not desired and this isn't a bug, perhaps I am misunderstanding the intention of the existence of `GRAPHCOOL_TARGET`. I will explain how I use the environment variable in a multiple developer team. I would be interested in knowing how the CLI is designed to be used in my situation.

My team runs a local graphcool cluster when developing locally and deploys to production when the development work is complete. So being able to share production deployment information is important, which is what I believe the intent of the `.graphcoolrc` file is. I assume that this file is intended to be checked into version control and shared with team members.

Using a `.graphcoolrc` file in version control is not optimal in multiple developer projects due to the local target id changing for each developer when they deploy locally. This results in changes to the  `.graphcoolrc` file. However, sharing a common target for production deployment is desirable. The way I've gotten around this issue is to not use a `.graphcoolrc` file, delete it from source control, store environment variables in a file, and load those in a script depending on which environment is desired.

Two environment configuration files are checked into source control:

**.env.production**
```
GRAPHQL_API_ENDPOINT=https://api.graph.cool/simple/v1/<production id> 
GRAPHCOOL_TARGET=<cluster id>/<production id>
```

**.env** (Local, intentionally blank)
```
GRAPHCOOL_TARGET=
GRAPHQL_API_ENDPOINT=
```

While another file is not checked in and used for local configuration by each team member:

**.env.local**
```
GRAPHCOOL_TARGET=local/<local id>
GRAPHQL_API_ENDPOINT=http://localhost:60000/simple/v1/<local id>
```

Then a helper script is used for local and production commands:

**graphcool.sh**
```
set -a
source .env
source .env.local 2> /dev/null # Suppress errors if file not found
./node_modules/graphcool/dist/index.js $*
set +a
```

**graphcool.production.sh**
```
set -a
source .env.production
./node_modules/graphcool/dist/index.js $*
set +a
```

They are used as substitutes for the graphcool globally installed CLI as follows:

```
./graphcool.sh deploy # local deployment
./graphcool.production.sh deploy # production deployment
```

However, as mentioned in the bug report in this issue, other commands will not respect the `GRAPHCOOL_TARGET` environment variable so this set up begins to break down when using other commands.

So what is the intended use of `.graphcoolrc` and `GRAPHCOOL_TARGET` in multiple-developer-single-production-deployment setups? Is there a simpler way of achieving my goals that I'm not seeing?

**Comment by kbrandwijk** [comment]
@marktani Can you confirm that this indeed the intended behavior for all CLI commands that have a target parameter, so we have consensus, and do a PR?

**Comment by vtsatskin** [comment]
Original rationale: https://github.com/graphcool/framework/issues/626

For anyone looking to do a PR on this, I've surfaced the original commit which implemented the behaviour for the deploy command: https://github.com/graphcool/framework/commit/a94ca4db01bcb1f36f28f6b4fcdfcb3b288c2883
