### ISSUE TITLE
Dynamic default values

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#122]
Offer dynamic default values for fields, for example

* auto increment (integer)
* now, an hour ago, ... (timestamps)
* random (strings)

**Comment by sedubois** [comment]
Also some of them may need to be shared across models. E.g on GitHub, identification numbers are shared across issues and PRs for a specific repo (i.e. there can't be simultaneously an issue number 1 and a PR number 1).

**Comment by sorenbs** [comment]
@sedubois Would it be feasible to introduce a separate model to keep track of the shared counter?

**Comment by sedubois** [comment]
Yes as usual, that could work as a first step but is cumbersome. You could start simple and then improve later on.

**Comment by BallisticPain** [comment]
I would also like to suggest very similar to auto-incrementing the id field, I commonly use UUID for my public "primary" keys. A UUID can be generated offline and synced up to the database so in the future when y'all have offline functionality, a UUID field that can be generated on the server if it doesn't come in a request, or accepts the one it's passed.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
