### ISSUE TITLE
Customer support integration

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#123]
- [ ] allow users to add Intercom to their Graphcool app right from the Integrations tab
- [ ] sync Graphcool's user model with Intercom
- [ ] allow to customize the connection (e.g which users shall be taken into account, which [custom attributes](https://docs.intercom.com/intercom-s-key-features-explained/tracking-user-data/tracking-user-data-in-intercom#custom-user-attributes-) to add to each user)
- [ ] allow to hook up custom [events](https://docs.intercom.com/the-intercom-platform/track-events-in-intercom)

If there's any workaround to make this integration possible meanwhile, would be great to know too.

EDIT: could be something else than Intercom, because their pricing is so prohibitive.

**Comment by sorenbs** [comment]
@sedubois Would adding a mutation callback to the user model that syncs the user to Intercom be enough?

Alternatively it would be great if you could specify in more detail what the integration should do.

Regarding custom events - I imagine many interesting events would be triggered on the frontend and never actually hit the Graphcool backend. Do you agree?

**Comment by marktani** [comment]
Maybe you can also use existing integrations like [Intercom with Zapier](https://zapier.com/zapbook/intercom/).

**Comment by sedubois** [comment]
@sorenbs that would be a start yes 🙂 The minimum is to be able to see all the Graphcool users within Intercom (name, email, connection time, etc), paying attention that Intercom can do its work of auto-detecting the user device, location, etc (as it does properly in my current intercom-rails integration).

Yes maybe about events, there could be a separate forwarding directly from the client, but would certainly be useful from backend side too (e.g "user bought X", "user friended Y", etc).

**Comment by sorenbs** [comment]
@sedubois Makes sense - thanks!

In your rails integration I assume the user device detection is handled by the clientside intercom api?

**Comment by sedubois** [comment]
@sorenbs I guess yes but I didn't investigate the inner workings: https://github.com/intercom/intercom-rails

(BTW I also have intercom hooked in iOS and Android, where these detections also work properly.)

But I think they know something about customer support so can ask them 😉

**Comment by sedubois** [comment]
As you point out in your freecom tutorial series, Intercom is super expensive so would be great to support some alternative if possible. Do you have some to suggest?

**Comment by heymartinadams** [comment]
In case of interest, I created a Customer Support feature (from inside the app) and integrated it via Mutation Callback → Zapier email for free. https://www.LifePurposeApp.com

**Comment by marktani** [comment]
This should be pretty straight-forward to build with Graphcool Functions, would love to see some input about this here: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405.

**Comment by heymartinadams** [comment]
Actually, @sedubois, I ended up integrating Intercom. Found it helpful at significantly increasing conversion rates. They have early-stage pricing, which I signed up for: https://www.intercom.com/early-stage

Just added an Intercom example to the functions: https://github.com/graphcool-examples/functions/pull/80

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
