### ISSUE TITLE
Ignore hidden folders when packaging (.git, .vscode etc.)

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1232]
**What feature are you missing?**
Until a more advanced mechanism to either filter or specify which files and folders to include is in place, it would at least be a good idea to ignore all hidden folders (like .git/.vscode). Beware that these are not hidden on Windows...

**How could this feature look like in detail? Tradeoffs?**
Maybe a hardcoded blacklist to start with?

**Comment by marktani** [comment]
Are you saying, ignore all files starting with a dot?

Related to #1198.

**Comment by kbrandwijk** [comment]
Yeah, and to #816. I just tried to create a more feasible short term first step than the general 'make bundling more intelligent', because that's quite a big chunk, and quite far away from `proposal/accepted`.

**Comment by marktani** [comment]
I like the proposal, it provides a simple change with a big impact :+1:
