### ISSUE TITLE
Framework debugging

### ISSUE THREAD

**Issue by Toosick** [graphcool/prisma#1236]
As far as I know debugging is hard. I was able to setup debugging in another Serverless application locally with Serverless offline. How does one go about setting up breakpoints for local clusters? Is this in the pipeline or can debugging already be done?

**Comment by kbrandwijk** [comment]
I use Serverless to deploy all my functions, then I use `serverless run --debug` to run a local AWS API Gateway, and I can attach my Visual Studio Code to the debugger.
This FR asks for more direct debugger support: https://github.com/graphcool/framework/issues/897

**Comment by Toosick** [comment]
@kbrandwijk Ok yeah I thought about just doing it with Serverless until debugging became a thing. So all your functions are used as webhooks?

**Comment by kbrandwijk** [comment]
@Toosick That depends. Functions I use in Graphcool (hooks and subscriptions) are. Most of my resolver functions are placed in my API Gateway nowadays, which I can also easily debug.

**Comment by wdoug** [comment]
@kbrandwijk how do you deploy functions with serverless in such a way that they can interface with graphcool itself? What is your workflow?

**Comment by fredantell** [comment]
@kbrandwijk Are you aware of a write up that exists anywhere that may help someone create a setup like this? This is definitely one of my bigger pain points. Just yesterday I lost a couple hours to a silly error that would've been caught within minutes using a debugger.

**Comment by beebase** [comment]
debugging resolver functions is VERY time consuming.
