### ISSUE TITLE
Can't see function log output in cli

### ISSUE THREAD

**Issue by ylac** [graphcool/prisma#1251]
**Current behavior**
Clicking on output entry in function log displays a white square (Chrome) or scroll buttons (Firefox)  instead of expanding the output. Occurs on Win7 x64.

![function log output](https://user-images.githubusercontent.com/25894581/32694711-f55d5796-c79a-11e7-9b21-d527dc7a194d.png)

**Comment by kbrandwijk** [comment]
Duplicate of https://github.com/graphcool/framework/issues/1073
