### ISSUE TITLE
Expose which users are online - presence channels

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/prisma#126]
When building a multi user application it can be highly interesting if other users are online.
We could detect it with the users that currently have subscriptions or just authenticated users and have a heartbeat.

**Comment by sorenbs** [comment]
Pusher calls this `presence channels` https://pusher.com/docs/client_api_guide/client_presence_channels

It would be helpful if the community could take a detailed look at the Pusher functionality and let us know if that fits your use case.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
