### ISSUE TITLE
gc login doesn't work on CircleCI

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1270]
When running `gc login` in a CircleCI 2.0 environment, I'm seeing the following error:

![image](https://user-images.githubusercontent.com/1567498/32773599-f6bc8810-c929-11e7-9573-2fd237638257.png)

With debugging on:

![image](https://user-images.githubusercontent.com/1567498/32773553-d07b10cc-c929-11e7-98d6-ffbabe4ab163.png)

**Comment by kbrandwijk** [comment]
I think this behavior is by design, because opening a browser in a non-interactive session cannot happen. Using `gc login --token ....` works however, from what I have tested.

**Comment by schickling** [comment]
For debugging purposes, it should still work since the URL is printed and can be copied to a desktop environment.

**Comment by rcy** [comment]
I am running into this problem as well, and unable to get my CI to deploy my backend.

Using `gc login --token $TOKEN` does not work for me.  I thought it was working locally, but then I removed my `~/.graphcoolrc` file and it opens a browser window to authenticate.

My expectation is that with `--token $TOKEN` a web redirect wouldn't be required, and the authentication could be scripted in noninteractive environments.

Tested with versions:
`graphcool/0.8.1 (darwin-x64) node-v8.9.0`
`graphcool/0.9.2 (darwin-x64) node-v8.9.0`

**Comment by kbrandwijk** [comment]
I think you don't need `gc login --token`, but `gc deploy --token`.

**Comment by rcy** [comment]
@kbrandwijk that makes sense, but its definitely not how it is advertised to work.

```
$ gc login --help
Usage: graphcool login [flags]

Login or signup to the Graphcool Platform

Flags:
 -T, --token TOKEN    System token

Note: Your session token will be store at ~/.graphcool
  
  Examples:
      
  - Authenticate using the browser
    $ graphcool login
  
  - Authenticate using an existing token
    $ graphcool login -t <token>
```

And `graphcool deploy --help` says nothing about accepting `--token`

**Comment by kbrandwijk** [comment]
No I'm sorry, `gc deploy` doesn't have a `--token` option, I have updated my answer. For CI purposes, `gc deploy` looks for an environment variable `GRAPHCOOL_PLATFORM_TOKEN`. If that's specified, you don't have to do `gc login` first.

**Comment by schickling** [comment]
@nikolasburk @timsuchanek can you make this more clear in the docs + CLI help text?

**Comment by rcy** [comment]
`DEBUG="*" GRAPHCOOL_PLATFORM_TOKEN="<TOKEN>" gc deploy` still results in opening a browser window for me here.  The last two lines of the output:

```
  environment taking process.env.GRAPHCOOL_PLATFORM_TOKEN as the token +454ms
Auth URL: https://console.graph.cool/cli/auth?cliToken=cja5o4n3t0000un10h3wr9sp0&authTrigger=auth
```

It shouldn't be both taking the token and still redirecting I don't think.

**Comment by kbrandwijk** [comment]
I agree that it shouldn't.

**Comment by mattfysh** [comment]
There is a bug in that the `login` command does not wait for the asynchronous `setToken` action before calling `ensureAuth` - this means that even if you provide a valid token, it is essentially discard - triggering the browser logic.

Created pull request here: https://github.com/graphcool/graphcool/pull/1575
