### ISSUE TITLE
Deploy does not deploy field name changes

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1273]
@JensMadsen commented on [Tue Nov 14 2017](https://github.com/graphcool/graphql-cli/issues/45)

running: graphcool/0.9.2 (linux-x64) node-v8.9.1

changing existing relation (here LawOnLaw) e.g. 

```
lawCites: [Law!]! @relation(name: "LawOnLaw")
lawCitesLaw: [Law!]! @relation(name: "LawOnLaw")
```
is not captured by deploy

**Comment by jaimebiernaski** [comment]
Same problem here...

I tried to change the relation "1-1" to "1-n", but the deploy does not changed the Type...

**Comment by marktani** [comment]
We're looking to improve the available workflows soon. Here's a proposal, I would love to hear your feedback @jensmadsen @jaimebiernaski https://github.com/graphcool/framework/issues/1160#issuecomment-345373277 🙂

**Comment by dohomi** [comment]
same here: I had a typo in the relation name, but after re-deploy the name of my local *.yml and the name of the deployed schema is different without throwing an error
