### ISSUE TITLE
Combined Nested Create/Nested Connect mutation losing existing node associations

### ISSUE THREAD

**Issue by btroia** [graphcool/prisma#1288]
**Current behavior**

Using the following schema and [following the "Combined" nested create/nested connect technique described here](https://www.graph.cool/forum/t/how-do-i-add-an-array-of-objects-to-a-mutation-in-apollo-react/365/6):

```
type Post @model {
  createdAt: DateTime!
  createdBy: User @relation(name: "PostsByUser")
  description: String @defaultValue(value: "''")
  id: ID! @isUnique
  tags: [Tag!] @relation(name: "TagsOfPost")
  ...
}
```

```
type Tag @model {
  id: ID! @isUnique
  tag: String!
  createdBy: User @relation(name: "TagsByUser")
  createdAt: DateTime!
  posts: [Post!] @relation(name: "TagsOfPost")
}
```

Where I have a `Post` type with a `tags` field (many-to-many relationship between `Post`->`Tag`). When I run a mutation to update a `Post`'s tags, there are 2 Graphcool-generated parameters I can include per the API:

<img width="273" alt="schema-2" src="https://user-images.githubusercontent.com/368747/32952294-d09a54e8-cb7a-11e7-90d8-b8c3926785cc.png">

- `tagsIds`: an array of `id`s of existing `Tag`s to be associated with the `Post` (i.e., `["aabbccddeeffgg", "hhiijjkkllmmnn"]`)
- `tags`: array _new_ tags to create and associate with this `Post` (i.e., `[{"tag: "newTag1"}, {"tag": "newTag2"}... ]`)

If I only include `tags` _or_ `tagsIds` in the mutation, it works as expected, i.e. this works (only pass `tags`):

```
const updatePostQuery = ({
  id,
  createdById,
  timestamp,
  description,
  tags,
}) => ({
  mutation: gql`
    mutation updatePost(
      $id: ID!
      $createdById: ID!
      $timestamp: DateTime!
      $description: String
      $tags: [PosttagsTag!]
    ) {
      updatePost(
        id: $id
        createdById: $createdById
        timestamp: $timestamp
        description: $description
        tags: $tags
      ) {
        id
        timestamp
        description
        tags {
          id
          tag
        }
        createdBy {
          id
          username
        }
      }
    }
  `,
  variables: {
    id,
    createdById,
    timestamp,
    description,
    tags,
  },
});
```
And this works (only pass `tagsIds`):

```
const updatePostQuery = ({
  id,
  createdById,
  timestamp,
  description,
  tagsIds,
}) => ({
  mutation: gql`
    mutation updatePost(
      $id: ID!
      $createdById: ID!
      $timestamp: DateTime!
      $description: String
      $tagsIds: [ID!]
    ) {
      updatePost(
        id: $id
        createdById: $createdById
        timestamp: $timestamp
        description: $description
        tagsIds: $tagsIds
      ) {
        id
        timestamp
        description
        tags {
          id
          tag
        }
        createdBy {
          id
          username
        }
      }
    }
  `,
  variables: {
    id,
    createdById,
    timestamp,
    description,
    tagsIds,
  },
});
```

*However*, if I pass both parameters, only the new `Tag`s will be created an associated (`tags`) - the other existing `Tag` ids I pass (`tagsIds`) are _not_ associated:

```
const updatePostQuery = ({
  id,
  createdById,
  timestamp,
  description,
  tags,
  tagsIds,
}) => ({
  mutation: gql`
    mutation updatePost(
      $id: ID!
      $createdById: ID!
      $timestamp: DateTime!
      $description: String
      $tags: [PosttagsTag!]
      $tagsIds: [ID!]
    ) {
      updatePost(
        id: $id
        createdById: $createdById
        timestamp: $timestamp
        description: $description
        tags: $tags
        tagsIds: $tagsIds
      ) {
        id
        timestamp
        description
        tags {
          id
          tag
        }
        createdBy {
          id
          username
        }
      }
    }
  `,
  variables: {
    id,
    createdById,
    timestamp,
    description,
    tags,
    tagsIds,
  },
});
```

**Expected behavior?**

`Post` mutation should result in existing `tagsIds` being associated with the given `Post` when `tags ` parameter values are also included.

**Comment by marktani** [comment]
Thanks! Also interesting for the current proposals here: https://github.com/graphcool/framework/issues/1280

**Comment by marktani** [comment]
A workaround for now is to only use `tags`, then use `addToTagsOfPost` for the existing tags afterwards.

**Comment by btroia** [comment]
@marktani Yes, that's my current workaround, even though it's a bit hacky and inefficient (iterating over an array of existing tag ids and calling the `addToTagsOfPost` mutation repeatedly) 😶

**Comment by marktani** [comment]
Please provide your feedback for this proposal of an improved nested mutation API here: https://github.com/graphcool/framework/issues/1280
