### ISSUE TITLE
Improve working with local logs

### ISSUE THREAD

**Issue by gaurav107** [graphcool/prisma#1297]
**What feature are you missing?**

Currently, while doing local development with docker containers, after a certain period of testing, the logs file becomes very huge. And every time you do `gc logs`, it prints out the entire file which gets hard to navigate.

Instead, there should be a better way to navigate those logs. Here are few of the additional filters that could be added to `gc logs` CLI command that would be useful:

1. `gc logs --delete`: To delete the logs file (with a filter to delete last N events)
2. `gc logs --limit <logs_file_limit_in_KBs>`: To set a limit to logs file with log eviction based on FIFO policy 
2. `gc logs export --path <local_file_path>`: To export logs from container
3. To show only the FAILED events
4. To display last N events with other filter options applied

**Comment by johhansantana** [comment]
any updates on this?
