### ISSUE TITLE
Problem with Graphcool website on Netlify

### ISSUE THREAD

**Issue by InderdeepBajwa** [graphcool/prisma#1303]
For **bug reports**, please fill in the next sections:

**Current behavior**

1. The first bug I observed is that the websites hosted on Netlify are broken. Example link: [How to create an Algolia key](https://www.graph.cool/docs/tutorials/algolia-auto-syncing-for-graphql-backends-aroozee9zu#creating-algolia-search-indices)
2. The second bug is that whenever I try to add Algolia keys to a newly created application, it gives the following error:

> Please check that the Application ID and API Key is correct. You can find both on the API Keys page in the Algolia web interface. You must create a new API Key and enable 'Add records' and 'Delete records'. Make sure that you are not using the Admin API Key, as Algolia doesn't allow it to be used here.

I have developed tons of Netlify and been doing that for more than a year. I can definitely check the website code if you'd like to have contribution on my behalf.

**Comment by marktani** [comment]
I'll update this issue to be about 1., 2. is already covered in #1304. Thanks for the report! 🙂

**Comment by marktani** [comment]
Closing this as the old page is not active anymore.
