### ISSUE TITLE
Nested Mutation operationAfter create hook

### ISSUE THREAD

**Issue by Toosick** [graphcool/prisma#1308]
I have a batch with multiple samples and samples with multiple tests. When I create a batch I expect the operationAfter hook Test.create to invoke, it does not. operationBefore & doing the same logic with a subscription works. operationAfter is the only 1 that doesn't work. Is this on purpose or a bug?

**Comment by steve-a-jones** [comment]
@Toosick - Experiencing this as well. @marktani - is this by design?  If so, what is the rationale? Subscriptions should suffice in the meantime..
