### ISSUE TITLE
Pusher template pushNotification function invocation causes error

### ISSUE THREAD

**Issue by ylac** [graphcool/prisma#1320]
**Current behavior**
Trying to send a push notification to my react-native/test web app via the relevant mutation 

`mutation {
   pushNotification(channels: ["donuts"], event: "la", message: "yo") {
     success
   }
}`

produces an error in the function log: `{"error":"Function returned invalid status code: 0. Raw body: empty.last"}`. Same as in #1031. The notification does appear though, at least for the web app. 

**Reproduction**
Setup Graphcool framework with the Pusher template: https://github.com/graphcool/templates/tree/master/messaging/pusher. 

Setup Pusher. Then send a push notification to a mobile app or the test web app as per the template readme.

**Comment by marktani** [comment]
What's your `graphcool version`? What's your OS?

**Comment by ylac** [comment]
I'm using graphcool@0.9.2 on Windows 7 x64.

**Comment by ylac** [comment]
Any progress on this?
