### ISSUE TITLE
REST API Wrapper example has broken Relay API

### ISSUE THREAD

**Issue by camachojuan** [graphcool/prisma#1327]
**Current behavior**
Using the [REST API Wrapper example](https://github.com/graphcool/framework/tree/master/examples/rest-wrapper), the Relay API is not working, only the Simple API is working.

When trying the example on the Relay API, all queries fail. For example, try:

```
{
  randomDogImage {
    url
  }
}
```

it is responding the following:
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'randomDogImage' on type 'Query'. (line 2, column 3):\n  randomDogImage {\n  ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Using the Simple API, everything works ok.

**Reproduction**

1. Install and run the [REST API Wrapper example](https://github.com/graphcool/framework/tree/master/examples/rest-wrapper).
2. After doing `graphcool deploy`, go to the URL of the Relay API.
3. Try the query:
 ```
{
  randomDogImage {
    url
  }
}
```
4. Receive:
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'randomDogImage' on type 'Query'. (line 2, column 3):\n  randomDogImage {\n  ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Expected behavior?**
The API should return
```
{
  "data": {
    "randomDogImage": {
      "url": "https://dog.ceo/api/img/affenpinscher/n02110627_11759.jpg"
    }
  }
}
```

Maybe the documentation can explain that the Relay API is not working while this is fixed.

**Comment by iamclaytonray** [comment]
The Simple API is much different from the Relay API. Everything you want to query for exists under `Viewer`

```
{
  viewer {
    randomDogImage {
      url
    }
  }
}
```

**Comment by iamclaytonray** [comment]
If you look in the docs (from the Playground), you will see all of your possible queries/mutations/subscriptions/etc. Make sure to check those when you're confused. (When I first started with GraphQL, I forgot to do that myself, which cost a lot of time + confusion.)

**Comment by jcamachocds** [comment]
Awesome. It's working ok.
I'll do a PR to point this out in the documentation. I think it can be useful.

This issue can be closed now.
Thanks.

**Comment by iamclaytonray** [comment]
I would, perhaps, just point to Relay docs so we don’t have to maintain them

**Comment by jcamachocds** [comment]
I agree. I'll do that.
