### ISSUE TITLE
Directive to change root field plural form and case sensitivity

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1342]
By default Graphcool uses a inflector library ([evo-inflector](https://github.com/atteo/evo-inflector)) to pluralize types (example: `User` -> `Users`). This approach only works for the english language and sometimes doesn't produce the desired results.

Also when it comes to generating the casing for root fields there might be edge cases where this approach falls short (example: `type API` -> `Query.aPIs`).

In these cases there should be a directive available to influence the name generation. Here is a suggested API:

## Before

```graphql
# data model
type Index {
  id: ID! @unique
}

type APIToken {
  id: ID! @unique
}

# generated API
type Query {
  index: Index
  indexes: [Index!]!
  apitoken: APIToken
  apitokens: [APIToken!]!
}
```

## After

```graphql
# data model
type Index @queries(many: "indices") {
  id: ID! @unique
}

type APIToken @queries(one: "apiToken" many: "apiTokens") {
  id: ID! @unique
}

# generated API
type Query {
  index: Index
  indices: [Index!]!
  apiToken: APIToken
  apiTokens: [APIToken!]!
}
```

## Open questions

- [ ] Terminology: Is there a better directive name than `@queries`?

**Comment by kbrandwijk** [comment]
This probably covers https://github.com/graphcool/framework/issues/604, so I'm okay to close that one.
