### ISSUE TITLE
Console logging an Error causes {"error":"Function returned invalid status code: 0. Raw body: empty.last"}

### ISSUE THREAD

**Issue by radicand** [graphcool/prisma#1359]
If an error during a function is encountered, and one attempts to log the error with `console.log(e)` (where e is an Error object), then the framework will instead log a generic `{"error":"Function returned invalid status code: 0. Raw body: empty.last"}`.

There's a possibility it may just be that logging an Object in general causes this, but I haven't tested that.

**Reproduction**
Initialize a new project, and create a function that throws an error in a try block. Catch it and attempt to console.log the error. You can also try applying the google auth template, and calling googleAuthentication with a bad token (which will trip into this logic path).

**Expected behavior?**
The Error to be logged.

Possibly related issues:
- #1320 

Moved from:
- #1031

**Comment by chinclubi** [comment]
I  also have this error message too
```
{ error: "Function returned invalid status code: 0. Raw body: empty.last" }
```
this issue has disappeared after `console.log` is removed.
is there any progress on this issue??

**Comment by marktani** [comment]
Do you have any insights into the shape of the error object?

Could you try running `console.log(JSON.stringify(e)` instead?

**Comment by mark-james** [comment]
I'm also getting this error fairly regularly. I've updated all my error handling and console logs to use e.message. There are no JSON.stringify calls anywhere in the function.

This issue is very frustrating as debugging becomes very time consuming.

**Comment by grimunit** [comment]
I have been getting the same error. I've been using the stripe integration code from the webshop example. The very first `console.log(event);` is what seems to be what was causing it. Once I commented that out I started actually getting the correct errors/logs coming through.

**Comment by sbornia** [comment]
Happening to me also only on the remote service, not locally. Error goes away when logging `error.message` instead of `error`

**Comment by dohomi** [comment]
I was having this issue due to a swolloed hard error on a synchronous function. I was using `jwt.sign` synchronous, after changing the code to promise based handling the error was printed out correctly

**Comment by heymartinadams** [comment]
Happened to me, too. Once I got rid of all ```console.logs``` such as ```console.log(`Created stripe customer: ${customer.id}`)``` the CLI showed the errors correctly.

**Comment by juanpprieto** [comment]
thanks @heymartinadams !
Found this same problem on shared cluster deployments. (Local was ok).
Solved it by adding a debug flag to all my console.logs.

**Comment by grimunit** [comment]
@juanpprieto do you mind posting an example of what setting the debug flag on the console.logs looks like. Or do you have a link to the NodeJS documentation that shows how to use it? I was unable to find the concept in the Node docs 😅

**Comment by juanpprieto** [comment]
Sure @grimunit
// 1. Define a debbuging flag
`const debug = false;`

// 2. Do a Find/Replace for  "console.log" > "if (debug) console.log"
i.e: if (debug) console.log('obj', obj);
