### ISSUE TITLE
Filestack/Cloudinary module

### ISSUE THREAD

**Issue by acorcutt** [graphcool/prisma#138]
It would be nice to be able to use [filestack.com](http://www.filestack.com) as an alternative to your file api for large file uploading and also allow on-demand image and video processing through a query such as 

```
{
  someFile {
     originalUrl
     mime
     previewImage: transform(format:'jpg', width:300, height:200, crop:'fit')
     largeImage: transform(format:'jpg', width:3000, crop:'limit')
  }
}
```

**Comment by sedubois** [comment]
How does it compare to e.g cloudinary?

**Comment by acorcutt** [comment]
I'm currently using a combination of uploadcare to handle uploads and cloudinary for processing... uploadcare has a nice uploader but does not support video transcodes, cloudinary supports video and other file processing but only has a basic uploader.

It looks like Filestack is the best of both, it has a nice uploader and supports video, audio and other doc transforms. It might be easier to integrate without needing extra backend hooks to store or import... just store the file id from the client side upload and query the api for on-demand transforms?

**Comment by sedubois** [comment]
FYI Graphcool already has a basic image size transform: https://www.graph.cool/docs/reference/platform/file-management-eer4wiang0/#image-api

**Comment by marktani** [comment]
A filestack and cloudinary module could be added to https://github.com/graphcool/modules. In https://github.com/graphcool-examples/functions/, there's already an cloudinary example.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
