### ISSUE TITLE
Following Node.js example throws error

### ISSUE THREAD

**Issue by mssngr** [graphcool/prisma#1384]
**Current behavior**
Following instructions from: `https://github.com/graphcool/framework/tree/master/examples/node-gateway-custom-schema` leads to an error. The instructions say to enter
```
curl https://codeload.github.com/graphcool/framework/tar.gz/master | tar -xz --strip=2 framework-master/examples/node-gateway-custom-schema
```
into your terminal. However, the operation exits due to an error:
```
tar: graphcool-master/examples/node-gateway-custom-schema: Not found in archive
```

**Reproduction**
- In your terminal, enter the above mentioned command.

**Expected behavior?**
Not receiving an error and the GitHub folder downloading to your local computer.

**Comment by beebase** [comment]
Same for auth example
```
curl https://codeload.github.com/graphcool/framework/tar.gz/master | tar -xz --strip=2 framework-master/examples/auth
cd auth
```

**Comment by marktani** [comment]
Both has been updated 🙂
