### ISSUE TITLE
Automatically create a user if a request is made with an unknown Auth0 id token

### ISSUE THREAD

**Issue by lpil** [graphcool/prisma#140]
Using the Auth0 lock widget with just the single sign on there is no way of knowing if the user is new or existing, so there is no clear point at which to perform `createUser`.

Currently I'm looking at running `createUser` always and catching the error.

On slack @sorenbs suggested that possibly we would able to use the id_token directly in the Authorization header, and Graphcool automatically creates a user if doesn’t exist. This seemed like the ideal solution to me. :)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by lpil** [comment]
Where is it there @marktani ? I wish to follow the issue but I can't find it there.

**Comment by marktani** [comment]
Here it is: https://github.com/graphcool/graphcool-framework/issues/43 🙂

**Comment by lpil** [comment]
Thanks!
