### ISSUE TITLE
RelayId Tab

### ISSUE THREAD

**Issue by mavilein** [graphcool/prisma#1412]
For **bug reports**, please fill in the next sections:

**Current behavior**
Currently the RelayIdTable maps globally unique ids to model names. This fails with the following exception as we have a size limit of 25 chars on the column:

```
Caused by: java.sql.SQLException: Data too long for column 'modelId' at row 1
Query is: insert into `cloud-api@dev`.`_RelayId` (`id`,`modelId`)  values (?,?), parameters ['cjbcglwa500hp0177zc5ejo9e','ClusterProvisionRequestProgress']
```

I did not consider the RelayIds at all when removing the model id. We should reintroduce stable ids for the sole purpose of using in the RelayId table. If we would use the model name instead, we would have to update all the rows in this table on each model rename.

**Comment by marktani** [comment]
Has been fixed 🙂
