### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#1417]
Prisma 1.0 will have the following endpoints:

### Cluster

**local and private clusters:**

`/[service]/[stage]` called the Prisma api. Or service GraphQL API
`/cluster` Previously called the deploy or system api
`/[service]/[stage]/import` called the import API
`/[service]/[stage]/export` called the export API

**development clusters:**

As these clusters are shared between all Prisma Cloud users we need to include the globally unique workspace slug in the url:

`/[workspace]/[service]/[stage]` called the Prisma api. Or service GraphQL API
`/cluster` We need to consider how to limit this for the dev cluster
`/[workspace]/[service]/[stage]/import` called the import API
`/[workspace]/[service]/[stage]/export` called the export API

> note: for now we keep the import/export api undocumented and encourage people to use the CLI as the only interface

#### urls

Ideally we should automatically configure dns and ssl for clusters:

`[cluster].[workspace].prisma.cloud`

### Cloud

This API is undocumented

#### Open Questions
- [ ] Should we set up Lets Encrypt for DO clusters? How?
- [ ] Should we also use Lets Encrypt for AWS clusters?
- [ ] Can we use Route 53 to set up subdomains? They have a default limit of 10.000 resources in a record set.

**Comment by dpetrick** [comment]
- What are the implications for project name + stage name uniqueness? Is uniqueness of a project now three dimensions (name, stage, workspace)?
- `/cluster` does virtually nothing related to clusters. A cluster is a system of several services / machines and thus a higher-level architectural concept that has nothing to do with deploying a database schema. This endopint would make sense in the platform API, but certainly not in an individual cluster.

## urls
`[cluster].[workspace].graphcool.cloud` should be `[workspace].[cluster].graphcool.cloud` to have a hierarchy that makes sense.

**Comment by sorenbs** [comment]
A bit of clarification:

1) A workspace is a virtual construct that contains users and clusters. All users in a workspace are allowed to deploy to all clusters in a workspace. A cluster will only be in a single workspace.

> The shared dev clusters are an exception that should not influence our design.

2) Nothing is called a project anymore. What used to be called project is now called service

3) As clusters are in one workspace only they do not need to know about the workspace component in the unique identifier.

4) A cluster (no matter how many services it contains or how many servers it is running on) has a single api that is responsible for managing the services running on this cluster. This api I propose we call `/cluster`

Are you suggesting that we add a deploy endpoint per service like this?

`/my-service/dev/deploy`

That would align with the import/export apis, but would require us to find a new home for listing all services, getting the cluster version among other things.

**Comment by dpetrick** [comment]
I still want a single endpoint for deployment, but do not want it to be called `/cluster`, as it is conveying the wrong idea of what it does. Taking `/deploy` as an alternative for the sake of the argument, the semantics are as follows: A _cluster_ is some opaque deployment unit, which can be _deployed to_, i.e. schemas. Having an endpoint `/deploy` *on a cluster* is simply the correct semantic, as you deploy your stuff to the cluster. If you have an endpoint `/cluster`, it implies that it is some kind of management interface or meta endpoint, which it is not, it only deploys. We're mixing terminology for different abstraction levels (again...).

**Comment by sorenbs** [comment]
Local and private cluster part of this is implemented

**Comment by marktani** [comment]
Closing this, as most has been implemented [in Prisma 1.0](https://github.com/graphcool/prisma/releases/tag/1.0.0). We'll add more documentation about this soon.
