### ISSUE TITLE
Delayed function invocation - cron jobs

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#142]
For now, external services like [webtask cron](https://webtask.io/docs/cron) are a great alternative.

**Comment by marktani** [comment]
For now, a cron job is a decent workaround. You can use [webtask cron](https://webtask.io/docs/cron) for example, and run a function periodically.

**Comment by kbrandwijk** [comment]
+1

**Comment by CameronK** [comment]
+1 as well

**Comment by dkh215** [comment]
+1

**Comment by brielov** [comment]
+1

**Comment by caeruscaerus** [comment]
+1
This would make building full apps so much simpler and maintainable.

**Comment by Aathi** [comment]
+1

**Comment by bayukp** [comment]
+1

**Comment by MarkLyck** [comment]
+1

**Comment by Zuzle** [comment]
+1

**Comment by the-simian** [comment]
+1 this is, in my mind, something **essential** to being able to fully replace a standard server with this architectural approach

**Comment by kbrandwijk** [comment]
Given how well Graphcool fits into a serverless architecture (AWS, webtask, or any of the other providers, useful for deploying resolver functions and other external endpoints as well), I strongly feel that making this built-in functionality should not be a priority.

**Comment by dardub** [comment]
@kbrandwijk Right now I have a scheduler in webtask.io, which means I have to have implementations for the same service split between two separate service providers. Maybe, I'm missing something, but this doesn't seem like good serverless architecture.

**Comment by jvbianchi** [comment]
Is this planned for 1.0 (#353)?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by kurt-o-sys** [comment]
+1

absolutely necessary. webtask cron isn't always a solution, if e.g. one needs to fetch new tokens (due to expiry dates) that are necessary to authorize api calls to external services. Please please...

**Comment by anaibol** [comment]
+1
