### ISSUE TITLE
Updates to secret or disableAuth is not executed

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1433]
In 1.0, when I change my secret in my graphcool.yml and try to deploy, it tells me that my service is already up to date and refuses to deploy.

graphcool/1.0.0-alpha4.2.4 (windows-x64) node-v9.0.0

Update: as it seems, the authentication is updated after all, just not reported.

**Comment by kbrandwijk** [comment]
By the way, I did _not_ test if the secret gets updated when I deploy it 'together' with another change.

**Comment by sorenbs** [comment]
@kbrandwijk Even though it is reported that no changes were detected, the secret change should still take effect. Is this not the case for you? 

Have you tried with the latest 4.2 beta?
Are you deploying to the `local` cluster?

**Comment by kbrandwijk** [comment]
I'm deploying to the shared eu cluster using graphcool/1.0.0-alpha4.2.4

**Comment by kbrandwijk** [comment]
Retested it again, and the security is actually updated. Leaving this one open because that definitely needs a user feedback message in the output.

**Comment by marktani** [comment]
Ah, so it says "Service already uptodate", but the secret is actually changed, right?

**Comment by kbrandwijk** [comment]
Yes, and especially: switching between `disableAuth: true` and a secret also works like this, without any warning.

**Comment by terion-name** [comment]
$ prisma -v
prisma/1.0.4 (darwin-x64) node-v9.4.0

disableAuth has no effect

run prisma in

- it hello-world
- setup a simple ts demo project with local cluster
- run prisma deploy
- open playground on http://localhost:4466/hello-world/dev and see token error
- set disableAuth: true in prisma.yml, comment out secret: mysecret123
- comment out secret: ‘mysecret123’ in index.ts
- run prisma deploy
- nothing changes

**Comment by timsuchanek** [comment]
In the latest cluster version (`1.0.1`), the change of whether `disableAuth: true` or `secret: mysecret` is used, is ONLY propagated, if there are changes on the data model.
Otherwise, the change is not applied.

**Comment by sorenbs** [comment]
@timsuchanek and @do4gr please coordinate so we can ship https://github.com/graphcool/prisma/pull/2021 :-)

**Comment by marktani** [comment]
This is now fixed and available in `1.4.0` 🙂The CLI will be updated to actually print the update soon (check #2084).
