### ISSUE TITLE
Relative imports not correctly resolved for dry run

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1456]
**Current behavior**

Relative imports, such as 
```
const serviceAccount = require('./data.json')
```

is not correctly resolved when doing `--dry-run`. Error message:

> :heavy_multiplication_x: Could not create serverless function for ‘myFunction’. Ensure that the code is valid

It works when normally deploying, however.

**Comment by michaelspeed** [comment]
i found a solution - 
 place firebase key in yml

`firebaseAuthentication:
     type: resolver
     schema: 
     handler:
       code: 
         src: src/firebase/firebaseAuthentication.ts
         environment:
           firebasekey:
             '{
               "type": "service_account",
               "project_id": "",
               "private_key_id": "",
               "private_key": "",
               "client_email": "",
               "client_id": "",
               "auth_uri": "",
               "token_uri": "",
               "auth_provider_x509_cert_url": "",
               "client_x509_cert_url": ""
             }'`

and then from ts accessing it like this  - 

`const serviceAccount = process.env['firebasekey'];`

**Comment by dohomi** [comment]
This issue is quite frustrating if you share code between resolver functions. @michaelspeed your solution is good for simple things like keys but not if you want to require more complex code.
