### ISSUE TITLE
Reorder fields

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#15]

**Comment by marktani** [comment]
This could be elegantly solved by using the order in the [project's schema file](https://www.graph.cool/docs/reference/cli/project-files-ow2yei7mew/).

**Comment by CameronK** [comment]
@marktani Would love to see the ability to do this via the schema file.

Along with re-ordering, I would appreciate being able to add comments to my schema that are persisted between changes. Right now, any re-ordering or comments added are overwritten after saving via the schema editor UI.

**Comment by kbrandwijk** [comment]
Well, according to the GraphQL spec, query result fields are *unordered*, so there's really no use for changing the order...

**Comment by marktani** [comment]
This is about the order of fields as shown in the databrowser and elsewhere in the console 🙂

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
