### ISSUE TITLE
Expose local mysql DB on port 3306

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1508]
Currently, it's exposed on port `7777`.

Edit: this might be a problem with running `gcf` and `gc` side-by-side:

```sh
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                      NAMES
78ef2ebde5a1        graphcool/graphcool-dev:1.0.0-beta3.3   "/app/bin/single-s..."   2 hours ago         Up 2 hours          0.0.0.0:60001->60001/tcp   localdatabase_graphcool-database_1
5d96791bba2c        mysql:5.7                               "docker-entrypoint..."   7 hours ago         Up 7 hours          0.0.0.0:7777->3306/tcp     graphcool-db
dccdcacf542a        graphcool/graphcool-dev:0.11.1          "/app/bin/single-s..."   27 hours ago        Up 27 hours         0.0.0.0:60000->60000/tcp   local_graphcool_1
c884aff04876        graphcool/localfaas:0.11.1              "/app/bin/localfaas"     27 hours ago        Up 27 hours         0.0.0.0:60050->60050/tcp   local_localfaas_1
6929cc6625c5        mysql:5.7                               "docker-entrypoint..."   2 weeks ago         Up 7 days           3306/tcp                   local_graphcool-db_1
```

note that `local_graphcool-db_1` is running on port `3306`, while `graphcool-db` is running on port `7777`.

**Comment by marktani** [comment]
This is probably related to #1475. My stance is to use the same logic  for the `mysql` port as for the `graphcool-dev` port.

**Comment by kbrandwijk** [comment]
The problem with that is that the database port falls in a way more restricted range... You can't just 'pick the next one' in that range...

**Comment by cupliz** [comment]
@marktani 

How you point `local_graphcool-db_1` to specific docker container? 
Because when i change published port in docker container `local_graphcool-db_1`, it will create a new container different ID with the same name. so, when run `graphcool local ps`,  container `local_graphcool-db_1` is missing

```sh
docker   Name                 Command           State            Ports
docker   -----------------------------------------------------------------------------
docker   local_graphcool_1   /app/bin/single-server   Up      0.0.0.0:60000->60000/tcp
docker   local_localfaas_1   /app/bin/localfaas       Up      0.0.0.0:60050->60050/tcp
```

**Comment by timsuchanek** [comment]
Graphcool already exposes the port on 3306. To avoid port conflicts, prisma now exposes the db port on 3307.

@cupliz if you want to change the port, the best approach is to use docker-compose yourself.
Here you can see the `docker-compose.yml` use in the CLI:
https://github.com/graphcool/prisma/blob/master/cli/packages/prisma-cli-core/src/commands/local/docker/docker-compose.yml
These are the env vars:
https://github.com/graphcool/prisma/blob/master/cli/packages/prisma-cli-core/src/commands/local/docker/env

If this is not working - we will pretty soon publish a guide on how to run docker-compose with Graphcool/Prisma on your own.
