### ISSUE TITLE
Cannot get self-relation with reverse field working.

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1520]
Thanks to doeke for reporting this bug here: https://www.graph.cool/forum/t/1-0-self-relation-with-reverse-field-errors/2066?u=nilan
```
Cannot get self-relation with reverse field working.

    type DataRow @model {
      id: ID! @unique
      mergedInto: DataRow
      mergedFrom: [DataRow!]!
    }

Deploy:

    DataRow
    × The relation field `mergedInto` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    × The relation field `mergedFrom` must specify a `@relation` directive: `@relation(name: "MyRelation")`

Next I tried with relation directive specified

    type DataRow @model {
      id: ID! @unique
      mergedInto: DataRow @relation(name: "MergeRelation")
      mergedFrom: [DataRow!]! @relation(name: "MergeRelation")
    }

Deploy:

    DataRow
    × A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'MergeRelation'
    × A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'MergeRelation'

What does work is if I leave out the reverse field:

    type DataRow @model {
      id: ID! @unique
      mergedInto: DataRow
    }
```

**Comment by pie6k** [comment]
I'm having the same issue. My schema causing it is:

```
type User {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  email: String! @unique
  followers: [User!]! @relation(name: "Following")
  follows: [User!]! @relation(name: "Following")
}
```

resulting in error:

```
Deploying service `XXXXX` to stage `dev` on cluster `local`... 29ms
Errors:

  User
    ✖ A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'Following'
    ✖ A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'Following'
```

**Comment by mvaivre** [comment]
The issue is still in Prisma and is unfortunately blocking my migration from Graphcool 0.x. Can't wait to be able to get Prisma to work :)

**Comment by wolszczak96** [comment]
does [e33c780](https://github.com/graphcool/prisma/commit/e33c780f9670bfe668e6e7900df0f902432d64e2#diff-bb95e5961e50ec285b9c75d029fe5e2d) and [9caf33e](https://github.com/graphcool/prisma/commit/9caf33ec9907308bef8d060edea2e82da6f7512b#diff-bb95e5961e50ec285b9c75d029fe5e2d) fix that issue? I'm still getting "1 or 2 times" error after update

**Comment by marktani** [comment]
Yes, this is supposed to be fixed in `1.0.11`. Do you have a reproduction?

I just tried to deploy this datamodel:

```graphql
type User {
  id: ID! @unique
  name: String!
}

type DataRow {
  id: ID! @unique
  mergedInto: DataRow @relation(name: "MergeRelation")
  mergedFrom: [DataRow!]! @relation(name: "MergeRelation")
}
```

It was successfully deployed to `prisma-us1` and `local`. You might need to run `prisma local upgrade` to pull the latest Docker image 🙂

**Comment by wolszczak96** [comment]
`prisma local upgrade` fixed my problem, thx

**Comment by johannpinson** [comment]
@marktani:

To go futher from the @pie6k exemple, is this wrong?

```
type User {
  id: ID! @unique
  email: String! @unique
  ...
  follwers: [User!]! @relation(name: "UsersFollowers")
  following: [User!]! @relation(name: "UsersFollowing")
}

```

**Comment by marktani** [comment]
This is now fixed in the latest release.

@johannpinson I am not sure what you mean exactly, can you elaborate your question? 🙂

**Comment by johannpinson** [comment]
In my own schema, to avoid 2 relation with the same name like "UserFollows", I add two different name for the self-relation (so "UserFollowers" and "UserFollowing").

I would like to know if it's a bad idea?

**Comment by marktani** [comment]
Both approaches result in different data models 🙂 Which one is the better choice in a concrete context is better discussed [in a new question in the Forum](https://www.graph.cool/forum/c/questions).
