### ISSUE TITLE
Data import from CLI does not work in 0.11.4

### ISSUE THREAD

**Issue by nickluger** [graphcool/prisma#1535]
**Current behavior**

`gcf import --source ./seed.zip` leads to:

```shell config definitionPath null +0ms
  config homepath /Users/xxx/.graphcoolrc +0ms
  config localRCPath /Users/xxx/xxx/xxxx/.graphcoolrc +0ms
  config globalRCPath /Users/nick/.graphcoolrc +0ms
TypeError: Cannot read property 'modules' of undefined
    at Import.<anonymous> (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/src/commands/import/index.ts:39:47)
    at step (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:42:23)
    at Object.next (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:23:53)
    at fulfilled (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:14:58)
    at <anonymous>
Exiting with code: 1
```

**Reproduction**

I'm using `graphcool-framework/0.11.4`. It's installed globally. This error happens for any zip file. Even if i put a movie in it, so i assume its not a problem with the data...

**Expected behavior?**

It should import data correctly.

**Comment by marktani** [comment]
Could you please provide a minimal example that reproduces this error? 🙂 

It should contain

* a `graphcool.yml` and `types.graphql` file
* an `seed.zip` file

Thanks!

**Comment by Nikica-Luger** [comment]
I'm sorry, i was invoking the command from another directory. The error is resolved, if invoked from the project folder. 

But even if i get no error message now, 

**no data gets imported, if i zip the files manually** 

using any zip tool.

You can check this out:  https://github.com/Nikica-Luger/graphcool-manual-zip-error

The file `export-2018-01-08T05/13/08.150Z.zip` can be imported, as it was the original file, exported by, i assume, this tool: https://github.com/graphcool/graphcool/blob/df3765220ff6c049e99369a76676d2b1e746cd5c/cli/packages/graphcool-cli-core/src/commands/export/Exporter.ts

The file `seed.zip` was created by unzipping `export-2018-01-08T05/13/08.150Z.zip` and simply rezipping it via `zip`. 

If you `gcf import --source seed.zip`, you get no error, but there is no data imported neither..

**Comment by Nikica-Luger** [comment]
I'm currently using this for seeding. I have a seed directory checked out in source control and would like to seed the database using something like `zip -r ...  && gcf import ...`. If there is a smarter or alternative way to [seed the db](https://github.com/graphcool/graphcool/issues/1536), i would be happy to know. 😄

**Comment by jharmon141** [comment]
I get this error when running `prisma import --data ./data.zip`:

```
raven@2.3.0 alert: failed to send exception to sentry: HTTP Error (413): undefined
Error: invalid signature: 0xa
    at /usr/local/lib/node_modules/prisma/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```

**Comment by WirthAware** [comment]
Same here: 

```
graphcool import --source data/<name>.zip --target <target_name>

Unzipping... ⣯
raven@2.4.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
Error: invalid signature: 0x80014
    at /<project>/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by marktani** [comment]
Thanks @WirthAware, can you share this information here: https://github.com/graphcool/graphcool-framework/issues/451?
