### ISSUE TITLE
Define Views for the Databrowser

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#154]
it's basically a combination of running queries in the playground and filtering in the data browser.

**Input:** any `allModel` query, using all available query arguments like `first`, `orderBy` or `filter`.

**Output:** the databrowser populated with the fields of the corresponding model showing the results of the above query

I'm not sure how to handle nested fields in the query, but they could be simply disabled at the start.
I think this could be very interesting on it's own, but also in combination with #94. You could define views for your collaborators that only have read access.

**Comment by ejoebstl** [comment]
I agree, but I'd rather design it as *using the grid view of the data browser in the playground*.

That seems more straight-forward, at least if you're used to other DB management tools.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
