### ISSUE TITLE
[1.0/RC1] generated file breaking with tick (`) in comment

### ISSUE THREAD

**Issue by philcockfield** [graphcool/prisma#1585]
[Posted in forum here](https://www.graph.cool/forum/t/1-0-rc1-generated-file-breaking-with-tick-in-comment/2133)

Version:
      - graphql-cli@`2.10.1`

When generated the `graphcool.ts` during a deploy (via `graphql prepare`) the file being generated contains:

    const typeDefs = `
    # THIS FILE HAS BEEN AUTO-GENERATED BY THE "GRAPHCOOL DEPLOY"
    # DO NOT EDIT THIS FILE DIRECTLY
    ...

On line 503 of my generated file, it is inserting some boilerplate documentation for `Long` which includes ticks, and therefore breaks the containing tick-marks of the template string:

    """
    The `Long` scalar type represents non-fractional signed whole numeric values.
    Long can represent values between -(2^63) and 2^63 - 1.
    """
    scalar Long

This results in `graphcool.ts` causing typescript build errors, eg:

![image](https://user-images.githubusercontent.com/185555/34863110-8553096a-f7d2-11e7-8521-6ed5d7bb2742.png)

**Comment by philcockfield** [comment]
## Solution?
Escape tick marks in all boilerplate documentation before writing into the file?

    """
    The \`Long\` scalar type represents non-fractional signed whole numeric values.
    Long can represent values between -(2^63) and 2^63 - 1.
    """

**Comment by gjungb** [comment]
@marktani @philcockfield This has been solved in https://github.com/supergraphql/graphql-static-binding/pull/51

**Comment by marktani** [comment]
Thanks for the heads up @gjungb 🙏
