### ISSUE TITLE
graphql create service name bug 

### ISSUE THREAD

**Issue by ragzor** [graphcool/prisma#1588]
**Current behavior**
graphql create command of the graphql cli creates a new project with a service name as "." when a directory name is not entered.

**Reproduction**

1. Run `graphql create`
2. Do not enter a directory name and hit enter
3. Select a boilerplate project (node-advanced in my case)
4. Select cluster

CLI throws the following error:

![image](https://user-images.githubusercontent.com/1730252/34866558-f5632990-f7a2-11e7-852b-20b22efcefbf.png)

This is happening because the script generates a service name as "." in the **graphcool.yml** file. It should, in turn, generate a valid name to avoid confusion.

**Versions of graphcool and graphql-cli**

graphcool: graphcool/1.0.0-beta4.1.1
graphql-cli: 2.10.1

**Comment by marktani** [comment]
This was fixed a while ago.
