### ISSUE TITLE
Feature(Docs): Add section for all custom Scalar types

### ISSUE THREAD

**Issue by iamclaytonray** [graphcool/prisma#1591]
For **feature requests**, please fill in the next sections:

**What feature are you missing?**
I am proposing a list of custom Scalar types that Graphcool implements, a description of that type, the data struct that the type implements, and it's use cases along with examples. This may already exist, and if so, can we add a section in the sidebar dedicated specifically to Scalar types from GC?

**How could this feature look like in detail? Tradeoffs?**
No tradeoffs.

**Comment by iamclaytonray** [comment]
I can submit a PR for this after I am done with my current PR for `examples/subscriptions`

**Comment by iamclaytonray** [comment]
@marktani - I'm going to go ahead and get a rough draft sent over. Do you have any additional thoughts toward this? 

@kbrandwijk? @schickling? Others?

**Comment by marktani** [comment]
Hey @iamclaytonray thanks a lot for this!
I'd love to see a draft, thematically I think this sort of content fits best to the [Data Modeling chapter](https://www.prismagraphql.com/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u).

**Comment by iamclaytonray** [comment]
Awesome. I'll throw that in there. Thanks!

**Comment by iamclaytonray** [comment]
@marktani - Is there a specific branch you want me to use? `db-docs`? `reference-docs`? `master`?

**Comment by iamclaytonray** [comment]
Oh, okay. So doesn't look like there is much to do. I'm going to go ahead and close this issue since it's already in the docs!

**Comment by iamclaytonray** [comment]
@marktani - I think the wording is fine. Maybe I should get a new pair of glasses 😂
