### ISSUE TITLE
`@default` doesn't work in "create" part of upsert

### ISSUE THREAD

**Issue by ForsakenHarmony** [graphcool/prisma#1593]
**Current behavior**
If you use `@default` to add a default value to a field it works when you use create, but not when using upsert

**Reproduction**
Add `@default` to a field and try to create with upsert, leaving out the field

**Expected behavior?**
upsert should use default values

**Comment by marktani** [comment]
I'm not sure if I'd agree with the expected behaviour you propose. For now, the default value is only reflected in create mutations and I think that's how it should be.

**Comment by ForsakenHarmony** [comment]
Why should it not work in upsert?

**Comment by Huvik** [comment]
Yea, i was thinking same. But only for `create` part of upsert

**Comment by marktani** [comment]
Ah, yea I agree 🙂

**Comment by ForsakenHarmony** [comment]
Obviously just for the create part, doesn't make sense to reset to the default value everytime ig

**Comment by do4gr** [comment]
Thanks for reporting this @ForsakenHarmony. I was able to reproduce and fix this. I will close this issue once the fix is rolled out.
