### ISSUE TITLE
cli does not pick up login

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1608]
Running `graphcool login`, getting the login page. Logging in for the first time. Console is still spinning with authenticating...

Cancel and retry. Now web page asks me to authenticate the CLI. This time, CLI picks it up.

Apparently, the flow does not complete succesfully the first time (after logging in, I go to the clusters page)

**Comment by sorenbs** [comment]
I believe this is now fixed. Please reopen if not :-)

**Comment by kbrandwijk** [comment]
Instead, I'm getting an error now:
```
Authenticating !

ERROR: Unexpected end of JSON input

{
  "data": {
    "cloudTokenRequest": null
  },
  "errors": [
    {
      "message": "Unexpected end of JSON input",
      "locations": [
        {
          "line": 2,
          "column": 7
        }
      ],
      "path": [
        "cloudTokenRequest"
      ],
      "code": 222
    }
  ],
  "status": 200
}
```

**Comment by marktani** [comment]
I close this due as I believe it's fixed now. Please create a new issue if you're still encountering this.
