### ISSUE TITLE
[1.0] Only able to create to-many Nodes using `id`

### ISSUE THREAD

**Issue by hoodsy** [graphcool/prisma#1616]
**Current behavior**
When creating a new Node in a relation, only able to use the `id` field instead of other `@unique` fields:

```js
  async createClass(parent, args, ctx, info) {
    const auth0Id = await parseUserAuth0Id(ctx)
    const user = await ctx.db.query.user({
      where: { auth0Id }
    })
    return await ctx.db.mutation.updateUser({
      where: { id: user.id },
      // where: { auth0Id },
      data: {
        taughtClasses: {
          create: [{ ...args.data }]
        }
      }
    })
  }
```

Error when using the unique field `auth0Id` vs `id` is: `Error: The given id 'facebook|10155255936088549' is invalid.`

**Comment by do4gr** [comment]
Thanks for reporting this @hoodsy . I could reproduce and fix this. This should be resolved with the next release. Same goes for the other issue you reported. I will close both issues once the fixes are released.

**Comment by hoodsy** [comment]
Great to hear, thanks Matthias!

**Comment by do4gr** [comment]
The fix is rolled out now.
