### ISSUE TITLE
[String] field 'set' does not behave as expected

### ISSUE THREAD

**Issue by lrholmes** [graphcool/prisma#1639]
I have a type:

    type Filter {
      field: String!
      value: [String!]
    }

Implemented like this:

    type Thing {
      id: ID! @unique
      name: String
      filters: [Filter!]!
    }

When I create a new Thing, I use this mutation:
```
mutation {
  createThing(data: {
    name: "test",
    filters: { create: [ { field:"testing", value: { set:["one", "two"] } } ] }
  }) {
    filters {
      field
      value
    }
  }
}
```
While the mutation has no errors, `value` is returned as an empty array (and is persisted as an empty array).

**Comment by do4gr** [comment]
Thanks for reporting this @lrholmes. I was able to reproduce the bug. List values were not set when they were nested. I already implemented a fix for all cases except upsert and will close this issue once it is rolled out.

**Comment by lrholmes** [comment]
Great, thanks for the update @do4gr 👍

**Comment by do4gr** [comment]
The fix is rolled out so I am closing this issue.
