### ISSUE TITLE
Increase limit for String typed fields. 

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/prisma#164]
It would be nice to increase the limits for string typed fields. 

For a project that stores news articles, we run into the issue that some news articles are just longer than 64k characters.

**Comment by marktani** [comment]
Meanwhile, the current limit is 256kB 🙂

**Comment by Pkmmte** [comment]
I'm also running into this issue when storing strings over 21KB in size. Same use case as ejoebstl. :(

**Comment by marktani** [comment]
That's weird, because the limit is supposed to be 256kB. Can you post a reproduction in a new issue, @Pkmmte? 🙂

**Comment by Pkmmte** [comment]
How strange, the issue seems to have completely disappeared now. It's working as intended even though I didn't do anything.

**Comment by Pkmmte** [comment]
Aaaaaannnnd it's back... :(
https://github.com/graphcool/framework/issues/1307

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
