### ISSUE TITLE
Deploy bug [Windows]

### ISSUE THREAD

**Issue by lolcoolkat** [graphcool/prisma#1661]
@nikolasburk @schickling @sorenbs @marktani 

How to recreate.. (Make sure you're on a **Windows** Machine)

1) `prism init` (choose the advanced TS /w auth version)
2) `prism deploy`
3) choose local deployment or hosted version (Doesn't matter)
4) open up url that is returned to you 
5) check the schema on the right side of the page (it's the wrong queries/mutations, etc)

**This is what you see..** [Wrong]

![Wrong](https://image.prntscr.com/image/d4qmfiYhRkyq0jkLPyQS7w.png)

**This is what you should see** [Correct] (Besides updatePassword mutation)

![Correct](https://image.prntscr.com/image/u_XWueH-RFi9sOWb7UOIOA.png)

It seems as though for `prism deploy` it isn't correctly generating the schema?

**P.S** - Running `yarn dev` works fine..and has the correct schema.

**Comment by kbrandwijk** [comment]
The url that `prisma deploy` returns is that of your backend API (the one you just deployed to Prisma). Opening that URL does return you the full API (which is actually correct).

Now running `yarn dev` will actually open the _frontend_ GraphQL server, with the public facing schema that it defines (so the second screenshot). Which is also the correct behavior...
