### ISSUE TITLE
Bug: Unable to deploy but able to user Graphcool account with email containing "."

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma#1678]
**Current behavior**

Prisma login allows you to log in using Graphcool credentials for a user with email ID containing a "." but `prisma deploy` fails for such a user with error. 

Partially omitted log: 
```
"message": "divyendu.z~prisma-base is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers, underscores and hyphens.",
```

**Reproduction**

Register using an email that has a "." and try to use `prisma deploy` on that. 

**Expected behavior?**

Either the service should allow deployment with "." or omit it in the username while building a shared cluster namespace.

**Comment by Julianojc** [comment]
same problem here.

**Comment by timsuchanek** [comment]
This has been fixed. Please reopen if still an issue.
