### ISSUE TITLE
React & Apollo Quickstart doesn't go as planned

### ISSUE THREAD

**Issue by drdaz** [graphcool/prisma#1684]
I'll break the standard bug report template here. Hope that's fine.

When working through the Quickstart (at https://www.prismagraphql.com/docs/quickstart/fullstack/react/apollo-tijghei9go/), I run into a number of unexpected issues. When initialising my app using the command:

`graphql create my-app --boilerplate react-fullstack-basic`

The console output contains some errors; the task claims to complete successfully nonetheless:

```
drdaz$ graphql create my-app --boilerplate react-fullstack-basic
[graphql create] Downloading boilerplate from https://github.com/graphql-boilerplates/react-fullstack-graphql/archive/master.zip...
[graphql create] Installing node dependencies for /Users/drdaz/Desktop/my-app/package.json...
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "apollo-client > apollo-link@1.0.0" has incorrect peer dependency "graphql@^0.11.3".
warning " > apollo-link-http@1.3.2" has incorrect peer dependency "graphql@^0.11.0".
[4/4] 📃  Building fresh packages...
[-/2] ⢀ waiting...
[2/2] ⢀ fsevents: node-pre-gyp http GET https://fsevents-binaries.s3-us
[-/2] ⢀ waiting...
[-/2] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/drdaz/Desktop/my-app/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/drdaz/Desktop/my-app/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.39\nnode-pre-gyp info using node@9.4.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/drdaz/Desktop/my-app/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/drdaz/Desktop/my-app/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)\nnode-pre-gyp ERR! System Darwin 17.3.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/9.4.0/bin/node\" \"/Users/drdaz/Desktop/my-app/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /Users/drdaz/Desktop/my-app/node_modules/fsevents\nnode-p✨  Done in 10.17s.
[graphql create] Installing node dependencies for /Users/drdaz/Desktop/my-app/.install/package.json...
yarn install v1.3.2
warning package.json: No license field
warning install@0.0.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-boilerplate-install@0.1.7" has unmet peer dependency "prisma-cli@beta".
[4/4] 📃  Building fresh packages...
✨  Done in 0.22s.
[graphql create] Installing node dependencies for /Users/drdaz/Desktop/my-app/server/package.json...
yarn install v1.3.2
warning package.json: No license field
warning graphql-boilerplate: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "graphql-yoga > apollo-upload-server@4.0.0-alpha.2" has incorrect peer dependency "graphql@^0.11.0".
warning "graphql-yoga > graphql-playground-middleware-lambda@1.4.0" has unmet peer dependency "aws-lambda@^0.1.2".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.0.7" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.1" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.5" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "prisma-binding > apollo-link-http@1.3.2" has incorrect peer dependency "graphql@^0.11.0".
warning "graphql-cli > graphql-playground-middleware-express@1.5.2" has unmet peer dependency "express@^4.16.2".
warning "prisma-cli > prisma-cli-core > graphql-cli > graphql-playground-middleware-express@1.4.9" has unmet peer dependency "express@^4.16.2".
[4/4] 📃  Building fresh packages...
✨  Done in 6.97s.
[graphql create] Running boilerplate install script... 
Running $ prisma deploy...

```

It's mainly the 'Error running script...' part that catches my attention here. Not sure if it's important?

I choose to deploy to one of the hosted servers (not local).

Running 'yarn start' from here starts a web app up on localhost:3000 (not 4000 as the documentation suggests); but it's completely non-functional. The 'Create Draft' button doesn't seem to actually save anything; at least nothing appears in drafts after the save.

Running 'prisma playground' at this point gives me a playground screen connected to the remote server. Unfortunately, it won't give me any other result than:

```
{
  "code": 3016,
  "requestId": "api:api:cjcl2hj820x9701406b85131x",
  "error": "Project not found: 'my-app@dev'"
}
```

And... it's hard to proceed further from here. Hope this helps the product.

**Comment by marktani** [comment]
Hey @drdaz, thanks a lot for bringing this up!

It looks like the process of setting up the project fails fairly early on (that's the Error running script you noticed), so let's try to focus on this first :slightly_smiling_face: Problems with deploying or with the createDraft are probably just results of that error. 

The error does look related to your node or npm installation. Could you share your versions here? 

You also have a quicker choice to get started, which is by running `prisma init` and choose the minimal setup. I expect this to work for you.

**Comment by drdaz** [comment]
Darrens-iMac:database drdaz$ npm --version
5.6.0
Darrens-iMac:database drdaz$ node --version
v9.4.0

**Comment by masumbillah** [comment]
Anyone help me, when add this comd " yarn add apollo-server-express graphql-tools"

MSs-Mac-mini:twitter-app ms$ yarn add apollo-server-express graphql-tools
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "apollo-server-express > apollo-server-core@1.3.2" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > apollo-cache-control@0.0.9" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > apollo-tracing@0.1.3" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > graphql-extensions@0.0.7" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "graphql-tools > apollo-link@1.1.0" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
warning " > graphql-tools@2.20.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0".
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ apollo-server-express@1.3.2
└─ graphql-tools@2.20.2
✨  Done in 1.97s.

**Comment by vlutton** [comment]
@masumbillah Try running `yarn add graphql apollo-server-express graphql-tools` that should solve that unmet peer dependency

**Comment by marktani** [comment]
The quickstart has since been improved a lot, so I'm closing this. Please create a new issue if you're still encountering problems.
