### ISSUE TITLE
Field type change does not break the prisma deploy

### ISSUE THREAD

**Issue by nikhilkawtakwar** [graphcool/prisma#1687]
I have a type "User" in datamodel.graphql.
```
type User { 
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  firstName: String!
  lastName: String!
  username: String! @unique
  active: Boolean
}
```
I changed the active field from Boolean to String just to test how it behaves. I ran command "prisma deploy" after the change. I expected that it will throw the error. However, prisma did not throw the error and generated prisma.graphql have active field as a Boolean type(Which is correct but it should have thrown error).

I noticed that if I change type of the field for which there isn't any data in db(mysql) then prisma.graphql has updated field type.

```
prisma --version
prisma/1.0.0 (darwin-x64) node-v8.4.0
```

**Comment by do4gr** [comment]
Thanks for reporting this @nikhilkawtakwar. Prisma 1.6.1 introduced warnings and errors when deploying. See https://github.com/graphcool/prisma/releases/tag/1.6.1. This case would now trigger a warning if there is data already. I am therefore closing this issue.
