### ISSUE TITLE
Add JSON schema to schemastore.org

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1691]
To add out-of-the-box support for the `prisma.yml` file in editors like VSCode, we should add the JSON schema to http://schemastore.org/json/

**Comment by Weakky** [comment]
A quick way to start this would be to convert the [prisma.yml example ](https://www.prismagraphql.com/docs/reference/service-configuration/prisma.yml/overview-and-example-foatho8aip) to JSON using [json2yaml.com](https://www.json2yaml.com/convert-yaml-to-json), and then generate a JSON Schema template with [this generator (jsonschema.net)](https://jsonschema.net/#/).
That could help build all the verbose syntax, leaving only the gaps to fill (such as defining what are the required/optional fields, adding the descriptions (which are already present on the yaml example), and some other things.
This is what I could get in a few minutes using this technique:

### YAML to JSON:
```json
{
  "service": "my-demo-app",
  "datamodel": [
    "database/types.graphql",
    "database/enums.graphql"
  ],
  "cluster": "local",
  "stage": "dev",
  "disableAuth": "${env:PRISMA_DISABLE_AUTH}",
  "secret": null,
  "schema": "schemas/prisma.graphql",
  "subscriptions": {
    "sendWelcomeEmail": {
      "query": "database/subscriptions/sendWelcomeEmail.graphql",
      "webhook": {
        "url": "https://${self.custom:serverlessEndpoint}/sendWelcomeEmail",
        "headers": {
          "Authorization": "${env:MY_ENDPOINT_SECRET}"
        }
      }
    }
  },
  "seed": {
    "import": "database/seed.graphql"
  },
  "custom": {
    "serverlessEndpoint": "https://bcdeaxokbj.execute-api.eu-west-1.amazonaws.com/dev"
  }
}
```

### And the generated JSON Schema:
```json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "service": {
      "$id": "/properties/service",
      "type": "string",
      "title": "The Service Schema",
      "default": "",
      "examples": [
        "my-demo-app"
      ]
    },
    "datamodel": {
      "$id": "/properties/datamodel",
      "type": "array",
      "items": {
        "$id": "/properties/datamodel/items",
        "type": "string",
        "title": "The 0 Schema",
        "default": "",
        "examples": [
          "database/types.graphql"
        ]
      }
    },
    "cluster": {
      "$id": "/properties/cluster",
      "type": "string",
      "title": "The Cluster Schema",
      "default": "",
      "examples": [
        "local"
      ]
    },
    "stage": {
      "$id": "/properties/stage",
      "type": "string",
      "title": "The Stage Schema",
      "default": "",
      "examples": [
        "dev"
      ]
    },
    "disableAuth": {
      "$id": "/properties/disableAuth",
      "type": "string",
      "title": "The Disableauth Schema",
      "default": "",
      "examples": [
        "${env:PRISMA_DISABLE_AUTH}"
      ]
    },
    "secret": {
      "$id": "/properties/secret",
      "type": "string",
      "title": "The Secret Schema",
      "default": "",
      "examples": [
        "your-secret-token"
      ]
    },
    "schema": {
      "$id": "/properties/schema",
      "type": "string",
      "title": "The Schema Schema",
      "default": "",
      "examples": [
        "schemas/prisma.graphql"
      ]
    },
    "subscriptions": {
      "$id": "/properties/subscriptions",
      "type": "object",
      "properties": {
        "sendWelcomeEmail": {
          "$id": "/properties/subscriptions/properties/sendWelcomeEmail",
          "type": "object",
          "properties": {
            "query": {
              "$id": "/properties/subscriptions/properties/sendWelcomeEmail/properties/query",
              "type": "string",
              "title": "The Query Schema",
              "default": "",
              "examples": [
                "database/subscriptions/sendWelcomeEmail.graphql"
              ]
            },
            "webhook": {
              "$id": "/properties/subscriptions/properties/sendWelcomeEmail/properties/webhook",
              "type": "object",
              "properties": {
                "url": {
                  "$id": "/properties/subscriptions/properties/sendWelcomeEmail/properties/webhook/properties/url",
                  "type": "string",
                  "title": "The Url Schema",
                  "default": "",
                  "examples": [
                    "https://${self.custom:serverlessEndpoint}/sendWelcomeEmail"
                  ]
                },
                "headers": {
                  "$id": "/properties/subscriptions/properties/sendWelcomeEmail/properties/webhook/properties/headers",
                  "type": "object",
                  "properties": {
                    "Authorization": {
                      "$id": "/properties/subscriptions/properties/sendWelcomeEmail/properties/webhook/properties/headers/properties/Authorization",
                      "type": "string",
                      "title": "The Authorization Schema",
                      "default": "",
                      "examples": [
                        "${env:MY_ENDPOINT_SECRET}"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "seed": {
      "$id": "/properties/seed",
      "type": "object",
      "properties": {
        "import": {
          "$id": "/properties/seed/properties/import",
          "type": "string",
          "title": "The Import Schema",
          "default": "",
          "examples": [
            "database/seed.graphql"
          ]
        }
      }
    },
    "custom": {
      "$id": "/properties/custom",
      "type": "object",
      "properties": {
        "serverlessEndpoint": {
          "$id": "/properties/custom/properties/serverlessEndpoint",
          "type": "string",
          "title": "The Serverlessendpoint Schema",
          "default": "",
          "examples": [
            "https://bcdeaxokbj.execute-api.eu-west-1.amazonaws.com/dev"
          ]
        }
      }
    }
  }
}
```

Besides the optional/required fields and the description, I also need to find how not to force object properties on objects like `headers`, or `subscriptions`.
Every `subscriptions` should follow the same semantic, but we should be able to use any key name.
Same for `headers`, we should be able to use any header key/value.

*What do you guys think?*

**Comment by Weakky** [comment]
Update: [Here's the almost finished JSON Schema](https://gist.github.com/Weakky/db47cae2ee607463a60d5cc25a90187e). There's only one thing that could be improved IMO, it's a regex to match the secret JWT. I found some, but I'm not sure of their accuracies.

Something else to be noted: The only existing VS Code extension at the moment which supports JSON schemas is [vs-code-yaml by redhat](https://github.com/redhat-developer/vscode-yaml). Although it works quite well, the _DX_ is nowhere as good as with JSON, especially because `default` properties are not evaluated at all. This means we can't provide any default values for developers to have some ideas of what the input data should look like.

@schickling: What are the next steps to be done now? Should we make a PR to [schemastore](https://github.com/schemastore/schemastore/)?

By the way, if you'd like to try the current experience directly in vs-code, just download the extension I mentioned above, and add this property to the [user and workspace settings](https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings).
```
"yaml.schemas": {
"https://gist.githubusercontent.com/Weakky/db47cae2ee607463a60d5cc25a90187e/raw/eca2be3d99319833fe9035275e14f8213a5b808e/prisma-schema.json": "prisma.yml"
 }
```

It should work right away !

**Comment by timsuchanek** [comment]
You can find the `prisma.yml` schema here: https://github.com/graphcool/prisma-json-schema.
If there are changes you want to add there, feel free to do a PR :)

**Comment by Weakky** [comment]
@timsuchanek What the f*** 🤣? Why is there already an existing JSON schema? And what is the whole point of the issue then ? ...

**Comment by timsuchanek** [comment]
@Weakky thanks for your research regarding the yml plugin!
That plugin is at least a beginning.
The task was not well defined, we should have linked to the `prisma-json-schema` before.
I created a PR here to add it to schemastore.org https://github.com/SchemaStore/schemastore/pull/411

The json schema is used in the prisma cli to validate the prisma.yml.

**Comment by timsuchanek** [comment]
The PR has been merged :)
@Weakky is helping us out with some documentation about the topic so people will soon know how to enable that for vscode.
