### ISSUE TITLE
prisma.ts is not updated

### ISSUE THREAD

**Issue by rohanray** [graphcool/prisma#1695]
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill in the next sections:

**What feature are you missing?**

**How could this feature look like in detail? Tradeoffs?**

---

For **bug reports**, please fill in the next sections:

**Current behavior**
src/generated/prisma.ts is not updated on adding a new type to database/datamodel.graphql

**Reproduction**
prisma init with type-script-advanced. I'm simply trying to follow the quick-start guide from here https://www.youtube.com/watch?v=g0wFABHMzL4

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.
1. prisma init with type-script-advanced as the server type
2. prisma deploy
3. Add below type in database/datamodel.graphql
```
type Like {
  id: ID! @unique
  post: Post!
  likedBy: User!
}
```
4. prisma deploy

**Expected behavior?**
src/generated/prisma.ts should be updated containing the new type

**Comment by giautm** [comment]
Install `graphql-cli` at global is the temporary workaround.
```
npm i -g graphql-cli
```
Linked issues: https://github.com/graphcool/prisma/issues/1674

**Comment by ojkelly** [comment]
So i noticed this happens when I have `schema:` set to a file in `prisma.yml`, it stops it from outputting `datamodel.graphql` which in turn breaks all of this.

**Comment by timsuchanek** [comment]
I just published a new beta that should fix both your problems
