### ISSUE TITLE
prisma login

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1696]
```
ERROR: GraphQL Error (Code: 502)

{
  "error": "An error occured with your deployment\n",
  "status": 502
}
```

**Comment by steida** [comment]
The same for prisma init.

**Comment by alapini** [comment]
```bash
mkdir helloprisma && cd helloprisma
prisma init
```
(Choosed typescript-advanced as preset and EU shared cluster for deployment)
It warned me about login to prisma cloud. But I have valid access to graphcool legacy public cluster.  

**Result**
```
ERROR: GraphQL Error (Code: 502)

{
  "error": "An error occured with your deployment\n",
  "status": 502
}
```

**Comment by mzygmunt** [comment]
Same for prisma deploy and prisma init. Here's debug info

>   config CWD /Users/mzygmunt/apps/test +0ms
  config HOME /Users/mzygmunt +2ms
  config definitionDir /Users/mzygmunt/apps/test/database +5ms
  config definitionPath /Users/mzygmunt/apps/test/database/prisma.yml +0ms
  isGlobal { argv:
  isGlobal    [ '/usr/local/Cellar/node/8.4.0/bin/node',
  isGlobal      '/usr/local/bin/prisma',
  isGlobal      'deploy' ] } +0ms
  isGlobal { argv:
  isGlobal    [ '/usr/local/Cellar/node/8.4.0/bin/node',
  isGlobal      '/usr/local/bin/prisma',
  isGlobal      'deploy' ] } +4ms
  cli { isGlobal: true } +0ms
  StatusChecker setting status checker +0ms
  cli command id deploy +8ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/mzygmunt/Library/Caches/prisma/plugins.json +0ms
  cli:plugincache Got plugin from cache +4ms
  cli:plugincache /Users/mzygmunt/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/prisma-cli/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', '192.168.1.3', 'fe80::9081:8bff:fea5:ec9b', 'fe80::ccec:a0d2:6698:2cd1', 'fe80::97cd:4021:de3d:a1c0' ] +0ms
  cli-engine:plugins:manager required +680ms
  plugin required command +684ms
  Environment [ 'graphcool-eu1', 'graphcool-us1', 'shared-public-demo' ] +0ms
  Environment { 'graphcool-eu1': 'https://graphcool-eu1.graphcool.cloud',
  Environment   'graphcool-us1': 'https://graphcool-us1.graphcool.cloud',
  Environment   'shared-public-demo': 'https://database-beta.graph.cool' } +1ms
  StatusChecker setting status checker +1s
  deploy run +845ms
  environment generateClusterToken +0ms
Error: GraphQL Error (Code: 502): {"response":{"error":"An error occured with your deployment\n","status":502},"request":{"query":"\n      mutation ($input: GenerateClusterTokenRequest!) {\n        generateClusterToken(input: $input) {\n     clusterToken\n        }\n      }\n    ","variables":{"input":{"workspaceSlug":"public-cloverlightning-787","clusterName":"prisma-eu1","serviceName":"test","stageName":"dev"}}}}
    at GraphQLClient.<anonymous> (/usr/local/lib/node_modules/prisma-cli/node_modules/graphql-request/src/index.ts:46:13)
    at step (/usr/local/lib/node_modules/prisma-cli/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/usr/local/lib/node_modules/prisma-cli/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/usr/local/lib/node_modules/prisma-cli/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  Output { statusChecker:
  Output    StatusChecker {
  Output      config:
  Output       Config {
  Output         debug: true,
  Output         windows: false,
  Output         bin: 'prisma',
  Output         mock: false,
  Output         argv: [Array],
  Output         commandsDir: '/usr/local/lib/node_modules/prisma-cli/node_modules/prisma-cli-engine/dist/commands',
  Output         defaultCommand: 'help',
  Output         userPlugins: false,
  Output         version: '1.0.0',
  Output         name: 'prisma',
  Output         pjson: [Object],
  Output         root: '/usr/local/lib/node_modules/prisma-cli',
  Output         warnings: [],
  Output         cloudApiEndpoint: 'https://api.cloud.prisma.sh',
  Output         consoleEndpoint: 'https://app.prismagraphql.com',
  Output         __cache: [Object],
  Output         cwd: '/Users/mzygmunt/apps/test',
  Output         home: '/Users/mzygmunt',
  Output         definitionPath: '/Users/mzygmunt/apps/test/database/prisma.yml',
  Output         definitionDir: '/Users/mzygmunt/apps/test/database',
  Output         globalPrismaPath: '/Users/mzygmunt/.prisma/',
  Output         globalConfigPath: '/Users/mzygmunt/.prisma/config.yml',
  Output         globalClusterCachePath: '/Users/mzygmunt/.prisma/cache.yml',
  Output         out: [Object] },
  Output      env:
  Output       Environment {
  Output         sharedClusters: [Array],
  Output         clusterEndpointMap: [Object],
  Output         globalRC: {},
  Output         out: [Object],
  Output         home: '/Users/mzygmunt',
  Output         rcPath: '/Users/mzygmunt/.prisma/config.yml',
  Output         clusters: [Array],
  Output         activeCluster: [Object] } } } +0ms
  isGlobal { argv:
  isGlobal    [ '/usr/local/Cellar/node/8.4.0/bin/node',
  isGlobal      '/usr/local/bin/prisma',
  isGlobal      'deploy' ] } +2s
  isGlobal { argv:
  isGlobal    [ '/usr/local/Cellar/node/8.4.0/bin/node',
  isGlobal      '/usr/local/bin/prisma',
  isGlobal      'deploy' ] } +9ms
  util timed out +0ms
Exiting with code: 0
MBP-Mateusz:test mzygmunt$

**Comment by marktani** [comment]
Thanks everyone, this is now fixed.

**Comment by Glitches** [comment]
Unfortunately, this error sees still in place..
