### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#17]
It could be useful to disable HTTP access to a project similar to [Heroku](https://devcenter.heroku.com/articles/maintenance-mode), for example:
- to do some bigger backend refactoring
- if an issue comes up (endpoint compromised, permission rules mixed up etc)
- simply to put a project "in the fridge" for a while

**Comment by sedubois** [comment]
Just a comment that I would still find it helpful to have this. E.g right now I'm building a backend whose access needs to be controlled, but there is no authentication system in place yet. So I'd need an easy way to disable access to the backend when I'm not doing the development. Right now I go to the permissions and disable all the permissions one by one.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
