### ISSUE TITLE
CLI should pick up next graphql-config from parent directory

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1700]
When working in a project with the following structure it should be possible to use the `prisma` CLI from within the `backend` folder:

```
backend/
  database/
    prisma.yml
    datamodel.graphql
frontend/...
.graphqlconfig.yml
```

**Comment by kbrandwijk** [comment]
Does it also find `prisma.yml` based on the `.graphqlconfig`? Because that would be a great combination. 

You could run `prisma` commands from any subfolder, as it would first search **up** for .graphqlconfig, then use it's pointer to `prisma.yml`.

**Comment by timsuchanek** [comment]
Yes, the CLI resolves the `prisma.yml` relative to the `.graphqlconfig` file.
This now implemented and available at `prisma@beta`
