### ISSUE TITLE
I feel like intoxicated with LSD. Am I?

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1702]
"prisma and prisma-cli are identical. At first, we didn’t have the prisma npm package name so we initially released it as prisma-cli. We then finally did get access to prisma on npm so we used that but we‘ll maintaining both."

Ok. And then I look into prisma package.json.

![screen shot 2018-01-20 at 19 19 45](https://user-images.githubusercontent.com/66249/35186631-497020d6-fe17-11e7-9ee6-b8f62ba1412f.png)

Why two identical libs... or... if you ever had LSD you know what I am talking about. 😳

Naming daymare.

**Comment by marktani** [comment]
Hey @steida, this must have been one of the most hilarious issue reports I've ever seen, thanks! 😄 

This is definitely not intended, which example or boilerplate did you follow to end up with this `package.json`? I'd love to clean that up 🙂

**Comment by steida** [comment]
I need relax. I added prisma to have the explicit dependency for `yarn prisma deploy` etc. without global install and didn't realize previous prisma-cli is already there. As I understand, all https://github.com/graphql-boilerplates should have prisma, not prisma-cli or vice versa. Having two same npm libs is confusing, especially when some have -cli suffix while the other not. I would go with -cli everywhere, but without is good enough as well. Choose one, deprecate second, otherwise people with be perplexed like me. Thank you for your understanding.
