### ISSUE TITLE
"Project not found" error in playground

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1704]
`prisma init foo`

- GraphQL server/fullstack boilerplate (recommended) 
- node-advanced GraphQL server (incl. database & authentication) 
- Added cluster: prisma-eu1 to prisma.yml

Then `prisma playground`.

**Current behavior**
```
{
  "code": 3016,
  "requestId": "api:api:cjcnymhag11bt01246z1tzf5j",
  "error": "Project not found: 'prisma@dev'"
}
```

**Expected behavior?**

It should not return an error I guess.

**Comment by cbioley** [comment]
@steida I'm having the same issue.

(Hi mate, BTW! - I hope you're doing well ;))

**Comment by steida** [comment]
In the other words, quickstart does not work. `yarn dev` works, but only locally. 

![screen shot 2018-01-23 at 01 22 54](https://user-images.githubusercontent.com/66249/35251544-fb229172-ffdb-11e7-92db-33ab4dd5250c.png)

**Comment by steida** [comment]
Deleting .prisma dir in user dir seemed to help.
