### ISSUE TITLE
Updating a field property with an empty value doesn't update?

### ISSUE THREAD

**Issue by goncy** [graphcool/prisma#1706]
It's possible to set a value to be empty after being defined?

**Current behavior**
![image](https://user-images.githubusercontent.com/6494462/35194016-80ee9d26-fe8a-11e7-848c-b102d9fc4a0f.png)

**Expected behavior?**
To be set to an empty array

**Comment by goncy** [comment]
It's this a confirmed bug already? Or just need to do it another way

**Comment by do4gr** [comment]
Hey @goncy,

thanks for reporting this. I can confirm that this is a bug. The syntax you were trying to use is the correct one and should work. A fix is in the works and should be released this week.

**Comment by goncy** [comment]
Excellent, please tell if you anything else is needed
