### ISSUE TITLE
Getting started does not work

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1717]
https://www.prismagraphql.com/docs/tutorials/prisma-basics/getting-started-ouzia3ahqu

Second attempt to deploy.

```
ERROR: GraphQL Error (Code: 502)

{
  "error": "An error occured with your deployment\n",
  "status": 502
}
```

Playground

{
  "code": 3016,
  "requestId": "api:api:cjcs92a245vu20113504b02lh",
  "error": "Project not found: 'prisma@dev'"
}

**Comment by steida** [comment]
Yet another attempt, yet another error.

```
ERROR: Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.",
      "requestId": "cluster:cluster:cjcs9br4k00020161gdslx5yl"
    }
  ],
  "status": 200
}
```

**Comment by marktani** [comment]
This should work now. Please reach out to `support@graph.cool` if you are still encountering similar issues.

**Comment by steida** [comment]
Deploy works, prisma plaground still "error": "Project not found: 'prisma@dev'"

**Comment by timsuchanek** [comment]
Hey @steida thanks for reporting!
What is the endpoint url that is being opened in the Playground? Thanks!

**Comment by steida** [comment]
https://eu1.prisma.sh/prisma/dev

**Comment by miyi** [comment]
i have a similar issue.

the most interesting part is that it worked briefly for a cool 10 minutes before dying again.

`
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    headers: {
      Authorization: "Bearer __TOKEN__"
    },
    db: new Prisma({
      endpoint: 'http://localhost:4466/dockerhost/dev', // the endpoint of the Prisma DB service
      secret: 'mysecret123', // specified in database/prisma.yml
      debug: true, // log all GraphQL queries & mutations
    }),
  }),
})
`

this is how you set request headers right?

**Comment by timsuchanek** [comment]
@steida ok, that url looks wrong, it should include the workspace that you deployed to.
Can you please show me your `prisma.yml`? Thanks!

**Comment by timsuchanek** [comment]
@miyi in order to have a properly working playground you have to use the `graphql playground` command.

What you're trying to do here, is adding a token to the endpoint exposed by yoga.
The endpoint that actually returns the token error is the prisma endpoint, these are 2 separate endpoints.

You can generate a token for the endpoint using the `prisma token` command.

**Comment by timsuchanek** [comment]
Just found the problem. A new beta is available, a new stable version will be released soon.

**Comment by marktani** [comment]
Thanks for your help with this, @steida and @miyi 🙏

**Comment by limux** [comment]
Update Prisma to the latest 1.0.10, then "prisma playground" works, @steida .

**Comment by TheDeveloperTom** [comment]
Still does not work. After prisma init, I got the same error...

**Comment by marktani** [comment]
@TheDeveloperTom what's your `prisma version`?
What cluster are you deploying to?
What are your steps to reproduce the problem? 🙂

**Comment by TheDeveloperTom** [comment]
1. 
![image](https://user-images.githubusercontent.com/25426552/35704879-8450fa9a-07a9-11e8-96d2-5481150d0cfb.png)

2. local/remote - the same result

3. streps to reproduce: prisma init -> open offered link -> get the error.

**Comment by marktani** [comment]
3. what do you mean with `open offered link`? When I run `prisma init`, I get to choose between "minimal setup" and "GraphQL server/fullstack".

**Comment by marktani** [comment]
@TheDeveloperTom thanks for adding the screenshots! Your error message is actually different than any other shared in this thread before 🙂 

Do you have a secret set in `prisma.yml`?

**Comment by leedan77** [comment]
Works when using "yarn dev", while "prisma playground" gets
![image](https://user-images.githubusercontent.com/10044119/35718828-344a7300-0821-11e8-92e4-c096614b2b6b.png)

A little confuse with using prisma playground or yarn dev.

**Comment by marktani** [comment]
Thanks @leedan77, can you create a new issue with full information for reproduction? I'm losing track of the different situations in this issue :slightly_smiling_face:

**Comment by tsdexter** [comment]
I'm getting this error on a prisma cloud hosted/managed production server... 2 members of my team get the error and the third is able to deploy... 

```
ERROR: Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Token can't be decoded: Invalid signature for this token or wrong algorithm.",
      "requestId": "__SERVER_NAME__:cjrmebr4uxuvq0854n43bmcvt"
    }
  ],
  "status": 200
}
```
