### ISSUE TITLE
connect?

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1718]
I am pretty sure meta props should be prefixed with something.

![screen shot 2018-01-24 at 01 11 54](https://user-images.githubusercontent.com/66249/35307574-972a903e-00a3-11e8-9a01-42608b7aa87a.png)

**Comment by steida** [comment]
Otherwise, creating a post with author could clash if an author would have a connect prop.

**Comment by marktani** [comment]
No, as `author` has the two input fields `connect` and `create`. This is how `create` would work:

```graphql
mutation {
  createPost(data: {
    title: "This is a draft"
    author: {
      create: {
        name: "Zeus"
        email: "zeus@example.com"
      }
    }
  }) {
    id
    author {
      name
    }
  }
}
```
