### ISSUE TITLE
It seems we can't open a local cluster on armv7 system.

### ISSUE THREAD

**Issue by async3619** [graphcool/prisma#1720]
First of all, I really like to apologize my bad English, but I try to do my best to explain what I do and what I want to know about:

I tried to serve Prisma cluster on my ODROID XU4 machine (armv7 architecture). but It was failed because prisma cluster docker image (`prismagraphql/prisma`) has MySQL image but that isn't supporting armv7 by default. so I've asked how to use custom image on cluster container on Slack community.

and I've received an [answer](https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu#install-prisma-on-your-droplet) that explains how I open a local cluster with custom docker image. so I made several files to create local cluster with that document. [you can visit here to take a look](https://gist.github.com/async3619/248d83c45679e9f8e1b954ae90dc1e30). In that time, I was succeeded to create MySQL container but there was a big problem: a container with `prismagraphql/prisma` image wasn't running and printing error continuously. like:

```
standard_init_linux.go:195: exec user process caused "exec format error"
standard_init_linux.go:195: exec user process caused "exec format error"
standard_init_linux.go:195: exec user process caused "exec format error"
...
```

and I know that most docker containers cause that error due to architecture issue. so.. I concluded that I should build `prismagraphql/prisma` for armv7 machine. so I cloned prisma repository to build image. and there was some docs about how to build `prismagraphql/prisma` image, so I followed instruction but I couldn't build because of different architecture.

so.. my curiosity is: Is there no way to serve prisma cluster on armv7 machine? or can I build `prismagraphql/prisma` image for armv7? 

I'm really appreciate about spending time on my issue article that wrote with broken English.

**Comment by sorenbs** [comment]
Thank you for the question @async3619 

Your english is fine :-)

We currently do not support armv7 and make no effort to test on the platform. Even if you do manage to build the prisma image on arm it is likely to break in the future.

We will reconsider this decision in the future if enough people show interest.
