### ISSUE TITLE
Query filtering on multiple values if the array is null

### ISSUE THREAD

**Issue by Kisepro** [graphcool/prisma#1723]
Hello,

As described on the doc ( https://www.graph.cool/docs/reference/graphql-api/query-api-nia9nushae/#traversing-many-nodes ), I want to do that : 

> query {
>   allPosts(filter: {
>     title_in: ["My biggest Adventure", "My latest Hobbies"]
>   }) {
>     id
>     title
>     published
>   }
> }

but sometimes I would like to replace ["My biggest Adventure", "My latest Hobbies"] by null.
The problem is that it returns no results.  I would have expected that is disactivate the filter.

- null : returns all values -> filter not activated
- [] : returns no values -> filter activated

In my opinion it can happen in a lot of business cases like a filter on a search screen.  I don't even find another clean solution to handle it.

To reproduce it, just go on the documentation page and replace the array by null

**Comment by marktani** [comment]
Hey @Kisepro, thanks for your suggestion!

You can construct a filter object client-side, depending on some logic. Check [this forum thread](https://www.graph.cool/forum/t/is-it-possible-to-build-a-filter-query-dynamically/268/3?u=nilan) or [this one](https://www.graph.cool/forum/t/optional-query-filters/355?u=nilan) for more information.

Please post feature requests and issues for the Graphcool Framework [in this repository](https://github.com/graphcool/graphcool-framework/) in the feature.

**Comment by Kisepro** [comment]
Thanks for your help !
