### ISSUE TITLE
No interaction with `prisma deploy --interactive`

### ISSUE THREAD

**Issue by Melv** [graphcool/prisma#1728]
> prisma/1.0.8 (linux-x64) node-v8.9.4

**Current behavior**
`prisma deploy --interactive`

deploys like

`prisma deploy`

**Reproduction**

`prisma deploy --interactive`

**Expected behavior?**

Expect to be prompted  for some input like with `prisma init <someName>`

**Comment by alapini** [comment]
Same Issue. It is not only the `--interactive` flag that is not working, but also the `--dotenv` flag.

For the `--interactive` issue, a workaround is to comment the line  `cluster: ${env:PRISMA_CLUSTER}` in your `prisma.yml`. This will promt you for the target cluster every time you run `prisma deploy`.

**Comment by Melv** [comment]
`--dotenv` :arrow_right:  #1701

@alapini my workaround for that is make a symbolic `.env` 
`ln -s .env.prod .env`

**Comment by johhansantana** [comment]
none of the flags seem to work.

**Comment by nampdn** [comment]
Same issue with prisma@1.2.8
Non of above work. But the workaround seem good!

**Comment by timsuchanek** [comment]
Fixed and released in latest beta.
