### ISSUE TITLE
Add documentation about scalar lists

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1732]
The relationship between scalar lists in the data model and the resulting GraphQL API is not yet covered in the reference documentation.

Also see https://github.com/graphcool/prisma/issues/1275

**Comment by johnkpaul** [comment]
Were these docs added somewhere? Thanks.

**Comment by nikolasburk** [comment]
Hey @johnkpaul, they're [here](https://www.prismagraphql.com/docs/reference/prisma-api/mutations-ol0yuoz6go#scalar-list-mutations) 🙌
