### ISSUE TITLE
How to throw error properly

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1738]
Is there any reason why combines two different errors throwing?

```
throw new Error('Invalid password');
```

vs

```js
class AuthError extends Error {
  constructor() {
    super('Not authorized');
  }
}
```

**Comment by steida** [comment]
Also, having a message only is limiting. 

```js
type BackendError =
  | validation.ValidationError
  | { type: 'signupEmailAlreadyExists' };

const throwError = (backendError: BackendError) => {
  // This is not enough.
  // throw new Error(backendError.type);
  // This looks like hack.
  // throw new Error(JSON.stringify(backendError));
};
```

**Comment by akoenig** [comment]
I can recommend using [apollo-errors](https://github.com/thebigredgeek/apollo-errors) which gives you the possibility to define own error types.

**Comment by marktani** [comment]
Thanks so much for raising this issue @steida, I created a separate issue to discuss how an example could look like that covers best practices for error handling: #1892.
