### ISSUE TITLE
Specify value for custom fields on the File type when uploading files

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#174]
Currently I know of these two ways to upload files:
- drag and drop onto data browser (nice!)
- curl -X POST

But in both cases, AFAIK there's no way to assign at the same time some extra data (e.g I added a `category` field) or specify the filename. This would be quite useful when bulk uploading files.

**Comment by marktani** [comment]
You can specify the file name when using `fetch`, as shown [in this tutorial](https://www.graph.cool/docs/faq/node-uploading-remote-files-boneix7ohm/).

```js
form.append('data', body, {
  filename: fileName
})
```

**Comment by sedubois** [comment]
Thanks. But if I need to change after upload, I can as well just change in the data browser.

It would just be great to avoid the extra step.

Also about specifying the filename, is there any way to do that using `curl`?

**Comment by marktani** [comment]
This uploads your local file `example.png` with the new file name `myname.png`
```sh
curl -X POST 'https://api.graph.cool/file/v1/__PROJECT_ID__' -F "data=@example.png;filename=myname.png"
```

I updated the line in the docs to reflect this :)

**Comment by sedubois** [comment]
Thanks @marktani that's helpful 🙂 

Would also be nice to specify custom fields that way too: 
```
curl -X POST 'https://api.graph.cool/file/v1/__PROJECT_ID__' -F "data=@example.png;filename=myname.png;category=myCategory"
```

If the field has another type than String (e.g numeric), it could be parsed the same way as is done in the console when typing values with the keyboard there.

**Comment by kbrandwijk** [comment]
+1 for file upload with additional metadata in a single request.

**Comment by patoncrispy** [comment]
I would also love to see something like this. Adding other metadata to the body of the request shouldn't be too tricky, right?

**Comment by kbrandwijk** [comment]
Please checkout my metadata-file-proxy example: https://github.com/kbrandwijk/functions/tree/file-proxy/file-proxy for a workaround until we get out of box support for this in the Graphcool File API.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
