### ISSUE TITLE
Add more examples for default value directive

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1741]
[The documentation for `@default`](https://www.prismagraphql.com/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#data-model-directives) can be expanded to include default values for more types:

```graphql
type Post {
  title: String! @default(value: "New Post")
  published: Boolean! @default(value: "false")
  someNumber: Int! @default(value: "42")
}
```

Also see #1740.

**Comment by codepunkt** [comment]
How does it work with array types?

```graphql
type User {
  roles: [UserRole!]! @default(value: ["User"])
}

enum UserRole {
  User
  Admin
}
```

**Comment by morajabi** [comment]
@marktani Looks like it doesn't work for `Int` too?
```
attempt: Int! @default(value: "0")
```

```
 ✖ You are making a field required, but there are already nodes that would violate that constraint.
```

**Comment by rip3rs** [comment]
> @marktani Looks like it doesn't work for `Int` too?
> 
> ```
> attempt: Int! @default(value: "0")
> ```
> 
> ```
>  ✖ You are making a field required, but there are already nodes that would violate that constraint.
> ```

I know this was a while back, but perhaps someone will associate the above response incorrectly.

the:
>  `✖ You are making a field required, but there are already nodes that would violate that constraint. `

Has nothing to do with the `@default`. Rather, the reason for that error is because there is already data stored `Nodes` on the database for that specific `Model`. By removing the `!` would fix that error.

**Comment by Riseley** [comment]
> How does it work with list types?
> 
> ```graphql
> type User {
>   roles: [UserRole!]! @default(value: ["User"])
> }
> 
> enum UserRole {
>   User
>   Admin
> }
> ```
> 
> Edit: I found that the documentation states that list scalar fields don't work with @default, which is a pity. Is there a feature issue to allow this?

Can you post such documentation?

**Comment by technicallynick** [comment]
@Riseley - I found and linked the docs below for this.

[Postgres](https://www.prisma.io/docs/datamodel-and-migrations/datamodel-POSTGRES-knum/#default-value)
[MySQL](https://www.prisma.io/docs/1.34/datamodel-and-migrations/datamodel-MYSQL-knul/#default-value)
[Mongo](https://www.prisma.io/docs/1.34/datamodel-and-migrations/datamodel-MONGO-knun/)

 It also comes up as an error when attempting to run `prisma deploy` with @default on a scalarList that looks like the following:

> ✖ The `@default` directive must only be placed on scalar fields that are not lists.
