### ISSUE TITLE
Authenticate no longer working in project

### ISSUE THREAD

**Issue by inxeptionjake** [graphcool/prisma#1748]
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill in the next sections:

**What feature are you missing?**

**How could this feature look like in detail? Tradeoffs?**

---

For **bug reports**, please fill in the next sections:

**Current behavior**
Nothing has changed on our side, but the authentication is no longer working.  We are using the authenticate function.   I don't see any error in logs, but the authentication does not pass.

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
Users are able to log into the our application

**Comment by inxeptionjake** [comment]
Getting response from 
const mutationStr = `mutation {
					signIn: authenticateUser(
						  	email: ${JSON.stringify(email)},
							password: ${JSON.stringify(password)}
					  ) {
						token,
						email
					  }
				  }`;

"Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: eu-west-1:simple:cjcwmt11s2f5v0102a1waxc0k"

**Comment by Kisepro** [comment]
I have the same issue since now, yesterday it was working fine

**Comment by littletower** [comment]
same here. Really annoying. In my case, it's not a production app yet, else that would have been terrible...
there is a thread in the [forum](https://www.graph.cool/forum/t/function-calls-return-whoops-looks-like-an-internal-server-error/2328) as well

**Comment by marktani** [comment]
Hey, thanks a lot for bringing this up @inxeptionjake, @Kisepro and @littletower.
We are looking into a fix here, please track https://status.graph.cool to stay informed.

**Comment by marktani** [comment]
The issue was resolved, thanks for your patience everyone 🙌
