### ISSUE TITLE
Issue deploying local to a remote cluster.

### ISSUE THREAD

**Issue by diit** [graphcool/prisma#1762]
**Current behavior**
- `Your token is invalid. It might have expired or you might be using a token from a different project.Your token is invalid. It might have expired or you might be using a token from a different project.`

**Reproduction**
- Commented out `cluster` to get around issue with deploying previously deployed local to cluster
- ran `prisma deploy`, deployed to us1 cluster
- attempted to access
- no errors during deploy

**Expected behavior?**
- Able to execute queries/mutations

**Comment by diit** [comment]
Attempted: https://www.graph.cool/forum/t/cannot-open-playground-your-token-is-invalid/2194/4 however it is unclear how to force token to use production dotenv and even when forcing (replacing .env fully) it does not change outcome.

**Comment by diit** [comment]
Solved: Issue was, production using wrong .env due to known cli bugs.

**Comment by marktani** [comment]
Hey @diit could you link to the issue describing the known bug? 🙂

**Comment by diit** [comment]
@marktani https://github.com/graphcool/prisma/issues/1701
