### ISSUE TITLE
No generated crud for searching in strings lists

### ISSUE THREAD

**Issue by terion-name** [graphcool/prisma#1765]
I have such datamodel:
```graphql
type Municipality {
  id: ID! @unique
  title: String!
  slug: String!
  domains: [String!]!
  about: String
  logo: String
  settlements: [MunicipalitySettlement!]! @relation(name: "Settlements")
  administrative_center: MunicipalitySettlement! @relation(name: "AdministrativeCenter")
  region: Region!
  edrpou: Int
  koatuu: Int
  area: Float
  population_density: Float
  machinery: String
}
```

But generated `interface MunicipalityWhereInput` does not contain `domains` filters, therefore I can't search for a Municipality by a containing domain string

**Comment by marktani** [comment]
Hey @terion-name, thanks for creating this issue!
Filters for scalar lists will be added later, as part of [this feature request](#1275).

Therefore I'm closing this issue. Feel free to subscribe the one I mentioned, to stay informed of our progress here 🙂

**Comment by terion-name** [comment]
@marktani oh, thank you

**Comment by terion-name** [comment]
@marktani any assumptions on when it will go live?
