### ISSUE TITLE
Increase files' browser cache lifetime

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#177]
E.g. for the website graphqltalks.com, the top recommendation of Pingdom to improve performance is to increase the caching lifetime of images hosted on files.graph.cool to at least a week:
https://tools.pingdom.com/#!/bXinKV/https://www.graphqltalks.com/

**Comment by lucfranken** [comment]
Totally agree. A file should be immutable and the url should not have a cache lifetime. It can be permanent in general. 

In https://github.com/graphcool/feature-requests/issues/182 is the solution to block access when not available anymore.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
