### ISSUE TITLE
Issues with import

### ISSUE THREAD

**Issue by miyi** [graphcool/prisma#1770]
I'm having the same issue on graphcool-framework as I do on prisma. After manually inserting some data into the playground and exporting that data, unzipping the file, rezipping it untouched, and import the rezipped file breaks the import. However importing the original exported zipped file works

my data model is very simple:

>type User {
  id: ID! @unique
  name: String!
  age: Int
}

I created 3 user objects

```javascript
{"valueType":"nodes","values":
    [
        {"name":"Mark","updatedAt":"2018-01-30T01:38:34.000Z","_typeName":"User","age":26,"id":"cjd0z55956vxk0111p9hbz1op","createdAt":"2018-01-30T01:38:34.000Z"},
        {"name":"Moses","updatedAt":"2018-01-30T01:38:57.000Z","_typeName":"User","age":22,"id":"cjd0z5mm96rbx0138ssm4sob6","createdAt":"2018-01-30T01:38:57.000Z"},
        {"name":"Mike","updatedAt":"2018-01-30T01:39:03.000Z","_typeName":"User","age":21,"id":"cjd0z5rey6rcm01388vbfa9jw","createdAt":"2018-01-30T01:39:03.000Z"}
    ]
}
```

i deleted the manually inserted users prior to importing, command line show no error. nothing is imported to graphcool. Maybe i'm doing something obviously wrong. 

>Unzipping... 36ms
Validating data... 9ms
Uploading nodes...
Uploading nodes done 1ms
Uploading lists
Uploading lists done 0ms
Uploading relations
Uploading relations done 0ms

using prisma/1.0.11

**Comment by marktani** [comment]
How exactly are you "rezipping" the folder? What's the tool you use?

Also, does it work to import tge unzipped folder directly?

**Comment by miyi** [comment]
i'm using apple default compression. 

it does work just by importing the unzipped file directly. I can't believe I never tried this. Thanks alot
