### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1776]
in https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu, It should say

`cat public.pem | sed -n -e 'H;${x;s/\n/\\\r\\\n/g;p;}'`
and
`cat private.pem | sed -n -e 'H;${x;s/\n/\\\r\\\n/g;p;}'`

instead of

`cat public.pem | sed -n -e 'H;${x;s/\n/\\\\r\\\\n/g;p;}'`
and
`cat private.pem | sed -n -e 'H;${x;s/\n/\\\\r\\\\n/g;p;}'`

**Comment by johannpinson** [comment]
Typo bug linked to this comment:
https://github.com/graphcool/prisma/issues/1686#issuecomment-361491227
