### ISSUE TITLE
Server response was missing for query 'null'

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1788]
Hitting a GraphQL Yoga server with many HTTP requests in a short amount of time results in the error message

> Server response was missing for query 'null'

Pseudo code:

```
Promise.all( map((article) => { insert(article) }) )
```

This happens both locally and on public clusters.

It's not clear yet whether that error is returned from the Node server, or from the Prisma API.
I will soon look into a reliable reproduction.

**Comment by delta98** [comment]
Thanks @marktani I believe this is from Prisma API as it's not going through Yoga, at least my side - unless of course Prisma clusters use it internally.

**Comment by marktani** [comment]
Gotcha, no they don't use Yoga internally 🙂

**Comment by marktani** [comment]
I conducted some experiments against the local and the public eu1 cluster.

## Parameters

I am running a script that creates 1000 records in batch size of 100 and 16 concurrent HTTP requests. A batch is a single GraphQL mutation with multiple top-level mutation fields (in this case 100):

```graphql
mutation {
  k_001: createArticle(
    data: {
      featuredImage: "http://example.com"
      summary: "Lorem ipsum dolor sit amet."
      publishedAt: "2017-02-02"
      url: "Lorem ipsum dolor sit amet."
      source: { connect: { slug: "test" } }
    }
  ) {
    id
  }

# ...

  k_100: createArticle(
    data: {
      featuredImage: "http://example.com"
      summary: "Lorem ipsum dolor sit amet."
      publishedAt: "2017-02-02"
      url: "Lorem ipsum dolor sit amet."
      source: { connect: { slug: "test" } }
    }
  ) {
    id
  }
}
```

## Local Cluster

I was able to reliably reproduce a specific error against the local cluster:

```
java.sql.SQLTransactionRollbackException: (conn=164) Deadlock found when trying to get lock; try restarting transaction
```

The script took ~2 seconds to run.

## Public Cluster

However, with the exact same script, I was _not_ able to reproduce the same behaviour when running against the public cluster eu1. The script took ~10 seconds.

## Conclusion

I assume that the rate limiting that is in place for the remote cluster is the crucial component that explains the difference here.

Overall, I would rate this behaviour as expected, based on my current observations.

---

Please ping me [in Slack](https://slack.graph.cool) (my handle there is @nilan) if you are able to reproduce a different error on the local cluster, or reliably reproduce an error at all against the public cluster. Thanks! 🙏

**Comment by marktani** [comment]
I was able to research this further and summarized the issue in #2060 more concisely.
