### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by nilocoelhojunior** [graphcool/prisma#1794]

**Comment by marktani** [comment]
Please reach out to support@graph.cool 🙂

**Comment by dbuarque** [comment]
Hi @marktani I see you have edited the issue and deleted the post. This isn't cool man. A lot of people can lose their data and accounts. 

This issue is a very critical issue.  Close the issue and delete the post is a very unprofessional way to solve this.

**Comment by marktani** [comment]
Hey @dbuarque we are fixing this problem as we speak. I removed the description for security reasons.

Please reach out to support@graph.cool if you have any further questions!

**Comment by dbuarque** [comment]
I understand your point, thanks for the answer. Hope you guys fix this soon. 👍

**Comment by dbuarque** [comment]
@marktani if you need help to reproduce the problem we can do a hangout so I can show to you

**Comment by marktani** [comment]
We are already testing our fix internally. There is no further input needed here, thanks!

**Comment by dbuarque** [comment]
@marktani no problem! Thanks!

**Comment by marktani** [comment]
Thanks @nilocoelhojunior @dbuarque for bringing this up, it is now fixed.
