### ISSUE TITLE
`prisma init` should offer a flag to directly choose the ` Minimal setup: database-only` setup

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/prisma#1801]
# Feature Request

**What feature are you missing?**

Currently I can only provide the `--boilerplate` option to specify a GraphQL boilerplates repo. The ` Minimal setup: database-only` template however is not part of the GraphQL boilerplates org.

**Comment by timsuchanek** [comment]
We can do this with the `--minimal` flag.

**Comment by supergoat** [comment]
I can have a look at this later today :)

**Comment by marktani** [comment]
With the latest changes of `prisma init`, this feature request is obsolete.
