### ISSUE TITLE
SQL injection (Slick, plain SQL)

### ISSUE THREAD

**Issue by BijanVan** [graphcool/prisma#1806]
I was looking at graphcool/prisma source code (database interface/Slick) and I noticed it uses " Splicing Literal Values (http://slick.lightbend.com/doc/3.2.1/sql.html#splicing-literal-values)" almost everywhere which could be vulnerable to SQL injection (my understanding).?

Example in graphcool/prisma: https://github.com/graphcool/prisma/blob/8dbdd73ec9e7eef31c423479488c26e7910959ff/server/api/src/main/scala/com/prisma/api/database/DatabaseQueryBuilder.scala#L154

**Comment by nickluger** [comment]
To me it seems they are using splicing literal values only for models, names etc. which are created **by the developer / owner**. SQL injections are only relevant for **user-generated** content, for example form input or comments. 

`#${project.id}`.`#${where.model.name}.` etc are defined by **you**, not your users.

This would only become dangerous if you let users define their own data models, but prisma does not define any interface to do such thing.

**Comment by dpetrick** [comment]
@nickluger is correct. We can't bind table names in slick queries, so we have to interpolate the values into the actual SQL. Afaik, the naming constraints on the interpolated strings (say, a model name) will prevent an injection even if the owner would try to trigger one.

**Comment by sorenbs** [comment]
Thanks for opening the issue @BijanVan 

As pointed out, we believe all cases are covered correctly. We also have a test suite for SQL Injection attacks that we haven't had time to move to the open source repository yet.

If you believe you have found a concrete issue, please open a new ticket :-)
