### ISSUE TITLE
Can not create two relations on same models

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1819]
# Bug Report

**Current behavior**
I have 2 models:
```
type User {
  id: ID! @unique
  username: String! @unique
  # calls innited by user
  calls: [Call!]! @relation(name: "CallRequester")
  # calls where user is member
  calls_member: [Call!]! @relation(name: "CallMembers")
}
```
```
type Call {
  id: ID! @unique
  created_by: User! @relation(name: "CallRequester")
  created_at: DateTime!
  members: [User!]! @relation(name: "CallMembers")
}
```

On deploy prisma create only one table for relation, not two. When i try exec query
```
mutation createCall(
  $call_date: DateTime!
){
  createCall(
    data:{
      created_at: $call_date
      created_by: {
        connect:{
          id:"cjcwr8ev954yz0116e6fxnx57"
        }
      }
      members: {
        connect: [{
          id: "cjcww5hnt73fr0116nrl4vrj7"
        },{
          id:"cjcwr8ev954yz0116e6fxnx57"
        }]
      }
    }
  ){
    id
  }
}
```

I catch error "Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjd8gko5k0mo50190u72pvfyo"

SQL log:
```
insert into `com@dev`.`_CallRequester` (`id`, `A`, `B`)
           Select 'cjd8gjwtb0mdo0190kdnss1tq', (select id from `com@dev`.`Call` where `id` = 'cjd8gjwta0mdn0190y20d0x0k'), `id`
           FROM `com@dev`.`User` where `id` = 'cjcwr8ev954yz0116e6fxnx57' on duplicate key update `com@dev`.`_CallRequester`.id=`com@dev`.`_CallRequester`.id
```
```
Table 'com@dev._CallRequester' does not exists;
```

**Comment by do4gr** [comment]
Hey @Fi1osof, thanks for the report. I tried reproducing the bug but did not succeed. I took your datamodel and deployed it to a fresh local cluster and it created two relation tables as expected. Could you try once more? Or maybe you have more info to reproduce this error?

<img width="1168" alt="bildschirmfoto 2018-02-09 um 17 16 10" src="https://user-images.githubusercontent.com/16278407/36037487-41902892-0dbd-11e8-9d80-1157395e5818.png">

**Comment by Fi1osof** [comment]
@do4gr since my reporting prisma-1.1.3 came and i think it`s fixed (in some relation). I close this issue and will open if will catch again.  Thanks!
