### ISSUE TITLE
Expiring file secrets

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#182]
Currently Graphcool exposes uploaded files on the web and keeps them somewhat secure by making their URL unintelligible. However, once a URL is known, it can still be freely passed around the web forever. 

Similar to [AWS presigner expires_in](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Presigner.html) which provides signed URLs, there should be a secret expiration mechanism, whereas a URL is only valid for a certain time.

Or will this be somehow resolved by the new Permissions system?

**Comment by checkmatez** [comment]
I think the expiration time should be controllable also.

**Comment by sedubois** [comment]
I'm still quite hesitant to migrate my production to Graphcool because of this issue. Is there any hope of having this fixed? How do other projects who distribute their content behind a paywall feel about this? Thanks a lot

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
