### ISSUE TITLE
Do not set default value for new record

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1820]
# Bug Report

**Current behavior**

Model:
```
enum IsActive{
  Yes
  No
}

type Service {
  id: ID! @unique
  name: String!
  description: String
  unit: String
  active: IsActive @defaultValue(value: "Yes")
}
```

Query:
```
mutation createService(
  $serviceName:String!
){
  createService(
    data:{
      name: $serviceName
    }
  ){
    id
  }
}
```

In datadase column active is null.

And is this OK that column active type mediumtext? Not enum(`Yes`,`No`).

**Comment by do4gr** [comment]
Hey @Fi1osof thanks for reporting this. I could reproduce it and am looking into it. And thanks for always providing schema and mutation, that makes the reproduction very easy for us.

**Comment by Fi1osof** [comment]
@do4gr thanks!

**Comment by Fi1osof** [comment]
@do4gr 
Model:
```
type Geo{
  id: ID! @unique
  lat: Float @default(value: "null")
  lng: Float @default(value: "null")
}
```
On create is OK, lat and lng is null.
But on prisma deploy create fields updated records not null values;
http://joxi.ru/L21WpJ8I698k9r

Is there way fix it?

**Comment by do4gr** [comment]
Sorry for the late reply. Can you clarify what you mean? Values you already had before you introduced the default value still show 0.00?  
Adding a default value only affects new nodes being created as far as I know. So existing nodes will not be affected. If you want to set all existing values to null you will need to update them.

**Comment by Fi1osof** [comment]
@do4gr 
> If you want to set all existing values to null you will need to update them.
Yes, want it.
OK, i will update them. Thnaks!
