### ISSUE TITLE
playground didn't show added description

### ISSUE THREAD

**Issue by llnewuser** [graphcool/prisma#1823]
# Bug Report

**Current behavior**
playground didn't show added description

**Reproduction**
in datamodel.graphql file, add a description, for example

type Post {
 
  "This is the title of a post"
  title: String!

}

**Expected behavior?**
in playground doc, show “This is the title of a post”. 

If add a description in generated/prisma.graphql file, playground doc will show added description.

**Comment by marktani** [comment]
That's intended behaviour at the moment. I created a detailed feature request to support SDL features like comments/descriptions in the datamodel here: #2152.

**Comment by yuguangmao** [comment]
Use Case: if add a comment for a field of data model , the auto-generated prisma.graphql also include it . thanks

**Comment by threem0126** [comment]
this is so great! waiting for release !
