### ISSUE TITLE
Getting Started Working?

### ISSUE THREAD

**Issue by idkjs** [graphcool/prisma#1831]
# Bug Report

**Current behavior**
run `prisma init hello-world`
select fullstack
select prismaeu public cluster
click link for cluster

get this error in playground
```json
{
  "code": 3015,
  "requestId": "api:api:cjdbgbag7aufz01440oldytto",
  "error": "Your token is invalid. It might have expired or you might be using a token from a different project."
}
```
macOS Sierra

**Expected behavior?**
loaded graphql schema and ability to run query

**Related?**
https://github.com/graphcool/prisma/issues/1717

**Playground**
https://graphqlbin.com/rkEVfn

**Comment by marktani** [comment]
This error message is expected, when you access a Prisma service that is protected by a secret without a valid token.

You need to run `yarn dev` to start server _and_ GraphQL Playground or `yarn playground` to open the Playground. This should automatically generate a valid `Authorization` header.

If that's not the case, run `prisma token` and set the header in the Playground manually with the received token:

```
{
  "Authorization": "Bearer <token>"
}
```

Read https://www.prismagraphql.com/docs/reference/prisma-api/concepts-utee3eiquo#authentication for more information.
