### ISSUE TITLE
Error when deploying Optional Backrelation

### ISSUE THREAD

**Issue by do4gr** [graphcool/prisma#1836]
Going from this 
<img width="344" alt="bildschirmfoto 2018-02-06 um 16 40 24" src="https://user-images.githubusercontent.com/16278407/35868344-80633482-0b5c-11e8-9daf-df8a80a62b22.png">

to this 
<img width="353" alt="bildschirmfoto 2018-02-06 um 16 37 00" src="https://user-images.githubusercontent.com/16278407/35868362-8c423654-0b5c-11e8-86aa-705616dec8e3.png">

results in this

<img width="703" alt="bildschirmfoto 2018-02-06 um 16 36 39" src="https://user-images.githubusercontent.com/16278407/35868383-9c6d2b9c-0b5c-11e8-8a83-3a9a29bef7fe.png">

removing both relations completely first and then just adding the optional backrelation works though.

It also does not seem to be possible to have two relations between two models and still have one of them omit the backrelation. This results in a schema validation error regarding the relation directive. The directive is required since there are two relations to the other type, but since one does not have a backfield the relation directive cannot also be in the schema twice as required.

**Comment by marktani** [comment]
Added to this list: https://github.com/graphcool/prisma/issues/2018.
