### ISSUE TITLE
Update and Upsert in relations

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1837]
# Bug Report

Model:
```
type Geo{
  id: ID! @unique
  latitude: Float!
  longitude: Float!
}

type Place{
  coords: Geo
}
```

I want create query
```
  updatePlace(
    where:{
      id:$placeId
    }
    data:{
      coords:{
        update:{
           where: {
              id: $coords_id
           }
           data: {
               latitude: 53.5
               longitude: 34.7
           }
        }
      }
    }
  ){
    ...place
  }
```

But available only:
type GeoUpdateOneInput {
   create: GeoCreateInput
   connect: GeoWhereUniqueInput
   disconnect: GeoWhereUniqueInput
   delete: GeoWhereUniqueInput
}

Update and Upsert exists only if declare relation both in Geo and Place

**Comment by do4gr** [comment]
Hey @Fi1osof thanks for reporting this. I can reproduce it and you are correct, update and upsert should be generated there. At the moment there is a bug with optional back relations that not all InputObjectTypes are generated. A fix should be coming soon.

**Comment by Fi1osof** [comment]
@do4gr thanks!

**Comment by seanchambo** [comment]
Think this issue can be closed yeah?

**Comment by Fi1osof** [comment]
@seanchambo i think so:)
