### ISSUE TITLE
Updating a field to the value null has no effect

### ISSUE THREAD

**Issue by RishitKedia** [graphcool/prisma#1848]
Hey there! 👋

# Bug Report

## Current Behavior

Updating a field to the value `null` does not work. 😭

## Reproduction

```gql
mutation {
  updateUser(
    where: {
      email: "email"
    },
    data: {
      code: null
    }
  ) {
    id
    email
    code
  }
}
```

The mutation above still returns the previous value of `code`:

```js
{
  "updateUser": {
    "id": "id",
    "email": "email",
    "code": 123456
  }
}
```

## Expected Behavior

The value of the field `code` should be `null`. 🤓

Thanks! 🙏

**Comment by do4gr** [comment]
The issue should be fixed on the unstable channel now.
