### ISSUE TITLE
NOT operator in filters

### ISSUE THREAD

**Issue by crubier** [graphcool/prisma#1852]
# Feature Request

A `NOT` operator would be useful in filters. We already have `AND` and `OR`. With the `NOT` operator we could have complete first order logic. I have a use case where this would be useful, and I have to fallback to dynamically generating a complex query instead. 

I don't know about the performance impact, but it does not look complicated to implement to me (as far as I know)

**Comment by sorenbs** [comment]
This is a very reasonable feature request.

If anybody is interested in preparing a Pull Request, then I'd be happy to help guide you and make sure we get adequate test coverage.

**Comment by jMuzsik** [comment]
Hi! I'd be up for doing this but I would be new to Scala so it may take me a bit of time to finish

**Comment by marktani** [comment]
Merged in #2234. Thanks a lot for the contribution @PatrykRudnicki 🙌
