### ISSUE TITLE
Not all Github accounts are supported for sign up

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1854]
# Bug Report

**Current behavior**

Signing up with a Github account that contains a single quote makes deploying impossible.

I imagine the same problem occurs for all kinds of different unicode characters in the Github name.

**Reproduction**

Read more information [here](https://www.graph.cool/forum/t/prisma-service-deployment-invalid-cluster-name/2496?u=nilan).

**Expected behavior?**

A Github name should be sanitized to adhere to naming rules of workspace/service names.

**Comment by schickling** [comment]
This should be fixed. Please re-open or comment if this is still a problem. 🙏
