### ISSUE TITLE
Make hyperlinks clickable

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#186]
- when I select in playground a field which is a URL, it would be great if it could be made clickable
- similar with browser view, e.g make the `File`'s `url` property clickable

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
