### ISSUE TITLE
Error deploying when sign in to cloud with email 

### ISSUE THREAD

**Issue by PatrickStrz** [graphcool/prisma#1862]
# Bug Report

**Current behavior**

Log in to cloud with email ( `prisma login`) and running `prisma deploy` gives me the following error:

ERROR: patrick.strzelec~testPrisma is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers, underscores and hyphens.
```
{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "addProject"
      ],
      "code": 4001,
      "message": "patrick.strzelec~testPrisma is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers, underscores and hyphens.",
      "requestId": "cluster:cluster:cjdg5xyvg7ysd01691e7k6win"
    }
  ],
  "status": 200
} 
```

 and the service is not deployed. It deploys just fine if remove remove the `cloudSessionKey` from `~/.prisma/config.yml`

**Reproduction**
Log in to cloud with email ( `prisma login`) and run `prisma deploy` for this service: https://github.com/PatrickStrz/prismaTest/blob/master/prisma.yml  

**Expected behavior?**
deploys to cloud without an error

**Comment by marktani** [comment]
This has been fixed a while ago 🙂
