### ISSUE TITLE
Permission query testing

### ISSUE THREAD

**Issue by altschuler** [graphcool/prisma#188]
It would be very useful to have a way to quickly test permission queries against users in the database.

For instance, I'm writing a Read permission query for a Story type, and would like to see what users can see a particular story or something like that. At the moment I'm using the playground to test.

**Comment by marktani** [comment]
Great suggestion!

Would it be good enough if you had to select the particular story and the particular user and see the result of the permission query?

**Comment by altschuler** [comment]
That would work, and even better would be selecting the user and getting a list of stories, or selecting the story and getting a list of users.

**Comment by marktani** [comment]
For now, you can use the playground. Let's say, this your permission query:

```graphql
query ($user_id: ID!, $node_id: ID!) {
  SomeTypeExists(filter: {
    id: $node_id
    owner: {
      id: $user_id
      role: ADMIN
    }
  })
}
```

This translates to the following query in the playground:

```graphql
query ($user_id: ID!, $node_id: ID!) {
  allTypes(filter: {
    id: $node_id
    owner: {
      id: $user_id
      role: ADMIN
    }
  }) {
    id
  }
}
```

Make sure to insert the correct node and user ids and to run the query as the user you want to check the permission for.
It's a bit tedious, but might be helpful 🙂

**Comment by marktani** [comment]
A simple way to add more control/insights here would be to expose the `SomeTypeExists` queries from the permission query schema.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
