### ISSUE TITLE
5 hours

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1881]
I just lost five hours of my life with https://github.com/este/este/issues/1466

prisma-binding and graphql-yoga should fix graphql dependency, or I don't know.

**Comment by marktani** [comment]
Thanks @steida, there looks to be a dependency issue with a package that `graphql-yoga` uses.
You can check https://github.com/graphcool/graphql-yoga/issues/162 for more information.

I'm sorry you lost 5 hours of your life, I hope you will regain them back quickly 🙂

**Comment by marktani** [comment]
For anyone still running into this, upgrading `yarn` from `0.27.5` to `1.3.2` fixed it for me.
