### ISSUE TITLE
Prisma deploy: ERROR: Workspace * does not exist

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma#1885]
# Bug Report

**Current behavior**

Running `prisma deploy` on a shared cluster yields the following error. 

```
divyendusingh [prisma]$ prisma deploy

ERROR: Workspace * does not exist

{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "Workspace * does not exist",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ]
    }
  ],
  "status": 200
}
```

**Reproduction**

I am not sure on this one but this is how my prisma.yml looks like

```
divyendusingh [prisma]$ cat database/prisma.yml
# the name for the service (will be part of the service's HTTP endpoint)
service: ds

stage: dev

secret: very-secret-going-to-version-control-but-i-know-it-and-dont-care

datamodel: datamodel.graphql

seed:
  import: seed.graphql

cluster: prisma-eu1
```

This is for this codebase:- https://github.com/divyenduz/ds
I just changed cluster from `local` to `prisma-eu1`.

Another point to note is that my email has a "." in it and in past I faced an issue while doing `prisma login`. That could be related to this. 

Please let me know how can I help reproduce this one. 

**Expected behavior?**
Prisma deploy should work on shared cluster when working on local.

**Comment by ragzor** [comment]
I'm getting the same error.

**Comment by marktani** [comment]
Does this still happen on the latest beta version?

**Comment by marktani** [comment]
@divyenduz confirmed that this hasn't happened in a while. I assume this is fixed.

@divyenduz @ragzor, please open a new issue if you're encountering this again.
