### ISSUE TITLE
Use custom docker-compose.yml file

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma#1886]
Is it possible to use a custom `docker-compose.yml` file to deploy Prisma infrastructure? 

I remember that there was something like `eject` in `graphcool-framework`.

**Comment by marktani** [comment]
Thanks for bringing this up, @divyenduz 🙂

`prisma local` works against this [docker-compose.yml](https://github.com/graphcool/prisma/blob/ffd71512e493c321c70e46cedbdfeb719bd1562d/cli/packages/prisma-cli-core/src/commands/local/docker/docker-compose.yml) file.

So you can easily run `docker-compose` yourself, providing a `docker-compose.yml` that is derived from the one above.

That should cover your use case - if you have a more specific use case, freel free to create a feature request 🙂

**Comment by marktani** [comment]
With the `1.7` release, the `docker-compose.yml` file is now directly exposed when running `prisma init`.
