### ISSUE TITLE
Lose parent on update Type-to-Type relation parent.

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1895]
# Bug Report

**Current behavior**

prisma local 1.2.1 (linux-x64) node-v9.4.0

Model:
```
type Service {
  id: ID! @unique
  name: String!
  parent: Service @relation(name: "ServiceParent")
  # ....
}
```

Mutation:
```
mutation serviceSetParent(
  $parentId:ID!
  $childId:ID!
){
  updateService(
    where:{
      id: $childId
    }
    data:{
      parent:{
        connect:{
          id:$parentId
        }
      }
    }
  ){
    id
    name
  }
}
```

On update id parent have no parent, it`s OK. But if parent have parent, connected parent lose parent.

https://youtu.be/QWkn3I6FffA

**Comment by do4gr** [comment]
Hey @Fi1osof, thanks for reporting this. I tried to reproduce the issue as I understood it, but it seems to be working now. In my example parent already had parentofparent as it's parent. I then updated child to set parent as it's parent. The parent of parent was then still set as parentofparent.  

![bildschirmfoto 2018-03-06 um 15 17 13](https://user-images.githubusercontent.com/16278407/37036952-7daa418a-2151-11e8-8f27-2083cd3bb128.png)
 
We fixed some bugs around self-relations, so maybe this fixed your issue. Or I might have misunderstood the issue. Could you try to see whether it still fails for you?

**Comment by Fi1osof** [comment]
@do4gr hi!

Yes, 1.3.5 all fine! Thanks! :)
