### ISSUE TITLE
Beta channel is not uptodate

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1900]
# Bug Report

**Current behavior**

Beta channel is not cut correctly.

**Reproduction**

```
npm install -g prisma@beta
prisma version
prisma local upgrade
prisma cluster list
```

```
prisma/1.2.0-beta.7 (darwin-x64) node-v8.3.0
local       1.2-beta-5  http://localhost:4466/cluster
```

For some reason, the beta channel is not uptodate

**Expected behavior?**

Should say something like this:

```
prisma/1.3-beta.1 (darwin-x64) node-v8.3.0
local       1.3-beta-1  http://localhost:4466/cluster
```

**Comment by dpetrick** [comment]
It should actually say `1.3-..` in this case, if I'm not mistaken. Minor version is upgraded.

**Comment by marktani** [comment]
Thanks, just updated it. You're right 🙂

**Comment by marktani** [comment]
It's now `prisma@1.3.0-beta.0` and `1.3-beta-6` 🙂
