### ISSUE TITLE
[1.3.0-beta.1] Wrong TypeScript type definitions

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma#1902]
# Bug Report

Current version: `1.3.0-beta.1`

**Current behavior**

The TypeScript type definitions are off in the current beta release. The signature of an `updateX` method is wrong.

An example:

```typescript
// ... snip
updateUser: (args: { data: UserUpdateInput, where: UserWhereUniqueInput }, info?: GraphQLResolveInfo | string) => Promise<User | null>

// ... snip

export interface UserUpdateInput {
  where: UserWhereUniqueInput
  data: UserUpdateDataInput
}
```

The `UserUpdateInput` defines the `where` and `data` whereas it should only contain the possible updatable attributes.

**Reproduction**

  * Create a new type in your Prisma service
  * Execute `graphql prepare --bindings -g prisma-ts --bundle`
  * `npm run build` to see all the compile errors

**Expected behavior?**

The `UserUpdateInput` should provide the updatable attributes.

**Comment by marktani** [comment]
When you look at the schema in the GraphQL Playground, is it also wrong there?

**Comment by akoenig** [comment]
#1911 fixed this problem. Closing here. Thanks to all who were involved 🎉
