### ISSUE TITLE
Deploying with Now

### ISSUE THREAD

**Issue by idkjs** [graphcool/prisma#1905]
# Bug Report

**Current behavior**
Playground works on now deployment: https://laft-with-prisma-aekhijqmxi.now.sh/

- [query](https://graphqlbin.com/v2xQi4)
```json
{
  feed {
    id
  }
}
```
- output:
```json
{
  "data": {
    "feed": [
      {
        "id": "cjd31fpete4my0144yu893dnl"
      },
      {
        "id": "cjd31fpf4e4n00144o9ym2fpw"
      }
    ]
  }
}
```
Playground schema loads but running query throws error on aliased with Zeit/Now url: https://laft-with-prisma.now.sh/ when you go to the url directly. Interestingly, if you click on the graphqlbin.com share link below, it takes you to the bin and runs the query correctly against the aliased url. 
- [query](https://graphqlbin.com/xkz2FP)
- output:
```json
Variables are invalid JSON: JSON.parse: expected ':' after property name in object at line 3 column 1 of the JSON data.
```
- other note
- this playground share [link](https://www.graphqlbin.com/v2xYCy) is sticking the beginnings of a default variable value for some reason.
**Expected behavior?**
Expected that queries work the same way on alias and generated url.

**Comment by idkjs** [comment]
And now that we have that info above, it turns out that what is going on is that the aliased link is populating a query variable. You dont see it unless you open up the variables panel. I tried to make a gif of it and then it stopped happening but if you click the old share links, its still doing it. FYI...

**Comment by ammichael** [comment]
Is there any solution to this? I'm trying to deploy to Now but I'm not really sure how.

**Comment by marktani** [comment]
Hey @idkjs I'm afraid I'm not quite following your problem. Can you elaborate what specific problem you're facing?

@ammichael, you can check out https://blog.graph.cool/deploying-graphql-servers-with-zeit-now-85f4757b79a7 as a start :slightly_smiling_face:

**Comment by idkjs** [comment]
Just an FYI. Will re-issue if comes up again.

**Comment by maierson** [comment]
@marktani re: demo for deploying to now. The instructions do not match up with what installs when running 

```
graphql create hello-advanced --boilerplate node-advanced
``` 

ie you do not get prompted to choose the demo server there is not `start` script for yarn to execute and . Am I missing something?
