### ISSUE TITLE
Endpoint information for services on private clusters is not correct

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1915]
# Bug Report

**Current behavior**

`prisma info` for a service on a private cluster prints the wrong endpoint.

**Reproduction**

* deploy a service to a private cluster
* run `prisma info`

You'll see an endpoint like this:

```
https://<cluster>.<workspace>.prisma.sh/<workspace>/<service-name>/<stage>
```

**Expected behavior?**

It should be

```
https://<cluster>.<workspace>.prisma.sh/<service-name>/<stage>
```

instead.

**Comment by timsuchanek** [comment]
Fixed in latest beta
