### ISSUE TITLE
Non-interactive mode for `cluster add`

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma#1919]
# Feature Request

**What feature are you missing?**

It would be great to have a non-interactive mode for `prisma cluster add`. With that in place it would be possible to integrate a `prisma deploy` into a CI/CD process.

**How could this feature look like in detail? Tradeoffs?**

Instead of asking the user in an interactive way, passing the options via CLI arguments could / should also be possible.

**Comment by marktani** [comment]
With the deprecation of `prisma cluster` in `1.7`, I'll close this issue.
We'll make it significantly easier to manage multiple clusters soon.
