### ISSUE TITLE
gc shortcut for graphcool interferes with graphviz gc

### ISSUE THREAD

**Issue by dbkaplun** [graphcool/prisma#1925]
Hi Graphcool team,

It looks like the `gc` command is already used by graphviz. It would be great if graphcool could use a different shorthand.

Thanks for considering!

**Comment by marktani** [comment]
Issue moved to [graphcool/graphcool-framework #476](https://github.com/graphcool/graphcool-framework/issues/476) via [**ZenHub**](https://www.zenhub.com/)
