### ISSUE TITLE
>2 seconds queries when using eu1 and us1 endpoints.

### ISSUE THREAD

**Issue by JofArnold** [graphcool/prisma#1934]
As per the title.

POSTing a simple to `http://localhost:4000/` for the apollo hacker news demo takes about 2.5 seconds in total to return the data to playground or the app. Pinging `us1.prisma.sh` takes about 150ms so it's not network I think.

Perhaps related to https://github.com/graphcool/prisma/issues/1863 ?

**Comment by sorenbs** [comment]
@JofArnold It sounds like you are experiencing the 1 request per second throttling in the public cluster. We are rolling out a change today or tomorrow to allow short bursts to prevent this issue. Please follow #1863 for updates :-)
