### ISSUE TITLE
No Unified Endpoint

### ISSUE THREAD

**Issue by fnolla-carecloud** [graphcool/prisma#1940]
I have the following in my index
```import { GraphQLServer } from 'graphql-yoga'
import { Prisma } from './generated/prisma'
import resolvers from './resolvers'

const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      endpoint: process.env.PRISMA_ENDPOINT, // the endpoint of the Prisma DB service (value is set in .env)
      secret: process.env.PRISMA_SECRET, // taken from database/prisma.yml (value is set in .env)
      debug: true, // log all GraphQL queries & mutations
    }),
  }),
})

server.start(() => console.log(`Server is running on http://localhost:4000`))
```
What i don't understand is why i am not able to query and use my resolvers through one url. Is this expected? I have to use two endpoints currently which to me seems wrong.

and for resolvers i have to use: http://localhost:4000
for db queries etc i have to use: http://localhost:4466/portover/dev

**Comment by marktani** [comment]
This is expected.

`localhost:4466` is your local Prisma cluster. There is one service deployed there called `portover`, with the stage `dev`. This results in the Prisma endpoint `http://localhost:4466/portover/dev`.

`localhost:4000` is your application server. It connects to the Prisma service and uses `prisma-binding` to expose your application GraphQL API.

I hope this helps with your understanding.

If you have further questions about usage or concepts, please refer [to the Forum](https://www.graph.cool/forum/c/questions). Thanks! 🙌
