### ISSUE TITLE
Cannot start local data cluster

### ISSUE THREAD

**Issue by fonzied** [graphcool/prisma#1946]
After using "prisma local start", I get this error:

The Compose file
 !    '...\prisma-cli-core\dist\commands\local\docker\docker-compose.yml'
 !    is invalid because:
 !    services.prisma-database.ports is invalid: Invalid port "0.0.0.0:local:local", should be
 !    [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

And it doesn't seem to matter what I change it to.

**Comment by zifahm** [comment]
try updating the images from prisma  local update

**Comment by fonzied** [comment]
Same error. Even tried on a clean boilerplate.

**Comment by akoenig** [comment]
@fonzied Could you share your `.env` and `~/.prisma/config.yml` files maybe? (even if dev version; remove the `secret(s)` before :smile:)

**Comment by fonzied** [comment]
So I fixed the problem by using someone else's docker-compose file that is configured differently, now it just infinitely loops at "Booting local development cluster..." :/

**Comment by fatjoeluke** [comment]
I get stuck at this step too, Just loops forever. DEBUG="*" offers no useful information as it just outputs the commands.

I have noticed the networks get created though.

**Comment by marktani** [comment]
Hey everyone, can you share your `prisma version` and `docker ps`? 🙂

**Comment by fatjoeluke** [comment]
@marktani #2013 appears to be the issue that i was facing. Looked like a hanging process but really the connection speed was making it take longer than expected.

**Comment by marktani** [comment]
It seems all problems were resolved :slightly_smiling_face: 

For anyone still running into this problem, you might need to also upgrade your `docker-compose` version.

**Comment by wuzhuzhu** [comment]
I stuck in this problem as well. And my docker osx software is fresh installed.  
docker-compose version 1.20.1, build 5d8c71b
