### ISSUE TITLE
Subscription filter for CREATED etc. not working

### ISSUE THREAD

**Issue by Lauchi** [graphcool/prisma#1950]
# Bug Report

**Current behavior**

When i use a filter for CREATED etc. on my subscription in prisma, the subscription does not get triggered. According to an example (that i do not find anymore) it should work with a `{mutation_in: [CREATED]}` where condition but that does not even compile. Adding it in " or passing as a string array does not work either.

**Reproduction**

https://github.com/Lauchi/rnv-graphql-backend

**Expected behavior?**

The subscription gets filtered correctly

**Comment by oiojin831** [comment]
maybe duplicate with
https://github.com/graphcool/prisma/issues/1734

**Comment by Lauchi** [comment]
Yes this is the same thing, thangks, I did not find that =)
