### ISSUE TITLE
For God's sake, use the semver, please

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1952]
> Hey  Daniel,
> 
> In an upcoming release of Prisma and Prisma Cloud we will introduce a change to simplify the nested mutation for to-one relations. This introduces a small breaking change in the API...

Use the foking semver for such things, please. Am I asking a lot? We have https://semver.org/ for a reason. Don't be ashamed to increment that foking major version. Thank you.

(In the middle of fixing broken stuff because people do not follow semver for some reason)

**Comment by steida** [comment]
Let me reformulate it. If Prisma has a breaking change in API, it should release a new major version. It's that simple. Thank you.

**Comment by sedubois** [comment]
@steida Regardless, it does not warrant such language. It is very possible to make a clear, positive, constructive request while remaining respectful. Would you like someone to talk to you this way?

**Comment by kbrandwijk** [comment]
@steida Feel free to open a new, more constructive issue on the matter, without the religious aspect and the profanity. Thank you.

**Comment by steida** [comment]
Fok it I am fixing other people bugs all days I don't care anymore...

**Comment by steida** [comment]
Use semver or not I don't care anymore...

**Comment by marktani** [comment]
Hey @steida, thanks for providing your feedback! 🙌 

Indeed, the version of `prisma` and [the related docker image](https://hub.docker.com/r/prismagraphql/prisma/) for the cluster is _not_ following semantic versioning.

Instead, we are following a ~bi-weekly release cycle, where we upgrade the minor version. Commits after a minor upgrade result in a new version being published on the "unstable" channel (which is being published under the `beta` tag in `npm`). Sometimes, we are bundling changes on the unstable channel into a new patch release.

The reason we follow this release system is that you are in charge of the version of your cluster, and therefore you are in control when to roll out an upgrade to your cluster.

The development clusters are managed by us, and are receiving continuous upgrades.

If you need more control over your cluster version, you can self-host a cluster (for example on [Digital Ocean](https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu) or [Kubernetes](https://www.prismagraphql.com/docs/tutorials/cluster-deployment/kubernetes-aiqu8ahgha)) or use Prisma Cloud to setup a private cluster that we host for you. In both cases, you can fully control the version of your cluster.

You can find more information about the release channels [here](https://github.com/graphcool/prisma/wiki/Release-Channels).

I hope this provides you with more context for our approach to releases and versioning 🙂
