### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by jelder** [graphcool/prisma#1956]
The documentation for the DateType type reads as follows.

- `datatime: "2015"`
- `datatime: "2015-11"`
- `datatime: "2015-11-22"`
- `datetime: "2015-11-22T13:57:31.123Z"`

Note "dat**a**time" not "dat**e**time" in the first three examples.

**Comment by akoenig** [comment]
Ahh, good catch. Thanks @jelder :+1:
