### ISSUE TITLE
Prisma Import fails when importing zipped file from Prisma Export

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma#1965]
# Bug Report

**Current behavior**

prisma import works for unzipped, but fails on zipped.  It appears there's some cache storing an old version of the data.  Simply extracting the ZIP file and pointing towards the folder allowed the import.

![image 2018-02-22 at 12 41 39 pm](https://user-images.githubusercontent.com/17485128/36560543-3e65ca9e-17ce-11e8-9614-48b049f9273f.png)

![image 2018-02-22 at 12 42 22 pm](https://user-images.githubusercontent.com/17485128/36560551-4744edc0-17ce-11e8-966a-98028e9f3a2a.png)

**Reproduction**

prisma import -d *.zip

**Expected behavior?**

Successful import

**Comment by johannpinson** [comment]
Hey @LawJolla 

When the import failed with a .zip, the property `dealership` is about a required relation?
Because I got the same reported here: https://github.com/graphcool/prisma/issues/1767

**Comment by LawJolla** [comment]
@johannpinson ,

Yes.  For me, when it was imported from an unzipped folder, it worked fine

**Comment by johannpinson** [comment]
Same for me, I think you can close this issue as a duplicate of #1767 😉

**Comment by timsuchanek** [comment]
Thanks for reporting everyone! As #1767 is fixed, can you confirm that this issue is fixed, too @LawJolla ?

**Comment by LawJolla** [comment]
@timsuchanek Good on my end.  Thank you!
