### ISSUE TITLE
throw from resolver should not be logged

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#1978]
Maybe I am wrong, but

```
const throwError = (error /*: ServerError */) => {
  throw new Error(JSON.stringify(error));
};

const throwNotAuthorizedError = () => throwError({ type: 'notAuthorized' });
```

Seems to be a recommended way how to stop resolver, but then probably this should not be logged.

![screen shot 2018-02-26 at 02 03 45](https://user-images.githubusercontent.com/66249/36648920-5229bac2-1a99-11e8-9018-0db7286ad8ab.png)

**Comment by marktani** [comment]
Issue moved to [graphcool/graphql-yoga #199](https://github.com/graphcool/graphql-yoga/issues/199) via [**ZenHub**](https://www.zenhub.com/)

**Comment by marktani** [comment]
Thanks for opening this discussion, I moved it here: https://github.com/graphcool/graphql-yoga/issues/199.
