### ISSUE TITLE
Changing alias does not delete the old endpoint

### ISSUE THREAD

**Issue by awwilhelm** [graphcool/prisma#1982]
# Bug Report

**Current behavior**
If you change the alias, you can still make queries to the old endpoint.
**Reproduction**
Go into settings and change the alias.  Then click the endpoint button and it will show you the new endpoint.  However, both the old and new endpoint work.
**Expected behavior?**
Once you change the alias, it should delete the old endpoint.

**Comment by marktani** [comment]
Thanks for the report, @awwilhelm. It looks very similar to this one: https://github.com/graphcool/graphcool-framework/issues/426.

Please report further questions and issues about Graphcool Framework in this repo instead: https://github.com/graphcool/graphcool-framework. Thanks!
