### ISSUE TITLE
Relations not created for nested nodes when seeding

### ISSUE THREAD

**Issue by kuldar** [graphcool/prisma#1984]
# Bug Report

**Current behavior**

When deploying a fresh Prisma service along with a seed file, the nodes seem to be created, but not the relations between them.

**Reproduction**

The `datamodel.graphql` file
```graphql
type Calendar {
  id: ID! @unique
  name: String!
  
  bookings: [Booking!]!
}

type Booking {
  id: ID! @unique
  totalPrice: Int!

  calendar: Calendar!
}
```

The `seed.graphql` file
```graphql
mutation {
  firstCalendar: createCalendar(
    data: {
      name: "Bob's Calendar"
      bookings: {
        create: [{
          totalPrice: 9900
        }]
      }
    }
  ) { id }
}
```

**Expected behavior?**

When testing in GraphQL playground, I can see the nodes created, but not the relations.

<img width="724" alt="screen shot 2018-02-27 at 17 26 25" src="https://user-images.githubusercontent.com/1710629/36737412-ab7027a6-1be3-11e8-9456-c270a035a9fb.png">

**Comment by marktani** [comment]
Hey @kuldar, thanks for reporting this problem.

When running the mutation yourself against the API, do you observe the expected behaviour?

**Comment by kuldar** [comment]
Hey @marktani, when I run the same mutation in the `https://eu1.prisma.sh/kuldar/MY-APP/dev` playground, things seem to work and nodes are created with correct relations.

<img width="917" alt="screen shot 2018-02-27 at 19 45 50" src="https://user-images.githubusercontent.com/1710629/36745023-fe0b379a-1bf6-11e8-843f-0ae8a7803348.png">
<img width="916" alt="screen shot 2018-02-27 at 19 46 27" src="https://user-images.githubusercontent.com/1710629/36745026-0123e864-1bf7-11e8-82d7-4e48c287c224.png">

**Comment by marktani** [comment]
Hey @kuldar, can you please describe how you are using `seed.graphql` exactly? Are you using the `seed` property in `prisma.yml`?

**Comment by do4gr** [comment]
The issue seems to have been fixed by recent changes. 

<img width="1217" alt="bildschirmfoto 2018-04-08 um 19 45 51" src="https://user-images.githubusercontent.com/16278407/38470598-894ffa7e-3b65-11e8-8550-2e96c0c8b2d0.png">
