### ISSUE TITLE
creating new cluster in GUI seems busted

### ISSUE THREAD

**Issue by brandonmp** [graphcool/prisma#1988]
windows 10, tested on latest Firefox developer and Chrome stable, adblock disabled

trying to create a new cluster in the prisma cloud console. upon clicking 'test connection' (to an aurora instance verified working), though, nothing happens. 

In the console, a second or so after clicking the 'test connection' button, a `POST` to `api.cloud.prisma.sh/` returns this error:

```
{"data":null,"errors":[{"message":"connect ETIMEDOUT","locations":[{"line":2,"column":3}],"path":["testConnection"]}]}
```

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma-cloud-feedback #68](https://github.com/graphcool/prisma-cloud-feedback/issues/68) via [**ZenHub**](https://www.zenhub.com/)

**Comment by marktani** [comment]
Thanks @brandonmp, I moved the issue here: https://github.com/graphcool/prisma-cloud-feedback/issues/68.
