### ISSUE TITLE
Subscriptions result in opcode -1

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1989]
# Bug Report

**Current behavior**

Creating subscription connections fails, and results in opcode -1.

**Reproduction**

https://github.com/moritzmorgenroth/prisma_subscription_issue

**Expected behavior?**

It works.

**Comment by Fi1osof** [comment]
I have same problem, 2 variants:
1. On http://..:4466 is OK, but http://..:4000 Opcode -1
2. On https:// website subscriptions via apollo-client OK, but when open many tabs will receive opcode -1 too (not right away). When i close other tab and reload tab with opcode, OK again.

**Comment by marktani** [comment]
Please open a new issue and provide a reproduction :slightly_smiling_face:

**Comment by Fi1osof** [comment]
@marktani i understood. I have site on https://domain/ and rewrite api on port 4000 by rule /api/ => / :4000
When i open playground on https://domain/api/ payload setted to https://domain/ I do add /api/ and all OK, but ws-requests still sending on root
![_077](https://user-images.githubusercontent.com/2550668/38343078-918f7ee0-388a-11e8-906d-8bbf63a97688.jpg)
I think it's issue for playground

**Comment by marktani** [comment]
Yes, that's looks like an issue in the Playground, please post it here: https://github.com/graphcool/graphql-playground 🙂

**Comment by Fi1osof** [comment]
@marktani , done.
Excuse for troubling
