### ISSUE TITLE
Update versions for self-hosting docs

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1990]
Example: 

The tutorial here https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu uses the image `1.0`, but should use `1.2`:

>     image: prismagraphql/prisma:1.0

This needs to be applied to all versions and all hosting tutorials.

**Comment by ForsakenHarmony** [comment]
shouln't it be 1.3?

https://hub.docker.com/r/prismagraphql/prisma/tags/

**Comment by marktani** [comment]
Sorry, I meant to share the version specific link https://www.prismagraphql.com/docs/1.2/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu instead (just updated the original post).

Yup, `1.3` is the latest stable version, thanks!
