### ISSUE TITLE
Updating existing relations can lead to an error

### ISSUE THREAD

**Issue by ForsakenHarmony** [graphcool/prisma#1991]
# Bug Report

**Current behavior**

```
prisma-database_1  | java.lang.IllegalArgumentException: requirement failed: This method must only be called for unambiguous relations!
prisma-database_1  |    at scala.Predef$.require(Predef.scala:277)
prisma-database_1  |    at com.prisma.shared.models.Schema.getUnambiguousRelationThatConnectsModels_$bang(Models.scala:114)
prisma-database_1  |    at com.prisma.deploy.migration.inference.MigrationStepsInferrerImpl.$anonfun$relationsToUpdate$3(MigrationStepsInferrer.scala:178)
prisma-database_1  |    at scala.Option.orElse(Option.scala:289)
prisma-database_1  |    at com.prisma.deploy.migration.inference.MigrationStepsInferrerImpl.$anonfun$relationsToUpdate$2(MigrationStepsInferrer.scala:178)
prisma-database_1  |    at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
prisma-database_1  |    at scala.collection.Iterator.foreach(Iterator.scala:929)
prisma-database_1  |    at scala.collection.Iterator.foreach$(Iterator.scala:929)
prisma-database_1  |    at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
```

**Reproduction**

add 2 relations between 2 types which were not there before

i.e.

```
type Mote {
 # creator: User!
 members: [User!]!
}

type User {
}
```
to
```
type Mote {
 creator: User! @relation(name: "Creator")
 members: [User!]! @relation(name: "MemberOf")
}

type User {
 motes: [Mote!]! @relation(name: "Creator")
 memberOf: [Mote!]! @relation(name: "MemberOf")
}
```

it works if you have it in the initial deploy

**Comment by do4gr** [comment]
Hey @ForsakenHarmony, thanks for reporting this. The error occurs because we cannot infer with complete certainty which of the two named relations in the second schema is an update of the relation in the first one. We could try to infer it from the fieldName, but that might have changed as well.

I will implement a proper error for this case. The solution for you, that I'll probably also provide in the error message for this case, is to use a relation directive on the first schema and name the relation. Than we are sure that you want us to update that relation and not delete and recreate a new one. 

So in your case this should work: 

```graphql
type Mote {
 # creator: User!
 members: [User!]! @relation(name: "MemberOf")
}

type User {
}
```

to

```graphql
type Mote {
 creator: User! @relation(name: "Creator")
 members: [User!]! @relation(name: "MemberOf")
}

type User {
 motes: [Mote!]! @relation(name: "Creator")
 memberOf: [Mote!]! @relation(name: "MemberOf")
}

**Comment by ForsakenHarmony** [comment]
oh ok, I'll try that, thanks

**Comment by ForsakenHarmony** [comment]
Well now it didn't create the corresponding table

`Caused by: java.sql.SQLException: Table 'productive@dev._MoteCreator' doesn't exist`

**Comment by ForsakenHarmony** [comment]
now I can't even undo it

**Comment by ForsakenHarmony** [comment]
managed to undo it by manually editing the database

**Comment by ForsakenHarmony** [comment]
but prisma import required me to set a lot of stuff as optional to work, it doesn't like relations

**Comment by sorenbs** [comment]
That sounds like a bug :-)

Would be super helpful if you can provide a minimal example with required relations that break export/import and open a new issue.

**Comment by marktani** [comment]
Hey @ForsakenHarmony, is this what you're encountering: https://github.com/graphcool/prisma/issues/1767?

**Comment by ForsakenHarmony** [comment]
yes

**Comment by marktani** [comment]
Thanks, we'll look into a fix soon. Let's continue our discussion there 🙂
