### ISSUE TITLE
Generated prisma.ts incorrectly escaping comments

### ISSUE THREAD

**Issue by delta98** [graphcool/prisma#1992]
Version: `prisma/1.3.1 (darwin-x64) node-v8.6.0`

`GraphQLError: Syntax Error: Unterminated string`

Steps to replicate:

Deploy to Prisma cloud: `prisma deploy`

Observe `prisma.ts` being generated with a string literal incorrectly escaped around "Long"

```
"""
The `Long` scalar type represents non-fractional signed whole numeric values.
Long can represent values between -(2^63) and 2^63 - 1.
"""
```

Schema

```
type Source @model {
    id: ID! @unique
    name: String!
    slug: String! @unique
    url: String!
    category: Category!
    country: Country!
    active: Boolean! @default(value: true)
    snippets: [Snippet!]! @relation(name: "SourceOnSnippets")
}

type Stats @model {
    id: ID! @unique
    words: Int! @default(value: 0)
    minutes: Int! @default(value: 0)
    difficulty: Float! @default(value: 0)
    sentiment: Float! @default(value: 0)
    snippet: Snippet! @relation(name: "SnippetOnStats")
    shares: Int! @default(value: 0)
}

type Lexicons @model {
    id: ID! @unique
    keywords: [String!]
    snippet: Snippet! @relation(name: "SnippetOnLexicons")
}

type Snippet @model {
    id: ID! @unique
    title: String!
    featuredImage: String
    summary: String
    publishedAt: DateTime
    url: String! @unique
    skip: Boolean @default(value: true)
    source: Source @relation(name: "SourceOnSnippets")
    stats: Stats @relation(name: "SnippetOnStats")
    lexicons: Lexicons @relation(name: "SnippetOnLexicons")
    updatedAt: DateTime!
    createdAt: DateTime!
}

```

**Comment by marktani** [comment]
Looks like that was fixed here: https://github.com/graphql-binding/graphql-static-binding/releases/tag/v0.8.1

So the question is why that is not part of the latest `prisma-binding` 🤔

**Comment by schickling** [comment]
@marktani the dependency tree is a bit unintuitive right now and needs to be cleaned up. To get the latest version of the `graphql-static-binding` you have to make sure you're using the latest version of the `graphql-cli`. Can you confirm @delta98?

**Comment by delta98** [comment]
@schickling I'm running latest version of `graphql-cli` `2.15.8` and still observing the issue with the backticks

**Comment by timsuchanek** [comment]
Thanks for reporting! Can you try the latest prisma beta `1.4.0-beta.2`?
I just tried it and the multiline comments are correctly generated in the prisma.ts

**Comment by johhansantana** [comment]
I was having this issue. To fix it in my project I just updated the following libraries:

```
-    "prisma-binding": "1.4.0",
+    "prisma-binding": "^1.5.15",
```

```
-    "graphql-cli": "2.12.4",
+    "graphql-cli": "^2.15.8",
```

```
-    "prisma": "1.0.4",
+    "prisma": "^1.3.2",
```

After trying to `prisma deploy` locally and when deploying to `now` everything works.

**Comment by donedgardo** [comment]
@timsuchanek 1.4.0-beta.2 generated correctly the `src/generated` files.

**Comment by timsuchanek** [comment]
Thanks everyone for reporting! This seems to be fixed now
