### ISSUE TITLE
Not about to get response from API

### ISSUE THREAD

**Issue by inxeptionjake** [graphcool/prisma#1993]
# Bug Report

**Current behavior**
Query responses are either very slow or they don't return.

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
Query should return response quickly.

**Comment by sorenbs** [comment]
Thank you for reporting. We experienced reduced performance in Graphcool Framework for less than ten minutes in that timeframe. The issue has been resolved.
