### ISSUE TITLE
Scalar type supported in Graphql is not supporting in Prisma

### ISSUE THREAD

**Issue by davisjohndavis3** [graphcool/prisma#1994]
I am new to Prisma. We are planning to migrate our existing Graphql DB to Prisma for a trial run. But when I use scalar for holding URL values it makes an error and relation problems.

    # Custom scalar type to holds URL values
    scalar URL

    # Custom scalar type to holds timestamp values
    scalar Timestamp

    # Enum holds the supported provenance types
     enum ProvenanceType {
      MANUAL
      IMPORTED
    }

    # This type holds the user details.
    type User {
      userName: String
    }

    # This type holds the provenance details.
    type Provenance {
      provenanceType: ProvenanceType!
      source: String
      sourceUrl: URL
      sourceImage: URL
      sourcePath: URL
      createdBy: User
      createdOn: Timestamp
    }
 
    Errors:

    Provenance
      ✖ The field `sourceUrl` has the type `URL` but there's no type or enum declaration with that name.
      ✖ The field `sourceImage` has the type `URL` but there's no type or enum declaration with that     name.
     ✖ The field `sourcePath` has the type `URL` but there's no type or enum declaration with that name.
      ✖ The field `createdOn` has the type `Timestamp` but there's no type or enum declaration with that         name.
      ✖ The relation field `sourceUrl` must specify a `@relation` directive: `@relation(name: "MyRelation")`
      ✖ The relation field `sourceImage` must specify a `@relation` directive: `@relation(name:                 "MyRelation")`
      ✖ The relation field `sourcePath` must specify a `@relation` directive: `@relation(name: "MyRelation")`

   When I correct it,  its shows error below

    type Provenance {
      provenanceType: ProvenanceType!
      source: String
      sourceUrl: URL @relation(name: "Url")
      sourceImage: URL @relation(name: "Url")
      sourcePath: URL @relation(name: "Url")
      createdBy: User @relation(name: "User")
      createdOn: Timestamp
    }

    ERROR: Whoops. Looks like an internal server error. Search your cluster logs for request ID: 
    cluster:cluster:cje8gzt7r006t0177e8meevwm

    {
      "data": {
      "deploy": null
      },
     "errors": [
      {
       "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID:         
       cluster:cluster:cje8gzt7r006t0177e8meevwm",
            "path": [
            "deploy"
          ],
          "locations": [
            {
              "line": 2,
              "column": 9
            }
          ],
          "requestId": "cluster:cluster:cje8gzt7r006t0177e8meevwm"
        }
      ],
      "status": 200
    }

**Comment by marktani** [comment]
Hey @davisjohndavis3, it's right that you can't add new scalar types to _the datamodel_ of Prisma.

However, you can add custom scalars to your _application schema_ in the GraphQL server.
In that case, I suggest the following _data model_:

```graphql
# src/database/datamodel.graphql

# Enum holds the supported provenance types
 enum ProvenanceType {
  MANUAL
  IMPORTED
}

# This type holds the user details.
type User {
  userName: String
}

# This type holds the provenance details.
type Provenance {
  id: ID! @unique
  provenanceType: ProvenanceType!
  source: String
  sourceUrl: String
  sourceImage: String
  sourcePath: String
  createdBy: User
  createdOn: DateTime
}
```

Here is how you can add a custom scalar and overwrite your `Provenance` type that is exposed in your _application schema_:

```graphql
# src/schema.graphql

# import Provenance, ProvenanceType from "./generated/prisma.graphql"

type Query {
  myQuery: Provenance
}

scalar Timestamp
scalar URL

type Provenance {
  provenanceType: ProvenanceType!
  source: String
  sourceUrl: URL
  sourceImage: URL
  sourcePath: URL
  createdBy: User
  createdOn: Timestamp
}
```

Now you can add resolvers for your custom scalars and `Provenance` type.

**Comment by davisjohndavis3** [comment]
Thanks for your fast response @marktani ... Now I am facing a relationship issue

 # This type holds the location Latitude
    type Latitude {
      provenance: Provenance
      value: Float
      visibilityStatus: Boolean
      dataQuality: DataQuality
    }

    # This type holds the location Longitude
    type Longitude {
      provenance: Provenance
      value: Float
      visibilityStatus: Boolean
      dataQuality: DataQuality
    }

    # This type holds the address line of person PhysicalAddress.
    type AddressLine {
      value: String
      dataQuality: DataQuality
    }

    # This type holds the city of person PhysicalAddress.
    type AddressCity {
      value: String
      dataQuality: DataQuality
    }    

    # This type holds the state  of person PhysicalAddress.
    type AddressState {
      value: State
      dataQuality: DataQuality
    }

    # This type holds the ZipCode  of person PhysicalAddress.
    type AddressZipCode {
      value: Int
      dataQuality: DataQuality
    }

    # This type holds the CountryCode  of person PhysicalAddress.
    type AddressCountryCode {
      value: CountryCode
      dataQuality: DataQuality
  
    }

    # This type holds the Available Times At Location of a Person and its provenance details.
    type AvailableTimesAtLocation {
      provenance: Provenance
      values: [AvailabilityAtLocation!]!
      visibilityStatus: Boolean
    }

    # This type holds the AddressType of person PhysicalAddress.
    type AddressType {
      value: String
      dataQuality: DataQuality
    }

    # This type holds the quality details
    type DataQuality {
      dataQualityStatus: DataQualityStatus
      comment: String
      updatedOn: DateTime
      updatedBy: User
    }

    # This type holds the address of person.
    type PhysicalAddress {
      addressLine: AddressLine
      city: AddressCity
      state: AddressState
      zipCode: AddressZipCode
      countryCode: AddressCountryCode @relation(name: "AdddressCountryCodeOnPhysicalAddress")
      mailingCountry: AddressCountryCode @relation(name: "AdddressCountryCodeOnPhysicalAddress")
      latitude: Latitude
      longitude: Longitude
      addressType: AddressType
      avaliablity: AvailableTimesAtLocation
      dataQuality: DataQuality
    }


When I execute command **sudo prisma deploy**. it shows error

**Errors:**

  PhysicalAddress
    ✖ The relation field `countryCode` must specify a `@relation` directive: `@relation(name: "MyRelation")`
    ✖ The relation field `mailingCountry` must specify a `@relation` directive: `@relation(name: "MyRelation")`


So I make relation like below

    # This type holds the address of person.
    type PhysicalAddress {
      addressLine: AddressLine
      city: AddressCity
      state: AddressState
      zipCode: AddressZipCode
      countryCode: AddressCountryCode @relation(name: "AdddressCountryCodeOnPhysicalAddress")
      mailingCountry: AddressCountryCode @relation(name: "AdddressCountryCodeOnPhysicalAddress")
      latitude: Latitude
      longitude: Longitude
      addressType: AddressType
      avaliablity: AvailableTimesAtLocation
      dataQuality: DataQuality
    }


after excecuting this .error changed to 


**Errors:**

  PhysicalAddress
    ✖ The relation field `countryCode` has the type `AddressCountryCode`. But the other directive for this relation appeared on the type `PhysicalAddress`
    ✖ The relation field `mailingCountry` has the type `AddressCountryCode`. But the other directive for this relation appeared on the type `PhysicalAddress`

**Comment by marktani** [comment]
I'm closing this for now, as your initial question seems answered.
Feel free to open another issue or a discussion in [the Forum](https://www.graph.cool/forum/c/questions) if you have further questions 🙂

**Comment by davisjohndavis3** [comment]
ok  @marktani ... Thanks for your fast response
