### ISSUE TITLE
Not about to get response from API

### ISSUE THREAD

**Issue by inxeptionjake** [graphcool/prisma#1998]
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

Same issue as yesterday.  Getting very slow responses or no response at all.

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

**Comment by marktani** [comment]
Thanks for bringing this up @inxeptionjake! 🙂
We resolved the issue. You can also refer to https://status.graph.cool.

Please report further problems or questions in the https://github.com/graphcool/graphcool-framework/ repository.

Thanks! 🙌
