### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by johhansantana** [graphcool/prisma#1999]
# Bug Report

**Current behavior**
After running `prisma deploy` it will give an error of:
```
TSError: ⨯ Unable to compile TypeScript
src/generated/prisma.ts (2435,6): ',' expected. (1005)
src/generated/prisma.ts (2435,10): '=' expected. (1005)
```

**Reproduction**
Not sure if this happens with every project but in to reproduce in our case is doing:
> prisma deploy

After files are generated we get the error

**Expected behavior?**
It should not error out.

**Temporary solution**
edit `src/generated/prisma.ts` where the error starts:
<img width="647" alt="screen shot 2018-03-01 at 1 15 55 pm" src="https://user-images.githubusercontent.com/9933887/36859347-6de58580-1d54-11e8-96ae-9eb10c776287.png">

Change the quotes around `Long` to use `'` instead of `

```
$ prisma -v
prisma/1.3.2 (darwin-x64) node-v8.9.3
```

**Comment by marktani** [comment]
This looks very similar to https://github.com/graphcool/prisma/issues/1992.

**Comment by johhansantana** [comment]
Oh yes, it is the same thing.
