### ISSUE TITLE
Class 'Prisma' incorrectly extends base class 'Prisma'.

### ISSUE THREAD

**Issue by iamclaytonray** [graphcool/prisma#2002]
# Bug Report

**Current behavior**
After trying to compile typescript, I get the following error:

```
src/generated/prisma.ts(6790,14): error TS2415: Class 'Prisma' incorrectly extends base class 'Prisma'.
  Types of property 'query' are incompatible.
    Type 'Query' is not assignable to type 'QueryMap'.
      Index signature is missing in type 'Query'.
```

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

You can reproduce this issue by deploying a Prisma API and visiting `generated/prisma.ts`. The issue is found near the bottom. IE:

```ts
// Error here
public query: Query = {
  // etc, not relevant
}
```
When hovering over `query`, due to red underline, this is the error notice:

```
Property 'query' in type 'Prisma' is not assignable to the same property in base type 'Prisma'.
  Type 'Query' is not assignable to type 'QueryMap'.
    Index signature is missing in type 'Query'.
```

More on repro later

**Expected behavior?**
Types should play nicely again. We're all friends. Let's all just be friendly.

**Comment by marktani** [comment]
How can I reproduce this?

**Comment by iamclaytonray** [comment]
Sorry man. I'll try to have an isolated repro today

**Comment by marktani** [comment]
Thanks! 😄

**Comment by SpaceK33z** [comment]
I got the same error and made an example repository: [SpaceK33z/prisma-typescript-error](https://github.com/SpaceK33z/prisma-typescript-error).

A workaround for now is to disable `strictFunctionTypes` in your `tsconfig.json`.

**Comment by kbrandwijk** [comment]
This seems to have something to do with a change in `prisma-binding` or `graphql-binding` not properly propagated into the static binding generators. This should be moved to https://github.com/graphql-binding/graphql-static-binding

**Comment by marktani** [comment]
Thank you all, I reported the issue here: https://github.com/graphql-binding/graphql-static-binding/issues/69.
