### ISSUE TITLE
throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))

### ISSUE THREAD

**Issue by vistriter** [graphcool/prisma#2025]
After I update Prisma to 1.3.3. I have a problem like this.

crash when yarn start

<img width="1035" alt="screen shot 2561-03-06 at 13 16 09" src="https://i.imgur.com/qgKoISK.png">

**Comment by cameronk** [comment]
Same issue as #1973.

This has not been fixed as of prisma@1.3.5. 

@vistriter You'll need to manually edit the prisma.ts file in the meantime.

**Comment by marktani** [comment]
Thanks for chiming in @cameronk!
I'm closing this as a duplicate. @vistriter please let us know in #1973 if that helps 🙂
