### ISSUE TITLE
prisma deploy token 'ERROR: Authentication token is invalid

### ISSUE THREAD

**Issue by miuan** [graphcool/prisma#2030]
# prisma deploy token 'ERROR: Authentication token is invalid

**Current behavior**
`prisma deploy`

ends with

```
yarn run v1.3.2
warning package.json: No license field
$ /Users/mmedlik001/Documents/triphub/server/node_modules/.bin/prisma deploy
Deploying service `prisma-enhaced` to stage `dev` on cluster `public-stickyfoe-312/prisma-eu1` 280ms

Changes:

  Place (Type)
  - Deleted field `trip_start_here`

  Trip (Type)
  - Deleted field `type`
  - Deleted field `startHere`
  + Created field `transportType` of type `Int`
  + Created field `startCountry` of type `String`
  + Created field `startRegion` of type `String`

Applying changes !

ERROR: Authentication token is invalid: Token can't be decoded: The token is expired since 2018-03-06T19:16:05Z

{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 11
        }
      ],
      "path": [
        "migrationStatus"
      ],
      "code": 3015,
      "message": "Authentication token is invalid: Token can't be decoded: The token is expired since 2018-03-06T19:16:05Z",
      "requestId": "cluster:cluster:cjeg1bxrk4mlm0104sjj7lto8"
    }
  ],
  "status": 200
}

```

**Reproduction**
I was setup the project roughly two months ago with `prisma init` without promting any account

till today everithing works fine, but novadays the `prisma deploy` return the issue with wrong token

After repeating this problem I did try `prisma account` where I was asking to login, but the forgoten-password doesn't work correctly I decided create new account and `granted cli`, so now my `prisma account` return

```
yarn prisma account
yarn run v1.3.2
warning package.json: No license field
$ /Users/mmedlik001/Documents/triphub/server/node_modules/.bin/prisma account
Opening https://app.prismagraphql.com/cli-auth?secret=$2a$08$da/p3LDnej5GcIb54R408e in the browser

Authenticating ✔
Email: m************@gmail.com
Name:  M************
✨  Done in 72.76s.

```
but the `prisma deploy` response the same error token

> Maybe could be also the problem with the project configuration what is connect to service with name `public-stickyfoe-312/prisma-eu1` but from `prisma account` my account is not stickyfoe... anymore :-) should I somehow reconfigure my project to connect to right account?

**Comment by timsuchanek** [comment]
Thanks for reporting @miuan! We just pushed a fix which will be available in `npm install -g prisma@beta` in about 10 min.
