### ISSUE TITLE
local upgrade

### ISSUE THREAD

**Issue by steida** [graphcool/prisma#2031]
When should it be run? Thank you.

**Comment by marktani** [comment]
`local upgrade` pulls the docker image associated with your current `prisma` version. So, a typical workflow for using this command is the following:

```
npm install -g prisma
prisma local upgrade
```

I hope this helps! Keep in mind that usage questions like yours are better posted [in the Forum](https://www.graph.cool/forum/c/questions). Thanks 🙌
