### ISSUE TITLE
Mutation returning error message "ctx.db.mutation.createUser"  is not a function

### ISSUE THREAD

**Issue by dhiraj-belkhode** [graphcool/prisma#2041]
Created createUser Mutation after calling it from playground it returning an error.

mutation{
  createUser(firstName:"abc", lastName:"xyz", 
  mobile:3453343443){
    id
  }
}

error:-
ctx.db.mutation.createVisitor is not a function"

**Comment by marktani** [comment]
Looks like an error in your resolver code. You are calling createVisitor, but it doesn't exist.

Is there a Visitor type in your data model?

**Comment by marktani** [comment]
I'm closing this, as it seems to be a problem with an outdated schema file. Regenerating it should resolve this issue.

Please let me know if you have any questions :slightly_smiling_face:
