### ISSUE TITLE
Documentation > YAML Structure > Schema property can be overrided

### ISSUE THREAD

**Issue by johannpinson** [graphcool/prisma#2044]
https://github.com/graphcool/prisma/blob/0acef3365f2245da0ee371be1c4768d26d83de70/docs/1.3/04-Reference/02-Service-Configuration/02-prisma.yml/02-YAML-Structure.md#L178-L184

It will be a good point to add a little "warning/info" block for this property to indicate that it can be overrided by the `graphqlconfig.yml` used during the command `graphql prepare`

Related to https://github.com/graphcool/prisma/issues/1824 and https://github.com/graphcool/prisma/issues/1927

**Comment by nikolasburk** [comment]
Great point! I would like to clarify upfront though whether this is intended behaviour or if it's a bug. Or rather: What should take precedence in `schema` in `prisma.yml` is set and `schemaPath` in `graphqlconfig.yml` is set. 

A reasonable rule could be that when using the Prisma CLI, `prisma.yml` should take precedence. When using the GraphQL CLI, `graphqlconfig.yml` (not sure if this should even consider `prisma.yml` at all).

**Comment by johannpinson** [comment]
In fact, the Prisma CLI use itselft `graphql-cli` so I'm not sure the good rule it to decide which file to use depending of the cli used.

For me, the actual solution to use `graphqlconfig.yml` instead of the `schema` property **is a good thing because we can add more configuration!**
And an extension (aka plugin) already exists for the `graphqlconfig.yml` works with the `prisma.yml`

First, we can evolve the documentation to indicate the actual behavior (and explain the role of the graphql-cli during a deploy)
Second, the best will be to add a console output here:
https://github.com/graphcool/prisma/blob/0acef3365f2245da0ee371be1c4768d26d83de70/cli/packages/prisma-cli-core/src/commands/deploy/index.ts#L484

Depending of the config selected by the cli, it will indicate to the user the configuration file followed.

**Comment by nikolasburk** [comment]
Thanks so much for the input @johannpinson, I updated the docs and added an info box to explain the behaviour when using `graphql-config`.

I also really like the idea of the CLI prompting which of the options should be used. I created an issue for that [here](https://github.com/graphcool/prisma/issues/2056).
