### ISSUE TITLE
Show title of related node

### ISSUE THREAD

**Issue by wvteijlingen** [graphcool/prisma#205]
This is just small fun feature that could be useful. Instead of showing the id of related nodes, it would be great if Graphcool could infer the title of that node and display that in the data table. Perhaps it could check whether a node contains fields named "title", "name", etc.

Nothing ground breaking, just a small feature that would make Graphcool even more of a pleasure to work with :).

**Comment by sedubois** [comment]
It would also be quite helpful to show a preview of the related node on mouse hover.

**Comment by marktani** [comment]
That's great feedback, thanks!

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
