### ISSUE TITLE
Graphcool implicit 'to-many' relations

### ISSUE THREAD

**Issue by joshhopkins** [graphcool/prisma#2061]
Graphcool and Prisma handle relations differently for the same SDL. For example if I have the following schema:

```
type User @model {
  id: ID! @unique
  firstName: String
  lastName: String
  managing: [User!]! @relation(name: "ManagerOnUser)
  managers: [User!]! @relation(name: "ManagerOnUser")
}
```

I can run this is graphcool playground:

```
mutation {
  createUser(
    firstName: "Tim"
    lastName: "Jones"
    managersIds: ["cj9zhzbd47iou0159n2xnulvy"]
  ) {
    id
    createdAt
    updatedAt
  }
}
```

And both the `managers` and `managedBy` properties will be updated, on connected nodes.

While running this against Prisma:

```
mutation {
  createUser(data: {
    firstName: "Tim"
    lastName: "Jones"
    email: ""
    managedBy: {
      connect: [{
          id: "cj9zhzbd47iou0159n2xnulvy"
        }]
    }
  }) {
    id
    createdAt
    updatedAt
  }
}
```

Only the`managedBy` property is updated for the connected nodes. Any tips on implementing similar Graphcool-like behaviour in Prisma?

**Comment by do4gr** [comment]
Hey,
 I think you are experiencing the bug addressed by this PR. https://github.com/graphcool/prisma/pull/2042
We will merge this shortly and the next release should fix this.

**Comment by joshhopkins** [comment]
Right! Thought it was a bit odd. Thanks for the clarification.

**Comment by joshhopkins** [comment]
#2042 has fix it. Thanks @do4gr 👍
