### ISSUE TITLE
Connect in nested update mutation not working

### ISSUE THREAD

**Issue by souleman13** [graphcool/prisma#2074]
Hello, I am trying to run the following mutation in my playground

`mutation{
  addProductToCart(
    user_id:"cjenmlpp3cwbf0197j5rtho8c"
    product_id:"cjeof1ohssntl0197gc7uvw12"
  ){
    cart{
      id
      products{
        id
        name
      }}}}`
This runs the upsert and provides me with cart id cjenon9fvf1bx0197erew9pw6 but does not seem to connect the product to the products array which returns [].
Here is the mutation on the server:
`updateUser(
        {
          data: {
            cart: {
              upsert:{
                update: {
                  products: { connect: [{ id: product_id }] }
                },
                create: {
                  products: { connect: [{ id: product_id }] }
                }
              }
            }
          },
          where: { id: user_id },
        }, info, )`
DATA MODEL: 
`type User {
  id: ID! @unique
  name: String!
  email: String! @unique
  pw: String!
  cart: Cart
}

type Cart {
  id: ID! @unique
  user: User!
  products: [Product!]!
}

type Product {
  id: ID! @unique
  name: String!
  imgURL: String
  desc: String!
  price: Float!
}`

**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

**Comment by do4gr** [comment]
Hey @souleman13 thanks for reporting this. 
The problem in this case is that the connect is nested within an Upsert. Upsert at the moment does not execute nested mutations. So you can change/create scalar values in the update and create branches of an Upsert, but not relations. I'll update the docs to reflect this since you are not the first one to run into this.

**Comment by souleman13** [comment]
Thanks for your timely  response! I will update my code to account for this! @do4gr

**Comment by marktani** [comment]
Thanks for bringing this up @souleman13, great that you found a workaround :slightly_smiling_face: 

The general issue is being tracked here: https://github.com/graphcool/prisma/issues/1579.
