### ISSUE TITLE
`prisma delete` on non-existing service throws wrong exception

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma#2076]
# Bug Report

**Current behavior**

When performing a `prisma delete -f` while you haven't deployed before, the Prisma server responds with the wrong exception:

```
Deleting service myservice@local... !

ERROR: myservice is not a valid name for a service name. It must start with a letter and may contain up to 30 letters, numbers, underscores and hyphens.
```

**Reproduction**

Try to perform a `prisma delete -f` on a non-existing service.

**Expected behavior?**

The server should respond with: `Can't delete a non-existing service` or shouldn't throw an exception at all. I'm in favor of not throwing anything 😄

**Comment by johannpinson** [comment]
Hey @akoenig 

I'm sure that doesn't show an message is the better solution because trying to delete an service which isn't found is an "error" from the user.

I think it can use the `InvalidProjectId` error model.
I will make a pull request quickly to update it 🙂

**Comment by marktani** [comment]
Thanks to @johannpinson for fixing this in #2078. :raised_hands:
