### ISSUE TITLE
New targeted permissions on lists/single-nodes data access

### ISSUE THREAD

**Issue by wallslide** [graphcool/prisma#208]
### Problem
It's really easy for people to scrape the data of my users.

### Background

I am creating an website where some managers create an Event, and other users participate in those events. When users are browsing events to sign up for, they need to be able to see the full name of the event organizers. With the current permission system, I don't have my options to lock down the name-data of my users. The best I can do is restrict `firstName` and `lastName` of the `User` model to be restricted to authenticated users, and to restrict accessible names to those of users that are managing an event. 

In other words, any authenticated user could run a a query like this:
```
query {
  allUsers {
    firstName,
    lastName
  }
}
```
and get the first/last names of all of my event managers. Even if it's not a large security threat, having a list like that leaked wouldn't inspire a lot of confidence in my user-base.

### Proposal
I propose that permissions be extended to allow us to choose to apply them to only single-node accesses, or both single-node accesses and list functions. By list functions, I mean the `all*` functions such as `allUsers` or `allEvents` that are automatically available to use for each model that we create. If list functions were disallowed in a permission, then any calls to `all*` functions, or any `to-many` relation call would cause an `insufficient permissions` error to be thrown.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
