### ISSUE TITLE
`deleteMany` where: <relation> = null results in deletion of all the nodes

### ISSUE THREAD

**Issue by johhansantana** [graphcool/prisma#2085]
# Bug Report

**Current behavior**
When running this code
```
mutation {
  deleteManyTrips(
    where: {
      ticket: null
    }
  ) {
    count
  }
}
```
It will delete every node, in this case, `trips`.

While using the same query like this:
```
{
  trips(
    where: {
      ticket:null
    }
  ) {
    ticket {
      id
    }
  }
}
```
Will return the `trips` that have `ticket` as `null`

**Reproduction**

> Run a `deleteMany` mutation where a relation = null. It will delete every node.

**Expected behavior?**
It should only delete the nodes where `ticket` = `null`

**Comment by sorenbs** [comment]
This fix is available on the unstable channel and will be released Tuesday next week
