### ISSUE TITLE
Looks Like an Internal Server Error on prisma deploy

### ISSUE THREAD

**Issue by souleman13** [graphcool/prisma#2090]
`$ prisma deploy
Creating stage dev for service lego-store-prisma !

ERROR: Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cjer9o051akx20905960z6yok

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cjer9o051akx20905960z6yok",
      "path": [
        "addProject"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "cluster:cluster:cjer9o051akx20905960z6yok"
    }
  ],
  "status": 200
}`
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

**Comment by marktani** [comment]
Hey @souleman13, what cluster are you deploying to?

**Comment by souleman13** [comment]
https://us1.prisma.sh/public-quillscorpion-38/lego-store-prisma/dev

**Comment by marktani** [comment]
Ok, the US development cluster is currently under maintenance. Please track the progress here: https://status.prismagraphql.com/

You can reach out to support@graph.cool if you have any further questions 🙂
Thanks 🙌

**Comment by souleman13** [comment]
Oh okay Thanks!

**Comment by kruyvanna** [comment]
it happens again

**Comment by marktani** [comment]
Please reach out to support@prisma.io, @kruyvanna :)

**Comment by kruyvanna** [comment]
@marktani  thanks. it's solved now. it's because of invalid schema
