### ISSUE TITLE
Deleting Relations

### ISSUE THREAD

**Issue by danielswallace** [graphcool/prisma#2091]
# Bug Report

**Current behavior**
After updating to v1.4 delete mutations on related fields no long works. Before you would supply a where clause. 

{ file: { id: "id" } }

Now according to the generated schema you should: 

{ file: { delete: true }

`input FileUpdateOneWithoutBrandInput {
  create: FileCreateWithoutBrandInput
  connect: FileWhereUniqueInput
  disconnect: Boolean
  delete: Boolean
  update: FileUpdateWithoutBrandDataInput
  upsert: FileUpsertWithoutBrandInput
}`

**Reproduction**

`type Brand {
  id: ID! @unique
  name: String! @unique
  file: File
}`

`type File {
  id: ID! @unique
  name: String!
  ext: String!
  mimeType: String!
  brand: Brand
}`

**Expected behavior?**

Before the file was deleted... Now despite supplying a boolean or a where clause I get an error stating the other. Wondering what behavior should be expected. The schema doesn't work. 

**Responses**

`{
  "errors": [
    {
      "message": "Field \"id\" is not defined by type FileUpdateOneWithoutBrandInput.",
      "locations": [
        {
          "line": 2,
          "column": 63
        }
      ]
    }
  ]
}`

`{
  "errors": [
    {
      "message": "Expected type FileUpdateOneWithoutBrandInput, found true.",
      "locations": [
        {
          "line": 2,
          "column": 62
        }
      ]
    }
  ]
}`

**Comment by do4gr** [comment]
Hey @danielswallace thanks for reporting this.
I tried reproducing the issue but could not do so. Could you try with a freshly set up project? And Which version did you update from?

This is me trying out your schema and delete works as expected.
<img width="1082" alt="bildschirmfoto 2018-03-15 um 11 14 56" src="https://user-images.githubusercontent.com/16278407/37457477-68e8788c-2842-11e8-93cd-e130eab09d80.png">

**Comment by marktani** [comment]
This feels like your local version of the generated schema has not been updated, @danielswallace.

Can you reproduce this when using the Playground directly, or only when using `prisma-binding`?

**Comment by danielswallace** [comment]
Mismatched cluster versions.. (Facepalm)
