### ISSUE TITLE
Delete cascade on deleteMany not supposed to work?

### ISSUE THREAD

**Issue by nickluger** [graphcool/prisma#2103]
https://github.com/graphcool/prisma/pull/2028 introduced relation checks. It seems it always gives us:

```
Error: The change you are trying to make would violate the required relation
```

even if 

```graphql
 @relation(name: "PostOfUser", onDelete: CASCADE)
```

Shouldn't it delete casace even on `deleteMany`?

**Comment by marktani** [comment]
That's a known limitation, which is documented here: #1936. Therefore im closing this issue.

Please leave an upvote and subscribe for the mentioned feature request :raised_hands:
