### ISSUE TITLE
Server Side Subscription Not Working

### ISSUE THREAD

**Issue by artemzakharov** [graphcool/prisma#2109]
# Bug Report

**Current behavior**
A server side subscription never hits my webhook. I don't know if the subscription isn't working or if it doesn't like something about the URL, but I can tell it doesn't call the endpoint by the cloud function logs.

**Reproduction**
1. Create a project using the 'node-advanced' template
2. Add the subscription example given in the docs to `prisma.yml`, with your own webhook to monitor:

```
subscriptions:
  userChangedEmail:
    webhook:
      url: __WEBHOOK__
      headers:
        Content-Type: application/json
    query: |
      subscription {
        user(where: {
          mutation_in: [UPDATED],
          updatedFields_contains: "email"
        }) {
          node {
            name
            email
          }
        }
      }
```
3. Run this mutation on the database when the project is launched:
```
mutation {
  updateUser(
    data: { email: "new@email.com" },
    where: { id: "cjexpad3m000c0796eg6m0mx6" }
  ) {
    id
  }
}
```
4. Note that webhook is never called.

Here's a reproduction, basically just the steps above
https://github.com/artemzakharov/server-side-subscriptions-bugged

**Expected behavior?**
I would expect the subscription to hit the webhook, or at least log something somewhere to tell me about a problem.

**Comment by marktani** [comment]
Hey @artemzakharov, thanks a lot for this detailed bug report. I suspect the behaviour you're observing is related to #1734, can you try if this subscription query works as expected:

```
      subscription {
        user {
          mutation
          node {
            name
            email
          }
        }
      }
```

You can then filter the subscription logic based on the information in `mutation`.

**Comment by artemzakharov** [comment]
@marktani It works! I was actually aware of that issue beforehand, and under the impression that I had already attempted that solution, but I guess something was off in my attempt - it works now. Thank you!

**Comment by marktani** [comment]
Thanks a lot for confirming! I added a note to #1734 that also server-side subscriptions are affected by this current limitation.

**Comment by EslamIsmail93** [comment]
its working for at local but not working with live not working
