### ISSUE TITLE
Prisma Console shows an error notification

### ISSUE THREAD

**Issue by OniVe** [graphcool/prisma#2113]
# Bug Report

**Current behavior**

The site [prisma.sh](https://app.prisma.sh) shows the notification: `GraphQL error: __typename did not match an object type: UpdateSecrets`

**Reproduction**

- Change the value of `PRISMA_SECRET` in the file "`.env`"
- Go to `https://app.prisma.sh/<slug>/services`
- Select a service from the list in which there were changes (or go to `https://app.prisma.sh/<slug>/services/prisma-eu1/<service-name>/dev/dashboard`)

**Expected behavior?**

No error notification

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma-cloud-feedback #107](https://github.com/graphcool/prisma-cloud-feedback/issues/107) via [**ZenHub**](https://www.zenhub.com/)
