### ISSUE TITLE
Inheritance in Schema definitions 

### ISSUE THREAD

**Issue by oguzgelal** [graphcool/prisma#2114]
Hello. I was wondering if there's a way to implement inheritance with schema definitions. 

So for example:

```
type Person {
  id: ID! @unique
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Employee extends Person {
  department: String!
  role: String!
}

type Customer extends Person {
  type: String!
}
```

When I create an Employee with `createEmployee` the `id`, `name` etc. fields should be available, along with `department` and `role`. Also, for example in the following case:

```
type SomeType {
  people: [Person!]!
}
```

`people` field of SomeType should be able to connect with both `Customer` and `Employee` instances as well as of `Person`.

Is there a way to do this ? Thanks in advance for the help!

**Comment by rohitghatol** [comment]
See if this project helps you - 

https://github.com/nicolasdao/graphql-s2s

**Comment by sorenbs** [comment]
See https://github.com/graphcool/prisma/issues/83

This is something we will implement :-)

**Comment by Mr-Cool** [comment]
> See https://github.com/graphcool/prisma/issues/83
> 
> This is something we will implement :-)

Hi, I'd just like to find out if there is an updated URL for this - the one in your comment above results in a 404.

Thanks
