### ISSUE TITLE
Cannot create non-relational types anymore

### ISSUE THREAD

**Issue by lrholmes** [graphcool/prisma#2119]
Since upgrading to 1.4.1 (though I haven't tried in a few versions) I am not able to create a new type in my datamodel, and refer to it without the `@relation` directive.

```
type Event {
    id: ID! @unique
    name: String
    country: Country
    anotherCountry: Country
}

type Country {
    name: String!
    alpha2: String!
    alpha3: String!
}
```
Using `prisma deploy` outputs the following error:
```    
✖ The relation field `country` must specify a `@relation` directive: `@relation(name: "MyRelation")
```
Please let me know any way that I can help to solve this issue as it's currently blocking progress for us.

**Comment by marktani** [comment]
I was able to deploy the datamodel you shared, without any problems.
Do you have a "before" and "after" schema, where you receive this error? I deployed the schema as is, in one go.

**Comment by lrholmes** [comment]
@marktani I just updated the example by adding another reference to `Country` - after another look at my own schema I believe this to be the cause of the issue. Can you try it?

**Comment by marktani** [comment]
Hey @lrholmes, this is expected behaviour. As soon as you have least two relation fields to the same type, you need to distinguish them using a relation name, as mentioned [in the docs](https://www.prismagraphql.com/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#relations).

**Comment by lrholmes** [comment]
Ah okay, I was trying to avoid defining the other end of the relation as it's not logical for our application. Perhaps I'll use a Json type or something instead. Thanks for the information!
