### ISSUE TITLE
Prisma CLI breaks when NODE_ENV=test

### ISSUE THREAD

**Issue by steve-a-jones** [graphcool/prisma#2126]
I discovered this while running `prisma reset` inside a child process where `NODE_ENV=true`

The following code:

https://github.com/graphcool/prisma/blob/2f2a943cd2eba668af97f9472490d65f9f33ceec/cli/packages/prisma-cli-engine/src/Config.ts#L202

will result in the follow error from the child process...

```
(node:26359) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Couldn’t find `prisma.yml` file. Are you in the right directory?
```

Because it alters `cwd`.

Is this intentional? @marktani

**Comment by marktani** [comment]
Thanks for the report, @steve-a-jones. That's a known limitation for now, but we could certainly improve this behaviour!
