### ISSUE TITLE
Passing cluster address and secret by cli argument or env var

### ISSUE THREAD

**Issue by mzygmunt** [graphcool/prisma#2131]
It would be nice if we could pass cluster address and secret by the cli argument or env var. To run the "prisma deploy" command by CI/CD. Then, it would not be necessary to create the file "~/.prisma/ config.yml" in the docker's image. Or by the file "database/prisma.yml".

**Comment by marktani** [comment]
Thanks a lot for your feature request!

This could be done using this command:

```
prisma cluster add --endpoint http://example.com/ --secret mysecret --name mycluster
```

**Comment by mzygmunt** [comment]
@marktani When I try to execute this command, than I get error "Unknown flag --endpoint". Are these parameters in version 1.4.1?

**Comment by marktani** [comment]
My message was a suggestion for introducing these flags. They are not present yet.

**Comment by mzygmunt** [comment]
@marktani I added this functionality as you suggested #2149

**Comment by marktani** [comment]
Thanks for providing the PR, but I'll close this issue due to the deprecation of `prisma cluster add`:

> Thanks for the PR @mzygmunt! We're deprecating the cluster commands, as the management of clusters will change significantly in the upcoming 1.7 release.
> Stay tuned for more information on that tomorrow!
