### ISSUE TITLE
 "Not authorized. Please provide a proper 'Authorization' header", when deleting public service

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2133]
# Bug Report

**Current behavior**

Deleting a service from the development cluster is not possible:

```
Deleting service import-id-missing@dev !

ERROR: Not authorized. Please provide a proper 'Authorization' header

{
  "data": null,
  "errors": [
    {
      "message": "Not authorized. Please provide a proper 'Authorization' header",
      "locations": [
        {
          "line": 2,
          "column": 11
        }
      ],
      "path": [
        "deleteService"
      ]
    }
  ],
  "status": 200
}
```

**Reproduction**

```
npm install -g prisma@1.4.1
prisma init test # choose minimal
cd test
prisma deploy
prisma delete
``` 

**Note:** `prisma reset` works as expected.

**Expected behavior?**

The service should be deleted without a problem

**Comment by juicycleff** [comment]
Also noticed this issue today. Usually fixed this by generating a new token, but after prisma update, new token doesn't fix it

**Comment by c316** [comment]
Anyone getting here from googling the issue title might also be getting the message from using `prisma deploy`

I had to `prisma login` then it got hung up, I refreshed the browser and canceled the login from the console. Then I did the `prisma login` again and I was able to get the console to authenticate and `prisma deploy` without a problem.

**Comment by timsuchanek** [comment]
The public service deletion is fixed. @c316 can you reproduce the problem and create a separate issue for this? Thanks!
