### ISSUE TITLE
Anonymous session is timing out

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2137]
# Bug Report

**Current behavior**

It appears to be the case that "anonymous" sessions in the CLI are expiring after some while (30 days?).

This leads to the following scenario (all while not being logged in in the CLI):

* deploy a project to the development cluster
* time goes by and the session expires
* try to deploy again => you'll receive this error:

> ERROR: Authentication token is invalid: Token can't be decoded: The token is expired since 2018-03-22T07:18:34Z

**Reproduction**

See above.

**Expected behavior?**

CLI is able to refresh tokens. Or another mechanism that solves this problem.

**Comment by timsuchanek** [comment]
Closed due to inactivity / nonreproducibility.
