### ISSUE TITLE
Graphcool project is unresponsive about half of the time

### ISSUE THREAD

**Issue by inxeptionjake** [graphcool/prisma#2139]
# Bug Report
On of my Graphcool projects (cje7kwnrz1bar0136nvbt0240) is unresponsive about half of the time.    

I get the following errors from the browser when making GraphQL calls:
- Failed to load https://api.graph.cool/simple/v1/cje7kwnrz1bar0136nvbt0240: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://tubthings-crate.inxeption.io' is therefore not allowed access. The response had HTTP status code 502.
- POST https://api.graph.cool/simple/v1/cje7kwnrz1bar0136nvbt0240 502 (Bad Gateway)

**Current behavior**
When I click around my application that makes GraphQL calls for project cje7kwnrz1bar0136nvbt0240, the requests often timeout or are very slow.  My other projects with the exact same setup and application seem fine.

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**
I expect the GraphQL calls to return in a reasonable amount of time.

**Comment by marktani** [comment]
Issue moved to [graphcool/graphcool-framework #500](https://github.com/graphcool/graphcool-framework/issues/500) via [**ZenHub**](https://www.zenhub.com/)
