### ISSUE TITLE
updatedAt is not updated when relations are changed

### ISSUE THREAD

**Issue by RoryKelly** [graphcool/prisma#2147]
# Bug Report

**Current behavior**

```
type Review {
  id: ID! @unique
  review: String!
  updatedAt: DateTime!
}

type Content {
  id: ID! @unique
  updatedAt: DateTime!
  book: Book @relation(name: "ContentBook")
  reviews: [Review!]! @relation(name: "ReviewContent")
}
```
if I connect a review to a content the updatedAt time of the content does not change 

**Reproduction**

**Expected behavior?**
when I connect a review to a Content updatedAt should change to the current time.

**Comment by marktani** [comment]
This is expected behaviour. You can ensure the `updatedAt` field is updated by also updating a dummy field on the for example.

Feel free to turn this into a feature request :slightly_smiling_face:
