### ISSUE TITLE
Self-relationship to many without being required

### ISSUE THREAD

**Issue by jferrettiboke** [graphcool/prisma#2150]
# Bug Report

**Current behavior**

```graphql
type Event {
  id: ID! @unique
  name: String!
  parentEvent: Event @relation(name: "ParentEvent")
  events: [Event!] @relation(name: "ChildrenEvents")
}
```

```
Errors:

  Event
    ✖ The relation field `events` has the wrong format: `[Event!]` Possible Formats: `Event`, `Event!`, `[Event!]!`
```

`[Event!]!` is not good for me since one event might or might not have sub-events.

**Expected behavior?**

- One event might have many sub-events or it might not have any.
- One event might belong to another event or it might not.

I know how to solve this on the app GraghQL API layer, but I would like to do it on the database layer setting up all the connections properly.

**Comment by jferrettiboke** [comment]
Oops! Sorry, guys. I misunderstood this. I thought that having `[Event!]!` requires to obligatory specify a sub-event. I got it!

**Comment by marktani** [comment]
Thanks a lot for bringing this up, @jferrettiboke. We should improve the documentation to clear things up around this topic. I created this issue to start a discussion about this: https://github.com/graphcool/prisma/issues/2154
