### ISSUE TITLE
Need MySQL connector for wordpress database

### ISSUE THREAD

**Issue by abhiindia** [graphcool/prisma#2156]
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

I want to use Prisma for React application which interact with MySQL database. Do anyone have working example of MySQL connector with reactjs??

For **feature requests**, please fill out the [feature request template](https://github.com/graphcool/prisma/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/graphcool/prisma/issues/new?template=bug.md)

**Comment by marktani** [comment]
There is already a MySQL connector. Have you tried out the quickstart? That works against a local MySQL DB, but you can change the `docker-compose.yml` to connect to a remote one as well.

https://www.prismagraphql.com/docs/quickstart/
