### ISSUE TITLE
Import is finish, but all relation field is missing data

### ISSUE THREAD

**Issue by kieusonlam** [graphcool/prisma#2175]
# Bug Report

I exported data from graphcool-framework and import to prisma with the same structure.

`prisma reset`
`prisma import --data DataExported.zip`

![image](https://user-images.githubusercontent.com/13093313/38197242-86452bbe-36b1-11e8-87fe-5a8abc9c5513.png)

**Current behavior**

The import is finish, but all relation field is missing data.

![image](https://user-images.githubusercontent.com/13093313/38197037-74a3439c-36b0-11e8-8efe-d9a14d259f31.png)

![image](https://user-images.githubusercontent.com/13093313/38197056-84c68f36-36b0-11e8-80d8-b83499835f6f.png)

**Expected behavior?**

Relation should be imported.

**Comment by marktani** [comment]
What's the version of the cluster you are importing to?

Can you provide a minimal reproduction?

**Comment by kieusonlam** [comment]
I used prisma cluster `prisma-us1` version 1.5.1

Here is it: https://github.com/kieusonlam/prisma-test

**Comment by marktani** [comment]
So what are the steps to reproduce this with this repository? 🙂

Also, I noted you have the `.import` folder still in there. Maybe removing that helps, as described in #2165.

**Comment by kieusonlam** [comment]
Sorry, here is what I do

I did a graphcool-framework export

Reset cluster with `prisma reset`

Import data from

**Comment by kieusonlam** [comment]
Sorry, here is what I do

I did a graphcool-framework export on Windows

```
C:\Users\sdas\Desktop\backend>gcf export
Downloading nodes... 2189ms
Downloading lists... 1597ms
Downloading relations... 1857ms
Zipping export... /
 !    'ENOENT': ENOENT: no such file or directory, open
 !    'C:\Users\kieus\Desktop\movie-backend\export-2018-04-02T13:38:15.150Z.zip'

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

It's error but I still got the .export folder from gcf project. Then I copy `.export` folder to prisma project.

Reset cluster with `prisma reset`

Import data with `prisma import --data .export

I got something in the console
```
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@445365c8 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@358c9655 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@7c610941 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@5725ecb9 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@807aeb0 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@5968bfdb rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@2db78eb6 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@550fef9d rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98098]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@60c8a9a2 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98100]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@7cc25407 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 999, completed tasks = 98100]",
  "Task slick.basic.BasicBackend$DatabaseDef$$anon$2@6d91b717 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6aa95118[Running, pool size = 10, active threads = 10, queued tasks = 1000, completed tasks = 98104]"
```
I check the data and all relation field is blank.

**Comment by marktani** [comment]
Please create a separate bug report for 

>  !    'ENOENT': ENOENT: no such file or directory, open

in the [`graphcool-framework` repo](https://github.com/graphcool/graphcool-framework/).

I suspect that the further observation result from that underlying issue.

**Comment by kieusonlam** [comment]
Ok, I created new bug report https://github.com/graphcool/graphcool-framework/issues/508

The `.export` folder still got all json file, and the json file, and they seem to be correct. You can take a look at 

https://github.com/kieusonlam/prisma-test/tree/master/.export

So i don't think it relate to why import on prisma is missing data.

**Comment by kieusonlam** [comment]
My bad, there is something I were miss.

The data from lists folder might be not fully finish yet. Maybe that why the import data for the relations can't run.

I create a `state.json` file
```
{"nodes":1,"lists":1,"relations":0}
```
And I ran `prisma import` and yes the relations was imported.

**Comment by kieusonlam** [comment]
I have 2911 row in list data. Do you think it is too many to import?

**Comment by kieusonlam** [comment]
I solved the problem, I manually split json in lists folder to 3 files, each contain 1000 row of data. And the import is work normally.

**Comment by marktani** [comment]
Thanks, it's probably the same as #2165 🙂
