### ISSUE TITLE
`prisma login` should let you sign in again if you're signed out of prisma dashboard

### ISSUE THREAD

**Issue by johhansantana** [graphcool/prisma#2176]
# Bug Report

**Current behavior**
After signing out of prisma dashboard and trying to use `prisma login` via cli, it still would think I'm signed in in prisma dashboard

**Reproduction**

1. Sign in to prisma dashboard
2. Sign out of prisma dashboard
3. Use `prisma login` cli command
4. It will show you a page where you click on allow permissions button (but you are signed out, how does it know which account you're allowing permission)

**Expected behavior?**
It should show a form to sign in again

**Workarounds**
Open developer tools in app.prisma.sh and delete cache and cookies, it will let you sign in again after using `prisma login` command

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma-cloud-feedback #122](https://github.com/graphcool/prisma-cloud-feedback/issues/122) via [**ZenHub**](https://www.zenhub.com/)
