### ISSUE TITLE
jwt malformed when use getUserId function.

### ISSUE THREAD

**Issue by vistriter** [graphcool/prisma#2181]
In auth example,  I make auth function. I use getUserId to check user logged. Before when user create something. I have jwt malformed exception.

![screen shot 2561-04-03 at 21 47 36](https://user-images.githubusercontent.com/24702575/38256499-a67481be-3788-11e8-975a-43815a288b43.png)

![screen shot 2561-04-03 at 21 04 13](https://user-images.githubusercontent.com/24702575/38256475-911b8a88-3788-11e8-8962-cd9132140578.png)

**Comment by marktani** [comment]
Hey @vistriter, this is an error thrown in your application code, not in Prisma. Please start a new discussion about this [in the Forum](https://www.graph.cool/forum/c/questions), so we can find out where the problem is 🙂
