### ISSUE TITLE
Prisma connect to external Mysql database

### ISSUE THREAD

**Issue by mrkhanakia** [graphcool/prisma#2200]
How to connect the prima local docker to external mysql database.

**Comment by divyenduz** [comment]
See if this helps you?
https://github.com/maxdarque/prisma-docker

**Comment by marktani** [comment]
Thanks for the answer, @divyenduz 🙂

**Comment by wuzhuzhu** [comment]
the problem is mysql 5.6.
connecting external db is simpler with docker-compose.yml > databases settings.

**Comment by dooboolab** [comment]
@wuzhuzhu I am working on this right now. Could you provide the solution?
