### ISSUE TITLE
Is it possible to customize MySQL connection?

### ISSUE THREAD

**Issue by chj-damon** [graphcool/prisma#2212]
prisma will generate a default database in docker and the username/password is set as default.
But what if I already have a database and I want to connect this database with prisma.
How can I achieve that?

**Comment by chj-damon** [comment]
Let's say if I have a database in AWS, and I want to use prisma to connect it. As we know that prisma will generate a database in docker. So, how can I make prisma connect to my database in AWS?

**Comment by marktani** [comment]
You can use the `prismagraphql/prisma` Docker container, which doesn't include a DB, and connect it to any MySQL DB using `docker-compose`. Here's an example: https://github.com/akoenig/prisma-docker-compose/

You can find more examples here: https://www.graph.cool/forum/t/sparkles-awesome-prisma/2878?u=nilan

**Comment by chj-damon** [comment]
@marktani Thanks for your reply. I'm confusing about one more thing, in the prisma.yml I specified the service and stage, for example 'prisma-test' as the service value and 'dev' as the stage value. then it will create a database named 'prisma-test@dev' if everything works fine. My question is: is there a way to use one existed database instead of creating one? I just want to connect prisma with my database, not create a new one.
