### ISSUE TITLE
Simplified Getting Started Experience

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#2217]
The goal of this ticket is to simplify the first run experience using the Prisma CLI. We will implement these features over the next month.

###  Optional service name and stage

Prisma is a multi-tenant system that allow you to deploy many services to a single installation. Each service can additionally be deployed in different stages. This is a very convenient feature when many developers are working together as well as for implementing CI workflows and blue/green deployment.

When first starting out with Prisma however this adds a new set of concepts that a developer must understand. In order to not overwhelm new developers we remove any mention of services and stages from getting started documentation and the initial CLI flow.

When a service is deployed without a name and stage it is called the "default service" and available at the root domain, ie `/` instead of `/service/stage`

### Simplified configuration

Currently Prisma requires many environment variables with difficult to understand relationships to run. When using `prisma local` this is entirely hidden from the developer as the CLI is orchestrating `docker-compose`, but as soon as you want to install Prisma on a remote server this complexity surfaces.

To simplify the process of deploying Prisma in production, we are changing the local experience so that the developer is in charge of `docker-compose`. At the same time we are cleaning up the many environment variables and introducing a yaml based format to specify Prisma server configuration.

### Simplified terminology

Prisma can run as a single node or multiple clustered nodes. Currently we call both a Cluster.  This terminology has lead to confusion, especially when running Prisma locally for development.
In the future we will refer to a Prisma installation simply as a Prisma server. `Cluster` terminology will be used only in documentation specifically discussing HA and clustering.

### Simplified Prisma server authentication

Currently Prisma relies on assymetric key encryption to secure communication between CLI and server. This is causing a lot of friction when deploying a Prisma server for the first time. We will introduce a simpler shared secret approach.
In addition we will change the default local setup to disable server authentication.

### Reduced complexity of CLI

Currently the CLI holds a large amount of global state in order to support cluster management workflows. This has turned out to be a large source of bugs and confusion. We will remove this global state and let developers be in charge by explicitly specifying what cluster they are working with. This change only affects clusters that are not managed by Prisma Cloud.

**Comment by marktani** [comment]
All the mentioned points have found their way into the [`1.7.0` release](https://github.com/graphcool/prisma/releases/tag/1.7.0).

You can also follow the [upgrade guide](https://www.prisma.io/docs/1.7/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b).
