### ISSUE TITLE
More available variables in Permission Queries

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#222]
* `$now: DateTime` - current time
* ...

**Comment by Geczy** [comment]
Is $now still not available? What is the workaround to make it available?

**Comment by alexanbj** [comment]
I too would like to see this implemented, and I'm also curious if there is any workaround?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
