### ISSUE TITLE
how to use prisma to connect with existed databases?

### ISSUE THREAD

**Issue by chj-damon** [graphcool/prisma#2236]
in the prisma.yml I specified the service and stage, for example 'prisma-test' as the service value and 'dev' as the stage value.
then it will create a database named 'prisma-test@dev' if everything works fine.
My question is: is there a way to use one existed database instead of creating one? I just want to connect prisma with my database, not create a new one.

**Comment by marktani** [comment]
Hey @chj-damon, right now you can connect Prisma to _your_ database using the `prismagraphql/prisma` Docker image. [Here](https://www.graph.cool/forum/t/sparkles-awesome-prisma/2878?u=nilan) are a couple of examples.

Soon, we'll make connecting Prisma to existing databases much easier. Stay tuned for the upcoming 1.7-beta release to learn more 🙂If you're interested in participating, ping me in [Slack](https://slack.graph.cool) (my handle is @nilan).
