### ISSUE TITLE
Upgrading Prisma from 1.1.3 to latest (1.6.3) - Best Practices

### ISSUE THREAD

**Issue by dsoraluz-carecloud** [graphcool/prisma#2246]
I'm working on a project that is running Prisma 1.1.3 and would like to update to the latest release, 1.6.3. 

Can someone lend advice on the best way to go about this so that we do not break anything as a result of jumping so many versions at once.

Thanks in advance!

**Comment by marktani** [comment]
There are general best practices for upgrading your Prisma cluster:

* Read through the [release notes](https://github.com/graphcool/prisma/releases) and make sure that you understand them. Ask questions if something is unclear or seems to be incomplete. Think about which changes affect you, and which changes don't.
* Before starting, run `prisma export` for all services to create a backup. Alternatively, you might be able to use a backup feature for your database. Verify that the backup contains all data, and importantly, verify that _restoring_ or `prisma import` works as well.
* It is recommended to do a "dry run" for the upgrade process in your staging environment. This is to get familiar with the process, and to verify that it all goes as expected. Ideally, when the upgrade process is finished, run your upgraded staging environment through your entire test suite and real world queries/mutations.

The particular upgrade you mentioned (from `1.1.3` to `1.6.3`) spans _two breaking changes_. 

* In `1.3.3.`, we [simplified the API](https://github.com/graphcool/prisma/releases/tag/1.3.3) for nested mutations of `to-one` relations. If you use nested mutations for `to-one` relations at the moment, you will need to regenerate your Prisma binding, and adjust your mutations accordingly.
* In `1.6.1.`, we [introduced strict checks for critical data model changes](https://github.com/graphcool/prisma/releases/tag/1.6.1). This is not a breaking change for your API, but might impact your CI workflow.

It would be great to hear back how that process went for you, and if you gained any additional insights that could help others 🙂

**Comment by marktani** [comment]
@nikolasburk let's add this to a general section for the upgrade guides in the documentation 🙂

**Comment by marktani** [comment]
Added [a section to the docs](https://www.prisma.io/docs/reference/upgrade-guides/upgrading-prisma/overview-tqfbfdzj7a) about this. Thanks for bringing this up, @dsoraluz-carecloud 🙌
