### ISSUE TITLE
How can disable `createdAt` and `updatedAt` in Prisma?

### ISSUE THREAD

**Issue by alireaza** [graphcool/prisma#2248]
In some models no needs to `createdAt` and `updatedAt`.

How can disable `createdAt` and `updatedAt` in Prisma?

**Comment by marktani** [comment]
`id`, `createdAt` and `updatedAt` are [system fields](https://www.prisma.io/docs/reference/service-configuration/data-modelling-(sdl)-eiroozae8u#system-fields). Quoting the documentation:

> The three fields id, createdAt and updatedAt have special meaning. They are optional in your data model, but will always be maintained in the underlying database. This way you can always add the field to your data model later, and the data will be available for existing nodes.

If you don't want these fields for a certain type, just omit them in the datamodel:

```
type MyTypeWithSystemFields {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
}

type MyTypeWithoutSystemFields {
  name: String!
}
```
