### ISSUE TITLE
Meta should be its own permission

### ISSUE THREAD

**Issue by dubcanada** [graphcool/prisma#225]
Right now the `_schemaMeta` is not part of the permissions it should be part of permissions as it's own permission (SCHEMA READ META for example)

Say something like

<img width="1111" alt="screen shot 2017-06-01 at 2 23 58 pm" src="https://cloud.githubusercontent.com/assets/120325/26692150/fffee750-46d5-11e7-9a09-bc03b3c2fed8.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
