### ISSUE TITLE
Can't change default port for server

### ISSUE THREAD

**Issue by darmie** [graphcool/prisma#2264]
# Bug Report

**Current behavior**
Prisma app server not running on set port
**Reproduction**
Simply change NODE_PORT value  in .env file
**Expected behavior?**
Server should run on set port

**Comment by marktani** [comment]
Hey @darmie, thanks for bringing this up.

With "Prisma app server", do you refer to `graphql-yoga`?
Can you show a code snippe that show cases the wrong behaviour?

**Comment by darmie** [comment]
@marktani  yes the issue is with `graphql-yoga`

port is set in `.env`
```
...
NODE_PORT= 4000
...
```

And the index.ts code is the default
```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      endpoint: process.env.PRISMA_ENDPOINT, // the endpoint of the Prisma DB service (value is set in .env)
      secret: process.env.PRISMA_SECRET, // taken from database/prisma.yml (value is set in .env)
      debug: true, // log all GraphQL queries & mutations
    }),
  }),
})

server.start({port: process.env.NODE_PORT})
console.log("Prisma app is now running on http://localhost"+process.env.NODE_PORT)
```

if I change the value of `NODE_PORT`, Playground will launch but server is not working.

**Comment by marktani** [comment]
Issue moved to [graphcool/graphql-yoga #281](https://github.com/graphcool/graphql-yoga/issues/281) via [**ZenHub**](https://www.zenhub.com/)
