### ISSUE TITLE
How to pass a valid token to "graphql get-schema"?

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2268]
With `1.7`, I can now set a post deployment hook to download the Prisma API schema:

```
# prisma.yml
hooks:
  post-deploy:
    - graphql get-schema --project db
```

However, this leads to an error message about an invalid token for secret-protected Prisma services.

How can I change this command to add a new `prisma token` on the fly?
I thought of something like this:

```
# prisma.yml
hooks:
  post-deploy:
    - TOKEN=Bearer ${prisma token}
    - graphql get-schema --header "{"Authorization": "${TOKEN}"}
```

I don't think this syntax works though.

**Comment by bazaglia** [comment]
@marktani same "Implications failed" error. :(

**Comment by marktani** [comment]
Thanks @timsuchanek for clearing that up 🙌

**Comment by nikolasburk** [comment]
This worked for me:

```
graphql get-schema \
--endpoint https://eu1.prisma.sh/public-lucksight-113/myservice/dev \
--header Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNlcnZpY2UiOiJkYXRhYmFzZUBkZXYiLCJyb2xlcyI6WyJhZG1pbiJdfSwiaWF0IjoxNTI0NzUyNjQyLCJleHAiOjE1MjUzNTc0NDJ9.ricwDHJoHtmYN8ZD4ldjH3ek_YMIUJqervXZ0ApjYpU \
--output prisma.graphql
```

**Comment by Huvik** [comment]
@timsuchanek With second option I get:`Unknown argument: header`, even in help `graphql get-schema --help` there is nothing about headers i have `2.3.0` version

**Comment by marktani** [comment]
@nikolasburk, thanks for sharing! It should be noted however that this doesn't work as post deployment hook, because your token will eventually expire if you hardcode it.

@Huvik, `2.3.0` is quite old. If you're on `prisma@1.7.0`, you should go with [`graphql-cli@2.15.10`](https://github.com/graphcool/prisma/blob/1.7.1/cli/packages/prisma-cli-core/package.json#L94) (or higher), if you're on `prisma@1.6.3`, with [`graphql-cli@2.15.7`](https://github.com/graphcool/prisma/blob/1.6.3/cli/packages/prisma-cli-core/package.json#L93).

**Comment by FredyC** [comment]
Made a little [suggestion here](https://github.com/graphql-cli/graphql-cli/issues/283) to have things a little easier (with all those escaped quotes, ughh..)

**Comment by FredyC** [comment]
> Use the .graphqlconfig.yml
> If you have defined your prisma endpoint in the .graphqlconfig.yml, just providing --project should be enough and the graphql-config-extension-prisma should provide the auth headers. If that's not the case, it's a bug.

I think this is indeed a bug as it asked me for a token on several occasions already. Need to test bit more though, I am not sure if it was before I updated other dependencies that were not mentioned in upgrade guide.

**Comment by marktani** [comment]
What dependencies were those? Sounds like we should add that information to the upgrade guide 🙂

**Comment by andrewjmead** [comment]
> If you have defined your prisma endpoint in the .graphqlconfig.yml, just providing --project should be enough and the graphql-config-extension-prisma should provide the auth headers. If that's not the case, it's a bug.

I was able to get that to work, but only after adding a `prisma` property to the `extensions` object in`.graphqlconfig`. I'm leaving this here for anyone else who might have run into the same issue.

Here's my before file where I was getting the auth token error:

```json
{
    "projects": {
        "prisma": {
            "schemaPath": "src/generated/prisma.graphql",
            "extensions": {
                "endpoints": {
                    "default": "http://localhost:4466"
                }
            }
        }
    }
}
```

Here's the final config file which no longer crashes due to a lack of an auth token:

```json
{
    "projects": {
        "prisma": {
            "schemaPath": "src/generated/prisma.graphql",
            "extensions": {
                "prisma":"prisma/prisma.yml",
                "endpoints": {
                    "default": "http://localhost:4466"
                }
            }
        }
    }
}
```

**Comment by Maxondria** [comment]
> ```json
> {
>     "projects": {
>         "prisma": {
>             "schemaPath": "src/generated/prisma.graphql",
>             "extensions": {
>                 "prisma":"prisma/prisma.yml",
>                 "endpoints": {
>                     "default": "http://localhost:4466"
>                 }
>             }
>         }
>     }
> }
> ```

Works like charm... and it sure had to be you @andrewjmead , you are a genius... You teach more than my college professors * 100000... Keep on... You 're amazing! Coming to buy your Prisma course very very soon on udemy! I need more clarity, that's why... I know I will understand better.... Cheers!

**Comment by MuhammadUmairMoosani** [comment]
projects:
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      endpoints:
        default: http://localhost:4466
