### ISSUE TITLE
Unable to update private cluster to v1.7.1

### ISSUE THREAD

**Issue by yoorw** [graphcool/prisma#2274]
# Bug Report

**Current behavior**
Using Prisma Console, private cluster does not update to Prisma v1.7.1.
Menu is displayed allowing to select upgrade from v1.6.3 to 1.7.1.
Popup is displayed stating "Upgrade will be done in about 10min." (see attached image)
However the cluster version stays at v1.6.3.

**Reproduction**
Reproduces 100% using Prisma Console. 

**Expected behavior?**
Expected cluster to update to v1.7.1.
Was previously able to update from v1.5.1 to v1.6.3 using the same method. 

![upgradecluster popup](https://user-images.githubusercontent.com/37107949/39263534-17d57c7c-4888-11e8-8f92-efa122062646.jpg)

**Comment by marktani** [comment]
Issue moved to [graphcool/prisma-cloud-feedback #136](https://github.com/graphcool/prisma-cloud-feedback/issues/136) via [**ZenHub**](https://www.zenhub.com/)
