### ISSUE TITLE
prisma init boilerplate seem not working

### ISSUE THREAD

**Issue by LuHugo** [graphcool/prisma#2276]
I upgrade to 1.7.1 version and init project with boilerplate node-advanced, then I got three files in my project: 
```
prisma.yml 
datamodel.graphql
docker-compose.yml
```

My question is how to development custom resolver

**Comment by nikolasburk** [comment]
Hey @LuHugo, can you please provide the exact command you were running?

Note that there is two ways to get started with Prisma:

1. Prisma-only (this will provide only a Prisma API which is the foundation for your GraphQL server)

```sh
npm install -g prisma
prisma init hello-world
# follow the CLI wizard to create/select a database or choose the sandbox environment for your Prisma API
```

Find more info [here](https://www.prisma.io/docs/tutorials/prisma-basics/getting-started-ouzia3ahqu).

2. Use a "GraphQL server starter kit" based on [GraphQL Boilerplates](https://github.com/graphql-boilerplates) (it seems this is what you wanted?!)

 ```sh
npm install -g graphql-cli
graphql create myserver
# select one of the available boilerplates, e.g. node-basic
```

Find more info [here](https://www.prisma.io/docs/quickstart/backend/node/node-phe8vai1oo).

Let me know if you have any further questions! 🙂

**Comment by LuHugo** [comment]
I use this command to create new project : 
```
prisma init my-app --boilerplate node-advanced
```
then just got three files and the --boilerplate option seem not work
Or I missed something ？

I use graphql-cli command to create new project is successfully
```
graphql create my-app --boilerplate node-advanced
```

But , run 
```
yarn prisma deploy
```
then got an error 

```
 ▸    Cluster secret in env var PRISMA_MANAGEMENT_API_SECRET does not match for
 ▸    cluster local
```

It's a bug ?

**Comment by nikolasburk** [comment]
I can not reproduce this issue, can you please provide the exact steps you're taking that produces this error? Have you tried following the Quickstart [here](https://www.prisma.io/docs/quickstart/backend/node/node-phe8vai1oo)? Are you running into any error messages with this?

Also, regarding your first question: `prisma init` indeed does not work with the boilerplates, it only creates a Prisma-only setup without a GraphQL server (see my previous comment about that).

**Comment by divneet** [comment]
I don't know if this is a new feature but if i'm right i used to able to initiate a new graphql server using `prisma init  ` , all i want to do start from scratch with a local prisma deployment running with a graphql server , instead of `graphql create` doing a cloud based prisma deployment when use boilerplates .
adding links of what i'm trying to ask .
Thanks 
https://divu.in/prisma-deep-dive-3162dea2820c ,
https://www.youtube.com/watch?v=20zGexpEitc

**Comment by LuHugo** [comment]
Thanks guys, I used Apollo server

2018-04-30 11:02 GMT+08:00 Divneet <notifications@github.com>:

**Comment by ebouJ** [comment]
prisma init doesn't initialize the boilerplate anymore.
You first need to install graphql-cli
`npm install -g graphql-cli`
Then run `graphql create` and follow the instruction

**Comment by gkTim** [comment]
Why was this feature removed?
Makes the first tryout of prisma much more complicated!

Otherwise it would be great to have a readme section about it.
I know there is a QuickStart but this isn't mention the way of generating boilerplate code
