### ISSUE TITLE
Cluster Deploy mutation reset project secret (1.6)

### ISSUE THREAD

**Issue by kMeillet** [graphcool/prisma#2299]
**Prisma version :** prismagraphl/prisma:1.6.3
**MySQL version :** mysql:5.7

I can't understand if it's desired or not.

My setup : 

- I start Prisma/MySQL container locally with Docker (not DockerCompose).
- Network and volumes are shared, Prisma/MySQL env configuration is provided, Prisma cluster is available.
- I don't use cluster authentication with RSA keys, i just want to secure my service for the moment.

At this point, i start my own programmatic solution to deploy service :

=> addProject mutation on cluster with one secret.
=> deploy mutation on cluster without secret.

**Expected :** service authentication should be enabled with secret and triggering deploy mutation without secret should fail (authentication error).

I expect something like this : 

=> addProject mutation on cluster with one secret.
=> deploy mutation on cluster with secret.
=> generateProjectToken (should not be empty).
=> Do my stuff with service and generated token.

Am i wrong ? 🗡 

**Currently :** deploy mutation work well and service authentication stay disabled. Is it because my cluster is not protected with RSA keys ? I expect deploy to fail without secret because it interact with service. It's not clear, is deploy mutation cluster-authentication based or service-authentication based ?

**Note :** if i trigger deploy mutation with secret, service authentication stay enabled. But i can imagine situation when people forgot to provide secret on deploy mutation and disable service authentication by inadvertently.

Thanks for the awesome work 🥇

**Comment by marktani** [comment]
You are mixing up

* Prisma server authentication
* Prisma service authentication

Please read [this](https://github.com/graphcool/prisma/issues/2283#issuecomment-384621559) to get a good understanding of both.

You are not protecting your Prisma server as you mentioned here:

> I don't use cluster authentication with RSA keys, i just want to secure my service for the moment.

Therefore, actions against your management API don't need to be authenticated.
Therefore, any deploy action is allowed by default.
So, you can overwrite any service datamodel, and even the service secret(s).

It sounds like you assume that protecting a service with a secret requires to provide the service secret for further deployments. This is incorrect.

Here is a correct statement: Setting up a Prisma server with a management API secret requires to provide the management API secret for any deployments to any services. 

Let me know if that doesn't clear up all your questions 🙂
