### ISSUE TITLE
Revoke/invalidate auth tokens

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#230]

**Comment by kbrandwijk** [comment]
Please implement something similar to how Auth0 does it: https://auth0.com/blog/blacklist-json-web-token-api-keys/

Also, support both existing auth integrations and 'roll your own' scenarios'. 

My current workaround is to never trust 'authentication required' alone for permissions, but also check the userId against the store. However, this will become more important when roles/permissions will become involved.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
