### ISSUE TITLE
Prisma creates an assumption about what's "local"

### ISSUE THREAD

**Issue by FredyC** [graphcool/prisma#2305]
# Bug Report

**Current behavior**

My Docker is running on a different network interface and getting a different IP address. Prisma checks if the specified endpoint includes _localhost_ or _127.0.0.1_ and considers that as a local which is not correct in my case.

https://github.com/graphcool/prisma/blob/e079b4e8469f3c796da91e906e336573bb15738a/cli/packages/prisma-yml/src/utils/parseEndpoint.ts#L24

If the endpoint is not recognized as local, it will fallback to _cluster_ name "default". This creates a collision in case there is another custom cluster. The host for running prisma commands (eg. deploy, token) is then taken from `config.yml` (default cluster) which turns out to be wrong if running against this custom cluster.

**Expected behavior?**

I assume this is still work in progress and eventually, there will be no need to parse "cluster" name from endpoint URL and to match those against `config.yml`. However, if it's still plan to stick to this file, I ask you to reconsider this. Since there is a whole endpoint in `prisma.yml`, it's easy to grab necessary information from it instead of keeping another list of hosts in a config file.

This goes together with `clusterSecret` which should be magically read from `PRISMA_MANAGEMENT_API_SECRET` env variable. I believe this should be part of `prisma.yml` so a correct value can be read based on environment.

Related: https://github.com/graphcool/prisma/issues/2273#issuecomment-385239823

**Comment by timsuchanek** [comment]
Thanks for reporting @FredyC ! We just pushed a fix which should tackle the problem you just described.
Can you confirm if this is fixed for you in `prisma@1.8.0-beta.5`?
Thanks!

**Comment by FredyC** [comment]
I haven't tried it, but as I said in the Slack to you, I don't think your commit fixes this particular issue. It will still fall back to "default" as cluster name if anything but localhost/127.0.0.1 is used as host.

Once again this whole dependence on `.prisma/config.yml` is totally weird and shouldn't be there. You should just parse provided endpoint from `prisma.yml` to assemble `http://origin/cluster` url for management calls. That config file is totally redundant in my opinion.

**Comment by timsuchanek** [comment]
Thanks for the answer. There is no necessity for the `~/.prisma/config.yml`. You're right, that would be totally confusing and inconsistent.
There are only 2 things needed to operate the cluster: The endpoint `http://origin/cluster` and optionally the cluster secret as an env var `PRISMA_MANAGEMENT_API_SECRET ` if you have set one. 
This also means there is no such concept as a cluster name anymore.

Being dependent on it was a bug. We now released the fix under `1.7.4`.
I assume this to be fixed now, please reopen if that's not the case.
