### ISSUE TITLE
"prisma login --key __MY_TOKEN__" still needs a browser

### ISSUE THREAD

**Issue by zadigus** [graphcool/prisma#2310]
Hi,

I worked until now with prisma 1.5.1. Under that version, I was able to 

    prisma login --key $PRISMA_SERVICE_TOKEN

This had the effect that I could login without opening a page in a web browser and clicking the "Grant permission" button. This is a feature I am using a lot because I deploy my code from bitbucket to heroku with the bitbucket pipelines. 

Now I upgraded this morning to prisma 1.7.3. Under that version, the above command opens a browser, i.e. I can't login anymore with the command-line only.

Am I doing something wrong? Did you guys change something in the way we login with prisma lately?

Thanks in advance for your help!

**Comment by zadigus** [comment]
I was able to test that a bit more and noticed that the feature is still working with prisma 1.6.0 but not any more with 1.6.1.

**Comment by SpaceK33z** [comment]
Having the same issue in Prisma 1.8.0. Pretty painful since now I'm unable to deploy at all (I deploy with Travis CI).

**Comment by SpaceK33z** [comment]
As a workaround you can do this:

```
echo "cloudSessionKey: >-\n  ${PRISMA_SERVICE_TOKEN}" > ~/.prisma/config.yml
```

**Comment by timsuchanek** [comment]
fixed in latest version :)

**Comment by zadigus** [comment]
I tested today with

     "prisma": "^1.11.0",

and it doesn't work: the web page gets opened and I need to manually grant the permission by clicking the "Grant permission" button.

**Comment by zadigus** [comment]
Ok I tried again and it seems to be working. I don't know what happened to my token but apparently it changed. I got no clear message in my console that the problem was that the token was invalid...

**Comment by Fi1osof** [comment]
Can i view account tokens in https://app.prisma.io/ for authorize in command line? Or i should install prisma local, run prisma login (for confirm auth in browser), then get token in ~/.prisma/config.yml and put them in ~/.prisma/config.yml for target server?

**Comment by marktani** [comment]
I created a feature request for this here: https://github.com/prisma/prisma-cloud-feedback/issues/217.

I think what you wrote will work as a workaround, but I'm currently not sure.
