### ISSUE TITLE
Authentication token is invalid: Token can't be decoded: Expected token [null] to be composed of 2 or 3 parts separated by dots.

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2316]
# Bug Report

**Current behavior**

![image 9](https://user-images.githubusercontent.com/1780597/39442187-ba327a34-4cb0-11e8-93b4-c6d58b1341b6.png)

**Reproduction**

> deploy a server somewhere using docker and set the `managementApiSecret` and try to deploy

**Expected behavior?**

It works.

**Comment by marktani** [comment]
This is fixed on the `beta` channel.

**Comment by timsuchanek** [comment]
We just released `1.7.4` fixing this issue.
