### ISSUE TITLE
More neutral way to abort the event pipeline

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#232]
Currently, the only way to abort the event pipeline in a hook, is to raise an error. This is nice, however if the behavior is by design, one might like a more neutral way to abort (like e.Cancel = true on traditional event handlers in .NET for example).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
