### ISSUE TITLE
Prisma Data Export & Import Issue

### ISSUE THREAD

**Issue by hjrobinson** [graphcool/prisma#2322]
Here are my files including my terminal_log:
[prisma-export-import-issue.zip](https://github.com/graphcool/prisma/files/1967618/prisma-export-import-issue.zip)

I am using Windows 7 Home Premium and git-bash 2.9.0.1 for my terminal.

I am following the instructions for Prisma Data Export & Import at: 
https://www.prisma.io/docs/tutorials/database/data-export-and-import-caith9teiy

At Step 8, I receive the following error:

$ prisma export
Downloading nodes 1230ms
Downloading lists 613ms
Downloading relations 614ms
Zipping export... \
Error: ENOENT: no such file or directory, open 'C:\Projects\prisma\prisma-export-import-issue\import-example\export-2018-05-02T14:06:51.422Z.zip'

This produces a .export folder (unzipped).  I manually zipped the folder for use in Step 12.

Step 12 indicates successful import in the terminal as follows:

$ prisma import --data .export.zip
Unzipping 41ms
Validating data 24ms

Uploading nodes...
Uploading nodes done 4ms

Uploading lists
Uploading lists done 2ms

Uploading relations
Uploading relations done 3ms

However, when I query for the data in the playground nothing is returned.

**Comment by hjrobinson** [comment]
I found a way to make it work (I think).  I didn't zip the .export file but simply imported it.  The data was then available in the playground.  I'm also using Prisma 1.6.3 in this case although I'm not sure if that matters. The timestamp feature still doesn't work when exporting but to me that's not significant.

**Comment by biels** [comment]
It is probably still an issue, see #3183

As I have posted to slack:
Prisma is failing to export / reset / import into itself
Throwing a bunch of  ... violates foreign key constraint ... is not present in table [Table]
It looks like it is not exporting all the data, because the export process is very fast and the resulting file very small
So basically I am unable to export my database and do any backups
I'm on 1.29

**Comment by ardsh** [comment]
@biels I had the same issue when importing from a zip file, but it worked correctly if I unzipped the file before importing.

So instead of
`prisma import --data export.zip`
you can execute
`unzip -d exportedDir export.zip && prisma import --data exportedDir`
