### ISSUE TITLE
Subscription not firing on where condition change

### ISSUE THREAD

**Issue by murdockq** [graphcool/prisma#2324]
# Feature Request

**What feature are you missing?**
Subscriptions don't fire when a batch update occurs in Prisma 1.7.4

**How could this feature look like in detail? Tradeoffs?**

Run this subscription and listen for mutation: UPDATED

```
subscription {
    post(where: {
    node: { isPublished: true }
    }) {
    mutation
    node {
        id
        isPublished
    }
}
```

Then I run a batch update to post that changes the isPublished data to true.  

```
{
  "data": {
    "isPublished": false
  },"where": {
    "isPublished": true
  }
}

mutation updateManyPosts(
  $data: PostUpdateInput!
  $where: PostWhereInput!
) {
  updateManyPosts(data: $data, where: $where) {
    count
  }
}
```

**Expected behavior?**
I would see the UPDATED subscription fire, when the batch isPublished condition changes.

**Comment by marktani** [comment]
Thanks, I opened a new feature request for better clarity here: https://github.com/graphcool/prisma/issues/2327 🙂
