### ISSUE TITLE
playground always goto http://localhost:4466/undefined/dev 

### ISSUE THREAD

**Issue by halton** [graphcool/prisma#2339]
# Bug Report

**Current behavior**
`prisma playground` will open http://localhost:4466/undefined/dev

**Reproduction**
`prisma.yml` as below:
```
endpoint: http://localhost:4467/hello-world/dev

datamodel: datamodel.graphql
```
Then run comment `prisma deploy && prisma playground`

**Expected behavior?**
`prisma playground` goes to exact the endpoint config, in above case, http://localhost:4467/hello-world/dev

**Extra information**
Tested on with `prisma/1.7.3 (linux-x64) node-v9.9.0` and current master HEAD `258ee4adce8eaab5b831bee249ea4dcd4c2017c3`, same result.

If I use the deprecated config as below, everything is fine.
```
service: hello-world
stage: dev
datamodel: datamodel.graphql
cluster: local
```

**Comment by marktani** [comment]
Hey @halton, can you share your `~/.prisma/config.yml` as well?

Please remove any sensitive information beforehand (`clusterSecret`, `cloudSessionKey`, ...)

**Comment by halton** [comment]
```
$ cat ~/.prisma/config.yml 
clusters:
  local:
    host: 'http://localhost:4466'
    clusterSecret: "-----BEGIN RSA PRIVATE KEY-----
----END RSA PRIVATE KEY-----\r\n"

```
