### ISSUE TITLE
where can I find the changelog of different versions?

### ISSUE THREAD

**Issue by chj-damon** [graphcool/prisma#2341]
I find v1.9.7 in tags. does it mean it has been released officially? where is the 1.8 version? I didn't find any changelog in this repository or the website. I want to know what is included in this version.

**Comment by marktani** [comment]
Hey @chj-damon, tag `v1.9.7` is not a valid version, it has been created by accident a long time ago.

Version `1.8` will be released next Tuesday, including detailed release notes at https://github.com/graphcool/prisma/releases. Until then `1.8-beta` Docker images + npm version is available.

Soon, we will also have a `CHANGELOG.md`: #1995.

**Comment by chj-damon** [comment]
@marktani Thanks for your reply. I'm looking forward to the new 1.8 Version!!
