### ISSUE TITLE
CLI: post-deploy hooks doesn't show errors

### ISSUE THREAD

**Issue by wolszczak96** [graphcool/prisma#2378]
# Bug Report

post-deploy command shows its output whe everything goes fine, but when there is an error, no output is shown

`prisma deploy` output:
```
post-deploy:
Running graphql get-schema --project db ✔
```

`graphql get-schema --project db` output:
```
✖ "db" is not a valid project name. Valid project names: app, database
```

**Comment by marktani** [comment]
Thanks for bringing this up,  @wolszczak96. This is a duplicate of #2362 🙂
