### ISSUE TITLE
Publish Graphcool on Zapier and IFTTT

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#238]
It would be really helpful if Graphcool was available on Zapier and IFTTT. As a source (based on a subscription or cron query) or target (based on a mutation). This would be really helpful, because a lot of integrations are available out of the box on these platforms, and being able to connect to Graphcool would be really helpful for a lot of applications.

**Comment by marktani** [comment]
It looks like [Zapier requires a REST or even XML-RPC API](https://zapier.com/help/getting-new-service-zapier/#requirements-for-any-new-app). 

I couldn't find a lot of useful information on building a IFTTT integration.

Does someone in the Graphcool community know more about building custom integrations with IFTTT or Zapier?

**Comment by kbrandwijk** [comment]
Zapier promotes the use of GraphQL: https://zapier.com/engineering/flexible-api-responses/
Here is the developer documentation: https://zapier.com/developer/documentation/v2/
Also, on the developer platform, when connecting to an external system, you have complete freedom over the HTTP request.

Here's some background on the partner channel program from IFTTT:
https://s3.amazonaws.com/features.ifttt.com/developer_platform/ChannelDevelopmentGuidebook_02082016.pdf
https://s3.amazonaws.com/features.ifttt.com/developer_platform/APIDocs_02082016.pdf

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
