### ISSUE TITLE
Project "Not Found" and "found" alternatively in Playground

### ISSUE THREAD

**Issue by Alosies** [graphcool/prisma#2388]
I am getting "Project Not found" error frequently in Playground. 
Error: 
`{
  "errors": [
    {
      "message": "Project not found: 'alosies~gp-server-v3@dev'",
      "code": 3016,
      "requestId": "eu1:api:cjgyxcfyk024p0b58tit19m9z"
    }
  ]
}`

Sometimes I get the required object output, but sometimes i get Project not found. What could be the issue. 
Below are the two different outputs in a span of hardly a minute

<img width="1440" alt="screen shot 2018-05-09 at 3 28 11 pm" src="https://user-images.githubusercontent.com/24241029/39808860-b8bbe912-539d-11e8-88ed-aa33e9fa50a9.png">

<img width="1440" alt="screen shot 2018-05-09 at 3 28 32 pm" src="https://user-images.githubusercontent.com/24241029/39808863-b8eed340-539d-11e8-8434-d1ae81eed113.png">

**Comment by marktani** [comment]
We are currently investigating this issue that happens for the free development servers. You can track our progress here: https://status.prismagraphql.com/.

**Comment by marktani** [comment]
This is now resolved.
