### ISSUE TITLE
Make prismagraphql/prisma image Dockerfile public

### ISSUE THREAD

**Issue by maticzav** [graphcool/prisma#2403]
Is there a way to access Dockerfile of `prismagraphql/prisma` image?

**Comment by dpetrick** [comment]
Not in a sense that you're probably looking for. We're building our docker images using a SBT plugin that allows us to declare Dockerfiles via code for maximum flexibility: https://github.com/graphcool/prisma/blob/master/server/build.sbt#L35 

Of course, you can more or less translate the Dockerfile into a plain one, however, it involves understanding parts of the artifact building process of the SBT native packager.

**Comment by maticzav** [comment]
Perfect! Thanks @dpetrick!
