### ISSUE TITLE
Add 'deny' permission functionality

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#241]
With the current permission system, there's no option to deny someone access based on a query. This means some usecases lead to elaborate permission setups (using 'not'), or might even be impossible to implement.

If a field has more restrictions for authenticated users, then for everyone *else*, I cannot set that up. The less restrictive permissions for everyone would always overwrite the more restrictive one for authenticated users.

This can easily solved by specifying if a permission is an 'allow' or 'deny' permission.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
