### ISSUE TITLE
@unique directive for the user-defined type breaks the server

### ISSUE THREAD

**Issue by email2vimalraj** [graphcool/prisma#2415]
# Bug Report

**Current behavior**
If I provide `@unique` directive for my own type, then the server is not responding.

**Reproduction**

I've added sample datamodel in the following repo: https://github.com/email2vimalraj/prisma-playground

My datamodel look like this:

```
    type Execution {
      id: ID! @unique
      name: String! @unique
      configuration: Configuration! @unique
    }

    type Configuration {
      id: ID! @unique
      environment: String!
      version: String!
      execution: Execution!
    }
```

Kindly update the endpoint in the prisma.yml file and deploy in your cluster. Then open the playground and see that the server is responding or not.

**Expected behavior?**
Server should be responding properly and should be able to execute graphql queries.

**Actual behavior**
Getting **Server cannot be reached** error.

**Comment by do4gr** [comment]
Hey @email2vimalraj  thanks for reporting this. Unique constraints can not be applied to relations only to non-list scalar values so the datamodel you posted would not work. 
But the server should return an error during deploy and not start hanging. I'll look into this in the next days.

**Comment by email2vimalraj** [comment]
@do4gr : Thanks for replying quickly. Can we have this as a feature request?

Because I would like to get the list of unique configurations for each execution. I believe it would be a typical use case for many.

**Comment by marktani** [comment]
Thanks for your input, @email2vimalraj! 🙂
A detailed feature request for this already exists here: #1300

**Comment by email2vimalraj** [comment]
@marktani : Thanks, I'll follow the thread that you have pointed out.
