### ISSUE TITLE
Multiple functions for the same hook point in the Request Pipeline

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#243]
Since functions (can) happen synchronously, it should be possible to set the order.
Also, I think I saw in the changelog that pre_write now gets the modified output of transform_argument. Does that also happen with two transform_argument functions for example?

**Comment by marktani** [comment]
Having [one function per trigger and hookpoint](https://www.graph.cool/docs/reference/functions/request-pipeline/overview-pa6guruhaf/#hook-points) is a current limitation. If we offer multiple hookpoints, the order of those should be controllable as well.

**Comment by kbrandwijk** [comment]
Well, that's why I didn't post it as a bug, but as a feature request :)

However, I don't want to check the documentation for every little thing when using the console. In other words, if it's not supported, the console should not allow you to. I'd rather check the documentation why I can't create a second hook, than wonder why it doesn't fire after creating it...

So, while this FR is open, and the limitation is still there, could you at least make sure you can't create a second one in the console?

**Comment by marktani** [comment]
Good point, I created this ticket: https://github.com/graphcool/console/issues/1117.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
