### ISSUE TITLE
Subscriptions for Relay modern

### ISSUE THREAD

**Issue by goldenbearkin** [graphcool/prisma#244]

**Comment by kbrandwijk** [comment]
What's this FR about? I'm dealing with subscriptions and Modern in my current project. Is something missing from Graphcool to support this?

**Comment by jonathanheron** [comment]
@kbrandwijk see here: https://www.graph.cool/forum/t/relay-modern-subscriptions/420

**Comment by kbrandwijk** [comment]
@jonathanheron Thank you. So this is about auto-generating the Subscription field in the schema for the Relay API.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
