### ISSUE TITLE
When PQ applied to whole applied to whole type, check it even with no scalar params in mutation

### ISSUE THREAD

**Issue by delgermurun** [graphcool/prisma#245]
```
mutation {
  createPost (authorId: "<authorUserId>") {
    id
  }
}
```

This kind of mutation should work. Now PQ always throws an error.
Only checking scalar fields is bad design, I guess

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
