### ISSUE TITLE
Generate additional permission queries on Types for _every and _none

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#247]
In a permission query, we can add a condition for a child collection, like `children_every`, `children_some` and `children_none`. It would be nice to have exactly the same options for the main query, so instead of just `SomeTypeExists`, having the same three queries: `Type_Some`, `Type_Every` and `Type_None`.

This allows for more use cases (with `Type_Every`) and also less contrived queries (with `Type_None`)

**Comment by wallslide** [comment]
I have run into the usecase where a `none` query would be helpful:

I have an `Event` model, and `EventPayment` model. Payments can have states such as `pending`, `paid`, and `error`. I want to restrict a user to only having one `paid` or `pending` event payment on an `Event`, however they can have as many `error` event payments as they want. The current permission queries don't support this scenario unfortunately. If I had  an `EventPayment_none` query, I could verify that the user had no `paid` or `pending` event payments for a given event.

**Comment by kbrandwijk** [comment]
@wallslide In your case, the child filters would already work I guess, with something like this:
```
query ($input_eventId: ID!) {
  SomeEventExists(
    filter: {
      eventPayments_none: { OR: [ {status: PAID}, { status: PENDING} ] }
      id: $input_eventId
    }
  )
}
```

**Comment by wallslide** [comment]
@kbrandwijk I don't think it would end up working. Let me change your query slightly, because I want to restrict the creation of `EventPayments`, not events:
```graphql
query ($input_eventId: ID!, $user_id: ID!) {
  SomeEventPaymentExists(filter: {
    user:{
      id: $user_id
    },
    event: {
      id: $input_eventId
    },
    status_not_in: [PAID, PENDING]
  })
}
```
This query would work if a user already had an `error` event payment. But if there are no existing event payments, then there is nothing for this query to return, and the permission will be denied. On the other hand, if a negative query existed:
```graphql
query ($input_eventId: ID!, $user_id: ID!) {
  NoEventPaymentExists(filter: {
    user:{
      id: $user_id
    },
    event: {
      id: $input_eventId
    },
    status_in: [PAID, PENDING]
  })
}
```
Then I could easily accomplish my task.

**Comment by kbrandwijk** [comment]
You can use `SomeEventExists` in the `CREATE` permission for `EventPayment`, I think that's the part you're overlooking. That's why I used `$input_eventId`, pointing to the `eventId` field on `EventPayment`.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
