### ISSUE TITLE
lastAccessedBy/lastAccessedAt automatic fields

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#250]
They would track when and who last accessed the data of a given node.

**Comment by sedubois** [comment]
Related: https://github.com/graphcool/feature-requests/issues/93

**Comment by kbrandwijk** [comment]
Accessing a node being a abstraction of 'who accessed any field of a given node'?
And may I suggest a toggle somewhere to turn this on or off? I wouldn't want the overhead on all Types if I hardly, if ever, use this functionality. It all counts towards database size in the end..

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
