### ISSUE TITLE
Overwriting Graphcool files

### ISSUE THREAD

**Issue by sedubois** [graphcool/prisma#261]
Once a Graphcool file has been uploaded, it's sometimes necessary to overwrite it while maintaining its URL (e.g to edit a mistake, etc).

It's important to keep the same file URL when some code still needs to refer to the URL directly instead of fetching the URL through the GraphQL API (which can happen e.g. when migrating an old codebase, or just for simplicity's sake).

Sorry if this is already possible, but didn't find any documentation about it.

**Comment by kbrandwijk** [comment]
If you're referring to the Graphcool cli, you can use `graphcool push` to update your current project with local changes the the `.graphcool` project file.

**Comment by sedubois** [comment]
Sorry. I mean the files at files.graph.cool.

**Comment by kbrandwijk** [comment]
That's not possible out of the box. I have created an example for a file proxy that is currently under review, that would easily enable you to do so.

**Comment by sedubois** [comment]
@marktani any news on this? It still appears quite necessary to me. It's an operation that is routinely needed during maintenance/editing of most kinds of digital content probably, as well as during putting content online where we have no choice but uploading content to its final web context to be able to check for issues, then to update/edit the file accordingly, often several times.

Needing to upload a new file every time then manually deleting the previous one, also leads to inconsistency issues, e.g forgetting the old broken file in the file storage, which leads to confusion as to which version is the right one.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
