### ISSUE TITLE
Provide existing values in RP function

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#262]
For a number of use cases, it is helpful to have access to the current values of a node in a RP transform_argument hook on update.

**Comment by wallslide** [comment]
Without access to both current/future values in a transform_argument hook on update, I cannot enforce a state machine logic upon a node. For instance, the state of an Event may only transition from `NEW=>RECRUITING` and `RECRUITING=>COMPLETED`

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by roycclu** [comment]
@marktani Where this is now discussed in prisma?
