### ISSUE TITLE
Partner with Scribe

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#263]
I come across a lot of companies that use [Scribe](https://www.scribesoft.com/) to do their data migration. It offers hundreds of connectors for all kinds of systems (https://www.scribesoft.com/connectors/). It would be a huge benefit if you could partner with these guys to develop a connector with them.

They don't offer any other GraphQL type connectors yet, so it would be a big advantage to competitors.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
