### ISSUE TITLE
Field to check equality in permission queries

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#264]
Especially for enums, this would be very helpful, but it works similar for other scalar field types. This would make it a lot easier to check the input of enum fields.

# Current Workaround

Right now, to check if the input for an enum is the value `A`, you need to create a new "reference type" (let's call it `Reference`), with one unique field (let's call it `key`) of that enum type and one node per available enum value, then use this PQ:

```graphql
query ($input_enum: MyEnum!) {
  SomeReferenceExists(filter: {
    AND: [{
      key: A
    }, {
      key: $input_enum
    }]
  })
}
```

# Feature request

Introduce `MyEnumEquals` and `MyEnumNotEquals` or similar, so this would be possible:

```graphql
query ($input_enum: MyEnum!) {
  MyEnumEquals(a: $input_enum, b: A)
}
```

**Comment by kbrandwijk** [comment]
Or... change permission queries to permission functions...

**Comment by marktani** [comment]
Good point, maybe it's better to wait on #183. 🙂

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
