### ISSUE TITLE
Allow 'silent' permissions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#274]
Currently, when you secure a field using permissions, and you try to access it, and it's nullable, it returns null. That's nice, but you also get a bunch of insufficient permission errors. Standard libraries (like your own `graphql-request`) go into different code paths for errors.

It would be nice if permission denied could be handled silently, e.g. no permission = null, without error messages. From a security perspective, this is a lot safer, because as opposed to 'there's no data', 'you don't have access to this data' is the start of a security hole...

**Comment by kbrandwijk** [comment]
Related to #280, initially this can only be done when fields are optional, because the GraphQL does not allow returning null on required fields. So this FR does _not_ change the way permissions affect the response, it's deliberately limited to 'don't return an error message, just return null'.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
