### ISSUE TITLE
Add 'owner' to permission query options

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#275]
If a Type has a User field, it would be nice to set the read or update permission to 'owner', without having to write a permission query for it.

**Comment by marktani** [comment]
That's a great idea! For this case, we would need the ability to mark a special field:

```graphql
type Post {
  id: ID!
  owner: User @relation(OwnerOnPost)
  guest: User @relation(GuestOnPost)
}
```

for this, we need to be able to handle multiple owners as well:

```graphql
type Post {
  id: ID!
  owners: [User!]! @relation(OwnerOnPost)
}
```

**Comment by kbrandwijk** [comment]
Or you could specify the owner field on the PQ. That might be easier to implement.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
