### ISSUE TITLE
Add 'inherit/relation' permission setting

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#276]
It would be efficient to 'inherit' permissions for a Type from a related type.

For example, if you have an Order, with OrderItems, and you define all permissions for Order, it would be nice to specify permissions on OrderItems to 'follow' permissions from 'Order'.
This is possible with the current permission queries, but it would be nice to configure it in the Console, instead of having to write a query for it. It also saves a lot of administration.

**Comment by marktani** [comment]
Can you make some examples which PQ would effectively be in use for `OrderItems` (for Create, Update, Read or Delete), given a PQ for `Order`?

**Comment by kbrandwijk** [comment]
For example: I have a the following PQ's on `Order`:
- Order read all fields for owner, and user with role 'backoffice';
- Order create for authorized user;
- Order update allowed for some fields for owner ;
- Order update allowed for all fields for user with role 'backoffice';
- Order delete allowed for user with role 'supervisor';

Now, these same permissions apply to `OrderItems` for the Order, so I would like to define:
- OrderItem create: owner, by relation: Order
- OrderItem read: all fields, inherit, by relation: Order
- OrderItem update: all fields, inherit, by relation: Order
- OrderItem delete: owner, by relation: Order

This example uses mostly inherited permissions by relation, and an owner permission (from my other FR)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
