### ISSUE TITLE
Control input and output schema separately

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#280]
Currently, the schema defined with the Console or CLI both describes the input as well as the output.

However, sometimes more control is needed. For example, while a field might be required for the input, it is not necessarily required for the output (because of permissions, for example). On the other hand, a field might not be required in the input, but in the output (because of a RP function).

**Comment by kbrandwijk** [comment]
This is definitely not the same as #260. It might be a precondition for it, but it does not cover it.
Also, always making FR more generic, and bigger, is not getting them implemented any faster...

**Comment by marktani** [comment]
Didn't mean to diregard your suggestion, I reopened your original feature request.

**Comment by kbrandwijk** [comment]
No worries, I clarified the scope of #274.

**Comment by rjspotter** [comment]
The example we have for this is dealing with images.  On input we're dealing with a ID from a external provider and width and height.  On output we pretty much only need to return a URI

**Comment by kbrandwijk** [comment]
@marktani What's needed to get this from `stage/discussing` to `stage/waiting` for controlling required on input/output?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
