### ISSUE TITLE
Make the system API official

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#281]
A lot of FR that people urgently need (like https://github.com/graphcool/feature-requests/issues/213#issuecomment-311242283 and quite a few other) can be worked around using the system API. For some, that might be the difference between using and not using Graphcool. And for Graphcool, it might relieve a bit of the pressure.

It's definitely not a beginner or intermediate solution, and you might decide not to offer support on it for now, but for advanced users it could offer a way to satisfy their requirements. For example, I use the system API to keep permission queries and functions under source control.

And I know it's not very polished yet at the moment, the point is that the API is currently not stable _officially_, so it can change without notice. GraphQL is a great way to make changes to an endpoint without backwards compatibility issues, so I guess this FR comes down to 'please don't break anything without telling us on the system API'.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
