### ISSUE TITLE
Ability to set project to 'import mode'

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#288]
Based on https://github.com/graphcool/graphcool-cli/issues/1#issuecomment-308681941:

- Don't count requests towards the monthly request quota (Might require disabling of conventional reads/writes to the project during this time - only allow access with client PAT to only the simple endpoint?)
- Temporarily lift required relations constraint to import data in two steps (1. import nodes 2. set relationships)
- Temporarily remove result size limit (needed to get a list of all existing id's in one query, not just 1000)
- Maybe disable other actions (like algolia?) for performance?
- Maybe do some tweaking on database/connection (turn of index regeneration, tweak some other things that might help the fact that there's a huge amount of data about to come in) for performance?
- Anything else?

**Comment by sorenbs** [comment]
Thanks Kim

I think having a special "import mode" has merit.

This import mode should:

- disable features that impacts performance
- disable data integrity checks that make it difficult to bulk import data
- ideally perform data integrity check when disabled, but an initial version without this is probably already valuable.

Concretely I propose:

- import mode can be activated and deactivated at any time, but will automatically be disabled after 2 hours
- don't count requests
- disable all integrations
- disable all serverside subscriptions and request pipeline functions
- disable required relations checking
- keep constraints enabled (unique constraint + simple validations on scalar values we will introduce soon)
- disable all permissions. The only way to access the apis is with a pat or the cli token.
- disable result size limit. Our system is designed around the 1k nodes result limit, so you will run into timeout issues, even when just querying for ids. My best guess is around 100k. The client will have to handle this.
- in the future, apply optimisations on the db level

Do you think this strikes the right balance between performance and features?

**Comment by kbrandwijk** [comment]
In addition, the reason why I explicitly *excluded* regular PAT's, is because they could be used on cron jobs/external webhooks etc., and those need to be disabled as well. So not even the PATs, but only the client tokens should get access.

On the other points, I'm glad my additions to the original comments are in line with your view on this. And I think those first steps would be a great help towards running a smooth import. I would even define a few extra milestones on this based (`orderby benefit desc`) to make this a more feasible (on a short term) FR. Technical requirements should get a higher priority than performance benefits.

- As it is used for inital data import, chances are that permission and functions/RP/SSS are not set up yet in most cases, so that one would get lower priority in my opinion.
- Disable all permissions is related to 'don't count requests' first, from a strictly technical point of view, not really relevant to the import, but they are relevant to Graphcool of course.
- Disable result size limit (for the id query) seems like a real technical requirement. **Priority 1**.
- Disable required relation checking. Would be very nice, although there is a workaround using the system API. **Priority 2**.

**Comment by kbrandwijk** [comment]
Maybe also interesting for import mode: https://github.com/graphcool/api-bugs/issues/110

**Comment by marktani** [comment]
I think the recently introduced import feature covers this well enough.
