### ISSUE TITLE
Extend permission types

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#290]
Current permission are: `READ`, `CREATE`, `UPDATE`, `DELETE`.

Proposal:
Extend/change permissions with the following:
- `DESCRIBE`: linked to the meta information (related: https://github.com/graphcool/feature-requests/issues/225)
- `LIST`: permission linked to retrieving a set of nodes (allXXX query, nested collection)
- `READ`: permission linked to retrieving an individual node (by ID)

Use case: `LIST` and `READ` allows you to more easily distinguish between being able to get only a few fields when a list of nodes is retrieved, and having more strict authorization and more fields for retrieving an individual item directly ('get details')

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
