### ISSUE TITLE
Stripe Template

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#3]
A Stripe template should be added to https://github.com/graphcool/templates.

**Comment by heymartinadams** [comment]
Will write up blog post on how to integrate Stripe with Graph.cool (probably in about a month or two).

**Comment by marktani** [comment]
That was a short month: https://medium.com/@ConsciousApps/integrating-stripe-with-react-graphql-and-apollo-client-e09fdc9e5b95

Thanks @heymartinadams :raised_hands:

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
