### ISSUE TITLE
Shift + space does nothing

### ISSUE THREAD

**Issue by brenmcnamara** [graphcool/prisma#300]
I know this is a super nit feature request and definitely not urgent, but I noticed while typing out a graphql type, I'll type out a colon (:) followed by a space, but my finger will still be on the shift key while typing out the space. Most interfaces process this as a space, but the console will ignore the space. This happens often enough that it caught my attention.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
