### ISSUE TITLE
Add configurable options for GraphQL schema export

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/prisma#302]
Right now there are two export schema buttons in the schema editor in the console that both return specific versions of the schema.

It would be awesome if there was a way to specify exactly what parts of the schema is required (only data model, full schema) and in what format (e.g. JSON or SDL).

Then certain combinations could be highlighted for their use cases, (e.g. for Relay or the Apollo iOS Client)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
