### ISSUE TITLE
Migration of enum values

### ISSUE THREAD

**Issue by phehaz** [graphcool/prisma#305]
When updating existing enums (In my case, wanting to change ENUM values from lowercase to uppercase) there is currently no way to do this in the console, you are met by a 'notification'-error:
<img width="305" alt="screen shot 2017-07-10 at 08 39 01" src="https://user-images.githubusercontent.com/5908415/28005508-4ad56b1c-654b-11e7-80a5-6da7deeb9be3.png">
but there is no way in the console to specify these migration values, I might have missed something, so please let me know if i have. :) After a quick chat with @marktani we came to the conclusion that the only way to achieve this right now, is by creating the new ENUM values, create a script to reassign old values in data to new ones and then delete the old enum values. 

The request is to have somekind of UI where you either visually or just by text, can assign which new ENUM values the old ones should be migrated to, so there won't be a data loss. Something along the lines of: 
OLD_ENUM1 & OLD_ENUM2 => NEW_ENUM_1

Hope that made sense. :)

**Comment by marktani** [comment]
Thanks for the detailed feature request, @phehaz 👍

**Comment by steve-a-jones** [comment]
@phehaz - Were you actually able to achieve this? I added the new enums and successfully migrated existing nodes to the new values, but am still getting the error when I deploy with the old enums removed. @marktani - Can you provide any insight or techniques for getting rid of enums that are not in use?

**Comment by steve-a-jones** [comment]
Interesting..

So my current type has a required one-to-many with a particular enum like so..


```
enum Thing {
   FOO,
   BAR,
   BAZ
}

type Stuff {
   things: [Thing!]!
}
```

If a Stuff instance only has `things: ["FOO", "BAR"]` and I try to remove "BAZ" from `Thing` I get the following error:

`✖ The type "Stuff" has nodes and therefore the enum values associated with "things" can't be removed. Please provide a migrationValue.`

I can add enums to `Thing` just fine, but can never delete it.

Is this a noob mistake or a bug? I expect to evolve enums over time and understand that I cannot remove values that have active relationships.

Appreciate any insight!

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
