### ISSUE TITLE
Query to get Session/Subscriber count.

### ISSUE THREAD

**Issue by Plinpod** [graphcool/prisma#307]
It would be handy to be able to query and/or subscribe to a count of the currently active sessions with the backend or a count of the current subscribers to a particular table filter.

**Comment by kbrandwijk** [comment]
Some ideas to get the thought train going:
- Something like this on the server side (https://github.com/websockets/ws#how-to-detect-and-close-broken-connections), to deal with both 'normal' closes and disconnections
- Minimum functionality: a simple query that returns the count `getWebsocketConnections { count }`
- Preferably create hooks so we can attach our own functionality (`onConnect`, `onClose`, `onDisconnect`).
- Preferably allow passing some metadata to the websocket connection so we can use this for grouping connections in our own function hooks, or use that to filter the query: `getWebsocketConnection(filter: { metadata_contains: 'room=MyRoom' }) { count }`
- Alternative: update some `User` field with the supplied metadata and a timestamp, but that wouldn't work for unauthenticated connections.

**Comment by kbrandwijk** [comment]
A current workaround would be:
- Use the `onConnect` and `onDisconnect` events on the `SubscriptionClient` to execute some mutation
- Use a cron job to cleanup disconnected session for which a `onDisconnect` event didn't fire (browser closes, terminated connections, etc.)
- Use a middleware function on the client to fire a update mutation for a `lastActive` field on every query as a sort of 'keepAlive'

**Comment by Plinpod** [comment]
In Socket.IO 1.4+ you can get this count like this
var room = io.sockets.adapter.rooms['my_room'];
room.length;

and I was hoping to replicate a similar functionality. It would allow for the most accurate client count.

**Comment by marktani** [comment]
Related to https://github.com/graphcool/graphcool/issues/126

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
