### ISSUE TITLE
Extend websockets to full Websocket support by enabling queries and mutations over wss

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#310]
Right now, only subscriptions are supported over wss. It would be helpful for a number of use cases to have support for queries and mutations over wss. It's supported by the latest Apollo Subscription Client (https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport).

**Comment by eliezedeck** [comment]
I'm really looking forward for this feature...

Surely I'm not aware of all the details involved in making this happen, but I guess it shouldn't be too hard to make this happen.

I've been waiting for this like for **several months** now, been waiting secretly on the emails to inform me of this thing being implemented. Sadly, it hasn't happened yet. Hopefully it will happen soon though. I know this probably isn't a priority for you guys, but for countries like mine (Madagascar), the reliability this provides is huge.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
