### ISSUE TITLE
Include permission check for empty result set

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#314]
When querying a Type that has no nodes (or a filter has no results), an empty array is returned, even if the user has no READ permissions. From a pentest perspective, knowing there are no nodes is also a security leak (not for most Types, but for some use cases, especially with filters).
This is probably a big one to change, as current permission checking is on a per-node basis.

First query:
```graphql
query
{
  allUsers{ id }
}
```
Throws: insufficient permissions, so I know nothing

Second query:
```graphql
query
{
  allUsers(filter:{ secret_starts_with: "a"}){ id}
}
```
Gives:
```graphql
{
  "data": {
    "allUsers": []
  }
}
```
So I now know there are no users with a secret starting with 'a'. I could continue this line of querying to find by elimination (for example, if secret="c", and I get an empty array for a,b,d...z, and insufficient permissions for 'c', I have found it by elimination without any read permissions)

I would also like to get an 'Insufficient Permissions' error when no nodes are present.

**Comment by sorenbs** [comment]
The way I am currently thinking about this issue is that we should enable normal permissions on fields on the top-level `Query` type. Would that be sufficient for you?

**Comment by kbrandwijk** [comment]
That would mean you get an extra Type on the permissions page 'Query', where you have all possible queries as fields right?
![image](https://user-images.githubusercontent.com/852069/28418937-d47aa980-6d5d-11e7-9cf3-a8473e5825a9.png)
If so, it only makes sense for `READ` permission, but for the rest it seems technically the most straightforward solution, in line with GraphQL architecture. But it's a very technical approach.

From a user perspective, an extra Permission type `QUERY` (next to C,R,U,D) that always applies to whole Type, is maybe more like the current UI, and requires less understanding about GraphQL architecture.
![image](https://user-images.githubusercontent.com/852069/28419181-86160ba8-6d5e-11e7-8afc-0274e483dad6.png)
![image](https://user-images.githubusercontent.com/852069/28419231-a5880c98-6d5e-11e7-80a9-5a523d7976b3.png)

**Comment by marktani** [comment]
But the former approach allows for a distinction between `Post` and `allPosts` for example, which would cover #208 as well.

**Comment by kbrandwijk** [comment]
Please keep the basics of the permission system in mind: it's a whitelisting system, so introducing this also means creating a default permission with all possible queries selected. Which is a bit of an administrative mess, because restricting one means opening that permission, with possibly 100's of selected queries, finding and deselecting one, and the creating a seperate permission for it...
Maybe it's best to create a composite approach, with the 'Query' permission type in the first step like I suggested above, but combined with the `Post` and `allPosts` in the 'select affected fields' step. This would make administration a lot easier. You still get the benefit @marktani describes, but without having all the queries (singular+plural) of your schema in one permission.
![image](https://user-images.githubusercontent.com/852069/28432074-dc72883c-6d86-11e7-8bc2-19e72e867d3c.png)
Notice I also took the liberty to show how another FR fits in here, which is schema extensions on existing Types.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
