### ISSUE TITLE
Support authorization middleware for WSS connections

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#317]
`subscription-transport-ws` uses a middleware concept for new connection parameters without requiring the client to be restarted. [Here's an example of how that works](https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-316376468).

Currently, Graphcool subscriptions only support sending the token when initializing the WS client, but should support the middleware approach as well.

A current workaround for setting the `Authorization` token after the app has been loaded is to persist the token after login into local storage or similar, and then reload the website.

**Comment by agborkowski** [comment]
in auth case @marktani and extend JWT WebSocket security level we should remember about refresh token challange to keep state Autohorized
```js
    applyMiddleware(operationOptions, next) {
     [if not expired]
      operationOptions["Authorization"] = returnJWT();
    [else]
      operationOptions["Authorization"] = returnJWTChalange(operationOptions["RefreshToken"])
   [end]
      next();
    }
  }
]);
```

still im @WIP on it

**Comment by abhitheawesomecoder** [comment]
Firefox can’t establish a connection to the server at wss://subscriptions.graph.cool/v1/cj8sfq2vs004c0170pcnymyo7.  
The connection to wss://subscriptions.graph.cool/v1/cj8sfq2vs004c0170pcnymyo7 was interrupted while the page was loading.

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by cipriancaba** [comment]
@marktani Is there any way at the moment to send Authorization token to Graphcool? If yes, please provide a working example for react-native.. Thank you

**Comment by cipriancaba** [comment]
Well, yes, but that's like 90% of the use cases.. it seldom you have the token when you initialize the client.. 

Sorry if I sounded angry yesterday but I lost my mind trying to configure the websockets permissions even with the example above and settings everything to public.. I ended up creating a new project from scratch to make it work

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
