### ISSUE TITLE
Define permissions for resolver functions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#324]
Currently, there's no way to define permissions for resolver function queries and mutations.

**Comment by marktani** [comment]
How should that look like in your opinion? The `EVERYONE` and `AUTHENTICATED` permissions would be straight-forward, but how about permission queries?

I'd like to brainstorm about possible PQs and what variables would be needed as a result 🙂 
`$user_id` makes a lot of sense here, what do you think about having access to the scalar input values a well?

**Comment by kbrandwijk** [comment]
I already took the first part into consideration when I came up with [this](https://github.com/graphcool/feature-requests/issues/314#issuecomment-316784869). So this fits in there nicely.

Regarding fields, yes I think that it would be the most consistent behavior if input values are available to the PQ.

**Comment by danielrasmuson** [comment]
What about using the same query syntax as check in order to call the function.

I.E.

```
- operation: MyFunctionName
  authenticated: true
  query: ./should-call-my-func.graphql
```

And if that query passes the function will be invoked.

**Comment by mikhailvs** [comment]
This feature would be helpful to have.

**Comment by donedgardo** [comment]
+1

**Comment by LFP6** [comment]
FWIW this is how permissions are supposed to be handled in Prisma at this point: https://www.prismagraphql.com/docs/tutorials/graphql-server-development/permissions-thohp1zaih is there still a reason to have a separate mechanism for defining permissions?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
