### ISSUE TITLE
Request Pipeline functions that trigger on relationships being connected / disconnected

### ISSUE THREAD

**Issue by danmkent** [graphcool/prisma#327]
It would be useful to be able to hook in functions to the addTo... and removeFrom... mutations that are used to connect and disconnect relationships.

I would expect these functions to be triggered by direct use of these mutations and when a relationships is connected or disconnected through a nested mutation

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
