### ISSUE TITLE
File type recognition for markdown files

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#330]
The official mime-type for markdown files (since March 2016) is `text/markdown` (https://tools.ietf.org/html/rfc7763). Yet, the File API doesn't recognize it, and uses `application/octet-stream`. Please parse `contentType` for markdown files as `text/markdown`. Also, charset is required according to the RFC, so it might have to be `text/markdown; charset=UTF-8`

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
