### ISSUE TITLE
Add 'generate auth token' option to data browser and enable using token in Playground

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#335]
As the `generateAuthToken` functionality of `graphcool-lib` is no longer necessarily linked to the `User` Type, the 'Select User' functionality in the Playground is no longer sufficient.

I would propose adding a button to the databrowser to generate an auth token for any node on any Type. Also, I would propose adding functionality to the Playground to paste in any token (possibly automatically set upon generation of a token in the data browser for UX bonus points), instead of selecting a user. Right now, I'm using a browser add-on to set the authorization header (e.g. to run queries in the Playground with any token I like), but it would be great if this functionality was available in the Playground directly.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
