### ISSUE TITLE
Database Events and an Admin API

### ISSUE THREAD

**Issue by nigeltiany** [graphcool/prisma#339]
Some integrations are really up to the developer and their imagination. It is almost impossible to create integrations for every service out there and maintain the many code bases. 

An admin API would allow developers to write functions that act like hooks to database events and the possibilities would be almost endless.

Some examples and syntax

```js
import graph_cool_admin from 'graph-cool-admin'

graph_cool_admin.schema('Post').on('node-added', 'comments', (node) => {
     // publish that the post has been updated to subscribed clients
     // Or import a messaging service api and send a message to e.g. slack that a comment was added
})

graph_cool_admin.listen({ 
  Post {
    comments
  }
}).on('node-added', (node) => {

})

graph_cool_admin.schema('comment').on('update', (node) => {
      node.post.id.// publish post update to subscribed clients
})
```
```js
graph_cool_admin.schema('User').on('create',  (node) => {
     // send a confirmation email to node.data.email
})
```

**Comment by nigeltiany** [comment]
#146

**Comment by pcooney10** [comment]
This would be awesome

**Comment by marktani** [comment]
How is this different from [server-side subscriptions](https://www.graph.cool/docs/reference/functions/server-side-subscriptions-ahlohd8ohn/)?

**Comment by marktani** [comment]
Closing this as sufficiently covered by sss. Please open a new issue if you have more thougths on this.
