### ISSUE TITLE
Support routing for default WSS endpoint

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#346]
For all APIs apart from the WSS endpoint, the default endpoint can be used across regions. However, for subscriptions, the region specific endpoint has to be used:

* default: `wss://subscriptions.graph.cool/v1/__PROJECT_ID__`
* AP: `wss://subscriptions.ap-northeast-1.graph.cool/v1/cislqwo6e039e01171nzb9mxw`
* US: `wss://subscriptions.us-west-2.graph.cool/v1/cislqwo6e039e01171nzb9mxw`

It should be possible for all regions to use the default endpoint.

**Comment by sorenbs** [comment]
We don't want to proxy websocket connections as they have to stay open for an extended period of time. Rather, we should redirect to the correct region. Some ws implementations are known to not follow redirects, so we should verify that this works with Apollo in most cases.

See for example https://github.com/websockets/ws/issues/812

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
