### ISSUE TITLE
Auto-generate Url field for File relation to support automatic file uploads

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#351]
Just like for every relation, there's also an `myRelationId` field generated that you can use in mutations, it would be nice if the backend could also auto-generate a `myRelationUrl` field, when I add a relation to the `File` type. When using this Url field, the behavior would be similar to the `...Id` field, which automatically sets the relationship, but it would also automatically upload the file from the Url.

## Example partial schema:
```graphql
type Post implements Node {
  ...
  image: File @relation(name: "PostImage")
}
```

## Example mutation:
```graphql
mutation {
   createPost(imageUrl: 'https://someDomain.com/image.gif') {
      id
      image {
         id
         url
         ...
      }
   }
}
```

Inspired by: https://github.com/graphcool-examples/node-remote-file-upload

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
