### ISSUE TITLE
Redact root tokens in function logs and errors

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#352]
Instead of returning the whole root token, we could return the last 10 characters, for example.

**Comment by kbrandwijk** [comment]
Or the name of the PAT?

**Comment by sorenbs** [comment]
I like injecting the name of the rootToken. How about this syntax:

`[redacted rootToken: rootTokenName]`

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
