### ISSUE TITLE
HTTP Webhook as Function Type/Trigger

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#354]
allow Graphcool Functions that would be triggered by HTTP requests.

**Comment by albert-tse** [comment]
Thanks @marktani It would be really nice to have this

**Comment by kbrandwijk** [comment]
So basically, built-in webtask.io?

**Comment by kbrandwijk** [comment]
As function exexution has now moved to AWS, and the project file has matured a lot, I think the steps to achieve this now are minimal.

I would propose adding another function type to the project definition, something like endpoint or something (needs a better term). Those functions would be available directly through https://api.graph.cool/simple/v1/c......./functionName. They probably also need a HTTP method (get/post).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
