### ISSUE TITLE
Offer more data formats for export in Playground 

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#358]
* CSV
* custom transform function
* ...

**Comment by danmkent** [comment]
I have to admit, I don't see this as a big priority compared to many of the other feature requests here.

There are plenty of methods to transfer data to any required format once it has been exported.

**Comment by kbrandwijk** [comment]
@danmkent I have to agree, as someone with currently 140 open issues across the repo's, that this shouldn't have the highest priority. However, `stage/waiting` means discussion is over, and it's clear what needs to be done. It's not `stage/wip` yet, so this status actually doesn't tell you anything about priorities...

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
