### ISSUE TITLE
Internal server error when too big file is uploaded

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#367]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Apr 17, 2017 at 14:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/44_

----

**Comment by schickling** [comment]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sorenbs](https://github.com/sorenbs)**
_Friday Apr 21, 2017 at 21:48 GMT_

----

Please note that we updated the file limit to 200 mb.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
