### ISSUE TITLE
Function does not affect payload response for fields with a defaultValue

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#368]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday May 23, 2017 at 12:42 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/68_

----

This function should flip the `isPaid` boolean - it works in test run, but not with an actual mutation

```js
module.exports = function (event, cb) {
  event.data.isPaid = !event.data.isPaid
  return {event}
}
```

This is the mutation:

```
 mutation ($id: ID!, $description: String!, $amount: Float!, $plan: PURCHASE_PLAN!, $stripeId: String!, $stripeToken: String!) {
    createPurchase(
      description: $description
      userId: $id
      amount: $amount
      plan: $plan
      stripeToken: $stripeToken
      stripeId: $stripeId
      ) 
      {
        id
        description
        amount
        plan
        isPaid
      }
  }
```

Note that `isPaid` is not part of the actual mutation in put, but the field has a default value of `false` - that's not correctly handled for the different function inputs.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Jul 17, 2017 at 09:32 GMT_

----

This basically comes down to **'defaultValue for fields set _after_ RP'**. This is because there are two symptoms:
1. fields with a defaultValue that are not part of the mutation don't have that defaultValue set in RP
2. setting the value of a field with a defaultValue in an RP will not be persisted (because overwritten after the RP by the defaultValue)

**Comment by marktani** [comment]
I think the default value should be available to the `operationBefore` step (formerly called `TRANSFORM_ARGUMEN`), in case that field was not part of the mutation input.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
