### ISSUE TITLE
Function returned an unhandled error, invocation is not stored to logs

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#369]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday May 24, 2017 at 12:11 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/73_

----

That's the function:

```js
require('isomorphic-fetch')

use strict;
module.exports = function (event, cb) {
  const endpoint = 'https://api.graph.cool/simple/v1/__PROJECT_ID__'
  const token = 'Bearer __PAT__'

  const companyId = event.data.id
  console.log(event.data)
  
  const query = `query {
	Company(id: "${comapnyId}" {
	  open
	}
  }`
  
  return fetch(endpoint, {
    method: 'post',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': token
    },
    body: JSON.stringify({ query })
  }).then((response) => {
      return response.json()
  }).then((data) => {
    console.log(data)
    console.log('Response ' + JSON.stringify(data))
    cb(null, 'success')
  })

  
  
  return {data: event.data}
}

```

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday May 24, 2017 at 14:04 GMT_

----

Even though there are many syntax errors in the function I posted, removing `use strict;` fixed the problem.

**Comment by sorenbs** [comment]
@marktani Is the issue that the function failed the compile step?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
