### ISSUE TITLE
Allow integration with Auth0 rules and createUser

### ISSUE THREAD

**Issue by mypark** [graphcool/prisma#37]
To make auth0 user integration simpler, allow an insert into createUser by auth0 userId rather than an auth0 token.  This could be restricted to admin roles.

Auth0 has a server side rule trigger than can post user data and userId to an http endpoint on user registration.  Unfortunately, it doesn't have a userId token that it can pass along to the graphcool endpoint.

This would make auth0 integration pretty simple.

**Comment by marktani** [comment]
Thanks for the report, I am adding a bit of information for further potential work on this issue.

https://auth0.com/docs/rules

http://stackoverflow.com/questions/40657935/can-i-get-an-idtoken-from-an-auth0-rule/40658783#40658783

As discussed in Slack, a mutation callback that uses the `auth0Id` of the user and the Auth0 api is probably the best approach to set additional information of the user right now.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
