### ISSUE TITLE
SSS: function logs are accumulative for concurrent function invocations

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#370]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Saturday May 27, 2017 at 14:43 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/81_

----

Let's say we log an integer in a SSS.

```js
module.exports = function(event) {
  console.log(event.data.Type.node.int)
}
```

If we quickly trigger it twice:

```graphql
mutation {
  updateType(id: "some-id", int: 1) {
    id
  }
}

# later:
mutation {
  updateType(id: "another-id", int: 2) {
    id
  }
}
```

The log for the first invocation will be 

```
[1]
```

The log for the second invocation will be

```
[1, 2]
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
