### ISSUE TITLE
Errors returned in promises are not logged in test run

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#371]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday May 30, 2017 at 11:49 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/85_

----

```js
const stripe = require('stripe')('some-test-key')

module.exports = function (event) {
  const coupon = event.data
  return new Promise(function(resolve, reject) {
    return stripe.coupons.retrieve(
      coupon.key,
      function(err, response) {
        if (err) {
          console.log('wrong coupon code')
          resolve({error: 'wrong coupon code'})
        } else {
          console.log('right coupon code')
          console.log(response)
          resolve(event)
        }
      }
    )
  })
}
```

`resolve({error: 'wrong coupon code'})` is never shown in the error logs in test run. triggering the function with a mutation logs the error correctly.

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Friday Jun 16, 2017 at 16:13 GMT_

----

➤ Nilan Marktanner commented:

Try to reproduce.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Jun 17, 2017 at 12:56 GMT_

----

Executing this function in test run:

```js
module.exports = function (event) {
  return new Promise(function(resolve, reject) {
    resolve({error: 'wrong coupon code'})
  })
}
```


Response:

```json
{
  "timestamp": "2017-06-17T12:55:04.648Z",
  "isError": false,
  "duration": 210,
  "inline": {
    "event": "{\n  \"data\": {\n    \"Post\": {\n      \"updatedFields\": [\n        \"updatedAt\"\n      ],\n      \"node\": {\n        \"id\": \"cj41ab8mg00033k5wnlk2hg47\"\n      }\n    }\n  }\n}",
    "logs": [
      
    ]
  }
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
