### ISSUE TITLE
Mutation fails when input field is not specified that is part of a permission query

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#372]
<a href="https://github.com/Jesus-Gonzalez"><img src="https://avatars1.githubusercontent.com/u/10809429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jesus-Gonzalez](https://github.com/Jesus-Gonzalez)**
_Wednesday May 31, 2017 at 17:00 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/89_

----

Hello,
I have just experienced an issue in the playground.

When I execute a mutation that has not been pushed enough parameters, it will fail once executed.

Thanks,
Jesús

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday May 31, 2017 at 17:46 GMT_

----

thanks for reporting that issue @Jesus-Gonzalez 🙏 

This happens when a permission query uses a relational input id like `$input_groupId` and the mutation looks like this:

```graphql
mutation {
  createItem(name: "Hello") {
    id
  }
}
```

It works when passing a `groupId`:

```graphql
mutation {
  createItem(name: "Hello" groupId: "some-id") {
    id
  }
}
```

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Jun 16, 2017 at 16:15 GMT_

----

The intended behaviour is that fields that are not specified in the mutation itself should be assumed to be `null` instead. We're looking to correct this behaviour soon!

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
