### ISSUE TITLE
Return meaningful error when FormData does not have expected shape

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#373]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jun 08, 2017 at 13:20 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/95_

----

The expected shape for `FormData` is this:

```
let formData = new FormData()
const data = {
  uri: profileImage.uri,
  name: 'hello.jpg',
  type: 'image/jpeg',
}
```

If the uploaded `FormData` does not follow that shape, for example when using `react-native-image-picker`, the API returns an internal server error:

![pasted image at 2017_06_08 09_12 am](https://user-images.githubusercontent.com/1780597/26930459-c61ab7c0-4c5d-11e7-9e22-0e9e02e1e43e.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
