### ISSUE TITLE
Unable to do a nested mutation when object has only system fields and a one-to-many relation

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#374]
<a href="https://github.com/Makazone"><img src="https://avatars3.githubusercontent.com/u/996769?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Makazone](https://github.com/Makazone)**
_Thursday Jun 08, 2017 at 18:23 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/97_

----

Given the following schema consisting of a User and a Post connected by a one-to-many relation:
```
type Author implements Node {
  name: String!
  posts: [Post!]! @relation(name: "AuthorOnPost")
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}

type Post implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  author: Author @relation(name: "AuthorOnPost")
}
```
It is impossible to run a nested create mutation:
```
mutation A {
  createAuthor(input: {
    name: "author 1",
    posts: [ {    } ],
    clientMutationId: "abc"
  }) {
    author {
      id
    }
  }
}
```
because `CreateAuthorInput` has `postsIds: [ID!]` but no `posts: [AuthorpostsPost!]`. So it's possible to create an author only by providing an array of post ids, but not by nesting new posts. However, once I added a custom field (or another relation):
```
type Post implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  author: Author @relation(name: "AuthorOnPost")
  title: String!
}
```
it became possible to run a nested mutation, because `CreateAuthorInput ` now has `posts: [AuthorpostsPost!]`:
```
mutation B {
  createAuthor(input: {
    name: "author 1",
    posts: [ {title: "hello world"} ],
    clientMutationId: "abc"
  }) {
    author {
      id
    }
  }
}
```

I stumbled upon this in a more unfortunate situation though. I had a _Post_ object with custom fields, so everything should have worked, however, my graphql schema still didn't have `posts: [AuthorpostsPost!]` inside `CreateAuthorInput `, so I wasn't able to create an author and posts with a single mutation. I ended up removing _Post_ completely and creating it from scratch incrementally adding fields. Thankfully I was just in the beginning of a project so no data was stored.

I can't reproduce my first scenario.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
