### ISSUE TITLE
Update permission query shows system fields as input variables

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#375]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Jun 09, 2017 at 10:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/99_

----

When writing a permission query, the console shows system fields like $input_updatedAt, although these fields cannot be part of the input.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Jun 16, 2017 at 16:34 GMT_

----

We should remove `$input_updatedAt`, `$input_createdAt` and `$input_id` and make them available as `$node_x` instead, where it makes sense.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
