### ISSUE TITLE
TRANSFORM_ARGUMENT functions are executed after PQs

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#376]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday Jun 09, 2017 at 19:37 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/100_

----

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Jun 09, 2017 at 19:40 GMT_

----

Documentation on event hooks says transform_argument fires before permission API.

**Steps to reproduce:**
- Create a Type with an integer field
- Create a node with that field set to **1**
- Create a transform_argument event hook on update that sets that field to, for example **5**
- Create a PQ on update that checks if that field equals **5**
- Create an update mutation that sets the field to **3**

**Expected behavior**: transform_argument fires first, changing the value to 5, after that, PQ should pass.
**Actual behavior**: PQ fails

**Conclusion**: PQ fires first...

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Jun 14, 2017 at 14:03 GMT_

----

Can you show the exact PQ you use? I'm afraid it does not do what you expect.
I used this PQ:

```graphql
query ($node_id: ID!) {
  SomePostExists(
    filter:  {
      id: $node_id
      int: 3
    }
  )
}
```

with the following behaviour: https://youtu.be/W4UygcqHduk
You'll notice that when I create the `Post` node with `int: 2`, the `updatePost` mutation doesn't work. However, when I create the `Post` node with `int: 3`, then `updatePost` works.

You can try it yourself with changing 

> Create a node with that field set to 1

to 

> Create a node with that field set to 5

in your step by step list. Then updating the node once should work, updating it again won't work anymore.

This is the intended behaviour of PQs 🙂

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 15, 2017 at 07:58 GMT_

----

It seems like you entirely skipped the part about transform_argument. What you're showing, is just the permission query.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 15, 2017 at 09:32 GMT_

----

With the permission query I'm using, the `TRANSFORM_ARGUMENT` function I used does not affect the outcome of the PQ, so I skipped it in my descriptions above:

```js
module.exports = function (event) {
  event.data.int = 3
  return {data: event.data}
}
```

That's because the `TRANSFORM_ARGUMENT` function affects the input arguments and not the node data itself, while the PQ runs against the node data itself.

Do your PQ or function differ notably from mine?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 15, 2017 at 09:39 GMT_

----

If you set the int field to '3' in the transform_argument, and then check for '3' in your PQ, that should always pass, right?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 15, 2017 at 09:40 GMT_

----

No - the PQ above checks the following condition:

> does the node that is being updated have the value `int: 3`?

and not:

> is the node about to be updated so that it will have the value `int: 3` afterwards.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 15, 2017 at 09:45 GMT_

----

I see the difference now. My PQ used $input_int. Which value should that have according to you?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 15, 2017 at 09:48 GMT_

----

Was that the only difference you had? 🙂 Then your PQ would say

> Only allow the node to be updated if the input and the current data for `int` is the same

If you want to enforce something like

> Only allow the update mutation if the input value for `int` is 3

then you could check that in the function itself. Right now, PQ do not cover this use case easily (there's a weird workaround: create a type with an integer field, create a node with the value 3 and check if the input equals that node's integer value 🙂)

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 15, 2017 at 10:07 GMT_

----

My point was, that the `$input_int` field of the PQ has the value of the original mutation, not the value that was updated in the function hook. That means the PQ runs on untransformed data, even though the docs state that PQ run _after_ the event hooks.

Real-world use case: I get a record from the database, with a version integer. I update the object locally, and send an update mutation. The `transform_argument` hook would increment the version number _first_, then the PQ runs to check if the version number of that record in the database is lower than that of the record that I am about to persist.

The subsequent observation when testing this was, that the `$input` field on my PQ still contained my original value, and _not_ the value that I incremented in my transform_argument function. Given that the docs say that `transform_argument` runs _before_ the PQ, I would expect the `$input` variables of the PQ to contain the values that are the result of `transform_argument`.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 15, 2017 at 10:13 GMT_

----

Got it! Let me try to reproduce

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 15, 2017 at 10:56 GMT_

----

I could verify your assumption. PQ:

```graphql
query ($node_id: ID!, $input_int: Int!) {
  SomePostExists(
    filter:  {
      id: $node_id
      int: $input_int
    }
  )
}
```

`TRANSFORM_ARGUMENT` for `Post is updated`:

```js
module.exports = function (event) {
  event.data.int = 3
  return {data: event.data}
}
```

Mutations:

```graphql
mutation create {
  createPost(int: 3) {
    id
    int
  }
}

mutation works {
  updatePost(id: "ID_FROM_ABOVE" int: 3) {
    id
    int
  }
}

mutation doesntwork {
  updatePost(id: "ID_FROM_ABOVE" int: 2) {
    id
    int
  }
}
```

Mutation `doesntwork` should work, but doesn't 😛 
Thanks so much for bearing with me and bringing this up! 🙌

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 15, 2017 at 11:03 GMT_

----

No problem, glad we got it sorted out now!

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jun 25, 2017 at 23:34 GMT_

----

Is this actually a bug, or desired functionality? When are PQ's supposed to run, before all RP, after transform_argument, before pre_write, after pre_write.

It's quite hard to determine how to proceed with this. The Console says `PRE_WRITE` is useful for calling external services like _charge a customer on stripe_. For stuff likes that, it makes a _big_ difference to know when the PQ is supposed to run. E.g. I'm not charging a customer before the PQ runs...

**Comment by kbrandwijk** [comment]
I'd like to revive this issue, as it's something that I regularly run into. What's the decision on this?

**Comment by marktani** [comment]
This is undesired behaviour which we will clean up in our efforts of streamlining the request pipeline.

**Comment by kbrandwijk** [comment]
Just a heads up before you do. This will be a breaking change. Make transition possible, by introducing a temporary switch between both behaviors, otherwise production apps _will_ break.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
