### ISSUE TITLE
Different HTTP status code for File and Image API for file not found

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#377]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Jun 09, 2017 at 21:19 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/101_

----

The Image API returns 502 Bad gateway when you try to request an image that does (no longer) exist. 
The File API returns 403 Forbidden when a file does (no longer) exist.

Please return a 404 in both cases.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Jun 16, 2017 at 16:38 GMT_

----

The issue with the Image API is tracked [here](https://github.com/graphcool/serverless-image-proxy/issues/5).

We should fix the File API to return 404 instead 👍

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
