### ISSUE TITLE
Cache miss with Graphcool files?

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#380]
<a href="https://github.com/sedubois"><img src="https://avatars1.githubusercontent.com/u/4217871?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sedubois](https://github.com/sedubois)**
_Saturday Jun 17, 2017 at 07:41 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/121_

----

**What is the current behavior?**

It looks like the cache isn't always hit when accessing files from https://files.graph.cool? This is probably more a question than a bug, I just don't understand why the first request is a cache miss.

Downloading https://files.graph.cool/cj1btogkaf14q010589c793ps/cj1m81p9j01f501030wyvrf8b using webpagetest.org (3 runs, first view only, from Australia):
- first try: miss, miss, miss
- second try: miss, miss, hit, miss (for some reason, it then started doing 4 requests)
- third try: miss, hit, hit, hit
- fourth try: miss, hit, hit, hit (screenshots are below)

**If the current behavior is a bug, please provide the steps to reproduce it.**

- Test this resource from webpagetest.org from Australia using default settings (3 runs, first view only): https://files.graph.cool/cj1btogkaf14q010589c793ps/cj1m81p9j01f501030wyvrf8b
- go to Details page and expand the request headers at the bottom
- check `X-Cache` headers
- repeat several times

**What is the expected behavior?**

I'm not very familiar with performance testing, but I was supposing that such a test should result in `X-Cache: Hit from cloudfront` every time? Below are the HTTP headers (skipping the one for favicon.ico). Does this have something to do with the fact that the file is a video and it's something about streaming?

<img width="894" alt="screen shot 2017-06-17 at 10 57 26" src="https://user-images.githubusercontent.com/4217871/27251296-a895fc00-534c-11e7-802d-640bc58073f4.png">
<img width="892" alt="screen shot 2017-06-17 at 10 58 33" src="https://user-images.githubusercontent.com/4217871/27251299-a8975a6e-534c-11e7-8d85-41ab9306c372.png">
<img width="887" alt="screen shot 2017-06-17 at 11 00 57" src="https://user-images.githubusercontent.com/4217871/27251298-a896e566-534c-11e7-8989-08979dde2a8a.png">
<img width="888" alt="screen shot 2017-06-17 at 11 01 08" src="https://user-images.githubusercontent.com/4217871/27251297-a896d7b0-534c-11e7-81de-f32ed7f06e58.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
