### ISSUE TITLE
Inconsisteny in File API 'endpoints'

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#381]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Jun 17, 2017 at 16:34 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/122_

----

**What is the current behavior?**
The upload endpoint for the File API uses your project alias, the generated download URL does not. It contains the original project cuid.

**If the current behavior is a bug, please provide the steps to reproduce it.**
Set a project alias, upload a file using the File API endpoint, see the generated URL.

**What is the expected behavior?**
It would be more consistent, if the download URL also used the project alias.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
