### ISSUE TITLE
SSS does not detect updatedFields if they're updated during the request pipeline

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#383]
<a href="https://github.com/CameronK"><img src="https://avatars2.githubusercontent.com/u/424892?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [CameronK](https://github.com/CameronK)**
_Monday Jun 19, 2017 at 23:00 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/128_

----

**What is the current behavior?**
- Create a type with an optional field
- Use a `TRANSFORM_ARGUMENT` request pipeline function to calculate the property on the server-side
- Create a SSS for create, update, and delete on the above type
- Send a mutation to the server

Inside the `updatedFields` property sent to the SSS, only properties passed in the original mutation are shown. The calculated property is not in the array.

**If applicable, share the query, mutation or subscription for reproduction**
(see schema below)
```
mutation($input: UpdateReminderInput!) {
        updateReminder(input: $input) {
            reminder {
               id
               interval # send this in mutation
               customProp # calculated by server
               createdAt
            }
        }
    }
```
```
[UpdateReminderInput mutation variables]
{ input: { id: "whatever", interval: 3 } } 
```
```
[TRANSFORM_ARGUMENT function]
module.exports = function (event) {
  return {
     data: Object.assign({}, event.data, {
         customProp: event.data.interval * 3 // example of something calculated server-side
     })
  };
}
```

**If relevant, share the relevant part of your GraphQL schema for reproduction**
```
type Reminder implements Node {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  customProp: Int
  interval: Int!
}
```
**What is the expected behavior?**
Even though the property was updated on the server-side, I would still expect it to be piped to the SSS as an updatedField.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jun 22, 2017 at 08:55 GMT_

----

Thanks for this detailed bug report, I can confirm this current behaviour :+1:

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
