### ISSUE TITLE
updating a non-existing node results in internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#384]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday Jun 20, 2017 at 11:48 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/130_

----

**What is the current behavior?**

```graphql
mutation removeImagesFromMemory($memoryID: ID!) {
  updateMemory(id: $memoryID, images: []) {
    id
    images {
      id
      __typename
    }
    __typename
  }
}
```

```json
	
{
  "memoryID": "cj3vkdvm2qbch0155ff32vhyw"
}
```

https://app.bugsnag.com/graphcool/prod/errors/594847f2ea7d7e00189f0ac4?filters%5Bevent.since%5D%5B%5D=3h&filters%5Berror.status%5D%5B%5D=open

**Comment by marktani** [comment]
As far as I know, this is now fixed.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
