### ISSUE TITLE
Permissions and relational input fields behave inconsistent

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#385]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Jun 21, 2017 at 10:27 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/132_

----

**What is the current behavior?**

Let's consider this schema

```graphql
type Post {
  id: ID!
  title: String!
  author: User! @relation(name: "UserOnPost")
}

type User {
  id: ID!
  name: String!
  posts: [Post!]! @relation(name: "UserOnPost")
}
```

No matter what your `CONNECT/DISCONNECT` permission setup is for `UserOnPost`, you can't make this mutation to work:

```graphql
updatePost(id: "post-id" authorId: "author-id") {
  id
}
```

The only way to make that work is to enable `Apply to whole Type` on the `update Post` permission which oftentimes is not desired.

However, this works:

```graphql
updatePost(id: "post-id" authorId: "author-id" title: "Same title") {
  id
}
```

when the only activated field for the `update Post` permission is `title`.

**What is the expected behavior?**

Either, `authorId` should be selectable on the `update Post` permission, or the `CONNECT/DISCONNECT` permission should be applied even when `authorId` is the only field in the `updatePost` mutation.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
