### ISSUE TITLE
For SSS webhooks, the function logs is not accurate for responses with non-ok status code

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#386]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jun 22, 2017 at 09:37 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/134_

----

**What is the current behavior?**

When a SSS webhook returns a status code other than `200`, the function still appears as a successful execution in the function log. Furthermore, the `returnValue` will be `{}`, so there's no way to inspect what happened.

**What is the expected behavior?**

The `statusCode` could be included for example.

**Comment by sorenbs** [comment]
@dpetrick you looked into this recently - do you know if this is still an issue?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
