### ISSUE TITLE
Support emojis in function code

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#391]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Sunday Jun 25, 2017 at 14:48 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/145_

----

**What is the current behavior?**

Trying to create or update a function containing an emoji results in an internal server error.

**What is the expected behavior?**

It does not result in an internal server error.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
