### ISSUE TITLE
Description not persisted for permission queries

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#393]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jun 25, 2017 at 20:22 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/147_

----

**What is the current behavior?**
If you try to update the description of a permission query, that description is not persisted

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
![image](https://user-images.githubusercontent.com/852069/27519462-a8dfd5c4-59f4-11e7-89de-b08c1de96fe9.png)
![image](https://user-images.githubusercontent.com/852069/27519467-bd79ebe6-59f4-11e7-9f3a-edfee96bb053.png)

**What is the expected behavior?**
Description is persisted

This is a blocking issue for my use-case (I need that description)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
