### ISSUE TITLE
Nested meta queries break for required relations with data

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#396]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Jun 29, 2017 at 16:36 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/157_

----

**What is the current behavior?**

Using a nested meta query breaks for required relations with data.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  links: [Link!]! @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "UsersVotes")
}

type Link implements Node {
  createdAt: DateTime!
  description: String!
  id: ID! @isUnique
  updatedAt: DateTime!
  url: String!
  postedBy: User @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "VotesOnLink")
}

type Vote implements Node {
  user: User! @relation(name: "UsersVotes")
  link: Link! @relation(name: "VotesOnLink")
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

**If applicable, share the query, mutation or subscription for reproduction**

First, run

```graphql
mutation d {
  createUser(votes: [{
    link: {
      description: ""
      url: ""
    }
  }]) {
    id
  }
}
```

Then

```graphql
query c {
  allVotes {
    link {
      _votesMeta {
        count
      }
    }
  }
}
```
results in an internal server error.

Interestingly, this works as expected:

```graphql
query a {
  allLinks {
    _votesMeta {
      count
    }
  }
}
```

Changing `link: Link! @relation(name: "VotesOnLink")` to `link: Link @relation(name: "VotesOnLink")` makes the query work as expected.

**What is the expected behavior?**

The meta query resolves the count.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
