### ISSUE TITLE
Connect permission is not correctly applied for nested connect mutations

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#398]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Jul 03, 2017 at 15:06 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/161_

----

**What is the current behavior?**

A connect permission does not grant expected rights for a nested connect mutation.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type Sale implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  store: Store! @relation(name: "SaleOnStore")
  updatedAt: DateTime!
}

type Store implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  sales: [Sale!]! @relation(name: "SaleOnStore")
  updatedAt: DateTime!
}
```

All type permissions are open to `EVERYONE`, and there is a `CONNECT SaleOnStore` permission for `AUTHENTICATED` users with this query:

```graphql
query ($salesSale_id: ID!) {
  SomeSaleExists(filter: {
    id: $salesSale_id
    store: null
  })
}
```

This permission query expresses, that a sale can only be connected if it doesn't have a connected store yet.

**If applicable, share the query, mutation or subscription for reproduction**

First, create a new store **and copy its id**:

```graphql
mutation {
  createStore(name: "Store") {
    id # Copy this ID!
  }
}
```

Then run this mutation as an authenticated user:

```graphql
mutation{
  createSale(
    name: "T1"
    storeId: "<id from above>"
  ){
    id
  }
}
```

You will receive an error:

```json
{
  "data": {
    "createSale": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createSale"
      ],
      "code": 3008,
      "message": "No CONNECT permissions",
      "requestId": "cj4o9qt4qamxo0177xap1j41s"
    }
  ]
}
```

**What is the expected behavior?**

The last mutation should work without a permission error.

**Comment by schickling** [comment]
<a href="https://github.com/danmkent"><img src="https://avatars2.githubusercontent.com/u/21933206?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danmkent](https://github.com/danmkent)**
_Monday Aug 21, 2017 at 13:22 GMT_

----

It looks like the problem lies in the permission for the nested connect mutation being checked before the object being created by the outer mutation is actually created.

I guess all the permissions are being checked before any data is written, which does make sense in some ways.

However, in this scenario the permission query for the nested connect mutation will likely rely on the existence of the thing being connected.

For example, even this very simple connect permission query will cause a create mutation with a nested connect mutation to fail:

`query ($postsPost_id: ID!) {
  SomePostExists(filter: {
    id: $postsPost_id
  })
}`

Presumably because at the point the permissions query is checked, the Post has not yet been created.

I would suggest that permissions for nested connect mutations are checked later in the processing order, when the object has been created and it about to actually be connected to things.

This would raise the question of what to do if the nested connect mutation failed. It may be necessary to roll back the outer mutation. For a create mutation that would be fairly easy - just delete the object.

I'm not sure if this would also affect update mutations, where rolling back would be more complex. My instinct is that it probably doesn't, as there is not the issue of the object not existing when the permission for the nested mutation is checked.

**Comment by sorenbs** [comment]
This is a general issue relating to permission queries for nested mutations.

In the future we will make it possible to decide if a permission query should run before or after the data transformation. We will still ensure that all permissions are successful before actually committing the changes

**Comment by divyenduz** [comment]
Is there a workaround for this one? I have a mutation that looks like this (removed extra fields for brevity). 
```
mutation M {
    createPost(
      postContents: [
        {
          title: "Post HC - EN"
          language: EN
        }
        {
          title: "Post HC - DE"
          language: DE
        }
      ]
    ) {
      id
    }
  }
```

and I think I am running into this one because a Post needs to be created before its PostContents in multiple languages. The schema looks like this (clipped for brevity). 

```
type Post @model {
  id: ID! @isUnique
  postContents: [PostContents!]! @relation(name: "PostOnPostContents")
}

type PostContents @model {
  id: ID! @isUnique
  relatedPost: Post! @relation(name: "PostOnPostContents")
  language: Languages!
  title: String!
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
