### ISSUE TITLE
Delete Subscription fires on types that don't match the filter

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#399]
<a href="https://github.com/TylerMizuyabu"><img src="https://avatars3.githubusercontent.com/u/7707888?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TylerMizuyabu](https://github.com/TylerMizuyabu)**
_Monday Jul 03, 2017 at 17:28 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/162_

----

**What is the current behavior?**
delete subscription is firing on the deletion of any node of the type its subscribed to, regardless of the node field in its filter

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```graphql
type TodoList implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  author: String!
  title: String!
  members: [User!]! @relation(name: "Memberships")
  todos: [Todo!]! @relation(name: "TodoListOnTodo")
}
```
All type permissions are open to everyone. This issue can also be completed with the default types such as User. 
**If applicable, share the query, mutation or subscription for reproduction**
```graphql
subscription {
  TodoList(filter:
  	{
      mutation_in:[DELETED],
      node:{
        id: "cj4k2arkqo1sr0134bizuz9vx"
      }
    }
  ){
    previousValues {
      id
      title
    }
  }
}
```
This also happens with other options for the node field in filter such as id_in, id_not_in, author, etc.

**What is the expected behavior?**
the delete subscription should only trigger when a node with the id in the filter is deleted.

**Comment by schickling** [comment]
<a href="https://github.com/TylerMizuyabu"><img src="https://avatars3.githubusercontent.com/u/7707888?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TylerMizuyabu](https://github.com/TylerMizuyabu)**
_Tuesday Jul 04, 2017 at 22:41 GMT_

----

Also this only happens with delete, if I switch the mutation_in field to use created and/or updated then the subscription works as intended. Probably should have explicitly said this in the issue, my bad.

**Comment by marktani** [comment]
I can still reproduce this:

![image](https://user-images.githubusercontent.com/1780597/30266014-4c3421fa-96de-11e7-94a8-f047869401c6.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
