### ISSUE TITLE
Data inconsistencies for nested mutations on self-relations with one field

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#401]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Jul 05, 2017 at 20:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/166_

----

**What is the current behavior?**
If I have a self-relation which consists of a single field, and I edit that field for one node in the data browser, that field is not set on the other node, like a two-field self relation does. Actually, the issue is related to the underlying mutation, that I included, that's why I filed it as an api-bug, and not console.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
Direct mutations on the connectionBetweenIds field of this type do not behave correctly:
```graphql
type Dummy implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  dummyName: String!
  connectionBetween: [Dummy!]! @relation(name: "ConnectionBetween")
}
``` 
The generated connection mutation (`addToConnectionBetween`) works as expected, updating the field on both sides.

**If applicable, share the query, mutation or subscription for reproduction**
This is the mutation generated by the data browser:
```graphql
mutation _ {
      updateDummy(
        input: {
          id: "cj4rg5ajs7u2p019780im0020"
          clientMutationId: "a"
          connectionBetweenIds: ["cj4rg5ajs7u2p019780im0020"]
        }
      ) {
        dummy {
          id
        }
      }
    }
``` 

**What is the expected behavior?**
The API should handle the mutation correctly, and set both sides of the relation, like it does with two-field relations.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Jul 06, 2017 at 09:00 GMT_

----

Thanks, I can confirm this faulty behaviour. Furthermore, running 

```graphql
mutation a {
  createDummy(dummyName: "Hi" connectionBetween: {
    dummyName: "Hi2"
  }) {
    id
  }
}
```

and

```graphql
query b {
  allDummies {
    id
    connectionBetween {
      id
    }
  }
}
```

results in 

```graphql
{
  "data": {
    "allDummies": [
      {
        "connectionBetween": [
          {
            "id": "cj4s763ypw3kq01940ktftrvk"
          }
        ]
      },
      {
        "connectionBetween": []
      }
    ]
  }
}
```

instead of 

```graphql
{
  "data": {
    "allDummies": [
      {
        "connectionBetween": [
          {
            "id": "cj4s763ypw3kq01940ktftrvk"
          }
        ]
      },
      {
        "connectionBetween": [
          {
            "id": "cj4s763ymw3kp01948jbfjnwu"
          }
        ]
      }
    ]
  }
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
