### ISSUE TITLE
Delete old functions

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#403]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Jul 08, 2017 at 21:12 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/173_

----

**What is the current behavior?**
Whenever you change a function, a new webtask is deployed under the hood. However, the old webtasks never get deleted. Not a big deal, but since they are (technically) still public, I have no way to prevent old function logic of being executed, making https://github.com/graphcool/api-bugs/issues/149 worse than it already is.

**What is the expected behavior?**
Delete old function when a new one is created by the execute-api.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
