### ISSUE TITLE
Unique constraint error message not accurate for nested mutations

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#407]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday Jul 11, 2017 at 20:42 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/179_

----

**What is the current behavior?**

When a nested create mutation would violate a unique key constraint, the error message is not accurate.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type Post implements Node {
  id: ID! @isUnique
  title: String! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  group: Group @relation(name: "PostOnGroup")
}

type Group implements Node {
  id: ID! @isUnique
  posts: [Post!]! @relation(name: "PostOnGroup")
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

Note that `title: String` is unique.

**If applicable, share the query, mutation or subscription for reproduction**

First, create a post:

```graphql
mutation {
  createPost(title: "test") {
    id
  }
}
```

Then, create a group and a nested post with the same title:

```graphql
mutation c {
  createGroup(posts: {
    title: "test"
  }) {
    id
  }
}
```

You'll receive an inaccurate error message:

```json
{
  "data": {
    "createGroup": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 16,
          "column": 3
        }
      ],
      "path": [
        "createGroup"
      ],
      "code": 3010,
      "message": "A unique constraint would be violated on Group. Details: Sorry, no more details available.",
      "requestId": "cj501kxknm3hs0147rmqbk7iy"
    }
  ]
}
```

It says, the unique constraint on `Group` is not fulfilled - but that's not right. Also, the group is still being created, but the post is not.

**What is the expected behavior?**

The error message should say 
> A unique constraint would be violated on Post. Details: Field 'title'

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
