### ISSUE TITLE
function webhook not being triggered on User Create, could be related to #182

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#408]
<a href="https://github.com/cj"><img src="https://avatars0.githubusercontent.com/u/1819?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cj](https://github.com/cj)**
_Thursday Jul 13, 2017 at 22:18 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/183_

----

**What is the current behavior?**

User Created subscription function not getting triggered and calling webhook.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Please, setup environment like #182.

Create a `User Created` function with the following below:

```graphql
subscription newUser {
  User(filter: {
    mutation_in: [CREATED]
  }) {
    updatedFields
    node {
      id,
      firstName,
      lastName,
      email
    }
  }
}
```

![](https://image.prntscr.com/image/3kbwxBR3RKKAadxUwehyOQ.png)

**What is the expected behavior?**

It should be triggering the webhook, but it isn't.

**fix**

If you add any customer header, the function works and the webhook is triggered.

![](https://image.prntscr.com/image/VeR8XIzoRo27Qm91F51SXA.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
