### ISSUE TITLE
Inconsistencies for one to one self relations

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#409]
<a href="https://github.com/johannchen"><img src="https://avatars0.githubusercontent.com/u/386977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johannchen](https://github.com/johannchen)**
_Friday Jul 14, 2017 at 21:15 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/186_

----

**What is the current behavior?**
There is a Contact model and self relate through relation Spouse (one-to-one). It can setSpouse(spouse1ContactId, spouse2ContactId). For example, Joe and Mary are couple. It can query Mary from Joe; however, it cannot do the reverse to query Joe from Mary with the same query.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
`type Contact implements Node {
  id: ID! @isUnique
  name: String!
  spouse: Contact @relation(name: "Spouse")
}
`
**If applicable, share the query, mutation or subscription for reproduction**
`query { 
  Contact(id: $id) {
    name
    spouse {name}
}}`

**What is the expected behavior?**
It should query spouse from a Contact vice versa.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
