### ISSUE TITLE
Scalar node variable is not available in permission query

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#410]
<a href="https://github.com/cj"><img src="https://avatars0.githubusercontent.com/u/1819?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cj](https://github.com/cj)**
_Saturday Jul 15, 2017 at 02:41 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/188_

----

**What is the current behavior?**

When you select a scalar value and set your permission as follows:

![](https://image.prntscr.com/image/34HO_KuETJ6Iaxr5ziQrRQ.png)

When you save and open the permission again, it now looks like this:

![](https://image.prntscr.com/image/hX9cUf-PQvS8VqfdJv7sZQ.png)

**What is the expected behavior?**

For it to save the permission without removing the entire query tag.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Jul 15, 2017 at 11:11 GMT_

----

How does the User type look like in the schema?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Jul 15, 2017 at 19:58 GMT_

----

That might have been the wrong paste @cj 🤔

**Comment by schickling** [comment]
<a href="https://github.com/cj"><img src="https://avatars0.githubusercontent.com/u/1819?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cj](https://github.com/cj)**
_Saturday Jul 15, 2017 at 20:32 GMT_

----

@marktani indeed it was lol, I updated it to the correct one :)

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Jul 15, 2017 at 20:36 GMT_

----

Thanks! Will look into reproduction soon.

**Comment by schickling** [comment]
<a href="https://github.com/vmatacale"><img src="https://avatars0.githubusercontent.com/u/25911983?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmatacale](https://github.com/vmatacale)**
_Wednesday Aug 02, 2017 at 13:45 GMT_

----

I reproduced this bug. It appears to be in the UI only. After the query is created with a scaler, if you open the query back up in the editor, the variables don't seem to be parsed correctly so the scaler fields aren't set properly. This triggers the validation.

All you have to do is click the correct scaler inputs and validation is passed again. It looks like the query is saved and works properly, it just loads improperly so it fails validation on an edit

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
