### ISSUE TITLE
Wrong behaviour of a webhook results in an internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#411]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Jul 19, 2017 at 09:39 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/193_

----

**What is the current behavior?**

Bug.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Create a new RP function with a webhook. Set `https://www.graph.cool/forum/` as the webhook URL, or any other random URL that does not act as a webhook should. Trigger the function using a mutation. You'll receive this error message:

> {
  "data": {
    "createDate": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createDate"
      ],
      "code": 5000,
      "message": "A function returned an unhandled error. Please check the logs for executionId 'cj5at9h0zik7m0199mt86nwdw'",
      "requestId": "cj5at9h0zik7m0199mt86nwdw"
    }
  ]
}

**What is the expected behavior?**

A useful error message that indicates a timeout or unavailability of the webhook function.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
