### ISSUE TITLE
Single scalar default value should be accepted as a default value for list scalars

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#414]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Jul 24, 2017 at 13:54 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/204_

----

**What is the current behavior?**

Error message for invalid default value for enum fields is not helpful.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Start with this schema:

```graphql
type A {
  id: ID!
  field: [MyEnum!]
}
```

And this enum:

```graphql
enum MyEnum {
  A,
  B
} 
```

If you now try to add a default value for `field` like this:

```graphql
type A {
  id: ID!
  field: [MyEnum!] @defaultValue(value: "A")
}
```

You get the error message

> `'A' is not a valid value for type 'Enum'`

However, the real issue is that you provided `"A"` instead of `"[A]"`.

**What is the expected behavior?**

It should work, and be migrated to `["A"]`

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
