### ISSUE TITLE
Mutations with an invalid DateTime value and a RP function result in an internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#415]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Jul 26, 2017 at 15:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/206_

----

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type A {
  id: ID
  date: DateTime
}
```

define a default RP function for `A is created`. Run this mutation:

```graphql
mutation {
  createA(date: "22017-07-27T12:00:00.000Z") {
    id
  }
}
```

It will result in an internal server error because `date` is not a valid `DateTime`.

**What is the expected behavior?**

A useful error message is returned.

**Comment by marktani** [comment]
I can still reproduce this.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by Fi1osof** [comment]
It`s useful use moment-js. Just moment().format()
