### ISSUE TITLE
Invalid project name error message is inaccurrate

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#417]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Saturday Jul 29, 2017 at 20:01 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/211_

----

![image](https://user-images.githubusercontent.com/1780597/28747871-6eca17b2-74a9-11e7-9199-36da6eb4b65f.png)

should mention alphanumeric, starting with an uppercase letter.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Jul 29, 2017 at 20:04 GMT_

----

https://github.com/graphcool/console/issues/805

**Comment by schickling** [comment]
<a href="https://github.com/DevanB"><img src="https://avatars0.githubusercontent.com/u/354652?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DevanB](https://github.com/DevanB)**
_Wednesday Aug 16, 2017 at 15:01 GMT_

----

I noticed this issue today:

```bash
10:57 $ graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews-test
✖  Error: 'Hackernews-test' is not a valid project name. It must begin with an uppercase letter.

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

Technically, the project name does start with an uppercase letter, but the issue is the hyphen. Specifying in the error message something like "It must begin with an uppercase letter, and must only contain alphanumeric characters" would cover this instance of the error.

**Comment by marceloogeda** [comment]
The same here:

<img width="450" alt="screen shot 2017-09-16 at 15 50 46" src="https://user-images.githubusercontent.com/3205036/30515009-de995e72-9af6-11e7-97ae-6b10589a658a.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
