### ISSUE TITLE
Inaccessible model property in permission query context

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#419]
<a href="https://github.com/wallslide"><img src="https://avatars3.githubusercontent.com/u/917069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wallslide](https://github.com/wallslide)**
_Tuesday Aug 01, 2017 at 10:16 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/214_

----

**What is the current behavior?**
I added a field to the User model that looks like this:
`flags: [USER_FLAGS!]`
`USER_FLAGS` is an enum that I also created right before adding the field to the model.

I then attempted to add a `create` permission query, that uses the `SomeUserExists` permission query. The environment was unaware of the `flags` field on the User model. The UI refused to autocomplete it, and it was missing from the docs as well. I logged out and logged back in hoping that it was a synchronization issue, but the problem remained.

I have other enum-based fields that can be accessed from the same permission query context, but they are all required. So I tried updating the `flags` field signature to this: `flags: [USER_FLAGS!]!`, but that did not solve the issue either.

**What is the expected behavior?**

I expect to be able to utilize the `flags` User model property in my permission queries.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
