### ISSUE TITLE
Splitting a relation with one field up into two fields is not recognized

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#421]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Friday Aug 04, 2017 at 13:17 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/219_

----

The behavior is a bug

**What is the current behavior?**

I have the following schema:

```
type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  post: Post @relation(name: "PostOnUser")
}

type Post implements Node {
  id: ID! @isUnique
  title: String! @defaultValue(value: "")
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User @relation(name: "PostOnUser")
}

type Post2 implements Node {
  id: ID! @isUnique
  title: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  post2: Post2 @relation(name: "Post2OnUser")
  test: String
}
```
which I want to migrate to this schema:
```
type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  post: Post @relation(name: "PostOnUser")
  post2: Post2 @relation(name: "Post2OnUser")
}

type Post implements Node {
  id: ID! @isUnique
  title: String! @defaultValue(value: "")
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User @relation(name: "PostOnUser")
}

type Post2 implements Node {
  id: ID! @isUnique
  title: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  post2: User @relation(name: "Post2OnUser")
  test: String
}
```
Preview changes does not recognize any changes and does not throw an error. I can preview and then click apply without any error or confirmation messages. Then when I want to leave the page I get a data loss warning and if I ignore that and later return all changes are lost and I am back to the original schema.

**What is the expected behavior?**

either apply the changes or give an error if they are invalid

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
