### ISSUE TITLE
Support `id` field as function payload with different type than String or ID

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#423]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 08, 2017 at 20:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/224_

----

**What is the current behavior?**
The returned data object structure is correct, however the SE still throws an internal server error (from the client/Playground only, the SE function logs shows a correct execution)

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
SDL:
```graphql
type GetWeatherByCityPayload {
  name: String
  dt: Float
  main: Json
  sys: Json
  wind: Json
  base: String
  id: Int
  coord: Json
  clouds: Json
  weather: [Json]
  visibility: Int
  cod: Int
}
``` 
Data returned from SE:
```json
{
  "coord": {
    "lon": 77.22,
    "lat": 28.63
  },
  "weather": [
    {
      "id": 701,
      "main": "Mist",
      "description": "mist",
      "icon": "50n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 29,
    "pressure": 1003,
    "humidity": 94,
    "temp_min": 29,
    "temp_max": 29
  },
  "visibility": 2500,
  "wind": {
    "speed": 2.32,
    "deg": 137.503
  },
  "clouds": {
    "all": 40
  },
  "dt": 1502222400,
  "sys": {
    "type": 1,
    "id": 7809,
    "message": 0.0029,
    "country": "IN",
    "sunrise": 1502151416,
    "sunset": 1502199359
  },
  "id": 1273840,
  "name": "Connaught Place",
  "cod": 200
}
```

However, if I rename the `id` field in the SDL and return data to `id2`, the function runs without error.

**What is the expected behavior?**
The SE should return the data, including the field named `id`, instead of throwing an internal server error.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 08, 2017 at 21:03 GMT_

----

Found something out, it's related to the id field. If I comment that one out, it works fine. Is it maybe that id is overridden somewhere, and that you can't return a field named id?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Aug 08, 2017 at 21:04 GMT_

----

That sounds very likely :+1:

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 08, 2017 at 21:06 GMT_

----

Yes, that's it. If I rename the field to `id2` in my SDL, and add `data.id2 = data.id` to my function, it runs without error. I'll update the title and description...

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Aug 25, 2017 at 14:32 GMT_

----

For now, `id` is only allowed in a SE function if it is of type `ID` or `String` (or `!`).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
