### ISSUE TITLE
Cannot require scoped npm package in function

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#424]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 08, 2017 at 23:11 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/225_

----

**What is the current behavior?**
Requiring a scoped package returns a server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```es6
import * as googleMaps from '@google/maps'
```
Error:
```js
"Function returned invalid status code:: 400. Raw body: {\n  \"code\": 400,\n  \"message\": \"Compilation failed: Cannot find module '@google/maps'\",\n  \"error\": \"Cannot find module '@google/maps'\"
```

**What is the expected behavior?**
Able to require scoped packages without error.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 08:40 GMT_

----

Looks like a duplicate of #170 to me, or am I wrong?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Aug 09, 2017 at 08:59 GMT_

----

No it's not. Normal packages where you want to require an export from a subfolder are dealt with in #170. The 'import ... from ...' syntax works there, so I don't believe that's still an issue actually. 

This is regarding _scoped packages_, so packages that start with '@something/...'. They do *not* work, even with the 'import' syntax.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 10:02 GMT_

----

Ah ok, thanks for the clarification! 🙂

**Comment by kbrandwijk** [comment]
Retested this, seems to work now.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
