### ISSUE TITLE
Nested promise is not correctly resolved in RP functions for required fields

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#426]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 21:05 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/227_

----

**What is the current behavior?**

Returning a promise which wraps another promise in a `TRANSFORM_ARGUMENT` function returns an internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Define this schema:

```graphql
type Order implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  token: String!
  updatedAt: DateTime!
}
```

define this `TRANSFORM_ARGUMENT` function for `Order is created`

```js
const someFunction = (parameter) => {

  return new Promise((resolve, reject) => {
    resolve({ a: "a" })
  })
}

module.exports = function(event) {
  return new Promise((resolve, reject) => {
    someFunction('abc')
      .then(res => {
        resolve({ data: event });
      })
      .catch(err => {
        reject({data: err});
      })
  });
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Run this mutation:

```graphql
mutation CreateOrder2 {
  createOrder(token: "a") {
    id
    token
  }
}
```

This result in an internal server error.

**What is the expected behavior?**

It should work.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
