### ISSUE TITLE
Deleting a file with not existing id results in internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#428]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday Aug 14, 2017 at 09:43 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/230_

----

**What is the current behavior?**

Trying to delete a non-existing file results in internal server error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Run

```graphql
deleteFile(id: "abc") {
  id
}
```

it results in an internal server error:

```
{
  "data": {
    "deleteFile": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: eu-west-1:simple:cj6bz0rwajf8t01031q43vvj4",
      "requestId": "eu-west-1:simple:cj6bz0rwajf8t01031q43vvj4",
      "path": [
        "deleteFile"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**What is the expected behavior?**

It should return an error like this instead:

```json
{
  "data": {
    "deleteFile": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "deleteFile"
      ],
      "code": 3002,
      "message": "'File' has no item with id 'abc'",
      "requestId": "eu-west-1:simple:cj6byzyjjjer40103cth60ou6"
    }
  ]
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
