### ISSUE TITLE
Unsupported usage of console.log silently fails

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#430]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Tuesday Aug 15, 2017 at 17:09 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/232_

----

**What is the current behavior?**

If you use `console.log` like this:

```
console.log('returned data: ', data) 
```

in an inline function, the statement silently fails.

**What is the expected behavior?**

It should either behave as `console.log` in the browser (would be a feature request), or throw a helpful error message, that this is not supported.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 15, 2017 at 17:12 GMT_

----

I just tested the same in webtask.io, and it works there. Where does this restriction come from?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Tuesday Aug 15, 2017 at 17:13 GMT_

----

`console.log` is a custom implementation

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 15, 2017 at 17:21 GMT_

----

In that case, I'm very much voting for 'behave as default console.log() in Auth0 webtasks'.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
