### ISSUE TITLE
Cloning a project results in an invitation email

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#432]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Aug 17, 2017 at 08:15 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/234_

----

**What is the current behavior?**
When I clone a project, I receive an invitation email for the cloned project.

**What is the expected behavior?**
I don't get one.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Aug 17, 2017 at 08:21 GMT_

----

Thanks, we'll look into this one.

**Comment by marceloogeda** [comment]
That's really happen 🙁

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
