### ISSUE TITLE
Deleting or renaming a file in a non-EU region results in an internal server error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#434]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Aug 17, 2017 at 15:40 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/237_

----

**What is the current behavior?**

Deleting or renaming a file works, but throws an internal server error in the US and AP regions.

**What is the expected behavior?**

It should not throw an error.

**Comment by eruby94** [comment]
I've also experienced this just now. Ignoring error catch for now, until a better solution is found.

**Comment by dohomi** [comment]
same error for me

**Comment by ViktorSoroka** [comment]
Any updates on this?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
