### ISSUE TITLE
File API ignores contentType, and incorrectly determines mimetype for files without extension

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#438]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Friday Aug 25, 2017 at 22:28 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/242_

----

**What is the current behavior?**
If you upload a file without an extension, but the content-type header is set correctly, the File API ignores the content-type, and determines the mimetype as `application/octet-stream`.

**What is the expected behavior?**
It should not (only) use extension, content-type should be leading.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
