### ISSUE TITLE
Server Side Subscription dropping invocations (suspected parallelism issue)

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#439]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattfysh](https://github.com/mattfysh)**
_Saturday Aug 26, 2017 at 08:17 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/243_

----

**What is the current behavior?**

An SSS Function has dropped an invocation when 3 applicable mutations occurred within quick succession of one another. The SSS Function was invoked only twice.

A similar SSS Function which also triggers when the same object type is updated successfully triggered three times.

The average duration for the Function which dropped an invocation is ~2000ms
And the average duration for the Function which was successfully invoked all 3 times is ~500ms

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

This does not appear to be a project-related issue.

**If applicable, share the query, mutation or subscription for reproduction**

For the SSS Function that only triggered twice:

```
subscription {
  MyType(filter: {
    mutation_in: [UPDATED]
    node:{
      status:NEWVALUE
    }
  }) {
    node {
      id
    }
  }
}
```

For the SSS Function that triggered three times:

```
subscription {
  MyType(filter: {
    mutation_in: [CREATED, UPDATED, DELETED]
  }) {
    node {
      id
    }
  }
}
```

**What is the expected behavior?**

The SSS Function should have been invoked once per mutation

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Aug 26, 2017 at 09:59 GMT_

----

Thanks for the bug report! Can you show the according mutation?

**Comment by schickling** [comment]
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Saturday Aug 26, 2017 at 10:01 GMT_

----

```
mutation UpdateStatus($id: ID!) {
  updateMyType(id: $id, status: NEWVALUE) {
    id
  }
}
```

**Comment by sorenbs** [comment]
@mattfysh To help narrow down the issue - how did you verify that the function had been triggered only 2 times instead of 3?

- By inspecting the logs in the Graphcool console
- By observing calls to an external system

**Comment by mattfysh** [comment]
Hey @sorenbs - by inspecting the logs (this is also how I noticed the other function had triggered 3 times)

**Comment by mattfysh** [comment]
In addition, the function creates a conversation on Intercom. Only 2 conversations were created instead of 3

**Comment by marktani** [comment]
I was not able to reproduce this @mattfysh, do you still experience this issue?

**Comment by mattfysh** [comment]
Since it's a suspected race condition, I don't expect this will be 100% reproducible. Is it possible to have an engineer do a bottom-up investigation into this? I am happy to give them access to my account where this happened

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
