### ISSUE TITLE
Collaborator can delete someone else's last project

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#441]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 29, 2017 at 18:55 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/246_

----

**What is the current behavior?**
A collaborator can delete a project.

**What is the expected behavior?**
A collaborator should not be able to delete a project.

Related: a collaborator can delete someone else's last project, which you cannot do yourself. If you decide not to fix the main issue, then please create a seperate issue for this one...

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Saturday Sep 02, 2017 at 02:39 GMT_

----

Thanks! The general case is a feature request and will be covered once we introduce access control configuration for collaborators: https://github.com/graphcool/feature-requests/issues/94

That a collaborator can delete the last project of someone else is unintended and should be changed.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
