### ISSUE TITLE
Default values not supported for arguments to resolver functions

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#442]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Aug 29, 2017 at 22:45 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/247_

----

**What is the current behavior?**
It's not possible to define default values for query parameters in a SE. The value of the parameter inside the function is `null`

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```
extend type Query {
  add(a: Int = 2, b: Int!): AdditionPayload
}
```

**What is the expected behavior?**
Default values should be used.

**Comment by sorenbs** [comment]
The current workaround is to simply handle the null case in code.

It would be nice to enable a default value in the extension schema. Is the proposed syntax valid GraphQL?

**Comment by kbrandwijk** [comment]
Yes: https://launchpad.graphql.com/73kmp8ppj

**Comment by sorenbs** [comment]
That's awesome - thanks!

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
