### ISSUE TITLE
PQ- and Non-PQ permissions behave inconsistent for mutations that only contain nested input arguments

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#445]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Thursday Aug 31, 2017 at 17:28 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/250_

----

**What is the current behavior?**

For *update and create*  mutations that only contain nested input arguments, Permission Query Permissions are not considered, while Non-Permission Query Permissions are considered.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Schema:

```graphql
type Model implements Node {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  projects: [Project!]! @relation(name: "ProjectOnModel")
}

type Project implements Node {
  name: String!
  createdAt: DateTime!
  id: ID! @isUnique
  models: [Model!]! @relation(name: "ProjectOnModel")
  updatedAt: DateTime!
}
```

Mutations to be considered (needs respective data), that will be executed as an authenticated user:

```graphql
mutation c($modelId: ID!, projectIds: [ID!]!) {
  updateModel(id: $modelId, projectsIds: $projectIds) {
    id
  }
}
```

```graphql
mutation d($modelId: ID!, projectIds: [ID!]!) {
  createModel(projectsIds: $projectIds) {
    id
  }
}
```

The above mutations works, if there is a "default" permission for `Model is updated`/`Model is created` for `AUTHENTICATED`. If you enabled any permission query on that default permission, the mutation returns an insufficient permission error.

**What is the expected behavior?**

The field-matching mechanism for create and update mutation permissions should behave consistently whether or not a permission query is present.

1.) To stay consistent with the currently specified behaviour, both PQ and non-PQ permissions should FAIL for the mutation, as no scalar field is present in the mutation, so there is no field that the permission can match on.

2.) However, it has been a frequent feature request that the state of type permissions should be disregarded if an update mutation only contains nested input arguments. This would mean that in both cases, the mutation should succeed, but this would slightly change semantics of permissions.

All in all, my proposal is to adjust the behaviour as mentioned in 1.). Then, once [transactions for nested mutations](https://github.com/graphcool/feature-requests/issues/191) are implemented, the behaviour mentioned in 2.) should be applied for both update and create mutations.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
