### ISSUE TITLE
Adding a field to a type with specific default values causes Internal Server Error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#448]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Monday Sep 04, 2017 at 14:38 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/253_

----

**What is the current behavior?**
```
type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type JsonModel implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  json: Json! @defaultValue(value: "{\"a\":2}")
  updatedAt: DateTime!
  jsonlist: [Json!] @defaultValue(value: "[{\"a\":2},{\"a\":3}]")
 anotherField: String
}

type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}

type DateTimeModel implements Node {
  createdAt: DateTime!
  datetime: DateTime! @defaultValue(value: "2018-01-01T00:00:00.000")
  id: ID! @isUnique
  updatedAt: DateTime!
}

type EnumModel implements Node {
  createdAt: DateTime!
  enumlist: [Weekdays!] @defaultValue(value: "[MO]")
  id: ID! @isUnique
  updatedAt: DateTime!
}

enum Weekdays {
  MO
  TU
  TH
}
```

Adding the anotherField in JsonModel results in an Internal Server Error.  No changes are made in the console schema view. Possibly related to DefaultValues.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
