### ISSUE TITLE
Validate PermissionQueries upon Creation

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#456]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Thursday Sep 07, 2017 at 16:29 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/261_

----

Permission queries can contain invalid GraphQL and also reference non-existing fields and types.

They should be validated against the schema.

**Comment by marktani** [comment]
This is actually still open.

**Comment by do4gr** [comment]
See https://github.com/graphcool/graphcool/issues/602

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
