### ISSUE TITLE
Algolia integration doesn't resync index when new field is added to integration query

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#462]
<a href="https://github.com/wallslide"><img src="https://avatars3.githubusercontent.com/u/917069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wallslide](https://github.com/wallslide)**
_Friday Sep 08, 2017 at 01:17 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/268_

----

**What is the current behavior?**

I setup my algolia integration like so:

```
	{
    node  {
      id,
     name,
  }
```

Later on, I go to add a new field:

```
	{
    node  {
      id,
     name,
     nickname
  }
```

After clicking save, the UI claims that the index was updated. When checking the algolia logs, I can see that the index was not updated, and the `nickname` field does not exist in my algolia index.

**What is the expected behavior?**

If I add a field to the algolia integration query, I expect that field to be propagated to the nodes in my algolia index (as the UI claims via toaster messages).

**Comment by marktani** [comment]
As a workaround, you can touch all nodes that you want to resync using a script like this: https://github.com/graphcool-examples/scripts/blob/master/touch-nodes/

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
