### ISSUE TITLE
Chat button hides part of the UI

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#466]
<a href="https://github.com/mwildric"><img src="https://avatars1.githubusercontent.com/u/5809973?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mwildric](https://github.com/mwildric)**
_Friday Mar 24, 2017 at 21:46 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/3_

----

<img width="1264" alt="screen shot 2017-03-24 at 5 42 34 pm" src="https://cloud.githubusercontent.com/assets/5809973/24314723/7ce3a8da-10b9-11e7-9ae5-d4afaad67e0e.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
