### ISSUE TITLE
Separate view for data that can be used as admin panel for end user

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#467]
<a href="https://github.com/mbiqbal"><img src="https://avatars2.githubusercontent.com/u/1829523?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbiqbal](https://github.com/mbiqbal)**
_Monday Mar 27, 2017 at 10:22 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/5_

----

if there could be two data views that would be great. The current one is cool for manual changes and additions but not easy to view.
So for searching and viewing if there could be another view thats easy on the eyes. It would be great. Plus i wont have to build an admin panel 😃

**Comment by sorenbs** [comment]
I know several people are thinking about creating an open source project around this. The general consensus is that an admin panel has to be very flexible to be suitable for all use cases, and an open source framework is the best fit for this.

The popular admin-on-rest project has a GraphQL adapter https://github.com/marmelab/aor-simple-graphql-client

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
