### ISSUE TITLE
As the number of types grow, it gets harder to find them in the UI 

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#468]
<a href="https://github.com/arrygoo"><img src="https://avatars2.githubusercontent.com/u/965429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arrygoo](https://github.com/arrygoo)**
_Wednesday Apr 05, 2017 at 00:17 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/8_

----

This is an issue that I've been having with GraphQL as well. As my number of Schemas and resolvers grow to say above 30, I can't keep them all in one place, and want to be able to split them by their types. 

This project for example allows you to split your resolvers and schemas into files and merges them all together:
https://github.com/okgrow/merge-graphql-schemas

It would be cool if there was a way to quickly get to a schema once their number grows high

![image](https://cloud.githubusercontent.com/assets/965429/24684368/6b66b1ca-1973-11e7-975c-834a76f76f3e.png)

I don't have a clear solution, but maybe being able to group them or have them searchable list would be a potential solution. This would make the submenu of Data also easier to use. What do you guys think?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Apr 05, 2017 at 14:16 GMT_

----

I had a similar experience and thought about different approaches here. I think we could find a different visual representation (maybe grid-layout?) that gives a better overview of all your models. Or we can integrate the "Graph View" feature better and make it more interactive.

The search function would be great in general, but I think it covers a different use case: getting to a specific model faster vs. getting an overview of the general data model.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
