### ISSUE TITLE
"Add Field" and "Add Relation" buttons are too discrete on schema page

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#469]
<a href="https://github.com/Thebigbignooby"><img src="https://avatars3.githubusercontent.com/u/4172090?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Thebigbignooby](https://github.com/Thebigbignooby)**
_Wednesday Apr 19, 2017 at 14:39 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/10_

----

i literally did not see those 2 buttons
![image](https://cloud.githubusercontent.com/assets/4172090/25185687/4d36a960-251e-11e7-9120-8dfa032c14b5.png)

I think the last row in table is where the "add field" button should be

I also expect to be able to define a relation when adding a field

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Apr 19, 2017 at 15:18 GMT_

----

Thanks for the feedback, we're researching a better solution here :slightly_smiling_face:

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
