### ISSUE TITLE
Align project list with horizontal line of tabs

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#470]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Monday May 08, 2017 at 08:57 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/14_

----

![pasted image at 2017_05_08 09_29 am](https://cloud.githubusercontent.com/assets/1780597/25797338/0c8dde24-33dd-11e7-9bc9-186f2881f37a.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
