### ISSUE TITLE
Perhaps change row layout for types

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#471]
<a href="https://github.com/jhalborg"><img src="https://avatars2.githubusercontent.com/u/6643672?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jhalborg](https://github.com/jhalborg)**
_Thursday May 11, 2017 at 14:12 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/17_

----

On every field row, I keep assuming that to delete or edit the field, I should press on the icons to the right. As a first time user, it’s not immideately obvious (to me at least), that I should instead press the name of the row. Just a small note :-) Instead of the icons on the right, it should perhaps just say "Permissions" instead

![pasted image at 2017_05_11 03_30 pm](https://cloud.githubusercontent.com/assets/6643672/25953661/52af38e2-3664-11e7-9b5b-caf0ba5143d0.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
