### ISSUE TITLE
Examples given for new field types

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#472]
<a href="https://github.com/2ne"><img src="https://avatars0.githubusercontent.com/u/2843638?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [2ne](https://github.com/2ne)**
_Thursday May 11, 2017 at 14:56 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/18_

----

Would be nice to have an example of a string, int, boolean and float when creating a new field. Just an example as a custom tooltip. Not sure all front-end devs would know straight away what they are. I didn't anway :slightly_smiling_face:

So for boolean "This could be used for true or false".

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
