### ISSUE TITLE
Can't tab to buttons

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#473]
<a href="https://github.com/2ne"><img src="https://avatars0.githubusercontent.com/u/2843638?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [2ne](https://github.com/2ne)**
_Thursday May 11, 2017 at 14:58 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/19_

----

Some buttons within the UI, such as the create field popup are created using divs and do not have a tabindex so you can't tab through the content. I prefer to just use the keyboard so from an accessibility POV I think the tabindex of the create field could be improved.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
