### ISSUE TITLE
Duplicated navigation

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#474]
<a href="https://github.com/2ne"><img src="https://avatars0.githubusercontent.com/u/2843638?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [2ne](https://github.com/2ne)**
_Friday May 12, 2017 at 09:28 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/21_

----

I find the walkthrough navigation which is duplicating the tab actions confusing. When you have 2 ways to perform an action on an area you feel that they must do something different to one another. I don't think that on this type of application that you can walk all users through every step so on a simple step like this (created a field) i don't think that it is necessary. 

<img width="1440" alt="screen shot 2017-05-12 at 10 17 19" src="https://cloud.githubusercontent.com/assets/2843638/25992087/6c4f0fb8-36fd-11e7-922d-09ccf3ae297d.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
