### ISSUE TITLE
Adding relationship popup overflow

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#475]
<a href="https://github.com/2ne"><img src="https://avatars0.githubusercontent.com/u/2843638?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [2ne](https://github.com/2ne)**
_Friday May 12, 2017 at 09:37 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/22_

----

When adding a relationship I think that the popup size could be bigger to use more of the current viewport width or use an ellipsis with the full title available on hover as it looks slightly broken.

<img width="1440" alt="screen shot 2017-05-12 at 10 35 19" src="https://cloud.githubusercontent.com/assets/2843638/25992557/cded17f0-36fe-11e7-90f6-0d6495a55526.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
