### ISSUE TITLE
Names given to permission queries don't persist

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#477]
<a href="https://github.com/wallslide"><img src="https://avatars3.githubusercontent.com/u/917069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wallslide](https://github.com/wallslide)**
_Wednesday May 17, 2017 at 08:33 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/25_

----

As demonstrated in the video below:

https://www.useloom.com/share/da0f420d07a9434397488b62178e83ff

I opened a permission, and its permission query. I then added a name to the query, and saved it. Upon reopening the same query, the name I gave it is gone.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
