### ISSUE TITLE
When you click any area outside the "New Function" dialog, it just closes dialog which is very bad UI (i guess)

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#478]
<a href="https://github.com/iamrommel"><img src="https://avatars1.githubusercontent.com/u/177265?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iamrommel](https://github.com/iamrommel)**
_Thursday May 18, 2017 at 09:41 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/27_

----

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
