### ISSUE TITLE
playground variables UI

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#480]
<a href="https://github.com/Geczy"><img src="https://avatars2.githubusercontent.com/u/1036968?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Geczy](https://github.com/Geczy)**
_Friday May 19, 2017 at 20:22 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/30_

----

It was not obvious that there is a variables screen on the very bottom. It's a faded gray and I didn't realize I could click it

I recommend having it expanded by default, and autofilling variables as you type in the playground

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
