### ISSUE TITLE
UI Editor, "ADD RELATION", "NEW RELATION", "DEFINE RELATIONS", relation of type to type itself

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#484]
<a href="https://github.com/mattferrin"><img src="https://avatars3.githubusercontent.com/u/2746787?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattferrin](https://github.com/mattferrin)**
_Saturday May 27, 2017 at 16:42 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/43_

----

I was using the UI editor. It actually was working perfectly. I had a mental mind funk out though. I do think it's easier to make my mental mistake when making a relation from a type to it's same type itself.

In the "NEW RELATION" "DEFINE RELATIONS" tab. I focus more naturally on the LEFT hand side where it says "will be generated" for the "related field".

That causes a mental problem for me on the RIGHT hand side where I glance at "Select Model", overlook the words "related field" and feel like I've already selected the "related" type. I haven't actually done the RIGHT hand side but feel like I have and that I can't do the LEFT.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
