### ISSUE TITLE
Setting permissions is cumbersome when doing batch operations

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#485]
<a href="https://github.com/bgraf-zlab"><img src="https://avatars1.githubusercontent.com/u/28538610?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bgraf-zlab](https://github.com/bgraf-zlab)**
_Monday May 29, 2017 at 16:10 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/44_

----

When doing "batch like" operations in the permissions pane, the current UI requires lots and lots of clicks through different panes.

I tried to set all my Types' CRUD to require authentication (I'm using a permanent token for testing). At first I created a new permission for each of the C/R/U/D: `7 clicks and going through the whole panel` * `4 cases (CRUD)` * `8 Types` is a lot of work ;-). Then I found out I could just change the default permission ("Everyone") to "Authenticated", which is still 4 clicks per case per type.

It would be really nice to have either an assistant that lets you apply settings to multiple Types and cases at once or to have a more streamlined gui which doesn't need a modal for setting simple settings, maybe a matrix of roles and types with checkboxes or thelike.

**Comment by marktani** [comment]
The new CLI version provides a much better experience to modify a lot of permissions at once, as it's file based. Check out [the feedback thread in the Forum](https://www.graph.cool/forum/t/feedback-new-cli-beta/949?u=nilan).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
