### ISSUE TITLE
provide correct font for credit card

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#488]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Saturday Jun 10, 2017 at 13:34 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/47_

----

See `CreditCardFront.tsx`.
We need OCR A Std:
`font-family: 'OCR A Std';`

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Jun 23, 2017 at 16:25 GMT_

----

`OpenSans` is ok for now

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
