### ISSUE TITLE
Switching project with collapsed side panel breaks layout

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#489]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Jun 11, 2017 at 17:10 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/48_

----

From #36 
> Is it already deployed? Because I think it broke something. Switch the project with the side panel collapsed:
![27012705-96f965fc-4ed5-11e7-872e-57840f7a2336](https://user-images.githubusercontent.com/852069/27012904-9e8f3216-4ed9-11e7-9f5a-143474dda134.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
