### ISSUE TITLE
Onboarding notification (Bottom) blocks query variables input in console playground

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#492]
<a href="https://github.com/phehaz"><img src="https://avatars0.githubusercontent.com/u/5908415?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [phehaz](https://github.com/phehaz)**
_Thursday Jun 15, 2017 at 14:47 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/51_

----

As the (long) title suggests, the 'Onboarding' pop-up at the bottom of the screen blocks the query variables input in the console playground. Just a minor annoyance when I was looking for the input field and hadn't completed (shame on me) or pressed 'skip' on the onboarding. 
With the notification/pop-up:
![image](https://user-images.githubusercontent.com/5908415/27186896-09f87bda-51ea-11e7-9ad9-bcc4ecdb8217.png)
Without:
![image](https://user-images.githubusercontent.com/5908415/27186967-3acf2204-51ea-11e7-9e4b-94444ff1456e.png)

I know, it's an edge-case, but still. :)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
