### ISSUE TITLE
In the algolia integration view tooltips showed on query errors cannot be read

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#493]
<a href="https://github.com/JensMadsen"><img src="https://avatars1.githubusercontent.com/u/6726111?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JensMadsen](https://github.com/JensMadsen)**
_Thursday Jun 15, 2017 at 19:42 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/52_

----

The the text in the tooltip is longer than teh size of the tooltip box, and hence the user cannot read the tooltip (unless you inspect the webpage source :-))

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
