### ISSUE TITLE
Resizing the window causes data loss

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#494]
<a href="https://github.com/JensMadsen"><img src="https://avatars1.githubusercontent.com/u/6726111?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JensMadsen](https://github.com/JensMadsen)**
_Thursday Jun 15, 2017 at 19:44 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/53_

----

When the window is resized to a size where the web app thinks that a mobile device is used the edits you have made to the query are lost

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Friday Aug 04, 2017 at 18:45 GMT_

----

potential places for data loss:

* Algolia integration
* Schema Editor
* Functions Editor
* Field, relation popup
* ...

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
