### ISSUE TITLE
Generate code from playground documentation

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#496]
<a href="https://github.com/XavierLeTohic"><img src="https://avatars0.githubusercontent.com/u/6340490?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [XavierLeTohic](https://github.com/XavierLeTohic)**
_Tuesday Jun 27, 2017 at 14:25 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/55_

----

Into the documentation panel of the playground, by clicking somewhere into the list of the mutations/queries that could be great to generate the needed code on the editor.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
