### ISSUE TITLE
Playground: Docs Button is not clear

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#498]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Thursday Jul 06, 2017 at 15:07 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/59_

----

<img width="968" alt="screen shot 2017-07-06 at 5 05 22 pm" src="https://user-images.githubusercontent.com/1094804/27917785-5a01fce4-626d-11e7-9070-2d42168d5513.png">

Suggestion: Put Docs and Intercom into a unified "Need help?" button to the bottom right, rename "Docs" in the Playground to "Schema Explorer"

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
