### ISSUE TITLE
Console keyboard shortcuts

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#499]
<a href="https://github.com/Jesus-Gonzalez"><img src="https://avatars1.githubusercontent.com/u/10809429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jesus-Gonzalez](https://github.com/Jesus-Gonzalez)**
_Thursday Jul 06, 2017 at 15:51 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/60_

----

Hello there,

It would be really useful to implement shortcuts I'd say everywhere.

I do use shortcuts everywhere and use the mouse as little as possible

I'd really like to see for example:

`Everywhere`
* <kbd>[CTRL + M] + D</kbd> navigate to `Data` || <kbd>[CTRL + M] + P</kbd> navigate to Playground

In `Data` section
* <kbd>DEL</kbd> in order to delete the currently selected row.
* <kbd>CTRL [+ SHIFT] + N</kbd> create new entry
* ~<kbd>← → ↑ ↓</kbd> navigate through cells and rows.~

In `Playground`
 * <kbd>CTRL [+ SHIFT] + N/T</kbd> new tab
* <kbd>CTRL + REPAG/AVPAG</kbd> navigate through tabs

Thank you, Jesús

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
