### ISSUE TITLE
Method to add new data through the data browser isn't obvious

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#500]
<a href="https://github.com/claym"><img src="https://avatars1.githubusercontent.com/u/230486?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [claym](https://github.com/claym)**
_Thursday Jul 06, 2017 at 18:44 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/61_

----

The "add new node" text doesn't really pop - it's hard to see it unless you know what to look for.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
