### ISSUE TITLE
Non-helpful label in Playground when fragment comes first

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#501]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Jul 08, 2017 at 22:59 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/62_

----

If you specify a fragment before the actual query, the Playground still recognizes it as a query (shows the Q icon), but it uses the field name of the fragment as tab header, instead of the query field.
![image](https://user-images.githubusercontent.com/852069/27989800-c2e839c8-6441-11e7-8d93-6931b23b99af.png)

![image](https://user-images.githubusercontent.com/852069/27989803-d830e370-6441-11e7-9931-1c255ca8c8b5.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
