### ISSUE TITLE
Change 'View as' label in Playground to 'Execute as'

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#502]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Jul 08, 2017 at 23:01 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/63_

----

You're actually not viewing anything as admin/everyone/user, you're executing the current query/mutation as admin/everyone/user. So I think this could be relabelled as 'Execute as'.
![image](https://user-images.githubusercontent.com/852069/27989807-1a725e08-6442-11e7-953d-238951b44a4c.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
