### ISSUE TITLE
Functions logs width prevent to show entire log's content.

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#503]
<a href="https://github.com/maelsan"><img src="https://avatars1.githubusercontent.com/u/7117292?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maelsan](https://github.com/maelsan)**
_Tuesday Jul 11, 2017 at 14:41 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/65_

----

First, all data on these pictures are fake.

I use chrome 59.0.3071.115 (Official Build) (64-bit) on macOS 10.12.5 - Sierra. 
Macbook pro 15-inch touchbar.
 
So, when I want to take a look on my function's logs, it appears that I cannot see all the json object. It's cut. I have to open my console to see the rest of the json object.

<img width="1576" alt="screen shot 2017-07-11 at 16 32 52" src="https://user-images.githubusercontent.com/7117292/28073631-a3de7c10-6656-11e7-9c0b-bbcd3b84ff40.png">

<img width="1662" alt="screen shot 2017-07-11 at 16 26 48" src="https://user-images.githubusercontent.com/7117292/28073667-bfc9a6fc-6656-11e7-97c7-7fc595aa5c63.png">

<img width="378" alt="screen shot 2017-07-11 at 16 40 38" src="https://user-images.githubusercontent.com/7117292/28073981-b4418470-6657-11e7-99d6-09c37dc6bf33.png">

It would be possible to show the whole log, without adapt what is show according to the resolution?
It's really painful to have to open the console each time to see my logs.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
