### ISSUE TITLE
Provide code examples inside the playground when hovering over arguments

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#504]
<a href="https://github.com/rcwestlake"><img src="https://avatars3.githubusercontent.com/u/9679076?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rcwestlake](https://github.com/rcwestlake)**
_Wednesday Jul 12, 2017 at 01:10 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/66_

----

As I was working in the playground I thought several times: I wish I could see a code example of how a query or mutation would work with these fields or arguments in the sidebar docs. For example, in the screenshot below, it would be awesome if you showed an example query whenever you hover over one of the arguments with the argument actually being used. It would save time by avoiding trial/error or going to the docs.

![image](https://user-images.githubusercontent.com/9679076/28097293-837f73d2-666c-11e7-8e4e-08cf568354e3.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
