### ISSUE TITLE
Difficulty to scroll

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#506]
<a href="https://github.com/gustavopch"><img src="https://avatars2.githubusercontent.com/u/10941958?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gustavopch](https://github.com/gustavopch)**
_Friday Jul 21, 2017 at 12:03 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/69_

----

When there's a lot of types in a project, it gets really difficult to navigate through the console.

For example, I click "Data" in the left menu, but only the types fitting my screen appear and there isn't any way to scroll to see the overflown content.

The right side panel doesn't provide any easy way to scroll through the types.

Also, everything in the UI is sort of big. That's beauty in expense of usability. I'd rather have a UI that fits as much information as possible in the screen.

Graphcool is already awesome. With some fixes in the UI, the whole experience will be delightful.

**Comment by schickling** [comment]
<a href="https://github.com/gustavopch"><img src="https://avatars2.githubusercontent.com/u/10941958?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gustavopch](https://github.com/gustavopch)**
_Thursday Jul 27, 2017 at 16:38 GMT_

----

I realized this is only an issue when one doesn't have a scroll wheel.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
