### ISSUE TITLE
Data creation is not easy

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#507]
<a href="https://github.com/slorber"><img src="https://avatars0.githubusercontent.com/u/749374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [slorber](https://github.com/slorber)**
_Thursday Jul 27, 2017 at 17:20 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/71_

----

Hi,

We are not using GraphCool in the context of a production app but rather a prototype. 
Later we'll have a custom GraphQL backend but in the meantime we are using GraphCool as a mock / readonly GraphQL endpoint.

So I have designed a schema, and I need to create some readonly data manually in GraphCool so that I can query it from the demo SPA.

For my usecase, I found the UX not convenient.

- Fields are ordered by name while I'd navigate in the fields more easily if the fields where following the declaration order of the schema

- During creation, it's quite easy to have a very long list of fields on a type, and having all them on a row is unconvenient. It would be better to display creation form in a popup, with 2 columns (fieldName -> fieldValue), and put the mandatory fields first, the optional afterward, and the "non-fillable" relationship fields at the end. (This popup could also be used view/edit more easily a single row)

- In case of creation failure, it would be very convenient to not dismiss the form data the user entered. Currently on every error we have to start filling the row data from scratch

- Unability to create relationships during row creation is a problem. This means it's currently impossible to create any row that has a one-to-one mandatory relationship. The workaround is to remove constraints from the schema before adding the data, but it's not very convenient or intuitive.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
