### ISSUE TITLE
Little playground editor issue when opening braces

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#508]
<a href="https://github.com/slorber"><img src="https://avatars0.githubusercontent.com/u/749374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [slorber](https://github.com/slorber)**
_Thursday Jul 27, 2017 at 17:30 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/73_

----

From a blank playground editor.

I want to get to this state:

```
{
  |...
}
```

So I open `{` and press enter. Unfortunately due to autocompletion on fields it produces:

```
{allAnswers}
```

I think this behavior is annoying and counterintuitive regarding IDE behaviors, and you should rather go to next line on enter (unless suggestion was selected by click, or user typed a space before enter...)

**Comment by sorenbs** [comment]
Hi @slorber

This doesn't happen for me.

As soon as I write

```
{
```
The editor takes me to this state:
```
{|}
```

When I press enter I get to this state:

```
{
  |
}
```

Could you verify that this is still an issue for you?

**Comment by slorber** [comment]
nop, still the case for me (as well as graphiql demo, on which I supposed the playground is built)

![image](https://user-images.githubusercontent.com/749374/30224506-61edac5c-94cf-11e7-921b-d27b58dfa661.png)


pressing enter does select the first suggestion

**Comment by sorenbs** [comment]
I remember somebody else talking about this maybe being related to the keyboard layout. I'm using US keyboard mapping. What is your keyboard layout?

I don't even get the auto complete list unless I press `ctrl-space`

**Comment by marktani** [comment]
You're thinking of this https://github.com/graphql/graphiql/issues/353, which was fixed in `graphiql` itself already.

**Comment by sorenbs** [comment]
That's right. So this should be solved in the Playground when we release the next version in a week or two.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
