### ISSUE TITLE
Nodes take a long time to load when adding a relation. 

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#510]
<a href="https://github.com/ejoebstl"><img src="https://avatars2.githubusercontent.com/u/1852126?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ejoebstl](https://github.com/ejoebstl)**
_Saturday Jul 29, 2017 at 15:42 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/75_

----

It's currently hard to add a relation to a node in the databrowser. 

When I click the (not yet set) relation field, the dialogue to select a node pops up. However, the nodes in the popup take awfully long to load (20+ seconds). The rest of the databrowser works normally.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Monday Jul 31, 2017 at 19:32 GMT_

----

This did not yet occur to me, maybe it's related to your specific data structure. Do you have a lot of potentially related nodes, or do they contain a lot of data?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
