### ISSUE TITLE
Adding relations to nodes by pasting the id of the related node

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#511]
<a href="https://github.com/ejoebstl"><img src="https://avatars2.githubusercontent.com/u/1852126?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ejoebstl](https://github.com/ejoebstl)**
_Saturday Jul 29, 2017 at 15:47 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/76_

----

For adding relations: It would be awesome if I could just paste the id of a node into the corresponding relation field in the data browser. 

In fact, I can't even easily copy an ID from the relation field, because any mouse-up event will show a popup. 

That makes working with the console quite slow.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
