### ISSUE TITLE
Auto completion in playground pops up when typing braces on german keyboards

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#512]
<a href="https://github.com/ejoebstl"><img src="https://avatars2.githubusercontent.com/u/1852126?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ejoebstl](https://github.com/ejoebstl)**
_Saturday Jul 29, 2017 at 15:52 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/77_

----

I know this is an Issue with graphiql, which is addressed [here](https://github.com/graphql/graphiql/issues/353). 

It should be fixed by now - please update your hosted graphiql.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
