### ISSUE TITLE
Frustrating behavior on number inputs

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#513]
<a href="https://github.com/wcastand"><img src="https://avatars3.githubusercontent.com/u/2178244?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wcastand](https://github.com/wcastand)**
_Wednesday Aug 09, 2017 at 13:24 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/81_

----

Hi, when i fill a number/float input in graph.cool, i have a big frustrating behavior.

By default, there is a 0 in the field but the cursor pop before so if i want to delete it, i just hit the right arrow, but that just switch the field to the next one.

I think it would be a lot better if the behavior was one of the following : 
- by default, there is no value in the input
- by default, when the input is focus, we select the value in it or put the cursor at the end of the value (so we can hit backspace to delete)
- by default, we deactivate the left/right arrow keybinding on input numbers, that way we can use the right/left arrow key to navigate in our field.

Switching field in the form should be done with the `tab` key and not the left/right arrow key.

If you have any question, don't hesitate :)

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Aug 09, 2017 at 14:09 GMT_

----

Thanks so much for your detailed description 👌 This experience is indeed frustrating and should be streamlined.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
