### ISSUE TITLE
Buttons are overlapping in permission view

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#514]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Saturday Aug 12, 2017 at 14:44 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/82_

----

![screen shot 2017-08-12 at 1 17 04 am](https://user-images.githubusercontent.com/1780597/29241598-6013b87a-7f7d-11e7-9d6e-75c3369ea803.png)

> Buttons are overlapping when height of the window is less than 760px

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
