### ISSUE TITLE
The playground has no scrollbars

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#515]
<a href="https://github.com/ejoebstl"><img src="https://avatars2.githubusercontent.com/u/1852126?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ejoebstl](https://github.com/ejoebstl)**
_Sunday Aug 13, 2017 at 22:31 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/83_

----

The playground has no scrollbars (at least in Chrome on OSX).

Browsing through 1000 result nodes is difficult this way.

**Comment by danmkent** [comment]
I agree - while showing scrollbars is not fashionable, they do make it a lot easier to scroll through lots of data quickly.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
