### ISSUE TITLE
Make the Sidebar Narrower by moving the Project Name 

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#516]
<a href="https://github.com/do4gr"><img src="https://avatars2.githubusercontent.com/u/16278407?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [do4gr](https://github.com/do4gr)**
_Tuesday Aug 15, 2017 at 15:03 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/84_

----

At the moment the width the sidebar takes is dominated by the need to have the logo and the project name next to each other. This wastes a lot of screen real estate since the menu items below don't need that full width. 
It also leads to truncated project names when they are very long. 
Instead of: 

<img width="734" alt="bildschirmfoto 2017-08-15 um 17 02 55" src="https://user-images.githubusercontent.com/16278407/29321709-a0369124-81db-11e7-8a81-f05cf127c04b.png">

I would like to have something narrower like this. This could be achieved by lowering the name below the logo:

<img width="196" alt="bildschirmfoto 2017-08-15 um 17 01 41" src="https://user-images.githubusercontent.com/16278407/29321671-77f65032-81db-11e7-898b-28d8ff6e1f78.png">

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
