### ISSUE TITLE
In the full logs view - it's not obvious that the text details view is scrollable

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#517]
<a href="https://github.com/mypark"><img src="https://avatars1.githubusercontent.com/u/470164?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mypark](https://github.com/mypark)**
_Friday Sep 01, 2017 at 13:15 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/86_

----

when expanding a log row - it's hard to tell that you can scroll to view the full log.  It's easy to mistake and think that the text is being truncated - even when you mouse over and click.

When expanding a row view - don't make the area fixed height and instead just let it expand to show the full log text.  No reason to have a fixed height with an overflow scroll - especially since the scroll bars are not visible.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
