### ISSUE TITLE
Search does not work with relation ID's

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#518]
<a href="https://github.com/ejoebstl"><img src="https://avatars2.githubusercontent.com/u/1852126?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ejoebstl](https://github.com/ejoebstl)**
_Thursday Sep 07, 2017 at 06:26 GMT_
_Originally opened as https://github.com/graphcool/ui-feedback/issues/87_

----

Consider the following model:

```
type Test {
  id: ID!,
  property: String!,
  user: User!
}
```

Viewing this model in the databrowser and searching for a certain user id does not yield any results, even if nodes associated with the user exist. 

This issue makes it difficult to look for all nodes which are related to a certain user.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
