### ISSUE TITLE
Add 'select user' functionality to standard endpoint playgrounds

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#525]
It would be helpful to be able to select a user when using the default playground at an endpoint. I now use a browser extension (Modify headers) for this.

**Comment by marktani** [comment]
This requires `graphcool-lib` (+ root token) or an authenticated call to the System API, so it cannot just be enabled in the public playground.

**Comment by kbrandwijk** [comment]
On the surface, you're right. However, there might be other solutions to consider. For example, a sign in button like on the console (using the same Graphcool console Auth0, so basically SSO). Or, a query parameter that allows you to specify a token (instead of having to modify the headers). Or... suggestions are welcome!

**Comment by marktani** [comment]
Yes we should definitely think about ways to offer this 🙂

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
