### ISSUE TITLE
Make filtering and constraints case sensitive

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#528]
As stated in the docs about the unique constraint:

> Please note that only the first 191 characters in a String field are considered for uniqueness and the unique check is **case insensitive**. Storing two different strings is not possible if the first 191 characters are the same or if they only differ in casing.

The same is true for filtering. Querying for nodes with the text `Test` might return nodes with text `test`, `Test`, `TEST` etc.

As this changes the behaviour of mutations and queries, this is considered a breaking change.

**Comment by kbrandwijk** [comment]
Would you consider adding a flag for case-sensitivity?

**Comment by sorenbs** [comment]
I would love to here more opinions on how we should treat case sensitivity and what should be the default.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
