### ISSUE TITLE
Scalar List Fields not displayed correctly in SchemaView

### ISSUE THREAD

**Issue by do4gr** [graphcool/prisma#542]
Scalar List fields are displayed in two different ways in the console. In the text schema a required list looks like this: [String!]! in the clickable type overview on the right it looks like this: [String]!

There should always be an inner exclamation mark for scalar lists and the outer one should denote the list status.

<img width="419" alt="bildschirmfoto 2017-09-12 um 13 41 20" src="https://user-images.githubusercontent.com/16278407/30324190-6c235bd8-97c0-11e7-88ba-24bc4952e9d6.png">

<img width="384" alt="bildschirmfoto 2017-09-12 um 13 41 30" src="https://user-images.githubusercontent.com/16278407/30324192-7149659e-97c0-11e7-84e2-84c2819c7193.png">

**Comment by do4gr** [comment]
moved to https://github.com/graphcool/console/issues/1302

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
