### ISSUE TITLE
One-to-one self-Relations with two fields are not updated correctly

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#545]
**What is the current behavior?**

Connecting two nodes in a one-to-one self relation with two fields unexpectedly removes other connections.

Interestingly, this only happens when using `setX` and not when using `updateY`.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

```graphql
type Module implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  name: String!
  moduleNext: Module @relation(name: "ModuleLinkedList")
  modulePrevious: Module @relation(name: "ModuleLinkedList")
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Create three new nodes:

```graphql
mutation {
  a: createModule(name: "a") {
    id
  }
  b: createModule(name: "b") {
    id
  }
  c: createModule(name: "c") {
    id
  }
}
```

Connect `a` and `b`:

```graphql
mutation first {
  setModuleLinkedList(
    modulePreviousModuleId: "a-id"
    moduleNextModuleId: "b-id"
  ) {
    moduleNextModule {
      id
    }
    modulePreviousModule {
      id
    }
  }
}
```

All is fine, `a` and `b` are now connected: `a <-> b` Let's connect `b` to `c` as well:

```graphql
mutation second {
  setModuleLinkedList(
    modulePreviousModuleId: "b-id"
    moduleNextModuleId: "c-id"
  ) {
    moduleNextModule {
      id
    }
    modulePreviousModule {
      id
    }
  }
}
```

`b` and `c` are connected as they should be: `b <-> c`. However, `a` and `b` are not connected anymore, but they should be.

**What is the expected behavior?**

The nodes should be connected like this: `a <-> b <-> c`.

**Comment by kbrandwijk** [comment]
Isn't this very similar to https://github.com/graphcool/graphcool/issues/401?

**Comment by Evilweed** [comment]
Any chance this gets fixed soon? Or any workaround? This is quite important to my project.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
