### ISSUE TITLE
Can't delete all files at the same time in graph.cool dashboard

### ISSUE THREAD

**Issue by johhansantana** [graphcool/prisma#561]
**What is the current behavior?**
In the graph.cool dashboard when you highlight every file and try to delete them all at the same time, after confirming the deletion, the files will stay the same, after refreshing, only 5 items have been deleted.

To delete all files you will have to keep selecting them all and pressing the delete button while it will only delete 5 each time you do this
**What is the expected behavior?**
Deletes all of the files when you select them all for deletion.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
