### ISSUE TITLE
Schema of subscription endpoint with alias is not invalidated correctly

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#579]
**What is the current behavior?**

Changing the name of a type is not being reflected in the schema of the subscription endpoint when using a project alias.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

* Create a new project, add a project alias `alias`, add a new type `Item`
* Subscribe to `Item` with a websocket client that is connected to `https://api.graph.cool/simple/v1/alias` - it works
* Change the name to `Items`
* Subcribe to `Items` with the same websocket client - it doesn't work. Error message:

> The provided query doesn't include any known model name. Please check for the latest subscriptions API.

With the Playground, both subscriptions worked, because it is connecting to the `https://api.graph.cool/simple/v1/projectid` endpoint.

**What is the expected behavior?**

The subscription schema should be invalidated immediately for the alias endpoint as well.

**Comment by Timopheym** [comment]
Oh, so how can i update scheme using subscription? I did had this problem playing worldchat example with wrong scheme from the start =(

**Comment by janvogt** [comment]
Just ran into this. Changing to project ID solved the problem for now. Any timeframe on when a fix is planned? At least there is a workaround, not like on #1367 😅

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
