### ISSUE TITLE
Include wrong id in error message for missing node

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#580]
> Error: GraphQL error: You are referencing a node that does not exist. Please check your mutation to make sure you are only creating edges between existing nodes.

Include the wrong id.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by baerrach** [comment]
Is there a specific issue in graphcool/graphcool-framework we should be watching?

**Comment by marktani** [comment]
[This one](https://github.com/graphcool/graphcool-framework/issues/465) 🙂
