### ISSUE TITLE
Add enum values to introspection query, even if it is not used yet

### ISSUE THREAD

**Issue by jhalborg** [graphcool/prisma#587]
**What is the current behavior?**
After I added a new type to an enum, I cannot query it - and I can't for newly created enums, either. Old enums still work. 

In the example above, I've added the "BOW" value to Weapons. Creating a new "TESTING" enum reproduced the same issue, also verified by user Agartha in the #general Slack channel

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
![image](https://user-images.githubusercontent.com/6643672/30806355-c39035f0-a1f5-11e7-82f7-223346bd250b.png)

**If applicable, share the query, mutation or subscription for reproduction**
![image](https://user-images.githubusercontent.com/6643672/30806367-d086e128-a1f5-11e7-93a8-5aea64f91a79.png)

**What is the expected behavior?**
To receive values for the new enum values as I can for the exisiting

**Comment by marktani** [comment]
Is this an ejected or non-ejected project?

**Comment by marktani** [comment]
confirmed for non-ejected projects. Thanks!

**Comment by marktani** [comment]
Query for quicker reproduction:

```graphql
query {
  __type(name: "A") {
    enumValues {
      name
    }
  }
}
```

**Comment by jhalborg** [comment]
Seems fixed now @marktani

**Comment by marktani** [comment]
Here's the current behaviour, and to my understanding it has always behaved like this:

the `__type(name: "SomeEnum")` query will only return the possible values in `enumValues` if there is at least one field in your data schema that references that enum.

I assume you are now using the enum in a field.

**Comment by jhalborg** [comment]
Absolutely nothing changed on my end, I ran the exact same query as shown in the screenshot :) kept it open in a tab, and tried to run the query for fun as I had finished up another query, and then it worked :)

**Comment by marktani** [comment]
Great, then I'll close this 🙂

**Comment by kbrandwijk** [comment]
Well... it's not working on my end, no matter what query I run, the enum Type does not show up in the introspection query when not in use.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
