### ISSUE TITLE
Support relative imports in inline code / CLI

### ISSUE THREAD

**Issue by joarwilk** [graphcool/prisma#588]
## This feature request applies to the CLI workflow mainly
**What feature are you missing?**

Being able to import another javascript file in my schema extensions / SSRs / pipeline functions.

**How could this feature look like in detail? Tradeoffs?**
Basic use case:
I wish to make a certain logic-heavy operation in a schema extension. This logic is shared by other schema extensions. Right now there is no way to share code between extensions, since calling `require` on a local file will fail in validation/deploy.

A solution would probably be to make the CLI perform some basic bundling of code in the deploy step.

**Comment by kbrandwijk** [comment]
It's actually really simple, here is a working implementation (taken from webtask-bundle). Does babel + requires, would fix the ES7 feature demand as well.

https://github.com/auth0/webtask-bundle/tree/master/lib

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
