### ISSUE TITLE
Backup and restore dashboard in the Console

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#593]
**What feature are you missing?**

A dashboard in the Console that gives an overview about existing backups, create new ones, apply backups to the current or other projects.

**How could this feature look like in detail? Tradeoffs?**

Might even be expanded to a full deployment dashboard, so you could control deployment + data backups + restore there.

**Comment by schickling** [comment]
#610 will also help.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by baerrach** [comment]
Is there a specific issue in graphcool/graphcool-framework we should be watching?

**Comment by marktani** [comment]
[This one](https://github.com/graphcool/graphcool-framework/issues/228) 🙂
