### ISSUE TITLE
Improved infrastructure for service deployment

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#595]
Our current approach to project deployment has several drawbacks:

 - A deployment can be interrupted when a system API server is restarted
 - A deployment can impact performance of system API
 - It is possible to start two deployments at the same time which can leave the project in an inconsistent state that has to be manually repaired.
 - A deployment can take longer to complete than the request timeout on the system API. This causes the CLI to return an error while the deployment is actually silently continuing.
 - The user receives no progress updates during a long-running deployment

This document describes a new approach to project deployment that aims to resolve all these issues. 

### Project Deployment Flow

This describes the flow when no issues arise during a deployment:

1. CLI schedules a deployment. If a deployment is already ongoing the deployment will be rejected
2. The CLI continuously polls for the deployment status and informs the developer with a progress bar
3. When the deployment worker has free capacity it will begin the deployment
4. As a deployment is being carried out, the state of each sub action is being logged so the CLI can show progress to the developer
5. When deployment is completed, the deployment request is marked as such to allow new deployments

### Data structure

We introduce two new tables to track project deployments:

 > Deployment

- id: String `deployment id`
- projectId: String `foreign key to Project table`
- input: String `input to deploy command. This can be quite large`
- state: Enum(scheduled|started|rollingBack|rolledBack|succeeded|failed) `current state of deployment`
- hash: String `a hash of all deployment steps`
- totalSteps: Int `the total number of steps in deployment`
- lastSuccessfulStep: Int `latest successful step`
- lastSuccessfulRollbackStep: Int `latest successful step during a rollback (traversed in reverse)`
- scheduledAt: DateTime `When the deployment was scheduled`
- startedAt: DateTime `When the deployment was started`
- updatedAt: DateTime `When the deployment was last progressed`
- finishedAt: DateTime `When the deployment was finished`

 > DeploymentStep

- id: String `deployment step id`
- deployId: String `foreign key to Deploy table`
- step: Int `the step in the deployment. Steps are executed one at a time`
- name: String `name of the action to perform. For example AddField`

### State transitions

The following state transitions are possible:

- scheduled
  - started `deployment worker begins working`
  - rolledBack `deployment steps does not match worker version`
- started
  - succeeded `all steps were completed successfully`
  - rollingBack `a step failed and deployment must be rolled back`
  - failed `a resumed deploy failed because the worker code is incompatible`
- rollingBack
  - rolledBack `roll back succeeded`
  - failed `roll back did not succeed. Manual intervention required`

### Resilience

The deployment system is designed in such a way that it will be able to return the project to a consistent state in most cases.

**Rollback**

Before a deployment Graphcool verifies that the current state of the project would allow the deployment to succeed. If during the deployment something changes in the project that causes the deployment to fail, we automatically perform a rollback. This allows the developer to correct the issue and try the deployment again. 

One example is making a field unique. If a node is added that violates the unique constraint after the deployment is verified but before it is fully completed, a rollback will be executed.

**Deployment Worker Restart**

As we keep track of each completed step in the deployment, the deployment worker can pick right up where it left before being restarted

Before resuming a deployment the worker re-computes all the steps in the deployment and validates the deployment hash to make sure it is running code that is compatible with the partially completed deployment

**Comment by kbrandwijk** [comment]
Added bonus: disable the endpoints during a long-running deployment, to prevent 'weird' client errors. Instead, return a predictable http status code from the endpoints during deployment.

**Comment by mwickett** [comment]
Are there any updates on the status here?

**Comment by sorenbs** [comment]
Hi @mwickett The improvements described here will be implemented together with the new  migration based deployment system described in https://github.com/graphcool/framework/issues/1263. It would be really helpful if you could take a look at the proposal and provide your feedback.

If you have any immediate issues with deployment you can reach out to support@graph.cool :-)

**Comment by hoodsy** [comment]
Hello! During a `graphcool deploy` to my `local` cluster I ctrl+C'd.

Since then, I encountered the following error and received 500's on DB calls (e.g. `ctx.db.mutation.createUser()`:

```
ERROR: You can not deploy to a service stage while there is a deployment in progress or a pending deployment scheduled already. Please try again after the deployment finished.

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "path": [
        "deploy"
      ],
      "code": 4004,
      "message": "You can not deploy to a service stage while there is a deployment in progress or a pending deployment scheduled already. Please try again after the deployment finished.",
      "requestId": "cluster:cluster:cjbwdrpqo00a50171r0t27biz"
    }
  ],
  "status": 200
}
```

@marktani worked through it with me and ultimately, by deploying to a new stage locally, resolved my issue

**Comment by dpetrick** [comment]
This is implemented (in a similar form, not exactly like the spec here) in the 1.0 Prisma release.
