### ISSUE TITLE
make certain console parts available directly from the endpoint

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#598]
Suggestion: is it possible to make certain parts of the console available directly from the endpoint? Like the playground is available from https://api.graph.cool/simple/v1/{projectid}/, the same could be done for the databrowser (https://api.graph.cool/simple/v1/{projectid}/databrowser) or the project dashboard (https://api.graph.cool/simple/v1/{projectid}/admin).

This would make it easier to integrate these components from for example IDE plugins, or other automated tools (like provisioning tools).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
