### ISSUE TITLE
Add QR codes to the endpoints dialog in the console (and maybe `gc info`)

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#600]
So that I can easily scan it from my mobile to open the playground.

For example: https://chart.googleapis.com/chart?cht=qr&chs=100x100&chld=L&chl=https%3A%2F%2Fapi.graph.cool%2Fsimple%2Fv1%2Fcj6xyadhn03mt01206y6hz9a0

![QR](https://chart.googleapis.com/chart?cht=qr&chs=100x100&chld=L&chl=https%3A%2F%2Fapi.graph.cool%2Fsimple%2Fv1%2Fcj6xyadhn03mt01206y6hz9a0)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
