### ISSUE TITLE
Confirm with the user when using the Console and switching function triggers

### ISSUE THREAD

**Issue by mrwillis** [graphcool/prisma#606]
**What feature are you missing?**
A warning/confirm when switching function triggers (i.e., schema extension -> s.s. sub or pipeline) so that code is not lost if you were editing in the editor and wish to change triggers

**How could this feature look like in detail? Tradeoffs?**
Simple dialog like the one used when you leave the function dialog and didn't save your changes

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
