### ISSUE TITLE
Continuous Deployment (Integrations for GitHub, Heroku, ...)

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#609]
**What feature are you missing?**

Version 0.4 opens up new workflows for continuous integration and deployment. However, this needs to be setup manually and requires some configuration and wiring overhead.

I'd like to kickstart a discussion about a seamless integration that allows you to connect a Graphcool project with a Github project, so that new pushes to the repo will initialize a new deployment.

**How could this feature look like in detail? Tradeoffs?**

### Components

* Ability to connect Github repo + Graphcool project
* Ability to deploy any commit from the repo to the Graphcool project
* Integration with CI, so a pre-deploy script can be executed before deploying, for testing etc.
* A migrations concept (also see https://github.com/graphcool/graphcool/issues/627)
* Multi stage deployments (dev, staging, prod).

### Prior Art

Github integration, Continuous Deployment, Multi stage deployments

* [Heroku](https://devcenter.heroku.com/articles/github-integration)
* [Netlify](https://www.netlify.com/docs/continuous-deployment/)
* [Serverless](https://serverless.com/framework/docs/providers/aws/guide/deploying/)

**Comment by kbrandwijk** [comment]
My first 5 cents on this:

The CI part for me would be:
- Doing a dry-run deploy (see the other FR for that)
- Executing tests

The deploy part for me would be:
- Having a Graphcool integration app on Github. This could be automatically setup using the cli like other Github integrations do (so you don't have to manually setup the webhooks on GH etc.)
- I really like the production/preview/branch concept from netlify
- I like the 'wait for CI to complete' setting on Heroku

Challenges:
- Authentication
- Configuring projectIds for the different environments without committing .graphcoolrc file to GH
- Using environment variables/secrets without committing them to GH
- Seeding (test data setup/production data setup)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
