### ISSUE TITLE
More datacenters for the shared cluster

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#61]
In order to guarantee even better response times there should be additional datacenters in...

- [ ] US East
- [x] US West
- [x] Asia Pacific

Note that private clusters can be hosted in any of these 12 AWS regions:

* us-east-2
* us-east-1
* us-west-2
* us-west-1
* ca-central-1
* eu-central-1
* eu-west-2
* eu-west-1
* ap-northeast-2
* ap-northeast-1
* ap-southeast-2
* ap-southeast-1

**Comment by marktani** [comment]
See #59 as well.

**Comment by malonehedges** [comment]
Here to request US West specifically. I'll be building apps primarily used in the west coast and would benefit greatly from that region.

**Comment by sedubois** [comment]
And could you also please remind where the current data center is? Ireland?

**Comment by marktani** [comment]
That's right

**Comment by mikeroelens** [comment]
+1 for US East. us-east-2 specifically.

**Comment by sorenbs** [comment]
@mikeroelens Can you elaborate on why us-east-2 specifically is important? Would a west cost datacenter provide any value to you at all?

**Comment by tomByrer** [comment]
@sorenbs If someone already has infrastructure in a particular AWS datacenter, it would be a performance benefit for all services would be in the same datacenter.  You know, TCP/IP latency and all :)

I'd suggest building a survey (Google Docs work fine, turn on random shuffle) for current customers to vote on what DC is best for them.  Maybe a first & second choice if you can only support 1 US DC.

**Comment by sedubois** [comment]
If I understand right, this issue proposes to have new locations, and the user would simply manually decide in which datacenter their project would be hosted, right?

How about websites with global presence (like the one I'm working on), what is the current and long-term strategy to ensure a fast response time for users from all major regions on Earth? I guess the data must then be replicated and kept synchronized across the various datacenters, is that planned?

**Comment by abefetterman** [comment]
Casting a vote for us-west-2 !

**Comment by stevewpatterson** [comment]
+1 for us-west

**Comment by sorenbs** [comment]
We are currently beta-testing regions in us-west-2 and ap-northeast-1. Please let me know if you want to be involved :-)

**Comment by aurnik** [comment]
@sorenbs If you need any help with US West I'd love to help!

**Comment by marktani** [comment]
Regions US West (Oregon) and Asia Pacific (Tokyo) are now available: https://www.graph.cool/docs/blog/introducing-regions-and-better-performance-she7yaab6l/

**Comment by k00k** [comment]
+1 for us-east-*

**Comment by glenbray** [comment]
+1 for Australian region - ap-southeast-2

**Comment by sorenbs** [comment]
Hi @glenbray Is there any reason other than performance that you can't use the Tokyo region?

**Comment by glenbray** [comment]
Hi @sorenbs, We collect personal information. Our privacy laws allow us to store offshore, but I'd prefer our data remain within Australia.

**Comment by sorenbs** [comment]
Got it - thanks! 👍

**Comment by sebas5384** [comment]
What about South America? there's an AWS zone in São Paulo, Brazil.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
