### ISSUE TITLE
CLI HTTP/HTTPS Proxy support

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#613]
<a href="https://github.com/JPinlac"><img src="https://avatars1.githubusercontent.com/u/13339045?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JPinlac](https://github.com/JPinlac)**
_Friday Jun 09, 2017 at 13:51 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/90_

----

Could you provide proxy support for people behind a firewall?

Thanks!

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Monday Jun 12, 2017 at 08:28 GMT_

----

Hi @JPinlac! Could you give some examples of other CLI tools that accomplish what you're looking for?

**Comment by schickling** [comment]
<a href="https://github.com/JPinlac"><img src="https://avatars1.githubusercontent.com/u/13339045?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JPinlac](https://github.com/JPinlac)**
_Monday Jun 12, 2017 at 14:03 GMT_

----

An example would be npm or git proxy configuration. 
https://docs.npmjs.com/misc/config#https-proxy

**Comment by schickling** [comment]
<a href="https://github.com/atanaskuzmanov"><img src="https://avatars1.githubusercontent.com/u/12197337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [atanaskuzmanov](https://github.com/atanaskuzmanov)**
_Thursday Aug 10, 2017 at 13:42 GMT_

----

The lack of proxy settings renders graphcool useless in a corporate environment, even though it's supposed to be production ready.
Very graphUNCOOL!
The graphcool-cli is using isomorphic-fetch, which does not seem to have any support for proxies.
It should probably be using an isomorphic-fetch wrapper such as omni-fetch instead to enable proxy support: https://github.com/marionebl/omni-fetch
Can you please fix this?
Raised this under issue: https://github.com/graphcool/graphcool-cli/issues/140

**Comment by schickling** [comment]
<a href="https://github.com/mraak"><img src="https://avatars2.githubusercontent.com/u/812714?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mraak](https://github.com/mraak)**
_Tuesday Sep 12, 2017 at 08:20 GMT_

----

Indeed it is useless in corporate environment.

**Comment by timsuchanek** [comment]
Closing in favor of https://github.com/graphcool/prisma/issues/618
