### ISSUE TITLE
CLI proxy support

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#618]
<a href="https://github.com/atanaskuzmanov"><img src="https://avatars1.githubusercontent.com/u/12197337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [atanaskuzmanov](https://github.com/atanaskuzmanov)**
_Thursday Aug 10, 2017 at 13:46 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/140_

----

The lack of proxy settings renders graphcool useless in a corporate environment, even though it's supposed to be production ready.
Very graphUNCOOL!

The graphcool-cli is using isomorphic-fetch, which does not seem to have any support for proxies:
https://github.com/graphcool/graphcool-cli/blob/master/src/api/GraphcoolAuthServer.ts

It should probably be using an isomorphic-fetch wrapper such as omni-fetch instead to enable proxy support: https://github.com/marionebl/omni-fetch

Token based authentication will hit the same problem: https://github.com/graphcool/graphcool-cli/issues/94

Can you please fix this, it will be greatly appreciated?

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Aug 16, 2017 at 14:40 GMT_

----

Thanks for raising this issue @atanaskuzmanov !
We're currently doing a major rewrite of the CLI and try to incorporate your use case with proxying!

How would an ideal api for providing proxy information look like for you?
Would something like this work for you like [npm](https://docs.npmjs.com/misc/config#https-proxy) does it?
```sh
$ export HTTP_PROXY=http://localhost:8000
$ export HTTPS_PROXY=https://localhost:8000
$ graphcool init
```

**Comment by schickling** [comment]
<a href="https://github.com/atanaskuzmanov"><img src="https://avatars1.githubusercontent.com/u/12197337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [atanaskuzmanov](https://github.com/atanaskuzmanov)**
_Wednesday Aug 16, 2017 at 15:44 GMT_

----

Hi @timsuchanek,

Thank you very much for coming back, much appreciated!

Yes, taking into account the `HTTP_PROXY` and `HTTPS_PROXY` environment vars would work great!

Another feature which can complement this is utilising some dot file, like `.graphcool` for proxy and other graphcool specific settings, but controlling these from env vars would be the first thing to do I think.

Cheers,

**Comment by atanaskuzmanov** [comment]
Nice! Looks like Milestone 0.9 is in progress, does this mean we can be expecting this feature once it is complete?

**Comment by timsuchanek** [comment]
Sorry for the silence about this issue, we're prioritizing this to get it into the 1.7 release.
