### ISSUE TITLE
generate command

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#620]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 05, 2017 at 18:35 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/150_

----

Command to generate Graphcool primitives:
- Functions
  - Subscriptions
  - Resolver functions
  - Operation hooks
- Permissions
  - Permission Queries

**Comment by kbrandwijk** [comment]
I have updated the terminology in the OP to reflect recent changes.

**Comment by marktani** [comment]
Closing for now.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
