### ISSUE TITLE
add generation wizard to init command

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#621]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 05, 2017 at 18:36 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/151_

----

When running init, we should ask first-time users which features they want to use, so they see how these features tie into the graphcool.yml

**Comment by marktani** [comment]
Closing for now.
