### ISSUE TITLE
Yaml validation: Show choices for "one of" error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#624]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 06, 2017 at 08:59 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/160_

----

Message is just cut off at "one  the of the allowed values"

**Comment by kbrandwijk** [comment]
See https://github.com/graphcool/framework/issues/979#issuecomment-342675365

**Comment by timsuchanek** [comment]
Implemented in latest cli.
