### ISSUE TITLE
Include linting/warning to indicate schema rewrites

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#625]
<a href="https://github.com/mavilein"><img src="https://avatars3.githubusercontent.com/u/2470881?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mavilein](https://github.com/mavilein)**
_Thursday Sep 07, 2017 at 09:01 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/169_

----

With `pull` we used to overwrite the schema of the user. We are very liberal in what we accept and then corrected the schema to what we actually do. E.g.:
A user declares a relation as: `comments: [Comment] @relation(...)`
The backend accepts it and rewrites to `comments: [Comment!]! @relation(...)`

With our new one way approach this rewriting won't be visible to the user anymore. So we should put a new feedback cycle in place to inform the user about those things. @schickling's suggestion was to put a linter in place. We still accept the input but inform the user that we treat the input slightly different.

We have a few of those places but could just recall this example right now.

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Thursday Sep 07, 2017 at 11:38 GMT_

----

More examples from the top of my head:
- spaces are trimmed, line breaks etc. 
- system types and fields are automatically added
- input field type of `defaultValue` and `migrationValue` of type string vs. boolean/int etc.

**Comment by schickling** [comment]
<a href="https://github.com/schickling"><img src="https://avatars2.githubusercontent.com/u/1567498?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [schickling](https://github.com/schickling)**
_Thursday Sep 07, 2017 at 12:52 GMT_

----

> system types and fields are automatically added
> input field type of defaultValue and migrationValue of type string vs. boolean/int etc.

Both of this will be removed going forward.

**Comment by marktani** [comment]
Closing for now.
