### ISSUE TITLE
Analytics/Metrics/Monitoring

### ISSUE THREAD

**Issue by Twinski** [graphcool/prisma#63]
Would be cool to monitor the speed/performance of a specific GraphQL query. To see how many effective queries were executed under the hood. 
( for example: https://youtu.be/c35bj1AT3X8?t=41m39s )

This makes sure the developer knows what happens under the hood instead of just relying on 'magic'. :)

> Maybe the amount of queries interests me & also execution time in total (and even better, per individual query under the hood)

**Comment by marktani** [comment]
We are researching possible approaches for analytics/metrics. If you have specific needs for a certain metric, please comment so we can consider it :slightly_smiling_face:

**Comment by philcockfield** [comment]
+1 👍

**Comment by sedubois** [comment]
👍 Besides the granular and aggregate performance monitoring mentioned, I'd like to be made aware of any special spikes e.g if some user starts to send an abnormally high number of requests.

**Comment by jhalborg** [comment]
Maybe look to scaphold for inspiration. A simple(?) but very effective way of getting this feature out to your users quickly would be to offer an Apollo Optics integration for starters (sa scaphold also provides).

**Comment by marktani** [comment]
Thanks for chiminig in, we're indeed planning an Apollo Optics integration here 🙂

**Comment by jhalborg** [comment]
Any ETA on the integration? It's an important factor for the decisionmakers I need to convince :-)

**Comment by marktani** [comment]
Thanks for reaching out in [Slack](slack.graph.cool) - it's tough to give an accurate estimate, but we're giving our best ;)

**Comment by kbrandwijk** [comment]
This has been WIP for a few months. Any news on the Optics integration?

**Comment by marktani** [comment]
We're still working on integrating a monitoring/analytics dashboard into the Console, in a first step it will likely be custom metrics and not a direct Apollo Optics integration.

**Comment by mattfysh** [comment]
Monitoring request: raising alerts when a Function should be invoked, but it is not (related to https://github.com/graphcool/api-bugs/issues/243)

**Comment by kbrandwijk** [comment]
I have created a repo with two examples of how to add your own metrics using Apollo Engine on top of Graphcool endpoints, using the API Gateway pattern and schema stitching:
https://github.com/AgarthaSolutions/graphcool-gateway-apollo-engine-demo

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
