### ISSUE TITLE
Rollback commands when interrupting

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#630]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Sep 09, 2017 at 10:33 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/183_

----

If I manually cancel a command (CTRL+C) like `gc init`, then the project is left in an intermediate state (for example, schema applied, functions and permissions not yet applied.

Please handle user breaks gracefully, for example with a proper library like https://github.com/jtlapp/node-cleanup.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
