### ISSUE TITLE
[1.3.13] Add project name to id in `gc get-root-token` output

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#647]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 22:13 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/217_

----

And everywhere else, preferably. I keep searching for my projects...
`There are no root tokens defined for project 'My Test Project' (cj7gpc3xl0igc0168dwotbm6l)`

**Comment by marktani** [comment]
Closing for now.
