### ISSUE TITLE
Improve root token commands

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#648]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 22:17 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/218_

----

Please explain, either:
- What get-root-token is supposed to do, or:
- How I can get tokens I create in the console into my project file after it's created

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Tuesday Sep 12, 2017 at 09:41 GMT_

----

get-root-token should give you the "content" of a token with a specific name.
The local `rootTokens` field in the `graphcool.yml` should be there to create new root tokens by a specific name.

So creating rootTokens should be done with the graphcool.yml, getting them via the command.
Creating is currently ignored, but that will be fixed soo.

Besides that, do you think this can still be confusing?

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 12, 2017 at 10:44 GMT_

----

I think there shouldn't be a use case for getting the contents of root-tokens. If you use inline functions, they should be passed in the context, if you're using external webhooks, they should also be passed somehow.
Also, refer to my other FR about authentication using clientId/clientSecret, as tokens are a little bit heavy to handle.

What's the use case you are thinking about for getting the content of a rootToken?

**Comment by schickling** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Wednesday Sep 27, 2017 at 14:45 GMT_

----

Root tokens are very useful for server-side scripts, or integrating with external services.
A specific example would be an admin panel with a few data creating forms.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Sep 27, 2017 at 14:59 GMT_

----

In that case, could you improve on the workflow. Maybe `gc token add` to add it to the graphcool.yml, and `gc deploy` could show the value for a new token when one is added, so I can use it directly? Now, I have to do:

- Edit graphcool.yml, add a new rootToken name manually
- Do `gc deploy`
- Do `gc get-root-token` to get the actual value

**Comment by marktani** [comment]
The situation is already improved by the automatically injected root tokens for functions. We'll rethink this workflow further down the road.

**Comment by marktani** [comment]
Closing for now.
