### ISSUE TITLE
[1.3.13] Add interactive project selection to commands that require project

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#650]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 11, 2017 at 22:47 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/224_

----

For example, `gc env:set`. Maybe others too.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
