### ISSUE TITLE
Lengthy error message when projectid not found

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#671]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Sunday Sep 24, 2017 at 21:38 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/263_

----

If you try to deploy to a projectid in your .graphcoolrc file that does not exist, you get a response dump with the error.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
