### ISSUE TITLE
Change function tail to websocket instead of polling

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#674]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Tuesday Sep 26, 2017 at 13:29 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/268_

----

Makes it easier to integrate into different solutions.
Also, if you keep the polling, make the polling interval configurable (currently hardcoded at 4000 ms).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
