### ISSUE TITLE
Bug in the console UI for permissions submit button

### ISSUE THREAD

**Issue by michaelpumo** [graphcool/prisma#693]
**What is the current behavior?**
Submit button for permission is greyed out in the console when it should be active.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
This video will make it easier to illustrate what's going on:
https://streamable.com/s/hvr5o/wzltfv

**What is the expected behavior?**
Button should be highlighted to submit when settings are made.

Thanks!

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
