### ISSUE TITLE
Deleting a type in the console breaks the UI (appears to resolve on refresh)

### ISSUE THREAD

**Issue by eruby94** [graphcool/prisma#695]
**What is the current behavior?**
When you attempt to remove a type through the console via edit, then delete, there are a boatload of console errors thrown and the UI freezes up

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
Go to any project, and for a user created type, try to delete it, and watch the chaos ensue

**If applicable, share the query, mutation or subscription for reproduction**
Don't think this applies here

**What is the expected behavior?**
The console should delete the node successfully, and return control of the UI back to the developer

**Comment by eruby94** [comment]
![](https://files.slack.com/files-pri/T0MQBS8JG-F7ATZHQF5/screen_shot_2017-09-29_at_10.58.01_am.png)

![](https://files.slack.com/files-pri/T0MQBS8JG-F7AEZD057/screen_shot_2017-09-29_at_10.58.16_am.png)

**Comment by eruby94** [comment]
![screen shot 2017-09-29 at 10 58 01 am](https://user-images.githubusercontent.com/12565404/31021975-7904a3dc-a505-11e7-9225-6a43fc65b8e4.png)
![screen shot 2017-09-29 at 10 58 16 am](https://user-images.githubusercontent.com/12565404/31021987-7bab485c-a505-11e7-8158-195b184ea95a.png)

**Comment by marktani** [comment]
Can confirm - reloading brings it back in order.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
