### ISSUE TITLE
Renaming a relation field is not recognized as a change

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#700]
**What is the current behavior?**

Changing only the name of a relational field in `types.graphql` is not picked up as a change by `graphcool deploy`.

Original types:

```graphql
type User {
  id: ID! @isUnique
  name: String!
  posts: [Post!]! @relation(name: "UserOnPost")
}

type Post {
  id: ID! @isUnique
  title: String!
  user: User! @relation(name: "UserOnPost")
}
```

Intermediate types:

```graphql
type User {
  id: ID! @isUnique
  name: String!
  posts: [Post!]! @relation(name: "UserOnPost")
}

type Post {
  id: ID! @isUnique
  title: String!
  author: User! @relation(name: "UserOnPost")
}
```

Running `graphcool deploy` tells me the project definition is identical.

**What is the expected behavior?**

Either:

* The renamed relational field should be detected and the change should be applied.

Or:

* The renamed relational field should be detected, and the user should be prompted to use `@rename`.

**Comment by marktani** [comment]
Not sure how much this overlaps with the migration concept, #627.

**Comment by welf** [comment]
I think it is the same bug as here: https://github.com/graphcool/graphcool/issues/764

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by robbyemmert** [comment]
Can you mention the issue this is being tracked on? I need to be able to rename relations without resetting my production database.

Thanks!

**Comment by Kisepro** [comment]
Any update about this ?
I still face the problem with onDelete
