### ISSUE TITLE
Allow for incremental deployments

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#710]
For a number of use cases, it would be useful to deploy two different projects to the same Graphcool project, without overwriting, so a merge deploy.

**Comment by kbrandwijk** [comment]
Okay, let me elaborate. I like to combine multiple local 'projects' into one Graphcool project. So I would have two different local folders, both with a graphcool.yml file, pointing to the same Graphcool projectId. One local project would contain a number of types and functions, the other local project would also contain different types and functions. I would like to deploy from both local project folders to the same Graphcool project.

**Comment by sorenbs** [comment]
@kbrandwijk Does modules not solve this use case?

**Comment by kbrandwijk** [comment]
No, modules do not solve this. Even with modules, the deployment to Graphcool is monolithic. I can only have one deployment that deploys everything. This FR is about allowing multiple deployments to the same Graphcool project.

**Comment by marktani** [comment]
Closing for now.
