### ISSUE TITLE
Increase connection between copied projects

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#72]
Imagine an original project and a copied 'child' project. Once you set up a parent-child connection like that, being able to overwrite the child by simply clicking a button in the parent project would be great.

* endpoint stays the same
* no need to remove old children and copy a new project

**Comment by lewisblackwood** [comment]
This would be helpful for us.

My particular use case would be having multiple databases that tracked the same schema. For example, I'd like individual development, staging and production databases. Updating a master schema would copy changes across to those three. I'd want three different endpoints to set as environment variables for the apps in my Heroku pipleline.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
