### ISSUE TITLE
Read permissions for relation fields

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#724]
Currently it is possible to use the permission system to define read permissions on specific scalar fields on a model. For example, I can specify that only members of a group can read the group name:

```graphql
type Group {
  name: String!
  members: [User!]
}
```

In addition I would like to be able to specify that only members of the group can see other members.

This will allow me to model situations where I am friends with Lisa (and therefore am allowed to see her name), but as we are not in the same group, I won't be able to see that she is member of the group.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
