### ISSUE TITLE
Create a graphcool-utils npm package

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#736]
This would be a package that can be required in Graphcool functions, and would provide a set of common utility functions.

The templates/functions repo's are great for 'full' solutions, but on a more granular level, it would be nice to have this package, because it offers an easier way to reduce small bits and pieces, within the community.

Examples:
- generate slug
- geolocate
- concurrency check (version field)
- increment field
- validation functions
- ...

It would have a more 'technical focus', where the functions and templates libraries offer the more functional building blocks.

**Comment by FredyC** [comment]
Personally, I don't see a purpose in this. All these things you have mentioned can be found more or less in NPM modules which you can use. Grouping them in some "utils" module is kinda opinionated as everyone has rather specific needs. As long as it's not graphcool specific, it's not useful imo.

**Comment by kbrandwijk** [comment]
If you look at the questions and FR's, you notice that a lot of people run into the same issues, and try to solve the same problems. This is the reason why there's so much community activity in the functions/templates/modules repo. The issue is (and that's become more apparent with the module/template discussion) that reusing those bits and pieces seems hard. While the template/module concept is great for solving larger functional issues, there's also a lot of GraphQL/Graphcool specific repetitive boilerplating going on in everybody's functions.
While I agree with you that existing npm modules help implement those features, it's bridging the gap between what those modules offer and how to apply those to Graphcool functions, is the area I'm focusing on with this proposal.

**Comment by FredyC** [comment]
Ok if anything, there could be a help document in style of FAQ and be pointing to recommended NPM modules. Duplicating code to some common library is a lot of work in maintaining it and solving other people problems. If you have time for that, be my guest, but I think there are other painful things that Graphcool needs to address first ;)

But honestly, is Graphcool a service that should teach people how to write apps? These small bits and pieces of code are part of an app and people just need to learn how to modularize their code.

**Comment by marktani** [comment]
Closing this for now.
