### ISSUE TITLE
New function added in UI is deleted by CLI

### ISSUE THREAD

**Issue by FredyC** [graphcool/prisma#737]
**What is the current behavior?**

In the ejected project there is a New Function button that works same as in legacy mode. However, any function created by this is simply removed when deploying with CLI. 

Besides, it's not possible to edit functions afterward, which only adds to a confusion.

**What is the expected behavior?**

It's kinda dangerous behavior as someone might create a function like this, forget about it and then it would get deleted accidentally.

I would say this button should no longer be there for ejected projects to avoid confusion.

**Comment by kbrandwijk** [comment]
So, you have a local workflow, that you use for source control, for deploying, and for everything else. And you would create a function in the console, to subsequently forget about it, as it gets accidentally removed?

I agree with you that it shouldn't be possible to create functions in the console for ejected projects, but I don't think it's actually dangerous.

**Comment by FredyC** [comment]
I've used the console to create a stub for a subscription function. It is inherently easier than typing all of that common stuff in the code/config. I was kinda hoping that CLI will notice that new function and pull it, but it got deleted instead.

Unless CLI will support generating these stubs, it's perhaps still easier to have that in Console, but function created like that would probably need to have some special flag so CLI know to pull it instead of deleting it.

**Comment by marktani** [comment]
Please note that **modifying functions, schema, permissions of a project from both the CLI and Console is NOT supported**, for exactly the reason you mentioned.

The Console already hides the UI elements to modify those parts of a project, but should be smarter in giving you a warning when you do try to edit stuff, or prevent it alltogether.

**Comment by FredyC** [comment]
I am well aware it does not work both ways, I just wanted to point for a button in UI that essentially should not be there ;)

**Comment by marktani** [comment]
The whole `/functions` route is 'not there'. But yes, I get your point.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
