### ISSUE TITLE
Watch mode for local development

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#751]
A `gc deploy --watch` mode could massively speed up local development. A native implementation of this would be to run `gc deploy` every time a local file has been changed.

Before implementing this feature we should discuss possible implications of this especially around:

* function bundling
* database migrations
* large service definitions

**Comment by kbrandwijk** [comment]
Related (possibly): implementing this might help get my request for incremental deployments going :crossed_fingers:

**Comment by marktani** [comment]
This is implemented in the latest preview 🙂

**Comment by antho1404** [comment]
I know this is still a work in progress but I saw the option on the CLI so I couldn't resist to try it and I got the following error few times, in case you didn't had this error yet

```
<--- Last few GCs --->

[10519:0x103000000]   505154 ms: Mark-sweep 1408.6 (1464.9) -> 1408.6 (1445.9) MB, 3784.5 / 0.1 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3785 ms) last resort
[10519:0x103000000]   508892 ms: Mark-sweep 1408.6 (1445.9) -> 1408.6 (1445.9) MB, 3736.4 / 0.1 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x252cc879cef1 <JSObject>
    1: _process [/Users/antho/prog/etherstellar/functions/node_modules/glob/glob.js:~298] [pc=0x3ef0d7a40983](this=0x8283c88d2a1 <Glob map = 0x3a2261b88921>,pattern=0x39f1036b5941 <JSArray[4]>,index=0,inGlobStar=0x252cc87822c1 <true>,cb=0x8283c88d211 <JSFunction done (sfi = 0x3c03996f5cc1)>)
    2: /* anonymous */ [/Users/antho/prog/etherstellar/functions/node_modules/glob/glob.js:~625] [pc=0x3e...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::LoadIC::LoadFromPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Smi>) [/usr/local/bin/node]
 6: v8::internal::IC::ComputeHandler(v8::internal::LookupIterator*) [/usr/local/bin/node]
 7: v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [/usr/local/bin/node]
 8: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
 9: v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x3ef0d76040dd
```

**Comment by Toosick** [comment]
I'm on 0.8.0. I tried the watch flag and it said bundling functions forever. Does this CLI option work?

**Comment by ntziolis** [comment]
I'm on latest gc version + windows. on any change (even just adding a semi colon at the end of a line) I'm getting:
`'ENOTEMPTY': ENOTEMPTY: directory not empty, rmdir 'C:\Users\nikol\Documents\git\assault-backend\.build'`  
SO same question as OP, does this option work? Is it considered to be work in progress? if you guys need folks for testing especially on win lmk. This one is kind of important for us.

**Comment by chromonav** [comment]
it is not working is there any way to fix this issue?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).

**Comment by warrenday** [comment]
This issue still exists. However you can create your own file watcher like:

`const { spawn } = require('child_process');
const watch = require('node-watch');
 

let commandComplete = true;
watch('./src', { recursive: true }, function(evt, name) {
  if (!commandComplete) {
    // Do not run until last deploy has finished
    return;
  }
  commandComplete = false

  console.log('%s changed.', name);
  console.log('graphcool deploy')

  // Run command to rebuild
  const ls = spawn('graphcool', ['deploy']);

  ls.stdout.on('data', function (data) {
    console.log(data.toString());
  });
  
  ls.stderr.on('data', function (data) {
    console.log(data.toString());
  });
  
  ls.on('exit', function (code) {
    commandComplete = true
  });
});`
