### ISSUE TITLE
Discovery of templates

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#755]
CLI tools that use plugins or similar often use the following strategy to 'discover' their plugins:

- When publishing an NPM module, specify a certain keyword or keywords
- CLI command searches the NPM registry for packages with that keyword to display

The idea is that you could have a command `graphcool templates ls` or `list` to discover available templates.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
