### ISSUE TITLE
`gc init` template argument

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#756]
As mentioned [here](https://github.com/graphcool/graphcool/issues/720#issuecomment-333532412) in the "Proposal: Templates #720" discussion, we need to redefine the `gc init` template workflow.

The initial idea behind this feature was to speed up the service bootstrapping process by already providing common functionality. As mentioned in #720 "templates" are now smaller building blocks which can be combined into services.

## Open Questions

- [ ] Can templates (based on #720) be used and composed directly to bootstrap new services? If not what's a more appropriate concept?
- [ ] Should the injected code be commented-out by default or enabled since there is no prior code available?
- [ ] Should multiple templates be allowed at the same time? If so, how should conflicting definitions be handled?

**Comment by kbrandwijk** [comment]
I think this plays very well with the template concept. `gc init --template` should behave the same as `gc add-template`. I don't see a reason to have different behavior for initializing with a template, or adding a template later on.

That also still plays well with additional improvements in template discovery (#755 and #637).

Injected code should not be commented out in my opinion, as you deliberately pick a template yourself.

What do you mean by 'multiple services'?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
