### ISSUE TITLE
Function invocation not logged when returning the wrong data format from resolver

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#761]
**What is the current behavior?**
When the wrong data format is returned from a resolver function, an error is returned, but the invocation of the function is not logged at all.

**What is the expected behavior?**
Every invocation should be logged.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
