### ISSUE TITLE
Can't rename a field in schema in console.graph.cool

### ISSUE THREAD

**Issue by welf** [graphcool/prisma#780]
For **bug reports**, please fill in the next sections:

**What is the current behavior?**

If I try to rename a field in my schema, I can't do it. As I rename a field, the schema name shows schema was changed (I see `*` symbol next to the schema name), but hitting "Apply changes" button doesn't change the name of the field and doesn't remove the `*` symbol. 

Next, I tried to add/delete another field to apply the new name to the field mentioned above. After hitting "Apply changes" it adds/deletes the field, but renamed field gets its old name. 

I've recorded a video, so you can see how it happens:

![Screen record of bug](https://files.graph.cool/cj8n3bpgs0rji01670ch7mwqg/cj8on31vu03cx0179671rn2xa)

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
```
# projectId: cj8n3bpgs0rji01670ch7mwqg
# version: 10
```

**What is the expected behavior?**

The user should be able to rename the field in his schema.

**Comment by kbrandwijk** [comment]
Unfortunately, the video is too big. Did you specify a `@rename(oldName: "...")` attribute on the field you are renaming?

**Comment by welf** [comment]
@kbrandwijk Yes, it does work, thanks!

**Comment by welf** [comment]
@kbrandwijk The screen record is here: https://files.graph.cool/cj8n3bpgs0rji01670ch7mwqg/cj8on31vu03cx0179671rn2xa

**Comment by welf** [comment]
@kbrandwijk It would be nice if Graph.cool detects field renaming and asks a user to add a `@rename` directive.

**Comment by kbrandwijk** [comment]
That used to be part of the console, but it caused more harm than good, because it was also added when, for example, you would copy a field and then rename it. It would be a new field, but 'touching' the existing field would at the attribute. That's the thing, when editors do to much automagically, you'll always reach an equilibrium with an equal amount of 'good' and 'bad' cases :smile:

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
