### ISSUE TITLE
Port bindings for local deployment

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#787]
Are there other options than `0.0.0.0` and `127.0.0.1`? Could it be configurable?

See https://github.com/graphcool/graphcool/issues/766#issuecomment-335972452 and https://github.com/graphcool/graphcool/issues/752#issuecomment-335032432.

**Comment by kbrandwijk** [comment]
I think the easiest option is make this configurable using an environment variable or command-line parameter.

**Comment by rwatts3** [comment]
I think this could really use an walk through from the core team for Docker Toolbox, the new features are almost impossible to use when you're on a windows 7 pc with docker toolbox which uses virtualbox. 
It seems as if the command line or the local service is unreachable to the docker virtualbox, therefore sends the user in a medley of loops for authentication when trying to deploy a local project to docker. For starters, I believe the internals of the local cluster are still expecting http://localhost:60001 , where the application is not available at localhost it's available at the docker machine's ip address which in this cases happens to be something along the lines of 192.168.99.100 or something else.

**Comment by arenowebdev** [comment]
I confirmed @rwatts3 hunch this evening by enabling debug mode on Mac with Docker Toolbox and found the initial `graphcool local up` command was pinging `http://localhost:60000/system` and my system is only responding on the docker-machine IP of `192.168.99.100:60000`, which I know as if I hit that `/system` page in the browser at that IP address I do get the working Playground.

**Comment by jbonigomes** [comment]
I am new to Docker, currently, is there a way to `graphcool local up` using `0.0.0.0` rather than `localhost`?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
