### ISSUE TITLE
Add `subscriptionEndpoint` field to the project info in the System API

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#793]
**What feature are you missing?**
Because subscription endpoints are dynamic based on region, you need to manually construct it based on the project region. A lot of code (in CLI, console, etc.) uses a duplicated switch to construct the endpoint. It makes more sense to add it to the System API, so it's not constructed manually, and not sensitive to breaking changes if the subscription endpoint would ever change.

**How could this feature look like in detail? Tradeoffs?**
A field on `Project`.

Also, see https://github.com/graphcool/graphcool-lib/issues/10 for another usecase for this.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
