### ISSUE TITLE
Building functions with native modules should be possible without Docker

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#795]
Making Docker a requirement to be able to build functions with native modules imposes some serious restrictions on your environment. Not every environment can run Docker containers easily.

- Windows environments with Hyper-V enabled
- Online IDE's based on Docker
- Workspaces with limited resources (SSH micro instances, Raspberry Pi and similar)
- CI environments

Not being able to run docker in every environment is fine if you opt out of using the local deployment workflow. But when it becomes a requirement to deploy your functions, that's a problem.

Would it be an option just to have a docker container / EC2 instance running on Graphcool infrastructure that can function as a build server?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
