### ISSUE TITLE
Enhance PATs

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#80]
* read/write access
* read/write access for specific types/fields
* expiration duration

**Comment by marktani** [comment]
Thanks to @lastmjs for this detailed write up:

> Right now permanent auth tokens provide full read and write access to everything in the database, as far as I understand. Blanket access is undesirable, as I'm sure there are use-cases where you want more fine-grained control. For example, I have a small server function that needs access to only a few entities in my schema, but the permanent auth token I'm using for that server function has access to the entirety of the database. That leaves a larger possible attack vector that is unnecessary.
>
> My proposal is that permanent auth tokens are assigned to a special type of user unique to the permanent auth token (i.e. a server user). That way authorizations and permission queries could work exactly as they do currently. All you would need to do is reference the user id or other properties of the user associated with the permanent auth token.
>
> Anyway, those are my thoughts on the matter.

**Comment by kbrandwijk** [comment]
Let's make it more generic then, and create the option to generate/revoke a permanent token for any user. That way, you don't need any special functionality for PATs beyond that.

**Comment by kbrandwijk** [comment]
Alternatively, when using Auth0 integration, it would be nice to be able to use their non-interactive client functionality, so you can generate those client ID's in the same place.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
