### ISSUE TITLE
API Gateway

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#801]
Graphcool enables you to create a CRUD-style GraphQL API.

## API Gateway

It is a common pattern to deploy an API Gateway in front of the CRUD-API to transform the auto-generated Graphcool schema and merge it with APIs from external systems or legacy applications.

Graphcool should make it easy to deploy an API Gateway as a serverless function developed with familiar tools:

- [Apollo Server](https://github.com/apollographql/apollo-server)
- [Schema stitching](https://dev-blog.apollodata.com/graphql-schema-stitching-8af23354ac37)
- [graphql-transform-schema](https://github.com/graphcool/graphql-transform-schema)

### Configuration

Ideally it should be possible to define the gateway function for a service in the `graphcool.yml` definition file.

### Url Structure

When deploying a service, the CLI lists available endpoints. We should simply add a gateway endpoint:

```
Simple API:        https://api.graph.cool/simple/v1/cj8pzhz3i00t20155jmjr5pxh
Relay API:          https://api.graph.cool/relay/v1/cj8pzhz3i00t20155jmjr5pxh
Subscriptions API: wss://subscriptions.us-west-2.graph.cool/v1/cj8pzhz3i00t20155jmjr5pxh
Gateway API:     https://api.graph.cool/gateway/v1/cj8pzhz3i00t20155jmjr5pxh
```

### Disable CRUD-APIs

When a Gateway API is deployed, it should be possible to lock down access to CRUD APIs.

**Comment by marktani** [comment]
[`graphql-yoga`](https://github.com/graphcool/graphql-yoga/) and [`prisma-binding`](https://github.com/graphcool/prisma-binding/) are two great tools to tackle this situation.
