### ISSUE TITLE
Improve the environment variable experience

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#810]
**What feature are you missing?**
An easy way to work with stage-specific environment variables.

**How could this feature look like in detail? Tradeoffs?**
I proposed the `dotenv` standard a while ago. That idea was discarded because the .graphcoolrc file structure wasn't a good fit for it. With the new structure, I think it's feasible to reconsider that decision.

If I have different secret environment variables for different stages, I can put them in the project file in the latest alpha, which exposes them when using git. So that's not an option. I can also use something like `direnv`, but that doesn't work well on Windows, and also, I don't have a seperate folder for each stage, so that approach doesn't work well either.

Unless there's another way I'm missing, I still don't have a proper solution for stage-specific env vars.

**Comment by maticzav** [comment]
Is this available already?

**Comment by jonasdumas** [comment]
+1
Any update about that ?

**Comment by marktani** [comment]
This should be covered by https://github.com/graphcool/framework/issues/1461.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
