### ISSUE TITLE
node_modules and deploying graphcool 

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#816]
It's important to make it clear that the service definition should live in a separate folder, because `graphcool deploy` bundles the `node_modules` folder in the current directory.

**Comment by schickling** [comment]
@marktani this kind of CLI functionality is pretty difficult to implement. The @serverless framework also still seems to struggle with this. My suggestion is to open a separate issue for the CLI functionality and tackle this further down the road.

**Comment by Toosick** [comment]
Serverless webpack is pretty smart and only bundles things that are actually part of the handler code. I also see the need for bundling files and directories based on a glob. I tried looking at the source for the CLI but gave up and put the service definition in its own folder for now. Ideally I don't won't to zip up everything in the project (I would like the graphcool.yml to be at the root of the project and specify what I want). I obviously don't want to package up my front end source code and resources. Somewhere you should mention that the bundler is literally bundling everything (I was puzzled why the deploy was taking 250 seconds).

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
