### ISSUE TITLE
provide automatic versioning of model data

### ISSUE THREAD

**Issue by balupton** [graphcool/prisma#82]
it would be nice if every change of model data created a new version of that particular model item - such that one can go back and revert a previous model item or cycle through revision history of a model item

**Comment by schickling** [comment]
That's a really interesting idea, @balupton. Would you imagine that only the newest model version is exposed via the GraphQL schema? How would you want to access older versions of the schema?

**Comment by balupton** [comment]
yeah, by default only the latest model is exposed, older versions can be returned by passing a version field

**Comment by schickling** [comment]
I'd love to further explore this feature. Can you ping me on our [Slack](https://slack.graph.cool)?

**Comment by sorenbs** [comment]
What should happen when the model schema changes?

Say the Photo model looks like this:

```graphql
type {
  url: String!
}
```

and has this data:

```graphql
{url: "some.url"}
```

now you change the model like this:

```graphql
type {
  url: String!,
  title: String!
}
```

with a migration value for the `title`.

If you want to query the old values through the same schema we would have to apply the migration value to historical nodes. Ie:


```graphql
{
  allPhotos(version:1){
    title
  }
}
``` 

would return the migration value.

Do you think this is reasonable?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
