### ISSUE TITLE
Subscription does not trigger when using variable for mutation_in

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#820]
**What is the current behavior?**
When you try to use an enum value in a subscription variable, the subscription does not trigger. In the playground, the subscription starts succesfully, but never gets any results.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
```graphql
type User @model {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```
```graphql
mutation{
  createUser{id}
}
```
**If applicable, share the query, mutation or subscription for reproduction**
This one works:
```graphql
subscription{
  User(filter: {mutation_in: [CREATED]}){
    node{
      id
    }
  }
}
```
This one doesn't:
```graphql
subscription($filter: [_ModelMutationType!]){
  User(filter: { mutation_in: $filter}){
    node{
      id
    }
  }
}
```
with variables:
```json
{"filter": ["CREATED"]}
```
This one also doesn't work:
```graphql
subscription($filter: UserSubscriptionFilter){
  User(filter: $filter){
    node{
      id
    }
  }
}
```
with variables:
```json
{"filter": { "mutation_in": ["CREATED"] }}
```
**What is the expected behavior?**
The subscription is triggered in all cases.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
