### ISSUE TITLE
Analyze node_modules when deploying

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#837]
The CLI should employ logic that makes sure `node_modules` does not contain packages that are not required in any function.

**Comment by kbrandwijk** [comment]
Is this really the responsibility of the CLI? Even the AWS/Serverless CLI just takes whatever is there, and zips and deploys it. If you really want to integrate this functionality in the CLI, have a look at a package like https://github.com/depcheck/depcheck.

**Comment by marktani** [comment]
Good point, this is rather a "long-term" feature. See #816 for more context.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
