### ISSUE TITLE
Graphcool Function webhook is not taking providing header.

### ISSUE THREAD

**Issue by nishantvarshnay** [graphcool/prisma#842]
Hi,

I am trying to test graph cool function by using test run in webhook option.
I have put url and header but in response show Not Authorization Error.

By Same details on Rest Client, it is working as expected.

Please suggest what should i do?

**Comment by marktani** [comment]
Hey @nishantvarshnay, can you provide a reproducible example?

**Comment by nishantvarshnay** [comment]
![1](https://user-images.githubusercontent.com/26719798/31611308-328f8aa6-b299-11e7-91f1-5519203f6d0f.PNG)
![2](https://user-images.githubusercontent.com/26719798/31611310-32dab058-b299-11e7-83a7-544095b623ac.PNG)
Please refer screen shot

**Comment by nishantvarshnay** [comment]
any update on it?

**Comment by marktani** [comment]
Did you read my reply? 🙂

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
