### ISSUE TITLE
Test run doesn't work when SSS query contains DateTime element

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#843]
_From @marktani on July 31, 2017 20:37_

**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**

`DateTime` values generated in Test Run are invalid.

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**

Create a new project and type:

```graphql
type Item {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

Create a new SSS with this query:

```graphql
subscription {
  Item(filter: {
    mutation_in: [CREATED]
  }) {
    updatedFields
    node {
      id
      createdAt
    }
  }
}
```

with the default function and execute the function in test run. Even though `createdAt` is set to `null` in the example event, you get the error message

> "Expected a value of type \"DateTime\" but received: 2017-07-31T20:33:13.657Z",

This error message does not change, no matter what you set `createdAt` to. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1780597/28797202-b974da8e-7640-11e7-9120-06fa52f2db19.png)

**What is the expected behavior?**

The `DateTime` value should not be initialized with `null` and should also be passed to the function correctly.

_Copied from original issue: graphcool/console#1251_

**Comment by marktani** [comment]
Current workaround: test the function by running a mutation from the Playground instead of using Test Run.

**Comment by nishantvarshnay** [comment]
How can i test in playground?

**Comment by marktani** [comment]
A subscription function is triggered by mutations according to the subscription filters you provided. In the above example, you could test the function in the Playground by running this mutation:

```graphql
mutation {
  createItem {
    id
  }
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
