### ISSUE TITLE
Update terminology for Permission Query variables

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#851]
For example, instead of `$user_id`, another word might be better.`$auth_node_id`?

Care has to be taken to choose a name that's not to be confused with `$node_id`.

**Comment by kbrandwijk** [comment]
`$token_node_id`, or just `$auth_id`?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
