### ISSUE TITLE
Specify what field is displayed for relations in the databrowser

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#86]
Right now, the databrowser displays the id of the related node. Imagine a `Colors` model with the `name` field. Now it would be helpful to see the color name (e.g., `red` or `blue`) instead of the id for related nodes.

Thanks to @arrygoo for the suggestion :pray:

**Comment by marktani** [comment]
One possible approach here would be to use a custom directive in the schema file, for example `@label`, that is used to express the field of the node that will be used for representation:

```graphql
type Color {
  id: ID! @isUnique
  name: String! @isUnique @label
  rgb: String
}
```

I would love to hear feedback for this idea 🙂

**Comment by kbrandwijk** [comment]
An alternative would be to have a directive on the Type, and specify a template string. This would allow more flexibility.
```
type Color @label(`${name} (${rgb})`) {
  id: ID! @isUnique
  name: String! @isUnique
  rgb: String
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
