### ISSUE TITLE
Permission editor shows node_id variable for create operations

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#861]
![pasted image at 2017_10_16 07_53 pm 1](https://user-images.githubusercontent.com/1780597/31636969-ee0770fe-b2cc-11e7-9b1a-2aed68a24218.png)

this variable is not available for create operations.

**Comment by kbrandwijk** [comment]
Seems taken care of by the added description:
![image](https://user-images.githubusercontent.com/852069/32140692-1e096658-bc6a-11e7-8277-69b545fc3c96.png)

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
