### ISSUE TITLE
Allow use of other pubsub 

### ISSUE THREAD

**Issue by bschwartz757** [graphcool/prisma#878]
**What feature are you missing?**
GraphQL currently allows the use of other pubsub engines (e.g. Redis) and there is an official(-ish) module to implement it: https://github.com/davidyaha/graphql-redis-subscriptions. 

I followed the Vue-Apollo tutorial on How to GraphQL and was unable to figure out how to make this work with the Subscriptions portion of the tutorial.
**How could this feature look like in detail? Tradeoffs?**
The implementation appears to be pretty straightforward:
```
import { RedisPubSub } from 'graphql-redis-subscriptions';
const pubsub = new RedisPubSub();
const subscriptionManager = new SubscriptionManager({
  schema,
  pubsub,
  setupFunctions: {},
});
```
However, it requires modifying the GraphQL server implementation:
```
import { PubSub } from 'graphql-subscriptions';
export const pubsub = new PubSub();
import { createServer } from 'http';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';
import { schema } from './my-schema';

const WS_PORT = 5000;

// Create WebSocket listener server
const websocketServer = createServer((request, response) => {
  response.writeHead(404);
  response.end();
});

// Bind it to port and start listening
websocketServer.listen(WS_PORT, () => console.log(
  `Websocket Server is now running on http://localhost:${WS_PORT}`
));

const subscriptionServer = SubscriptionServer.create(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server: websocketServer,
    path: '/graphql',
  },
);

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
