### ISSUE TITLE
Many subscription events in quick succession - some events are skipped

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#886]
_From @sorenbs on March 31, 2017 15:28_

In the playground, start a simple subscription:

```graphql
subscription{
  Issue{
    node{
      id
    }
  }
}
```

In a new playground tab, manually execute a mutation 12 times in a row.

```graphql
mutation {
  createIssue(d: B, date: "2020", published: true, title: "lala"){
    id
    title
  }
}
```

Observe that only 8 events appear in the playground, even though the websocket actually receive all 12 events:

![image](https://cloud.githubusercontent.com/assets/281337/24557238/4a49e7e4-1637-11e7-9da4-c9d29cf9d4b4.png)

_Copied from original issue: graphcool/console#799_

**Comment by mwickett** [comment]
I think this is more than just a playground issue. I'm seeing this happening with a subscription based function in our application where a different function (operation) sets multiple records in a different collection to `true`. We have subscription function firing on updates to that field, and it's the incoming data stream is missing some of the records.

**Comment by marktani** [comment]
Hey @mwickett can you create a separate issue for this? If you could nail it down to a small minimal reproduction, that would be much appreciated, too! 🙂

**Comment by mwickett** [comment]
I believe I sorted out an issue with my function, so false alarm. Sorry about that!

**Comment by lewisblackwood** [comment]
Hey @marktani - I've observed this issue in the playground too. But I've also observed another issue with subscriptions that's causing us problems.

If I toggle a boolean field on one of my records, then the node returned in the subscription does not always contain the correct data. For example, my `Hire` type has a boolean field `sessionsAddedToCalendar`. If I register the subscription:

```javascript
subscription updatedHire {
  Hire(
    filter: {
      mutation_in: [UPDATED]
    }
  ) {
    mutation
    node {
      sessionsAddedToCalendar
    }
  }
}
```

and toggle the field in the console, I'm often seeing playground output like this:

```javascript
{
  "data": {
    "Hire": {
      "mutation": "UPDATED",
      "node": {
        "sessionsAddedToCalendar": false
      }
    }
  }
}

{
  "data": {
    "Hire": {
      "mutation": "UPDATED",
      "node": {
        "sessionsAddedToCalendar": true
      }
    }
  }
}

{
  "data": {
    "Hire": {
      "mutation": "UPDATED",
      "node": {
        "sessionsAddedToCalendar": true
      }
    }
  }
}

{
  "data": {
    "Hire": {
      "mutation": "UPDATED",
      "node": {
        "sessionsAddedToCalendar": true
      }
    }
  }
}

{
  "data": {
    "Hire": {
      "mutation": "UPDATED",
      "node": {
        "sessionsAddedToCalendar": false
      }
    }
  }
}
```

I don't think events have been skipped - the total number is correct. It's that the updated node doesn't reflect the correct information. It should go `false` -> `true` -> `false` -> `true` -> `false`.

Is there any way to fix this? We've only noticed it recently, but it's causing lots of inconsistencies on our client app 😬

**Comment by marktani** [comment]
Hey @lewisblackwood just saw this - could you please provide a reproduction for this in a new issue? 🙂

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
