### ISSUE TITLE
mutations for models with `input` fields should work

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#887]
**Current behavior**

A create mutation with a field called `input` returns internal server error:

```graphql
mutation {
  createCar(input: 42)
}
```

This will fail with internal server error

**Reproduction**

Create a model with a field called `input` and run the mutation.

**Expected behavior?**

Fields called `input` should behae no differently than any other field

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
