### ISSUE TITLE
Permission queries and upgrading legacy projects

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#894]
Upgrading legacy projects with permission queries comes with several problems:

* the "description" of  a permission query is free form. These are all valid descriptions: `Hi!`, `_3space;    &space`, `'tes}|%`.
* descriptions of permission queries are not unique

Therefore, upgrading a legacy project that either has cryptic permission query descriptions (used as GraphQL operation name) or two permission queries with the same description for the same type or relation is problematic.

**Comment by kbrandwijk** [comment]
Isn't it possible to just add the description as a comment line to the query file? And just use `[operation][Type][index]` as query name?

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
