### ISSUE TITLE
Add debugging capabilities to local docker image

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#897]
**What feature are you missing?**
The ability to debug functions locally. Most docker images used to locally run AWS Lambda functions offer some kind of debugging capabilities. For example, serverless-offline, serverless-plugin-simulate and the new aws-sam-local all offer a standard command line switch, like `--debug 5858` that you can attach to with Chrome debug tools, or Visual Studio Code for example, preferably with hot loading.

For Typescript debugging, this would requiring sourcemaps. I don't know if Typescript is currently compiled with or without, but for debugging, you need those.

Also, take a look at hot reloading. It would be useful to be able to change your function without having to do anything else if the local docker is up.

**How could this feature look like in detail? Tradeoffs?**
Add the debug switch to the relevant `graphcool local` commands. You can look at the docker images the mentioned serverless plugins use to see how it's set up.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
