### ISSUE TITLE
Make it easier to get the endpoint URLs for a stage

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#903]
**What feature are you missing?**
I am trying to find out in a script what the endpoints are for a certain stage (local or cloud). My scenario is this:
- I call `graphcool deploy` for a stage. This can be a local stage or a deployed stage
- Next, I want to deploy some external webhooks. These webhooks need to know what my endpoint is.

Now, I can more or less construct this information by combining the information from .grapcoolrc in my project folder (contains the serviceId) and, if cluster is local, get the cluster information from ~/.graphcoolrc to find the url, but this is not very straightforward.

**How could this feature look like in detail? Tradeoffs?**
An exported function from the graphcool-cli that I can call from a script to get the endpoint for a stage. Basically what `graphcool info` does, but accessible from a script.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
