### ISSUE TITLE
Cannot deploy interactively to second local cluster

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#905]
**Current behavior**
I can't select a second local cluster with `graphcool deploy`

**Reproduction**
- I create a second local cluster with `graphcool local up --name second`.
- The cluster is succesfully added to ~/.graphcoolrc
- When I run `graphcool deploy -t newstage`, It only shows one local cluster (local).

**Expected behavior?**
All local clusters show up.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
