### ISSUE TITLE
Inconsistent command line argument processing for deploy

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#906]
The `-c` switch for deploy has full name `--new-service-cluster` and description 'Name of the cluster to deploy to'. However, you can only specify an existing cluster, which is subsequently ignored.

For example, if I have two local clusters defined (local and second), and I use `graphcool deploy -c second` , it still deploys to default target.

Also, I cannot specify a new cluster name here, even though the switch is 'new service cluster'.

Using a cloud cluster, like `graphcool deploy -c shared-eu-west-1` also doesn't work, it also still deploys to the default.

If I run -i, I get asked for cluster, name, target. I would expect that specifying any one those would just ask me the remaining questions.

Specifying -c AND -t, asks for name.
Specifying -t asks for cluster and name.

Just specifying -n crashes, it asks for a cluster and then complains that it can't find projectId .... (defined as serviceId for my default environment).

So when specifying -c, I would expect to be asked for target and name.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
