### ISSUE TITLE
Deploy same project to multiple clusters

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#907]
**What feature are you missing?**
The ability to deploy the same project to multiple shared clusters. All clusters have the same endpoint URLs, so deploying the same project to multiple clusters would be effectively a CDN-like feature.

**How could this feature look like in detail? Tradeoffs?**
This would take a bit of thinking, because it affects the deployment flow, how projects are shown in the console, and how you manage this. So this is quite a broad feature request, to get the thought train going.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
