### ISSUE TITLE
Graphcool local commands could default to work for all local clusters

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#910]
**What feature are you missing?**
If I don't specify a name, I would like the `graphcool local` commands to work on all clusters.

**How could this feature look like in detail? Tradeoffs?**
Two options. Allow `-n *`, and keep the default behavior, or change the default behavior.

At the very least, I would like that commands that use 'default' clusters or stages, to _always_ tell me which cluster or target they are working on. With the `graphcool local` commands, that's not clear.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
