### ISSUE TITLE
Wrong faas port used when deploying to second local cluster

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#912]
**Current behavior**
I deploy to a second local cluster, using `gc deploy -c test2 -t bla` and get an error showing the wrong faas port.

![image](https://user-images.githubusercontent.com/852069/31772985-9bd8773a-b4e1-11e7-8b0e-9ccd78de05ae.png)

![image](https://user-images.githubusercontent.com/852069/31773100-f3575e5e-b4e1-11e7-9de7-ff6f6d93a982.png)

`graphcool local ps -n test2` shows that everything is up, and that faas is on 60051.
Cluster configuration in ~/.graphcoolrc also defines 60051.

I also noticed that the db and mq machines use the same port on all clusters. Does that work well together?

**Expected behavior?**
It works.

**Comment by smmoosavi** [comment]
I have same issue (or related)

graphcool try request port 60050 and get error.
```
'ECONNREFUSED': request to http://127.0.0.1:60050/functions/files/cj98y******wierej failed, reason: connect ECONNREFUSED 127.0.0.1:60050
```



graphcool and docker info:
```
graphcool --version
graphcool/0.8.1 (linux-x64) node-v8.6.0

# graphcool local ps output
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60051
This may take several minutes
$ docker-compose ps

docker   Name                           Command               State                               Ports                            
docker   --------------------------------------------------------------------------------------------------------------------------------------
docker   local_graphcool-db_1            docker-entrypoint.sh mysql ...   Up      3306/tcp                                                     
docker   local_graphcool-rabbit-host_1   docker-entrypoint.sh rabbi ...   Up      15671/tcp, 15672/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp
docker   local_graphcool_1               /app/bin/single-server           Up      0.0.0.0:60000->60000/tcp                                     
docker   local_localfaas_1               /app/bin/localfaas               Up      0.0.0.0:60051->60051/tcp

```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
