### ISSUE TITLE
Support https on local environment

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#913]
**What feature are you missing?**
I would like the local environment to use https. Testing a local https client app against the local http endpoint throws warnings/errors in some cases.

**How could this feature look like in detail? Tradeoffs?**
Add an 's' to the url :wink:

**Comment by schickling** [comment]
To my understanding, this is not as simple as it sounds. @kbrandwijk could you suggest a workflow in regards to SSL certificates? Are you proposing to use self-signed certificates or something like Let's Encrypt?

**Comment by kbrandwijk** [comment]
Just self signed ones.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
