### ISSUE TITLE
Access control for collaboration

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#94]
This is an improvement for #19.

Thanks for @matthiasak's suggestion:
> An additional need here. Allowing team administration abilities here (CMS features mentioned above) it would be awesome to be able to specify a team member's access level, so that they can (in decreasing tiers):
 SuperAdmin - create/edit schema, configure user access levels, as well as below
 Admin - create/edit rows in certain tables, as well as below
 User - read rows in certain tables

**Comment by marktani** [comment]
Currently, collaborators cannot view usage statistics. This should be controllable by the team owner.

**Comment by marktani** [comment]
Deleting projects should be another configurable right.

**Comment by Jannis** [comment]
At @functionalfoundry, we've found the way team seats are allocated per service to be a little confusing and cause friction in our processes. We would very much welcome a team/organization account, where all services deployed within that organization are accessible by everyone in the organization (we don't currently need more fine-grained access control but I guess that wouldn't be unrealistic to add later on).

Right now, we have to add collaborators manually after deploying e.g. a new staging service, and then we're also limited by 2 seats for each service. A global limitation on the number of seats per organization with a corresponding paid plan structure (either different plan for different team sizes (e.g. 5, 10, 20...) or prices per seat) would be great.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
