### ISSUE TITLE
Simplify deploying a locally deployed service definition to the shared cluster

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#945]
![pasted image at 2017_10_19 08_09 pm](https://user-images.githubusercontent.com/1780597/31813938-5ec931d4-b588-11e7-8801-73175dae023c.png)

> When I create a new service locally, and then eventually want to deploy to a shared cluster, it is not easy to figure out what to do. This part of the cli help is not helpful. I would like the same interactive experience as the initial deploy

**Comment by timsuchanek** [comment]
`--interactive` is the way to go here. However, it is still an issue to find this out.

**Comment by kbrandwijk** [comment]
Also, this: https://github.com/graphcool/graphcool/issues/906

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
