### ISSUE TITLE
event.context.auth is null for operationBefore, operationAfter and subscriptions even when providing a valid Authorization header.

### ISSUE THREAD

**Issue by meikoudras** [graphcool/prisma#955]
**Current behavior**
event.context.auth is null for operationBefore, operationAfter even when providing a valid Authorization header.

**Reproduction**
Example project
https://github.com/meikoudras/test-auth

Create a new user.

Select the user in playground.
Run in playground:
`
mutation ($id:ID!, $name:String!) {
  updateUser(id: $id, name:$name) {
    id
    name
  }
}
`

This will return an error "no auth" - that means the auth property in event.context is null.

Run a resolver with the same user:

`
query {
  testAuth(a: 1, b: 1) {
    sum
  }
}
`

This will pass as the auth property is defined.

**Expected behavior?**
That all functions have an event.context.auth set when an authorization header is present.

**Comment by do4gr** [comment]
This issue also affects subscription functions. At the moment the auth is only created for Resolver functions.

**Comment by justmatt** [comment]
+1

**Comment by aandresrafael** [comment]
Hello, any update about his bug, actually i' creating log handler function where i need the user Id to create the log

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
