### ISSUE TITLE
Add --json option to cli commands

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#967]
**What feature are you missing?**
Adding a --json option to cli commands to get the output in 'machine-readable' form.

**How could this feature look like in detail? Tradeoffs?**
Examples:
`$ graphcool root-token`
```json
{
  serviceId: "c.......",
  rootTokens: [
     "mytoken",
     "othertoken"
  ]
}
```

`$ graphcool info`
```json
{
  services: [
    { serviceName: "myService", cluster: "local", serviceId: "...." },
    { .... }
  ],
  endpoints: {
    simple: "http://..........",
    relay: "....",
    ...
  }
}
```

**Comment by marktani** [comment]
Has been implemented by now.
