### ISSUE TITLE
Add line number to graphcool.yml validation warnings/errors

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#971]
**What feature are you missing?**
Getting a line number for a validation error/warning in graphcool.yml would really save a lot of time. Real world example: 'data.permissions[n] should have required property 'operation'' when you make a typo.

**How could this feature look like in detail? Tradeoffs?**
Show the line number in the command output.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
