### ISSUE TITLE
Don't update all functions when deploying any change

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#975]
Currently, _any_ change in the file system will result in _all_ functions to be 'updated' when deploying. A concept needs to be designed to only update functions when necessary.

**Comment by mattfysh** [comment]
Possibly hash the contents of each function and use a similar process to the e-tag / 304 response?

Also - this is super important for those of us on poor connections, especially those of us in Australia using IP over Two Tin Cans and a Piece of Wet String

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
