### ISSUE TITLE
[Meta] validation for graphcool.yml service definition based on json-schema

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#979]
* [ ] #624 
* [ ] #934 
* [ ] #971 
* [ ] #989

In general, the yaml validation should be awesome and helpful based on the json-schema.
If an error is detected, the error message should be helpful and as actionable as possible

**Comment by kbrandwijk** [comment]
I strongly suggest you have a look at https://github.com/epoberezkin/ajv. It allows you to define custom validation functions easily (like checking types.graphql for type existence), supports custom validation messages with variables, etc. It is also the fastest and most compliant validator.

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
