### ISSUE TITLE
Enable Auth0 rules

### ISSUE THREAD

**Issue by jeffgorder** [graphcool/prisma#98]
When integrating with Auth0, the way to create users now is to use the idToken return from the authentication request. 

Auth0 provides a rules pipeline that allows any code to be executed on the user object before the authentication process is completed. Since we have to wait for the idToken before we can create the user in graphcool, that means that we can't use the rules pipeline.

Every user has a unique id in auth0. So, it would be great to be able to create and query graphcool users with that auth0UserId in the rules pipeline.

Beyond creation querying of users, the rules pipeline is very helpful in user engagement.  Check this list for types of things you can do: https://manage.auth0.com/#/rules/new

**Comment by marktani** [comment]
Thanks for the detailed write up! Enabling Auth0 rules would be great, we have to consider the best way moving forward here.

A lot of the rules that I saw on the Auth0 docs can actually be implemented using mutation callbacks on the `createUser` mutation. Here's an example for [Slack notifications after User sign up]().

Also, you can query the `auth0UserId` that gives you some more flexibility for using the rules right now:

```graphql
query {
  allUsers {
    auth0UserId
  }
  User(auth0UserId: "google-oauth2|XXX") {
    id
  }
}
```

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
