### ISSUE TITLE
Webhook examples

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#983]
* now
* webtask
* StdLib
* ...

**Comment by kbrandwijk** [comment]
May I add to that?
- [ ] hook.io
- [ ] docker-based (e.g. sloppy.io or other docker hosting)
- [ ] IronFunctions

**Comment by marktani** [comment]
I think the best way to tackle this is to create one shiny & polished [template](https://github.com/graphcool/templates). This serves as foundation for more template requests in that repo.
