### ISSUE TITLE
Invalid directives in types.graphql are ignored

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#992]
### Current Behaviour

```graphql
type Item @model {
  id: ID! @isUnique
  amount: Int! @default(value: 1)
}
```

```graphql
graphcool deploy
```

This works without an error message. Note `default` vs. `defaultValue`.

### Expected Behaviour

An error message should be returned:

> Item
>   Unknown directive @default detected on field 'amount: Int!'. Did you mean @defaultValue?

**Comment by do4gr** [comment]
Fixed with this https://github.com/graphcool/prisma/pull/1871
