### ISSUE TITLE
Improve "Details: Sorry no more details" error message

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#995]
![image](https://user-images.githubusercontent.com/1780597/31855254-df4165d2-b6a7-11e7-8780-7607a06cc3d7.png)

**Comment by marktani** [comment]
I believe this error message is returned when the unique constraint occurs on a related model for a nested mutation, as in #407.

**Comment by do4gr** [comment]
This is fixed now. We now return the field name if we can infer it.
